### ISSUE TITLE
detail document expected

### ISSUE THREAD

**Issue by askdong** [zzzprojects/EntityFramework-Plus#1]
this project is very useful! 
For the custom audit entry, is there an detail example to explain how to use?  I try to figure out how it works, but it does not work as expected!

 public class CustomInheritAuditBlogDbContext : DbContext
    {

        public DbSet<Blog> Blogs { get; set; }
        public DbSet<BlogImage> BlogImages { get; set; }

        public DbSet<CustomInheritAuditEntry> CustomAuditEntries { get; set; }
        public DbSet<AuditEntryProperty> AuditEntryProperties { get; set; }

        public CustomInheritAuditBlogDbContext()
        {           
            this.Database.EnsureDeleted();
            this.Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var path = @"C:\WORK\PRODUCT\data\blog.data";

            var connectionStringBuilder = new SqliteConnectionStringBuilder { DataSource = path };
            var connectionString = connectionStringBuilder.ToString();
            var connection = new SqliteConnection(connectionString);

            optionsBuilder.UseSqlite(connection);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //base.OnModelCreating(modelBuilder);
            //modelBuilder.Entity<CustomInheritAuditEntry>().HasKey(x => x.AuditEntryID);

            modelBuilder.Entity<CustomInheritAuditEntry>().HasMany(x => x.Properties)
                                      .WithOne(x => (CustomInheritAuditEntry)x.Parent);

            AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
            {
                // Use a constructor to create your own custom audit entry
                var customAuditEntries = audit.Entries.Select(x => new CustomInheritAuditEntry(x, "test"));
                (context as CustomInheritAuditBlogDbContext).CustomAuditEntries.AddRange(CustomAuditEntries);
            };

            AuditManager.DefaultConfiguration.IgnorePropertyUnchanged = false;

        }

    }

**Comment by zzzprojects** [comment]
Thank you for your feedback,

You probably already read our small documentation from here: https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Audit-%7C-Entity-Framework-Audit-Trail-Context-and-Track-Changes

Let us know what’s not working or what you don’t understand and we will help you and improve the wiki at the same time.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Closing Comment: no answer.
