### ISSUE TITLE
QueryFilter for parent entities

### ISSUE THREAD

**Issue by jasonhjohnson** [zzzprojects/EntityFramework-Plus#100]
Hi,

I have the following scenario:

Entities:
`public class Group : BaseEntityWithTenant`
`public class ProductCategory
{
  public int GroupId { get; set; }
  public Group { get; set; }
}`

Query filter:
`this.context.Filter<BaseEntityWithTenant>(QueryFilterType.Tenant, q => q.Where(x => x.TenantId == tenantId));`

How can I apply the tenant filter automatically to the ProductCategories entity which does not directly inherit from the `BaseEntityWithTenant` class?

`await this.context.ProductCategories
    .Include(x => x.Group)
    .ToListAsync();`

Is this even possible? If not are there any workarounds?

Thanks,
Jason

**Comment by zzzprojects** [comment]
Hello Jason,

This is certainly possible.

You will need to create a new filter for every class which doesn't inherit directly from BaseEntityWithTenant

```csharp
this.context.Filter<ProductCategory>(QueryFilterType.TenantProductCategory, q => q.Where(x => x.Group.TenantId == tenantId));
```

Let me know if that answer to your question.

Best Regards,

Jonathan

**Comment by jasonhjohnson** [comment]
@zzzprojects Perfectly. Thanks.

**Comment by zzzprojects** [comment]
Close Comment: Question Answered
