### ISSUE TITLE
Audit new entry problem with foreign key

### ISSUE THREAD

**Issue by Compusa** [zzzprojects/EntityFramework-Plus#101]
I just tried the Audit feature and it seems to be exactly what we need. However, I stumbled upon an issue.

Lets say that I have a parent child relationship.
Parent:
int:Id (Identity specification)

Child:
int:ParentId (FK)

When I create new parent and a new child associated with it, the newValue of ParentId (Child) in AuditProperties is set to 0 instead of the actual value of the newly created Parent. If I check the newValue of Id (Parent) it is set to 18. I guess there is an issue related to the id being an identity specification. Any way to solve it?

**Comment by zzzprojects** [comment]
Hello Compusa,

We successfully reproduced the issue.

It seems our Audit library work with navigation properties but not when the ParentId is directly the value.

We will investigate more the issue this weekend and try to release a fix for Monday.

Best Regards,

Jonathan

**Comment by Compusa** [comment]
Thanks, for the fast response and a fix for Monday will be very appreciated.

**Comment by zzzprojects** [comment]
Hello @Compusa,

Unfortunately, it will take a few more days before releasing the fix.

We tried two solutions, but both failed (causing side effect).

We took some time to think about a third solution (this time working!). Unfortunately, we will not have the time to implement it tomorrow due to having meeting all the days. So we will try on Wednesday.

Sorry for the delay,

Best Regards,

Jonathan

**Comment by Compusa** [comment]
Ok @zzzprojects. Your feedback is highly appreciated and I'm looking forward to the release of the fix.

**Comment by zzzprojects** [comment]
Hello @Compusa ,

The v1.4.18 has been released which should fix this issue.

Can you try it and let us know if it's fixed?

Best Regards,

Jonathan

**Comment by Compusa** [comment]
Hello @zzzprojects 
Sorry for the late feedback. I have been busy with the release of our product and I didn't have any time to look at this until now. I have verified it now and the bug fix solved the problem. Thank you very much! :)
