### ISSUE TITLE
Oracle 11g incompatibility - ORA-00911: invalid character

### ISSUE THREAD

**Issue by dstarosta** [zzzprojects/EntityFramework-Plus#105]
I am trying to use EF-Plus in the following environment.

- .NET 4.6.1
- Oracle 11g
- Entity Framework v6.1.3
- Oracle.ManagedDataAccess (ADO .NET) v12.1.24160719
- Oracle.ManagedDataAccess.EntityFramework v12.1.2400
- Z.EntityFramework.Plus.EF6 v1.4.18

When I am trying to run any future query (with parameters or not), the following error is thrown:

Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00911: invalid character

EF shows correct queries in the log file and the debugger that work if you copy-paste them into Oracle Developer.

Any help would be appreciated.

**Comment by zzzprojects** [comment]
Hello @dstarosta ,

We have not tested our features in all providers (especially Oracle).

I will check this one and try to fix it this weekend.

I will let you know more on Monday,

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Hello @dstarosta ,

Can you try the latest version v1.4.19

Our library should now support Oracle for Query Future.

Let me know if it's working.

Best Regards,

Jonathan

**Comment by dstarosta** [comment]
The latest version is working correctly. Thank you for the prompt fix.
