### ISSUE TITLE
Are Query Filters supposed to filter Included entities as well? (They don't)

### ISSUE THREAD

**Issue by jooooel** [zzzprojects/EntityFramework-Plus#111]
Hi!
I really like your EF extensions, but unfortunately I have a bit of a problem with Query Filters. I want to use them for excluding soft deleted entities, but I can't get it to work when loading them as related entities via Includes. 

I have simplified the code a bit, but I'm doing something like this:

```C#
public class DataContext : DbContext
{
        ...
	public DataContext(string connectionString) : base(connectionString)
	{
		QueryFilterManager.InitilizeGlobalFilter(this);
	}

	protected override void OnModelCreating(DbModelBuilder builder)
	{
		base.OnModelCreating(builder);

		QueryFilterManager.Filter<Item>(x => x.Where(x => !x.IsDeleted));
		QueryFilterManager.Filter<Group>(x => x.Where(x => !x.IsDeleted));
		QueryFilterManager.Filter<Category>(x => x.Where(x => !x.IsDeleted));
		
		...
	}
}

// Get all items for a Category
var items = dataContext
	.Items
	.Include(item => item.Group)
	.Include(item => item.Group.Category)
	.Where(item => item.Group.Category.Id == categoryId);
```

This query will return all Items, even if their category or group is marked as IsDeleted. Am I doing something wrong or is it just how it is?

I would expect the filter on Group and Category to exclude Items belonging to them.

Thank you!

**Comment by JonathanMagnan** [comment]
Hello @jooooel ,

Which version of Entity Framework do you use?

Some features are currently possible under EF6 (Include, LazyLoading, Set).

If you use Entity Framework Core, is unfortunately still doesn't have Interceptor, so I don't know a solution to yet filter the Include method.

This can still be possible to have something similar by adding to your project an IncludeFiltered extension method and use our Include filter feature. It's for sure not as elegant as a working Filter solution but at least that will work:

```csharp
public static partial class CustomExtensions
{
	public static IQueryable<Items> IncludeFiltered(this IQueryable<Items> query)
	{
		return query.IncludeFilter(x => item.Group.Where(y => !y.IsDeleted))
					.IncludeFilter(x => item.Group.Category.Where(y => !y.IsDeleted));
	}
}
```

**Comment by jooooel** [comment]
Sorry! Should have mentioned that. 
I'm using EF 6.1.3, with MySQL (MySql.Data.Entity 6.9.9)

**Comment by JonathanMagnan** [comment]
Thank you, I will look at this issue. It should be already filtered

**Comment by jooooel** [comment]
I could send you the complete code and generated SQL in a PM if you'd like?

**Comment by JonathanMagnan** [comment]
Yes, this can always help ;)

You can send it here: info@zzzprojects.com

**Comment by JonathanMagnan** [comment]
Closing comment: No answer or solved in PM? feel free to re-open if not closed
