### ISSUE TITLE
QueryFilterSet.AddOrGetFilterQueryable NullReferenceException on QueryFilterManager.InitilizeGlobalFilter

### ISSUE THREAD

**Issue by serkan-indg** [zzzprojects/EntityFramework-Plus#118]
I am not sure if you support the preview versions of the framework but I am trying to use .NET Core 1.2.0-preview1-23339 packages and "var internalQuery = field.GetValue(set);" seems to be returning null. 

Call Stack:
   at Z.EntityFramework.Plus.QueryFilterSet.AddOrGetFilterQueryable(DbContext context)
   at Z.EntityFramework.Plus.QueryFilterContext.EnableFilter(BaseQueryFilter filter, Type[] types)
   at Z.EntityFramework.Plus.BaseQueryFilter.Enable(Type[] types)
   at Z.EntityFramework.Plus.QueryFilterManager.InitilizeGlobalFilter(DbContext context)

Let me know if you need more information.

**Comment by JonathanMagnan** [comment]
Hello @serkan-indg ,

Unfortunately, we do not support preview packages not released yet on NuGet.

Trying to support EF Core with all changes they make is already very hard, so, unfortunately, we don't want to add on us more difficulty by supporting preview version with high chance to change.

Just remember us this issue when the new version will be available on NuGet.

Best Regards,

Jonathan

**Comment by DerekChasse** [comment]
@JonathanMagnan I am seeing this same behavior still, and additionally when trying to filter by instance.

I am using .NET Core 2.0, Microsoft.EntityFrameworkCore 2.0 and QueryFilter.EFCore 1.6.8.

Can you share how QueryFiltering can work using EFCore?

**Comment by JonathanMagnan** [comment]
Hello @DerekChasse ,

Could you try with the latest version? It should now be supported but only for the full version.

I will try to make release for standalone version to support .NET Standard 2.0 this weekend.

Best Regards,

Jonathan

**Comment by DerekChasse** [comment]
Thanks @JonathanMagnan,  I'm slightly confused though.  Version 1.6.8 is the latest is the latest at least that is available via Nuget at this moment.

https://www.nuget.org/packages/Z.EntityFramework.Plus.QueryFilter.EFCore/

Is there another package I should be targeting?

**Comment by JonathanMagnan** [comment]
This package `Z.EntityFramework.Plus.QueryFilter.EFCore` is the standalone version (only have Query Filter feature). It doesn't support .NET Standard 2.x simply because I wanted to make some test before with the full package.

This package https://www.nuget.org/packages/Z.EntityFramework.Plus.EFCore/ (v1.6.19) already contains support for .NET Standard 2.x

At this moment, I'm currently making project required to release standalone features for next Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @DerekChasse , @serkan-indg ,

The v1.6.20 has been released including all standalone version for .NET Core.

Please reopen the issue if I have not fixed it correctly.

Best Regards,

Jonathan
