### ISSUE TITLE
When use EFCore In ConsoleApp ,a "FileNotFoundException" occurred.

### ISSUE THREAD

**Issue by xbuilder** [zzzprojects/EntityFramework-Plus#12]
Code just like this:
`EFCoreDbContext ctx = new EFCoreDbContextFactory().Create();`
`var query=ctx.Movies.DeferredCount();`

**Comment by zzzprojects** [comment]
Can you post the full Stack Trace (or send it by email if you want to keep it private)?

The DeferredCount only defer the query and doesn't execute it unless you call the method. Using your code you posted, I cannot reproduce this issue without more information.

**Comment by xbuilder** [comment]
System.IO.FileNotFoundException was unhandled
  FileName=EntityFramework.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  HResult=-2147024894
  Message=Could not load file or assembly 'EntityFramework.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. 系统找不到指定的文件。
  Source=Z.EntityFramework.Plus.EFCore
  StackTrace:
       at Z.EntityFramework.Plus.QueryDeferred`1..ctor(IQueryable query, Expression expression)
       at Z.EntityFramework.Plus.QueryDeferredExtensions.DeferredCount[TSource](IQueryable`1 source)
       at HelloEFCore.Program.Main(String[] args) in C:\Programming\Demos\HelloEFCore\src\HelloEFCore\Program.cs:line 16
  InnerException:

**Comment by zzzprojects** [comment]
Judging by the error, you probably use a different version of EntityFramework.Core from the one (EFCore R1) used to build the EF+ library.

If you already use EFCore R2, we are currently migrating all our project to this version. We hope to release all versions next week.

**Comment by xbuilder** [comment]
Yes, I did use EFCore RC2.

Thanks for your reply.

**Comment by zzzprojects** [comment]
Hello xbuilder,

Just to let you know, the version 1.2.0 supporting RC2 is now released.
