### ISSUE TITLE
Custom_Audit_Entry cannot do automigration using EF Core CLI

### ISSUE THREAD

**Issue by FukKwang** [zzzprojects/EntityFramework-Plus#121]
Hi Love this extension, and it's working properly 
but when i want to add custom field for Audit i got this error on build through dotnet core ef cli
![image](https://cloud.githubusercontent.com/assets/13637549/22858832/62f5cc1a-f0fb-11e6-86e6-c2b7bc671d0b.png)

Custom_Audit_Entry .cs
```csharp
public class Custom_Audit_Entry : AuditEntry
{
	public DateTimeOffset CreateDateOffset { get; set; }
	public string From { get; set; }
}
```

DbContext.cs
```csharp
protected override void OnModelCreating(ModelBuilder builder)
{
	builder.Entity<Custom_Audit_Entry>()
	 .ToTable("_Audit_Entry")
	 .HasKey(m => new
	 {
		 m.AuditEntryID
	 });
	builder.Entity<AuditEntryProperty>()
	 .ToTable("_Audit_Entry_Property")
	 .HasKey(m => new
	 {
		 m.AuditEntryPropertyID
	 });
}
```

Do you have any idea why this happening ? and way to get aroung this ? 

Thanks again !

**Comment by JonathanMagnan** [comment]
Hello @FukKwang ,

Thank you for reporting this issue.

### Problem
The following error is throw in Entity Framework Core:

> The type 'NavigationEntry' cannot have base type 'MemberEntry' because both types include the properties: IsModified.

### Cause
Some new properties to ignore has been added recently. But we forgot that the `[NotMapped]` attribute doesn't still work well under Entity Framework Core

```csharp
[NotMapped]
public EntityEntry Entry { get; set; }
```
### Fix
We must change all properties added with `[NotMapped]` to field

```csharp
public EntityEntry Entry;
```

We are currently making modification and testing, more information will be available soon.

**Comment by JonathanMagnan** [comment]
Hello @FukKwang ,

The v1.4.28 has been released:
https://www.nuget.org/packages/Z.EntityFramework.Plus.EFCore/

You should not have this error anymore.

However, to make it work in my test in the OnModelCreating, I had to ignore the base entity

```csharp
protected override void OnModelCreating(ModelBuilder builder)
{
    builder.Ignore<AuditEntry>();

    builder.Entity<Custom_Audit_Entry>()
        .ToTable("_Audit_Entry")
        .HasKey(m => new
        {
            m.AuditEntryID
        });
    builder.Entity<AuditEntryProperty>()
        .ToTable("_Audit_Entry_Property")
        .HasKey(m => new
        {
            m.AuditEntryPropertyID
        });

    base.OnModelCreating(builder);
}
```

**Comment by FukKwang** [comment]
Hello @JonathanMagnan  thanks for your help ! it's resolved !
