### ISSUE TITLE
SQL CE query contains [dbo]?

### ISSUE THREAD

**Issue by sunib** [zzzprojects/EntityFramework-Plus#124]
I'm trying to use EntityFramework-Plus with SQL Server Compact 4.0, but I'm having trouble while using the Update() function.

This is my code (including extra code te retreive the SQL string).

```
context.Transacties
  .Where(t => ids.Contains(t.Id))
  .Update(t => new Transactie()
  {
    Status = TransactieStatusEnum.OpgenomenInMutatie,
    MutatieId = mutatieId,
    RecordInfo_ModifiedBy = context.Username,
    RecordInfo_ModifiedOn = DateTime.Now
  }, bu => bu.Executing = b => Console.WriteLine(b.CommandText));
```

Running it throws the next next exception:
```
An unhandled exception of type 'System.Data.SqlServerCe.SqlCeException' occurred in System.Data.SqlServerCe.dll
```
Inner message is set to:
```
There was an error parsing the query. [ Token line number = 7,Token line offset = 1,Token in error = FROM ]
```

Setting a breakpoint on the WriteLine allowed me to retreive the constructed query:
```
UPDATE A 
SET A.[Status] = @zzz_BatchUpdate_0,
A.[MutatieId] = @zzz_BatchUpdate_1,
A.[RecordInfo_ModifiedBy] = @zzz_BatchUpdate_2,
A.[RecordInfo_ModifiedOn] = @zzz_BatchUpdate_3
FROM [dbo].[Transactie] AS A
INNER JOIN ( SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[MutatieId] AS [MutatieId], 
    [Extent1].[Status] AS [Status], 
    [Extent1].[RecordInfo_ModifiedBy] AS [RecordInfo_ModifiedBy], 
    [Extent1].[RecordInfo_ModifiedOn] AS [RecordInfo_ModifiedOn], 
    FROM [Transactie] AS [Extent1]
    WHERE [Extent1].[Id] IN (1, 2)
           ) AS B ON A.[Id] = B.[Id]
```

I noticed that `[dbo]` is indeed added in line 7, which is strange as SQL Compact does not support schemas. So that would explain why it throws an syntax error.

Any ideas on resolving this? I would really appreciate it! If you need more info let me know.

Here's a dump of my packages.config, if it helps:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFramework" version="6.1.3" targetFramework="net461" />
  <package id="EntityFramework.SqlServerCompact" version="6.1.3" targetFramework="net461" />
  <package id="Microsoft.SqlServer.Compact" version="4.0.8876.1" targetFramework="net461" />
  <package id="Z.EntityFramework.Plus.EF6" version="1.4.27" targetFramework="net461" />
</packages>
```

**Comment by JonathanMagnan** [comment]
Hello @sunib ,

Thank you for reporting us this issue.

Batch Update doesn't support all providers yet.

We will try to support it this weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @sunib ,

The support to SQL Compact for EF5 && EF6 has been added in v1.4.30

Since SQL Compact has a syntax more limited than SQL Server, there will be some limitation to this provider.

Let me know if you successfully make Batch Update work under SQL Compact.

Best Regards,

Jonathan

**Comment by sunib** [comment]
Great @JonathanMagnan! Thanks for resolving this. Most of my queries are working like a charm now!

One query is failing however, I'm going to create a new issue to see if there also might be room to get that one working.
