### ISSUE TITLE
How to use Audit with ASP.NET Identity

### ISSUE THREAD

**Issue by mhsimkin** [zzzprojects/EntityFramework-Plus#130]
Any suggestions on the best way to hook up the Audit framework with ASP.NET Identity?

**Comment by mhsimkin** [comment]
Ok, I think I can follow the instructions in this section "Saving automatically by overriding SaveChanges & SaveChangesAsync" of this wiki page Entity Framework Audit Trail Context and Track Changes.

Any other thoughts?

Thanks

marc

**Comment by mhsimkin** [comment]
Upon reviewing the section  "Saving automatically by overriding SaveChanges & SaveChangesAsync", it seems to me that you need to have the DbSets for AuditEmtries and AuditEntryProperties in the **same** DbContext as where the SaveChanges and SaveChangesAsync are being overridden.

Is that correct?

**Comment by JonathanMagnan** [comment]
Hello @mhsimkin ,

You are right. If you use code first and your context is named "EntityContext", you need to add AuditEntries & AuditEntryProperties (or whatever you name it) DbSet to your context.

Also, you need to cast the context as "EntityContext" instead of "TestContext" as you said.

Let me know if you successfully implement it.

Best Regards,

Jonathan

**Comment by mhsimkin** [comment]
Hi Jonathan, that is what I thought.  I've coded it, just haven't tested it yet.  I have another question.

I have 3 different DBContext classes in  use, ASP.NET Identity, Identity Server Clients, and Identity Server Scopes.

I can inherit the DBContexts for each one, but is there a way to make the AutoSavePreAction unique for each context?  Could I make it work with an Interface something like:

`public interface IAudit
{
     IDbSet<AuditEntry> AuditEntries { get; set; }
     IDbSet<AuditEntryProperty> AuditEntryProperties { get; set; }
}
`

Then code the AutoSavePreAction as

`
AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) => {
    (context as IAudit).AuditEntries.AddRange(audit.Entries);
}
`

If not, I guess I will just use an if statement in that block of code to choice the correct context.

Thanks

marc

**Comment by mhsimkin** [comment]
Yes, an Interface will work.
