### ISSUE TITLE
Has TPT been improved in EF Plus

### ISSUE THREAD

**Issue by smurfster** [zzzprojects/EntityFramework-Plus#134]
Hey,

I'm looking at trying to convince the company I work for the EF plus has some huge benefits and we should use it. 
One of the areas we have trouble with is TPT, its just so slow in EF and the SQLgenerated is just ridiculous.
I have noticed that a lot of sql optimisation has been applied to other areas, I was wondering if TPT has been addressed in EF Plus?

Cheers

**Comment by JonathanMagnan** [comment]
Hello @smurfster ,

I'm not sure if the library will currently help you or not with the SQL Generated. In short, our library doesn't generate SQL yet, they are still generated by Entity Framework so you may suffer from the same issue.

Most monster SQL are normally coming when using Include, as you probably know, we have a [Query IncludeOptimized](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Query-IncludeOptimized-%7C-Entity-Framework-Filter-Child-Collections-and-Optimize-Include) feature which split the monster query into multiple smaller queries which are generated again by Entity Framework.

Let me know if I answered correctly to your question.

Best Regards,

Jonathan

**Comment by smurfster** [comment]
Yes thanks you have answered my question.

Its a shame as EF TPT is really REALLY bad. 28 sub classes is generating half a million characters of sql, which as you can imagine takes a long time.
