### ISSUE TITLE
AuditEntryProperty - DateTime locale

### ISSUE THREAD

**Issue by JesseKlaasse** [zzzprojects/EntityFramework-Plus#140]
Today, I have started using the Audit functionality of EntityFramework-Plus, which seems to work great.
However, I have one question; currently, all DateTime properties appear in the OldValue and NewValue fields like this: 3/20/2017 2:15:02 PM
I would like all DateTime properties to be formatted in ISO8601 format. Is there a way to do this?

**Comment by JonathanMagnan** [comment]
Hello Jesse,

We released a new version today (v1.4.36) fixing an issue with Format when an entity is deleted.

At this moment, it's only possible to format value by property

```csharp
AuditManager.DefaultConfiguration.Format<EntitySimple>(x => x.DateCreated, x => ((DateTime) x).ToString("yyyy-MM-dd"));
```

However, we added a task to add more global formatted to allow you to format the value for a specific type instead.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JesseKlaasse ,

The v1.4.40 is now available.

We added an option to allow to format all value from a specific type.

```csharp
AuditManager.DefaultConfiguration.FormatType<DateTime>(x => x.ToString("yyyy-MM-dd"));
```

We will close this issue but feel free to re-open if needed.

Best Regards,

Jonathan

**Comment by JesseKlaasse** [comment]
Hi Jonathan,

Thanks, it’s working!

Best regards,
Jesse.
