### ISSUE TITLE
Slow performance using Query Filter

### ISSUE THREAD

**Issue by adamlepkowski** [zzzprojects/EntityFramework-Plus#148]
Hi, I noticed some performance issues in the application and during the investigation, it appeared that problem is connected with the Query Filter feature. The initialization of database context takes up to 300 ms because of the Query Filter.

```
public class DatabaseContext : DbContext
    {
        internal BaseQueryFilterInterceptor SoftDeletableFilter;

        public DatabaseContext()
        {
            this.SoftDeletableFilter = this.Filter<ISoftDeletableEntity>(x => x.Where(a => a.Deleted == false));

            // OR
            //this.Filter<ISoftDeletableEntity>(q => q.Where(x => !x.Deleted));
            //QueryFilterManager.InitilizeGlobalFilter(this);
        }
}
```

The problem exists in Z.EntityFramework.Plus.EF6 1.4.37 and Z.EntityFramework.Plus.QueryFilter.EF6 1.4.33. I wanted to make some further investigation, and I downloaded the source code from the  „EntityFramework-Plus-1.4.37” tag. I built the solution, and I added a reference to my project, and I noticed that issue doesn't exist anymore- database initialization took 2ms. I checked some details of the created DLL file, and I noticed that in details version is 1.4.26. Have you created „EntityFramework-Plus-1.4.37”  tag correctly? I reverted the reference to a nuget package and issue exists.

**Comment by JonathanMagnan** [comment]
Thank you for reporting.

The code source is currently not the latest version. We will try to update it tomorrow.

We will look as well about the performance issue.

We will provide you more information Tuesday or Wednesday.
Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @adamlepkowski ,

The v1.4.39 has been released.

Could you try again? A critical if was missed which was causing the performance issue

```csharp
if (ClearCacheRequired)
{
    UpdateHook(Context);
}
```

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
The code also has been updated to the latest version.

**Comment by adamlepkowski** [comment]
Hi @JonathanMagnan
Thanks for such quick reaction. I will make a test tomorrow morning.

/Adam

**Comment by adamlepkowski** [comment]
I verified initialization and it takes up to 30 ms what is very good result compering to the previous one. I just don't know why in the previous version initialization took only 2 ms but I think you can mark it as a solved. Thanks a lot.

**Comment by JonathanMagnan** [comment]
In short, we had to modify the code to support more scenario.

We need to add a filter with a unique ID to every DbSet which was not done before. That is probably here the time difference.

I will try this weekend to improve this performance for people having a lot of DbSet, but I cannot guarantee anything.

Best Regards,

Jonathan

**Comment by adamlepkowski** [comment]
Sure, no problem. Current execution time is acceptable for me.

**Comment by JonathanMagnan** [comment]
Hello @adamlepkowski ,

Make sure to download to the latest version (v1.4.44)

By adding our fix, we forget to set the property ClearCacheRequired to true to clear the cache at least the first time a filter is used with the context.

Sorry for this mistake.

Best Regards,

Jonathan

**Comment by adamlepkowski** [comment]
@JonathanMagnan Issue has appeared once again in the latest version (1.4.46) and I think it's closely related with https://github.com/zzzprojects/EntityFramework-Plus/issues/155.

**Comment by JonathanMagnan** [comment]
Hello @adamlepkowski ,

Which kind of performance are you receiving this time?

I believe a Lazy Type initialization causes the issue.

The performance on my side decreased by more than 80% only by removing it.

By example, this code
```csharp
{
    List<Lazy<string>> list = new List<Lazy<string>>();

    for (int i = 0; i < 100; i++)
    {
        list.Add(new Lazy<string> (() => null));
    }

    clock1.Start();

    foreach (var item in list)
    {
        var test = item.Value;
    }

    clock1.Stop();

    var time = clock1.ElapsedMilliseconds;
}
```

May take up to 20ms... And it becomes worse if there is actual code inside the initializer instead of null.

I'm very surprise of such poor performance.

I will try to complete this request tomorrow.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @adamlepkowski ,

The v1.4.48 has been released.

You should see a huge performance gain!

Pleaser, report us how much time it takes now.

Best Regards,

Jonathan

**Comment by adamlepkowski** [comment]
Hi everything works perfectly :) On my side it takes up to 20ms.
