### ISSUE TITLE
Update from v1.4.9 to v1.4.37 breaks IDbCommandInterceptor

### ISSUE THREAD

**Issue by IanYates** [zzzprojects/EntityFramework-Plus#150]
I have an `IDbCommandInterceptor` in my project to log queries and their execution times.

Yesterday I thought I'd get my NuGet packages up to date and test to make sure things are still working.  My application still functions except my interceptor is malfunctioning.

Debugging is a little tricky at the moment but I've found my interceptor's start methods (eg `ReaderExecuting`) are getting called but the finish methods (eg `ReaderExecuted`) are not getting called.

It's definitely due to the change in EntityFramework-Plus version as I've rolled back just that one NuGet package and my interceptor starts working again.

Reading through your code I see a commit https://github.com/zzzprojects/EntityFramework-Plus/commit/012de825dfd13d5036143ab4cf13d66cefc99df5 which appears to be making calls to `ReaderExecuting` but never makes any calls to `ReaderExecuted`.  This would match the behaviour I'm seeing.

Is this intentional?

The problem for me is that I log every 5 seconds that a query is still running so I get a deliberately noisy log when the database is taking longer to service requests  (I'd rather know about an issue before we get a call from a customer, and then have something good to look at from the time things went bad).  With the `ReaderExecuted` call missing our logs get very noisy and the log messages never stop.

For now I'll stay on the old version but it'd be great to get the balanced `Executed` calls into this awesome library.  I only use the `IncludeOptimized` functionality but that alone has been very helpful.     

Thanks

**Comment by JonathanMagnan** [comment]
Hello @IanYates ,

We did a test and Interceptor is still working.

The code you will find call the ReaderExecuting method but only to take the command text and parameter, it will never really call `ExecuteReader` method at this point. That is necessary because some provider like MySQL set the parameter value for the command to execute using interceptor. Some people may also create Interceptor to change the CommandText / Parameter.

So this section of the code only take the command text & parameter and will NOT execute it.

All queries will be combined later and then will be executed using Interceptor

```csharp
var interceptionContext = Context.GetInterceptionContext();
using (var reader = DbInterception.Dispatch.Command.Reader(command, new DbCommandInterceptionContext(interceptionContext)))
{
	foreach (var query in Queries)
	{
		query.SetResult(reader);
		reader.NextResult();
	}
}
```

I have added the test I made.

- readerExecuting count: 3 (2 command text generated + the command executed)
- readerExecuted count: 1 (The command executed)

```csharp
using System.Collections.Generic;
using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.Infrastructure.Interception;
using System.Linq;
using System.Windows.Forms;

namespace Z.EntityFramework.Plus.Lab
{
    public partial class Form_Request_IncludeOptimized_Interceptor : Form
    {
        public Form_Request_IncludeOptimized_Interceptor()
        {
            InitializeComponent();

            // CLEAN
            using (var ctx = new EntityContext())
            {
                ctx.Lefts.RemoveRange(ctx.Lefts);
                ctx.Rights.RemoveRange(ctx.Rights);
                ctx.SaveChanges();
            }

            // SEED
            using (var ctx = new EntityContext())
            {
                var left = ctx.Lefts.Add(new Left {ColumnInt = 1});
                left.Rights = new List<Right>();
                left.Rights.Add(new Right {ColumnInt = 1});

                ctx.SaveChanges();
            }

            var interceptor = new ZedCommandInterceptor();
            DbInterception.Add(interceptor);

            // TEST
            using (var ctx = new EntityContext())
            {
                var list = ctx.Lefts.IncludeOptimized(x => x.Rights).ToList();
            }

            var readerExecuting = interceptor.readerExecuting;
            var readerExecuted = interceptor.readerExecuted;
        }

        public class EntityContext : DbContext
        {
            public EntityContext() : base("CodeFirstEntities")
            {
            }

            public DbSet<Left> Lefts { get; set; }
            public DbSet<Right> Rights { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x => x.ToTable(GetType().DeclaringType != null ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class Left
        {
            public int Id { get; set; }
            public int ColumnInt { get; set; }

            public List<Right> Rights { get; set; }
        }

        public class Right
        {
            public int Id { get; set; }
            public int ColumnInt { get; set; }
            public Left Left { get; set; }
        }

        public class ZedCommandInterceptor : IDbCommandInterceptor
        {
            public int readerExecuted;
            public int readerExecuting;

            public void NonQueryExecuting(
                DbCommand command, DbCommandInterceptionContext<int> interceptionContext)
            {
            }

            public void NonQueryExecuted(
                DbCommand command, DbCommandInterceptionContext<int> interceptionContext)
            {
            }

            public void ReaderExecuting(
                DbCommand command, DbCommandInterceptionContext<DbDataReader> interceptionContext)
            {
                readerExecuting++;
            }

            public void ReaderExecuted(
                DbCommand command, DbCommandInterceptionContext<DbDataReader> interceptionContext)
            {
                readerExecuted++;
            }

            public void ScalarExecuting(
                DbCommand command, DbCommandInterceptionContext<object> interceptionContext)
            {
            }

            public void ScalarExecuted(
                DbCommand command, DbCommandInterceptionContext<object> interceptionContext)
            {
            }
        }
    }
}
```

Let me know if my explanation is clear.

Best Regards,

Jonathan

**Comment by IanYates** [comment]
Hi,

Thank you for the very detailed thought and response.

I understand your point.  However this breaks what I saw (probably incorrectly) as the contract of the interceptor.  That is, every call to Executing should be balanced with a call to Executed.

I'm happy to work around it.  In our interceptor I'm now seeing if our specific DbContext is present, and if so, I'm using a method we already had on it to register a callback when the context is disposed.  
That callback will terminate our ongoing logging messages arising from that context and its commands/queries.  Since we're not currently leaking any instances of DbContext in our code that should achieve close to the the desired outcome - the timely conclusion of our logging messages so that an actually long-running query (particularly one that's still in progress) is properly identified in our logs.

We'll now be more robust too if we ever have something else also interfering with EF's workings.

It would be even nicer though if there was a way to pick up that the OnExecuting is being called in this fake manner.  
Looking at https://msdn.microsoft.com/en-us/library/dn343510(v=vs.113).aspx I can see there are properties such as `IsExecutionSuppressed`.  Could I rely on that being set, or some other signal (apart from `UserState` since I'm using that already) to detect additional these calls?  I don't want to rely on examining the stack to see which method was calling our interceptor code since that'll be slow.  The dispose callback above is 99% good but if we do have some long-lived EF context with multiple operations (ie, lots of reads, some processing for maybe 10 seconds and then a save) then we'll still get logging occurring for the early queries despite them not being a source of trouble.

I really appreciate your help & thoughts.
Cheers

**Comment by JonathanMagnan** [comment]
Hello @IanYates ,

You are right, if we call Executing, we should balanced it with Executed. However, is still feel weird since nothing has been really executed!

Actually, we have a few options available from our side:

- Always calling ReaderExecuted
- Adding options to allow to skip the ReaderExecuting from your interceptor from this method
- Doing both solutions!

We don't want to automatically remove all "custom" interceptor since I believe calling them should be the default behavior.

Best Regards,

Jonathan

**Comment by IanYates** [comment]
Hi Jonathan,

Certainly a fix from your side would be preferred.  I agree it might feel weird to call ReaderExecuted when nothing actually has been executed but then again, calling Executing when you're not actually going to execute what's been given is also a bit weird 😄 

How about a subclass of `DbCommandInterceptionContext<T>` is created and is used for your extra calls?  I can then check for the interception context being of your custom type (which means it'll need to be a public type) and use that as a signal that it's a fake Executing call.

Calling Executed immediately after your call to Executing could work.  What'd be even better is storing up a list of Actions to invoke (basically a list of ...Executed calls to make) after the overall query has executed you then invoke these actions.  That way the Executing/Executed calls are still balanced and the gap in time is also meaningful.  Whether or not the calls are made sophisticated enough to also include the exceptions is a side detail as EF's own calls to the interceptor with exceptions should still occur.

**Comment by IanYates** [comment]
Hi Jonathan,

Just wondering if you've had any further thoughts about this based on my ideas above?

I could probably put together a PR if I had your opinion as to which way you'd like to go.

Cheers.

**Comment by JonathanMagnan** [comment]
Hello @IanYates ,

Sorry for the delay,

It's currently on the todo list, but we got quite a few request recently for paid library (which is always the priority).

This request will be completed this weekend. If I don't come back with an answer Monday, make sure to remember me! That will become the top 1 priority ;)

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @IanYates ,

The v1.4.47 is now available.

I finally choose to simply balance call. Not because I was lazy but because all others options didn't feel right for people using standalone library.

By example, the idea you proposed about creating a subclass of the DbCommandInterceptionContext is great, I almost implemented it. However, for people using standalone solution, the same class will exist in multiple features unless we create a common library (which I believe will eventually happen).

The same go if I add options. People using standalone solution will need to setup it multiple times.

Anyway, when we think about it, it's already weird the library call ReaderExecuting when nothing will get executed, so it's not so weird to call ReaderExecuted ;)

Let me know if your interceptor is now balanced.

Best Regards,

Jonathan

**Comment by IanYates** [comment]
Hi Jonathan,

My apologies for the late reply.  I'll definitely give this a try in the next day or so and get back to you.  Your reasoning is certainly sound.

Cheers,
Ian

**Comment by IanYates** [comment]
Hi,

The fix is *almost* perfect.  Can I suggest we change

```
interceptors.ForEach(i => i.ReaderExecuting(prepareEntityCommandBeforeExecution, new DbCommandInterceptionContext<DbDataReader>(objectQuery.Context.GetInterceptionContext())));

                sql = prepareEntityCommandBeforeExecution.CommandText;
                var parameters = prepareEntityCommandBeforeExecution.Parameters;

                interceptors.ForEach(i => i.ReaderExecuted(prepareEntityCommandBeforeExecution, new DbCommandInterceptionContext<DbDataReader>(objectQuery.Context.GetInterceptionContext())));

```

to

```
var interceptionContext = new DbCommandInterceptionContext<DbDataReader>(objectQuery.Context.GetInterceptionContext());

interceptors.ForEach(i => i.ReaderExecuting(prepareEntityCommandBeforeExecution, interceptionContext));

                sql = prepareEntityCommandBeforeExecution.CommandText;
                var parameters = prepareEntityCommandBeforeExecution.Parameters;

                interceptors.ForEach(i => i.ReaderExecuted(prepareEntityCommandBeforeExecution, interceptionContext));

```

The context's `UserState` property is lost with all these new instances so I still can't tie the `...Executed` call to the `...Executing` call.

Would that be OK for you?

**Comment by IanYates** [comment]
Sorry for the bad formatting in previous post.

Looking at the code a bit more, if you wanted to have a separate context for each interceptor could we perhaps use a dictionary of contexts with one entry per interceptor?

```
var interceptionContexts = new Dictionary<IDbCommandInterceptor, DbCommandInterceptionContext<DbDataReader>>();

interceptors.ForEach(i => {
    var interceptionContext = new DbCommandInterceptionContext<DbDataReader>(objectQuery.Context.GetInterceptionContext());
    interceptionContexts[i] = interceptionContext;
    i.ReaderExecuting(prepareEntityCommandBeforeExecution, interceptionContext);
});

sql = prepareEntityCommandBeforeExecution.CommandText;
var parameters = prepareEntityCommandBeforeExecution.Parameters;

interceptors.ForEach(i => {
    var interceptionContext = interceptionContexts[i];
    i.ReaderExecuted(prepareEntityCommandBeforeExecution, interceptionContext);
});
```

I don't really know if that's better or worse but it at least gives each interceptor something unique to work with and is therefore probably more correct and reliable in an environment with multiple interceptors registered.

I suspect the interceptors in real EF code work in a nested fashion where the second interception context is a clone of the first with its own bits added, and then the interceptors have `...Executed` called in reverse order, unwrapping the interception contexts as they go.

Since you're really just faking it all here I think there's no real need for the nested approach and just having a separate context for each pair of interceptor calls is all that's required.

**Comment by JonathanMagnan** [comment]
Hello @IanYates ,

That's a great suggestion.

The v1.5.3 has been released with the code you provided.

Let me know if you find something else about this issue.

Best Regards,

Jonathan

**Comment by IanYates** [comment]
Hi Jonathan,
I had just finished making a PR and had SourceTree telling me about a conflict.  You beat me by a few minutes!

I made the same changes so I'll scrap the branch, etc.

Thanks so much for being so quick with this :)

**Comment by JonathanMagnan** [comment]
lol ;)

I try to do my best with the time available for this library ;)

Best Regards,

Jonathan

**Comment by IanYates** [comment]
A quick smoke test...
The new code seems to work a treat.  Thank you so much!
