### ISSUE TITLE
IncludeOptimized yields error when filter that follows contains a boolean expression

### ISSUE THREAD

**Issue by stryker1977** [zzzprojects/EntityFramework-Plus#152]
IncludeOptimized results in an error when the the query that follows an `IncludeOptimized` call contains an `Any ` boolean subquery on the include. I suppose it would do the same for a numeric aggregation too. Code works fine when used with standard EF include. 

Error:
` Unable to cast object of type 'System.Data.Entity.Core.Objects.ObjectQuery1[System.Boolean]' to type 'System.Data.Entity.Core.Objects.ObjectQuery1[TypeSubType]'`

Example Code:
`_dataContext.Set<TypeSubType>().IncludeOptimized(x => x.SubType).Any(x => x.Id == typeId && x.SubTypes.Any(st => st.id == subTypeId));`

I'm using EF 6.1.1, .Net 4.5.1, and Z.EntityFramework.Plus.EF6  1.4.37 and I traced the error to line # 165 of Z.EntityFramework.Plus.QueryIncludeOptimizedProvider<T> :

`var immediateQuery = (ObjectQuery<T>) createQueryMethod.Invoke(provider, new object[] {expression});`

**Comment by JonathanMagnan** [comment]
Hello @stryker1977 ,

I'm not sure if you pasted your code correctly or not.

Currently, when I look and try your code example, you return a boolean value

```csharp
bool isTrue = _dataContext.Set<TypeSubType>().IncludeOptimized(x => x.SubType).Any(x => x.Id == typeId && x.SubTypes.Any(st => st.id == subTypeId));
```

In this case, our library cannot help you. Even the Include or IncludeOptimized method doesn't help you either since you don't have to include anything because you return a boolean value. So, trying to include something here is only a bad practices.

Let me know if I misunderstood the issue.

Best Regards,

Jonathan

**Comment by stryker1977** [comment]
Hi Jonathan, so the code I pasted does expect a Boolean result. Essentially it's saying tell me if there are any records of the table that I'm querying that contain one or more related records matching some input. You need an include for this sub filter over navigation property, and it does indeed work with standard EF include. Additionally sub query filter with aggregation is also supported in standard EF, for example compare to a count of related include set as a filter.

The code I pasted above is production code and has been working for sometime. As soon as I switched to EF Plus to test backwards compatibility this is the only thing so far that i've encountered that is broken. 

Thanks and please let me know if you need any additional examples of clarification. I really appreciate all the hard work you've all put into this is a great library.

The code I pasted above is production code and has been working for sometime. As soon as I switched to EF Plus to test backwards compatibility this is the only thing so far that i've encountered that is broken. 

Thanks and please let me know if you need any additional examples of clarification. I really appreciate all the hard work you've all put into this is a great library.

**Comment by stryker1977** [comment]
Hi Jonathan, so the code I pasted does expect a Boolean result. Essentially it's saying tell me if there are any records of the table that I'm querying that contain one or more related records matching some input. 

The code I pasted above is production code and has been working for sometime. As soon as I switched to EF Plus to test backwards compatibility this is the only thing so far that i've encountered that is broken.

Logically you make a good point though the include is unnecessary in this case and does in fact work without it. However this does work fine with builtin EF 6.1 include, but errors out when used with include optimized and is a deviation from base EF supported functionality. Given this is unnecessary include, this issue can probably be closed if you concur. 

Thanks for the quick response, and all the hard work you've all put into this is a great library.

**Comment by JonathanMagnan** [comment]
Hello @stryker1977 ,

Thank you, I just wanted to make sure I was doing the right thing ;)

I will probably check this issue again and try to handle some method like "Any", "All", etc and make them skip the logic about IncludeOptimized as the Include do.

I will let you know very soon.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @stryker1977 ,

The v1.4.42 has been released.

We now ignore our library when following immediate method is executed:

- All
- Any
- Count
- LongCount

Let me know if that successfully fixed your issue.

Best Regards,

Jonathan

**Comment by stryker1977** [comment]
Hi Jonathan,  

Thanks I'll check it out. Is this also an issue if you use sum, min, max or any other scalar operation, or was it just with the methods you listed above?

**Comment by JonathanMagnan** [comment]
Hello @stryker1977 ,

Oops! I just added methods that has a predicate.

Thank you for letting me know, I will add all other method this weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @stryker1977 ,

Other methods has been added in the v1.4.43

- All
- Any
- Average
- Contains
- Count
- LongCount
- Max
- Min
- SequenceEqual
- Sum

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing comment: Fix released, feel free to re-open with not completely done
