### ISSUE TITLE
Change AuditEntryID to GUID

### ISSUE THREAD

**Issue by dieterdp** [zzzprojects/EntityFramework-Plus#153]
Hello

Is it possible to change AuditEntryID and AuditEntryPropertyID from int to Guid?

regards
Dieter

**Comment by JonathanMagnan** [comment]
Hello @dieterdp ,

When we will re-write this feature, we will change the AuditEntryID from int to long.

If you want to use a Guid, you will need to create your own auditing and import value from the one created by our library.

See the section "Custom AuditEntry & Database First Approach" in the Wiki.

Let me know if that's clear.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing comment: No answer, feel free to re-open with more information
