### ISSUE TITLE
Bulk Delete doesn't work with Oracle

### ISSUE THREAD

**Issue by pizycki** [zzzprojects/EntityFramework-Plus#154]
Hi, I've tried Batch Delete on Oracle and it doesn't seem to work. It looks much alike this [issue (Oracle 11g incompatibility - ORA-00911: invalid character)](https://github.com/zzzprojects/EntityFramework-Plus/issues/105). I get the exactly same error.

Does EntityFramework-Plus Batch Delete supports Oracle RDBMS? 

Z.EntityFramework.Plus.BatchDelete.EF6 @ 1.4.30.0
Oracle @ 12c
EntityFramework @ 6.1.3
.NET @ 4.6

**Comment by JonathanMagnan** [comment]
Hello @pizycki ,

Thank you, I will try to get a look at it tomorrow. If we have no time, this may go to the weekend (We try to support only this library on weekend and focus on paid library during the week.)

So product owner finally decided to merge the Oracle to the master branch? :)

Best Regards,

Jonathan

**Comment by pizycki** [comment]
@JonathanMagnan , thats right! :)

Thanks for quick response. I'm waiting for this issue to be resolved.
In the meantime I'll add Dapper with Bulk operations and see how it work.

**Comment by JonathanMagnan** [comment]
Hello @pizycki ,

The first version to try to support Oracle for Batch Delete has been released in v1.4.45

Some improvement will still be required (Binding variable by name, I believe it's false by default).

So let me know if that's currently working with your expression.

Best Regards,

Jonathan

**Comment by pizycki** [comment]
Hello @JonathanMagnan 

I've tested updated version of EF Bulk Delete and it worked! 
Great job !

If I encounter any other issues with bulk delete, I'll write about them in this thread.

Thank you for your help. 
Have a great week :)
