### ISSUE TITLE
Questions about DeferredCount？

### ISSUE THREAD

**Issue by haninfo** [zzzprojects/EntityFramework-Plus#157]
query.DeferredCount().FutureValue();     

The generated SQL script contains count (1)。

How to change count (column name)？

Thank you

**Comment by JonathanMagnan** [comment]
Hello @haninfo ,

## COUNT(1) vs COUNT(column name)
_(That information are for people that might read this issue but doesn't know the difference)_

There is a huge difference between both methods.

- COUNT(1): Count the number of rows in the table
- COUNT(column name): Count the number of NON-NULL value of this column in the table

---
Unfortunately, that query is generated by Entity Framework (Of course, there is some stuff we can do).

So the real question is how we can do it with Entity Framework?

I made some small research, but I have not found anything yet besides making a count and explicitly checking that the value is not null.

```csharp
ctx.EntityInts.Count(x => x.ColumnInt != null);
```

I don't like the SQL generated from it but at least it works...

```sql
SELECT 
[GroupBy1].[A1] AS [C1]
FROM ( SELECT 
    COUNT(1) AS [A1]
    FROM [Z.EntityFramework.EFCore].[dbo].[Rights] AS [Extent1]
    WHERE [Extent1].ColumnRightLeft IS NOT NULL
)  AS [GroupBy1]
```

Let me know if that answered to your question and if you find a better way, please let me know, I will be happy to learn how to do it ;)

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing comment: No answer, feel free to re-open with more information
