### ISSUE TITLE
How to translate AudityEntityProperty for report?

### ISSUE THREAD

**Issue by mhsimkin** [zzzprojects/EntityFramework-Plus#159]
Hi:

I'm trying to understand how I can translate the information stored in the AuditEntityProperties table to something that is more user friendly for display/reports.

I have figured out how to translate most of the data expect for the Json below.

```
[
  {
    auditEntryPropertyID: 15,
    auditEntryID: 8,
    propertyName: "Id",
    relationName: "Scope_ScopeClaims_Source",
    newValue: "2",
    oldValue: null
  },
  {
    auditEntryPropertyID: 16,
    auditEntryID: 8,
    propertyName: "Id",
    relationName: "Scope_ScopeClaims_Target",
    newValue: "8",
    oldValue: null
  }
]
```

What do the _Source and _Target on the relationship represent?

In my specific case is the _Source relationship the Primary Key table, and the _Target the Foreign Key table.  Furthermore, is the relationship formatted as PrimaryKeyTable_ForeignKeyTable ?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @mhsimkin ,

The relation name is taken from the Entity Framework model, so we don't control it. It represents a relation between two tables.

The "Source" should normally represent the table (Principal), the "Target" should normally represent a child table (Dependent)

By example for Invoice && InvoiceItem
- Source: InvoiceID from the Invoice
- Target: InvoiceID from the InvoiceItem

However, don't base your logic on this statement, I don't think it's respected.

Yes, the name is normally formatted using the primary key table with the foreign key table.

For EF6 && EF5, when a new relation is added/deleted, a new objectStateEntry is created with the EntityState Added or Deleted.

You can find how we take it here: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/Z.EntityFramework.Plus.EF6/Audit/Audit/AuditRelationshipAdded.cs

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by mhsimkin** [comment]
Jonathan, I'm all set.  Thanks.
