### ISSUE TITLE
Problem with multiple DbContext and AutoSavePreAction

### ISSUE THREAD

**Issue by drodic** [zzzprojects/EntityFramework-Plus#163]
I passing two DbContexts in manager constructor responsible for business logic as interface, and in those DbContexts constructors I put this code:
`// Globally
            AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
                (context as BeeGoDbContext).AuditEntries.AddRange(audit.Entries);`
and:
`            // Globally
            AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
                (context as AcctDbContext).AuditEntries.AddRange(audit.Entries);`

Only settings for last resolved DbContext is set and I'm get error for second one. This is probably because this AuditManager is static class and because of that it has only one instance.
Is it posible to configure AutoSavePreAction for this case?

**Comment by JonathanMagnan** [comment]
Hello drodic,

Since the AutoSavePreAction is global, it can only be configured once.

However, you can easily check the instance of the context to handle multiple DbContext scenarios.

By example, something like this:

```csharp
AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) => (
	var beeGoDbContext as BeeGoDbContext
	if(beeGoDbContext != null)
	{
		beeGoDbContext.AuditEntries.AddRange(audit.Entries);
	}
	else
	{
		(context as AcctDbContext).AuditEntries.AddRange(audit.Entries);
	}
);
```

Let me know if that helped you.

Best Regards,

Jonathan

**Comment by drodic** [comment]
Hi Jonathan,

I figured out how to solve this problem. Thank you for example but I have those DbContext in separate assemblies and I don't want to include one assembly in the other assembly.
Finally, I decided to remove AutoSavePreAction and manually add Audit entries in SaveChangesAsync method.
So, I replaced this code:
```            
if (audit.Configuration.AutoSavePreAction != null) 
{
     audit.Configuration.AutoSavePreAction(this, audit);
     await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
}
```
with this code:
```
await AuditEntries.AddRangeAsync(audit.Entries);
await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
```
And in the end, thank you for this great library :)
