### ISSUE TITLE
No EntitiesContext() available

### ISSUE THREAD

**Issue by LucaspNet** [zzzprojects/EntityFramework-Plus#165]
ASP NET MVC5 web application, E.F. 6.0
I set up Z.EntityFramework.Plus.EF6 v 1.5.5 Package in Visual Studio 2015 using VS Nu-Get Package Manager Console, and the assembly is correctly referenced.
I referenced it by "using Z.EntityFramework.Plus;" in my Controller Class, notwithstanding I cannot instantiate a new EntitiesContext() (The type or namespace EntitiesContext() could not be found).

1. What am I doing wrong?
2. Where can I find more "how-to" documentation?

**Comment by JonathanMagnan** [comment]
Hello @LucaspNet ,

> 1. What am I doing wrong?

The `EntitiesContext` is only the class name we use in our example, it's not really part of the library. You must replace it with your context class.

> 2. Where can I find more "how-to" documentation?

Currently the only documentation we have can be found in the Wiki: https://github.com/zzzprojects/EntityFramework-Plus/wiki

We plan to move/re-write all the documentations during summer.

---

Let me know if I answered correctly to your both questions.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing comment: Question answered, feel free to re-open if you need more information
