### ISSUE TITLE
I can not find Z.EntityFramework.Plus.EFCore.NETStandard.dll anywhere

### ISSUE THREAD

**Issue by joeryw** [zzzprojects/EntityFramework-Plus#166]
In my project I get the folowing error:

> {"Could not load file or assembly 'Z.EntityFramework.Plus.EFCore.NETStandard, Version=1.5.5.0, Culture=neutral, PublicKeyToken=59b66d028979105b' or one of its dependencies. The system cannot find the file specified.":"Z.EntityFramework.Plus.EFCore.NETStandard, Version=1.5.5.0, Culture=neutral, PublicKeyToken=59b66d028979105b"}

I tried to resolve it by looking for this assembly, but I even can't find any reference in the code to it. Just that the nuget Z.EntityFramework.Plus.EFCore is dependant on this assembly...

I get this error when I try to run folowing code:

`var handlers = assemblies.SelectMany(s => s.GetTypes()).Where(p => interfaceType.IsAssignableFrom(p) && !p.IsInterface).ToList();`

The error occurs on the s.GetTypes()

(One of the handlers I try to load references a UOW package that uses Z.EntityFramework.Plus.EFCore

**Comment by JonathanMagnan** [comment]
Hello @joeryw ,

Thank you for reporting this issue. We have recently modified all our projects to migrate them to VS2017. It seems we forget to change the assembly name for this one.

A new release will be available today.

Best Regards,

Jonathan

**Comment by joeryw** [comment]
Did some further investigation: in the nuget package In the netstandard1.3 folder, the assembly is named "Z.EntityFramework.Plus.EFCore.NETStandard.dll"
in the net451 folder the assembly is called "Z.EntityFramework.Plus.EFCore.dll"

For one or another when you add the "Z.EntityFramework.Plus.EFCore" nuget package to a netstandard1.4 project X (and create a nuget X), and then reference this nuget X to a .net47 project, the 47 project is looking for the "Z.EntityFramework.Plus.EFCore.**NETStandard**.dll"

**Comment by joeryw** [comment]
Hi thank you for the fast release !!
I'm looking forward to it.
Great !

**Comment by JonathanMagnan** [comment]
Yup, that's exactly the problem ;) We forget to rename the assembly name in the project to have both the same name.

**Comment by JonathanMagnan** [comment]
Helo @joeryw ,

The v1.6.0 has been released.

We have renamed the assembly to remove the `.NETStandard` part.

Let me know if that is now working.

Best Regards,

Jonathan

**Comment by joeryw** [comment]
Hi ,

It's working perfectly !
Thanks !
