### ISSUE TITLE
Why is not there a SelectFilter method: what is the equivalent ?

### ISSUE THREAD

**Issue by AnthonyBr** [zzzprojects/EntityFramework-Plus#168]
Filtering relative entities with InfuldeFilter is very useful, but I cannot achieve it in my simple case.

My database model is a panel:
- linked with many many states, 
- linked with devices that are linked to many many status

I need to query for a panel with last state, and all devices with their last status. 

I can filter panels with IncludeFilter, but I don't see how can I filter device's status.  How can I do it without a SelectFilter method ?

```
var panelQuery = actiContext.Panels.Where(conditionExpression)
    .OrderByDescending(p => p.AliveTimeStamp).Take(1)
    .IncludeFilter(
        p => p.Devices
            .SelectFilter(d => d.DeviceStatus // I just need the last status, there are too many status
                .OrderByDescending(s => s.TimeStamp).Take(1)))
    .IncludeFilter(p => p.PanelStates.OrderByDescending(ps => ps.TimeStamp).Take(1));
```
.. but SelectFilter does not exist.

**Comment by JonathanMagnan** [comment]
Hello @AnthonyBr ,

What's SelectFilter? You could simply use a normal Select like this:

```csharp
var panelQuery = actiContext.Panels.Where(conditionExpression)
    .OrderByDescending(p => p.AliveTimeStamp).Take(1)
    .IncludeFilter(p => p.Devices)
    .IncludeFilter(p => p.Devices.Select(d => d.DeviceStatus.OrderByDescending(s => s.TimeStamp).Take(1)))
    .IncludeFilter(p => p.PanelStates.OrderByDescending(ps => ps.TimeStamp).Take(1));
```

Be careful, you must include all paths. By example, you include Device than in another IncludeFilter, you include the DeviceStatus.

Let me know if that's working.

Best Regards,

Jonathan

**Comment by AnthonyBr** [comment]
It works perfectly !

> Be careful, you must include all paths. By example, you include Device than in another IncludeFilter, you include the DeviceStatus.

Yes otherwise there is no device at all.

It is not obvious because with the basic "Include" method, there is no need to add devices in another Include method.

Thank you very much for help.

**Comment by JonathanMagnan** [comment]
Yup,

This summer, we will probably review all our features and try to improve them. We currently have all the code needed to make it work without people having to include child entities. We already support it in IncludeOptimized when an option is enabled.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing Comment: Help has been provided & confirmed
