### ISSUE TITLE
Foreign key error when saving related entity

### ISSUE THREAD

**Issue by dondracek** [zzzprojects/EntityFramework-Plus#17]
Hi,

a simple scenario:
I have a DB (with EF5 on it) with about 300k of Products, the product data themselves is updated only once a day via Import.
I have a customer, a customer has a cart and a cart has a list of products (obviously :)) Now - maybe a bit naive - I did the following (very very simplified):
`
CartEntry entry = new CartEntry();
var product = db.Product.Where(p=>p.ProductId=productIdToAdd).FromCache().FirstOrDefault();
cartEntry.Product = product;
db.CartEntry.Add(cartEntry);
db.SaveChanges();
`

The "SaveChanges" however throws an error saying something like (it's in german, so a rough translation): "Can't determinate a valid order vor independent operations. The dependencies might be caused by foreign key constraints, model requirements or values generated from memory."

Any guess what I can do about this? I thought I can simply cache the product as it's basically immutable. By the way: a GREAT project!!! :)

**Comment by zzzprojects** [comment]
Thank you for your feedback ;) We will for sure improve it over years with tons of new features.

I may be wrong, but I believe it's because Entity Framework assumes the product is a new entity since you use it in a related property. The product is currently not tracked because it taken from the memory cache.

You should first attach the product before saving the cart entry

```csharp
CartEntry entry = new CartEntry();

var product = db.Product.Where(p=>p.ProductId=productIdToAdd).FromCache().FirstOrDefault();
db.Product.Attach(product);
cartEntry.Product = product;

db.CartEntry.Add(cartEntry);
db.SaveChanges(); 
```

Let me know if that worked.

**Comment by dondracek** [comment]
Hi, Thanks a lot, this sure does sound reasonable, will try first thing tomorrow. Just an idea, what do you think about an extension method like this?:
T FirstOrDefaultFromCacheToContext(this Query<T> query, DbSet<T> contextSet) {
 var res = query.FromCache().FirstOrDefault();
 if (res!=null) {
  contextSet.Add(res);
 }
 return res;
}

BR
David

Am 20.07.2016 um 18:05 schrieb ZZZ Projects <notifications@github.com<mailto:notifications@github.com>>:


Thank you for your feedback ;) We will for sure improve it over years with tons of new features.

I may be wrong, but I believe it's because Entity Framework assumes the product is a new entity since you use it in a related property. The product is currently not tracked because it taken from the memory cache.

You should first attach the product before saving the cart entry

CartEntry entry = new CartEntry();

var product = db.Product.Where(p=>p.ProductId=productIdToAdd).FromCache().FirstOrDefault();
db.Product.Attach(product);
cartEntry.Product = product;

db.CartEntry.Add(cartEntry);
db.SaveChanges();

Let me know if that worked.

-

**Comment by zzzprojects** [comment]
There is a huge issue with your extension methods.

You don't attach the entity but add it. It's like creating a new whole entity.

You should use instead the attach method
```
public static T FirstOrDefaultFromCacheToContext<T>(this IQueryable<T> query, DbSet<T> contextSet) where T : class
{
    var res = query.FromCache().FirstOrDefault();
    if (res != null)
    {
        contextSet.Attach(res);
    }
    return res;
}
```

We added to our roadmap a task to allow to attach it from the cache. The complexity here is an object cannot be attached in multiple context at the same time, so be careful.

**Comment by zzzprojects** [comment]
Closing: There is nothing more to do with this issue unless I forget something?
