### ISSUE TITLE
it's not work in efcore with postgresql by npgsql

### ISSUE THREAD

**Issue by tldzyx** [zzzprojects/EntityFramework-Plus#170]
the batch delete or update will be throw exception, because the warpper in postgresql is "TableName", but not [TableName].

**Comment by JonathanMagnan** [comment]
Hello @tldzyx ,

Thank you for reporting.

We don't support BatchUpdate yet for PostgreSQL, in fact, I have added the support yesterday but this version has not been released yet.

I will try to look at EF Core before releasing this version.

It should be available for next Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @tldzyx ,

We added a first version for support to PostgreSQL && EF Core.

Let me know if that's working.

Best Regards,

Jonathan

**Comment by saeedmsdi** [comment]
Hi @JonathanMagnan 

I use npgsql ,1.6.1 installed. 

This is dbcontext constructor : 

`        public DbContext()
        {
            QueryFilterManager.ForceCast = true;
            QueryFilterManager.Filter<Product>("IsDeleted", q => q.Where(b => !b.IsDeleted));
            QueryFilterManager.InitilizeGlobalFilter(this);
        }
`
But it doesn't work for me and all records returned.

Best,

Saeed

**Comment by JonathanMagnan** [comment]
Hello @saeedmsdi ,

Make sure to create your own thread, it's way easier to follow request this way. This issue was about supporting BatchDelete && BatchUpdate for EF Core and will be closed soon.

Could you create your own thread to let us investigate this issue? There is currently an issue in your example, you add global filter every time you create a context which is very bad.

Best Regards,

Jonathan

**Comment by saeedmsdi** [comment]
@JonathanMagnan where is the best palace to define GlobalFilters in aspnet core ?

This is the Product entity :  

`public class Product : IEntityBase
    {
        public int Id { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public bool IsDeleted { get; set; }
        public virtual ICollection<Buyer> Buyers { get; set; }
    }`

and this the Context :  

`public class ProductsDbContext : DbContext
    {
        public DbSet<Product> Products { get; set; }
        public DbSet<Buyer> Buyers { get; set; }
        public DbSet<Coupon> Coupons { get; set; }
        public DbSet<Campaign> Campaigns { get; set; }

        public static string ConnectionString { get; set; }

        public ProductsDbContext()
        {
            QueryFilterManager.ForceCast = true;
            QueryFilterManager.Filter<Product>("IsDeleted", q => q.Where(b => !b.IsDeleted));
            QueryFilterManager.InitilizeGlobalFilter(this);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseNpgsql(ConnectionString, b => b.MigrationsAssembly("PayPing.Products"));

            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<Buyer>().HasKey(k => k.Code);

            base.OnModelCreating(builder);
        }

    }`

**Comment by JonathanMagnan** [comment]
Closing Comment: Version Released
