### ISSUE TITLE
Model fails to initialise if it includes Audit entities in EF Core

### ISSUE THREAD

**Issue by knightpfhor** [zzzprojects/EntityFramework-Plus#172]
I'm using EF Core (1.1.2) running in .Net core 1.1.2 and I'm attempting to use the Audit functionality.  However, when it tries to initialise the model I get the following error:

`The entity type 'Audit' requires a primary key to be defined.`

The error message is accurate, because Audit does not have a property for it's primary key, so it can't be mapped.

Would there be a big problem with simply adding an Id property to both Audit and AuditEntry?

**Comment by JonathanMagnan** [comment]
Hello @knightpfhor ,

Only AuditEntry && AuditEntryProperty need to be mapped to your context.

You are currently trying to map also the Audit class which is not required and have no key defined.

```csharp
public class EntityContext : DbContext
{
   // ... context code ...
   public DbSet<AuditEntry> AuditEntries { get; set; }
   public DbSet<AuditEntryProperty> AuditEntryProperties { get; set; }

   static EntityContext()
   {
      AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
         // ADD "Where(x => x.AuditEntryID == 0)" to allow multiple SaveChanges with same Audit
         (context as EntityContext).AuditEntries.AddRange(audit.Entries);
   }
}
```

Let me know if the reason why you are getting this error is clear with my explanation.

In short, you should NOT MAP the Audit class in your context.

Best Regards,

Jonathan

**Comment by knightpfhor** [comment]
Ah, I see my problem.  I failed to read the instructions carefully enough.  I was binding to Audit, not AuditEntry.  Thanks for the prompt response.

**Comment by JonathanMagnan** [comment]
Closing comment: Problem found
