### ISSUE TITLE
EF Core marks entities removed From child collections as modified and results in incorrect audit

### ISSUE THREAD

**Issue by knightpfhor** [zzzprojects/EntityFramework-Plus#174]
If you are using EF core, and you remove an entity from a child collection, EF sets the state of the deleted entity in the change tracker to be Modified, but it does delete the entity from the DB when you call `SaveChanges`.  This state causes the `PreSaveChanges` method to incorrectly mark this entity as modified, not deleted.  If you delete the entity from the collection on the  DB Context, it works as expected (this is my current work around).  I was trying to create a test in the project that showed my particular problem, but I've had problems getting it working.  The following is close to what I'm doing:

```csharp
// Given the following entities
public class Association_ManyToMany_Left
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ID { get; set; }

    public int ColumnInt { get; set; }

    public List<Association_ManyToMany> Rights { get; set; }
}

public class Association_ManyToMany_Right
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ID { get; set; }

    public int ColumnInt { get; set; }

    public List<Association_ManyToMany> Lefts { get; set; }
}

public class Association_ManyToMany
{
    public int LeftId { get; set; }
    public Association_ManyToMany_Left Left { get; set; }

    public int RightId { get; set; }
    public Association_ManyToMany_Right Right { get; set; }
}

...

var currentLeft = context.Association_ManyToMany_Lefts().First();

var child = currentLeft.Rights().First();

currentLeft.Rights.Remove(currentLeft);

context.SaveChanges(new Audit());
```

**Comment by JonathanMagnan** [comment]
Hello @knightpfhor ,

Thank you for reporting. We successfully reproduced the issue.

We are currently investigating to check how we can fix that.

Currently, the easier solution is simply on the PostSaveChanges event to check if the new entity state is detached, which should only happen when a modified entity is deleted instead.

We will fix this issue this week,

Best Regards,

Jonathan

**Comment by knightpfhor** [comment]
Excellent, thanks @JonathanMagnan.

**Comment by JonathanMagnan** [comment]
Hello @knightpfhor ,

The v1.6.3 has been released.

Could you check this new version and let us know?

Best Regards,

Jonathan

**Comment by knightpfhor** [comment]
That has fixed the problem, thank you.
