### ISSUE TITLE
Correlation name is specified multiple times in a FROM clause. (EF6)

### ISSUE THREAD

**Issue by rlenders** [zzzprojects/EntityFramework-Plus#176]
No matter what I try, I can't get batch updates to work.

```
The correlation name 'B' is specified multiple times in a FROM clause.
```

Sounds as if the SQL generated is invalid.

I am using Z.EntityFramework.Plus.EF6.

**Comment by rlenders** [comment]
I've did some testing and came to the conclusion that this happens when the update query has a depth of three levels of entities. In my example these are called Foo, Bar and Baz.

```
DbContext.Foos.Update(f => new Foo
{
    Property = f.Bars.Count(b => b.Baz.AnotherProperty)
});
```

**Comment by rlenders** [comment]
I did some more digging and found something interesting. I have no issues with this when using up to (and including) version v1.4.33. From v1.4.34 onward, this error starts showing up.

**Comment by JonathanMagnan** [comment]
Thank you for reporting.

I believe you give us more than enough information to try to reproduce it.

We will try to fix this issue this week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @rlenders ,

We have successfully reproduced the issue and have found what's causing it.

We are currently looking for a fix that will not break other fix made by the change we have done on v1.4.34 and onward.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @rlenders ,

The v1.6.4 has been released.

We now only replace the first alias found instead of all alias to avoid issues with the scenario you provided.

Let us know if this issue is now resolved.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing Comment: Feel free to re-open if you still have the issue

**Comment by rlenders** [comment]
I just updated to v1.6.4, works great! Overall performance seems to be better too, thanks.
