### ISSUE TITLE
Soft-Delete(filter) not work on npgsql 

### ISSUE THREAD

**Issue by saeedmsdi** [zzzprojects/EntityFramework-Plus#177]
Hi

I'm using npgsql , ef-plus 1.6.3 installed.

1. where is the best palace to define GlobalFilters in aspnet core ?

2. This code doesn't work for me and all records returned.

This is the entity :

```csharp
public class Product : IEntityBase
{
	public int Id { get; set; }
	public DateTime? CreatedDate { get; set; }
	public DateTime? ModifiedDate { get; set; }
	public string Code { get; set; }
	public string Title { get; set; }
	public bool IsDeleted { get; set; }
	public virtual ICollection<Buyer> Buyers { get; set; }
}
```

and this the Context :  

```csharp
public class ProductsDbContext : DbContext
{
	public DbSet<Product> Products { get; set; }
	public DbSet<Buyer> Buyers { get; set; }
	public DbSet<Coupon> Coupons { get; set; }
	public DbSet<Campaign> Campaigns { get; set; }

	public static string ConnectionString { get; set; }

	public ProductsDbContext()
	{
		QueryFilterManager.ForceCast = true;
		QueryFilterManager.Filter<Product>("IsDeleted", q => q.Where(b => !b.IsDeleted));
		QueryFilterManager.InitilizeGlobalFilter(this);
	}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.UseNpgsql(ConnectionString, b => b.MigrationsAssembly("PayPing.Products"));

		base.OnConfiguring(optionsBuilder);
	}

	protected override void OnModelCreating(ModelBuilder builder)
	{
		builder.Entity<Buyer>().HasKey(k => k.Code);

		base.OnModelCreating(builder);
	}

}
```

Best,

Saeed

**Comment by JonathanMagnan** [comment]
Hello Saeed,

> where is the best palace to define GlobalFilters in aspnet core ?

The best place is normally in a static construction since it's initialized only once

```csharp
public class ProductsDbContext : DbContext
{
	static ProductsDbContext()
	{
		// Definite Filter Here!
		QueryFilterManager.ForceCast = true;
		QueryFilterManager.Filter<Product>("IsDeleted", q => q.Where(b => !b.IsDeleted));
	}

	public ProductsDbContext()
	{
		QueryFilterManager.InitilizeGlobalFilter(this);
	}
}
```

> This code doesn't work for me and all records returned.

Before we investigate, could you show us the LINQ used and the SQL generated? 

Best Regards,

Jonathan

**Comment by saeedmsdi** [comment]
> the LINQ used

`await _products.AsQueryable().Where(w => w.UserId == userId).ToListAsync()`

> the SQL generated

`Executed DbCommand (160ms) [Parameters=[@__userId_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT "w"."Id", "w"."Code", "w"."CreatedDate", "w"."ModifiedDate", "w"."Title", "w"."UserId"
      FROM "Products" AS "w"
      WHERE "w"."UserId" = @__userId_0`

Regards,

Saeed

**Comment by JonathanMagnan** [comment]
Thank you, we will try to look at it today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @saeedmsdi ,

Unfortunately, we are not able to reproduce this issue.

But something is weird in your class and queries.

In your class, you have the following property specified: `public bool IsDeleted { get; set; }` and no property exists about `UserId`

In your query, you make a reference to the `UserId` but the SQL statement doesn't return any information about `IsDeleted`

Are you sure both class is the same? Perhaps you have another product class with a very similar name? 

Best Regards,

Jonathan

**Comment by saeedmsdi** [comment]
@JonathanMagnan 

I have more than 30 property on product, I send an example.

> Unfortunately, we are not able to reproduce this issue.

Can you produce an example? I don't see any samples for your awesome package.

Regards,

Saeed

**Comment by JonathanMagnan** [comment]
Hello @saeedmsdi ,

Here is the latest test we have made

```csharp
using System.ComponentModel.DataAnnotations.Schema;
using System.Configuration;
using System.Linq;
using System.Windows.Forms;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace Z.EntityFramework.Plus.Lab.EFCore.PostgreSQL
{
    public partial class Form_Request_Batch : Form
    {
        public Form_Request_Batch()
        {
            InitializeComponent();

            // CLEAR
            using (var ctx = new EntityContext())
            {
                ctx.Lefts.RemoveRange(ctx.Lefts);
                ctx.SaveChanges();
            }

            // SEED
            using (var ctx = new EntityContext())
            {
                var left1 = ctx.Lefts.Add(new Left {ColumnInt = 1}).Entity;
                var left2 = ctx.Lefts.Add(new Left {ColumnInt = 2}).Entity;
                var left3 = ctx.Lefts.Add(new Left {ColumnInt = 3}).Entity;

                ctx.SaveChanges();
            }

            // TEST
            using (var ctx = new EntityContext())
            {
                var columnID = 1;

                var list = ctx.Lefts.Where(x => x.ColumnInt > columnID).ToList();
            }
        }

        public class EntityContext : DbContext
        {
            static EntityContext()
            {
                var ctx = new EntityContext();
                var isCreated = ctx.Database.EnsureCreated();

                QueryFilterManager.Filter<Left>(x => x.Where(y => y.ColumnInt <= 2));
                QueryFilterManager.ForceCast = true;
            }

            public EntityContext()
            {
                QueryFilterManager.InitilizeGlobalFilter(this);
            }

            public DbSet<Left> Lefts { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseNpgsql(new NpgsqlConnection(ConfigurationManager.ConnectionStrings["CodeFirstEntities"].ConnectionString));

                base.OnConfiguring(optionsBuilder);
            }
        }

        [Table("Left", Schema = "dbo")]
        public class Left
        {
            public int ID { get; set; }

            public int ColumnInt { get; set; }
        }
    }
}
```

**Comment by saeedmsdi** [comment]
Hi @JonathanMagnan 

the problem is when I use injection :  

`private ProductsDbContext _context;

        public EntityBaseRepository(ProductsDbContext context)
        {
            _context = context;
            var d = _context.Set<Product>().Where(x => x.UserId == 1).ToList();
        }`

it doesn't work.

Regards

**Comment by saeedmsdi** [comment]
@JonathanMagnan can you tell me it could be resolved or not. Or another solution?

**Comment by JonathanMagnan** [comment]
Hello @saeedmsdi ,

Thank you for this additional info, that's what was missed to reproduce it.

Unfortunately, we cannot fix it due to how the `Set` method works.

However, a workaround is already existing by using the `SetFiltered` method instead

Example

```csharp
private ProductsDbContext _context;

public EntityBaseRepository(ProductsDbContext context)
{
	_context = context;
	var d = _context.SetFiltered<Product>().Where(x => x.UserId == 1).ToList();
}
```

Let me know if the SetFiltered is working.

Best Regards,

Jonathan

**Comment by saeedmsdi** [comment]
@JonathanMagnan 

Yes it works. So I should change all Set<> to SetFiltered<> ? right ?

Regards,

Saeed

**Comment by JonathanMagnan** [comment]
Exactly,

Currently, it's the only way we found to filter the Set.

Best Regards,

Jonathan
