### ISSUE TITLE
Null errors when using Audit and InMemory database

### ISSUE THREAD

**Issue by daveyjay** [zzzprojects/EntityFramework-Plus#181]
I am getting null errors when using the Audit features with EF's in memory database.

I set up my context options to use the in memory database like so

`optionsBuilder.UseInMemoryDatabase()`

My DbContext has the SaveChanges method overridden - I call SaveChanges() when I want to perform the audit and save the audit entries and I have a method called SaveChangesNoAudit() that does not perform the audit.  

For my unit tests that are testing my Datalayer I am using the InMemory database and I call SaveChangesNoAudit wherever possible to skip the auditing.  However, when testing some of my generic repository methods, internally they call the SaveChanges.  This seems to be triggering null errors when it hits the EntityFramework-Plus Auditing library - it is inconsistent behaviour though as sometimes these tests pass after hitting the auditing code and other times they don't.  

Here is the error message that I am getting:

{System.NullReferenceException: Object reference not set to an instance of an object.
   at Z.EntityFramework.Plus.AuditConfiguration.IsAuditedProperty(EntityEntry entry, String propertyName)
   at Z.EntityFramework.Plus.Audit.AuditEntityDeleted(AuditEntry entry, EntityEntry objectStateEntry)
   at Z.EntityFramework.Plus.Audit.PreSaveChanges(Audit audit, DbContext context)
   at DataLayer.MyDbContext.SaveChangesAndAuditRows() in C:\source\MyApp\MyApp\DataLayer\MyDbContext.cs:line 310
   at DataLayer.MyApp.SaveChanges() in C:\source\MyApp\MyApp\DataLayer\MyDbContext.cs:line 279
   at DataLayer.Repositories.Repository`1.Remove(TEntity entity) in C:\source\MyApp\MyApp\DataLayer\Repositories\Repository.cs:line 96
   at DataLayer.Repositories.MyRepository.RemoveEmployees(List`1 employeesToRemove) in C:\source\MyApp\MyApp\DataLayer\Repositories\EmployeeRepository.cs:line 38

I also get errors when trying to Attach an object:

System.NullReferenceException : Object reference not set to an instance of an object.
   at Z.EntityFramework.Plus.AuditConfiguration.GetEntityModifiedState(EntityEntry entry)
   at Z.EntityFramework.Plus.Audit.PreSaveChanges(Audit audit, DbContext context)
   at DataLayer.MyApp.SaveChangesAndAuditRows() in C:\source\MyApp\MyApp\DataLayer\MyDbContext.cs:line 310
   at DataLayer.MyContext.SaveChanges() in C:\source\MyApp\MyApp\DataLayer\MyDbContext.cs:line 279
   at DataLayer.Repositories.Repository`1.Attach(TEntity entity) in C:\source\MyApp\MyApp\DataLayer\Repositories\Repository.cs:line 78

And here is the relevant code:

The DbContext class:

`namespace DataLayer`
`{
   public class MyDbContext : IdentityDbContext<User>
   {`
`          // usual DbContext stuff - DbSets etc.`

` public int SaveChangesNoAudit()`
`        {`
`                    return base.SaveChanges();`
`        }`

 `       public override int SaveChanges()`
`        {`
  `          return SaveChangesAndAuditRows();`
`        }`

`private int SaveChangesAndAuditRows()`
`        {`
`            var audit = new Audit();`
`            audit.CreatedBy = "App User"`
`            audit.PreSaveChanges(this);`

 `           var rowAffecteds = base.SaveChanges();`
 `           audit.PostSaveChanges();`

`            if (audit.Configuration.AutoSavePreAction != null)`
`            {`
`                audit.Configuration.AutoSavePreAction(this, audit);`
   `             base.SaveChanges();`
`            }`

 `           return rowAffecteds;`
`        }`

Here are my repository methods that are triggering the error.  This all works fine when using EF with SQL server.

` public class EmployeeRepository: Repository<Employeel>`
`public void RemoveEmployees(List<int>employeesToRemove)`
`        {`
`            var employees = _context.Employees.Where(e => employeestoRemove.Contains(e.Id));`
`            foreach (var employee in employees)`
`            {`
`                this.Remove(employee);`
`            }`
`        }`

and here is the generic repository methods that calls the SaveChanges that trigger this error:

`public int Remove(TEntity entity) `
`        {`
`            DbSet.Attach(entity);`
`            DbSet.Remove(entity);`
`            return Context.SaveChanges();`
 `       }`
`public void Attach(TEntity entity) `
`        {`
`            DbSet.Attach(entity);`
`            Context.Entry(entity).State = EntityState.Modified;`
`            Context.SaveChanges();`
 `      }`

Again, this code all works when using SQL server - these errors seem to be tied to the InMemory database.

**Comment by JonathanMagnan** [comment]
Hello @daveyjay ,

Thank you for reporting.

Unfortunately, we tried a few scenario similar to your and we have not been able to reproduce the issue using InMemory.

We will check again this week why could cause the entry to throw a null reference exception.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @daveyjay ,

Do you think you could give us a full example that's not working?

Best Regards,

Jonathan

**Comment by daveyjay** [comment]
I will try to recreate this issue with a stripped down project that doesn't contain any proprietary code - thanks

**Comment by daveyjay** [comment]
I have sent an email to you (the info email listed on your profile) with a link to where you can download my solution - thanks!

**Comment by JonathanMagnan** [comment]
Hello @daveyjay ,

Thank you, we successfully downloaded your solution.

We will look at it during the weekend.

Best Regards,

Jonathan

**Comment by daveyjay** [comment]
Great! Thanks very much

**Comment by daveyjay** [comment]
I am still having this issue when testing with the InMemory database.  Were you able to recreate this with the test project I sent?

**Comment by inatlewski** [comment]
Hi,

I've encountered the same problem in my project.
Is there any update about the issue?

**Comment by JonathanMagnan** [comment]
Hello @daveyjay , @inatlewski ,

I'm very sorry for the delay, I completely forget this request.

I will put it in high priority and make sure I don't forget it again.

I will work on it today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @daveyjay , @inatlewski 

Sorry again for the delay, I'm not even sure why I needed a test project either since the error was obvious when I looked at it today.

One common problem is people add some `global` configuration in the context constructors as you did:

```csharp
public MyDbContext(DbContextOptions<MyDbContext> options, IDomainEventDispatcher eventDispatcher = null)
    : base(options)
{
    _eventDispatcher = eventDispatcher;

    AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
            // ADD "Where(x => x.AuditEntryID == 0)" to allow multiple SaveChanges with same Audit
            (context as MyDbContext).AuditEntries.AddRange(audit.Entries);
    AuditManager.DefaultConfiguration.ExcludeDataAnnotation();
    AuditManager.DefaultConfiguration.Exclude<AuditEntry>();
    AuditManager.DefaultConfiguration.Exclude<AuditEntryProperty>();
    AuditManager.DefaultConfiguration.IgnorePropertyUnchanged = true;
    AuditManager.DefaultConfiguration.SoftDeleted<User>(x => x.IsDeleted);
}
```

Which means, every time a new context is created, the same configuration is added again and again. Since they are global configuration, they are not safe thread either (you should only do it once!), which leads to some error like the one you got some time.

You should add these global configurations somewhere that get invokes only once, by example, a static constructor or in the OnModelCreating event.

Example:
```csharp
        static MyDbContext()
        {
            AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
                // ADD "Where(x => x.AuditEntryID == 0)" to allow multiple SaveChanges with same Audit
                    (context as MyDbContext).AuditEntries.AddRange(audit.Entries);
            AuditManager.DefaultConfiguration.ExcludeDataAnnotation();
            AuditManager.DefaultConfiguration.Exclude<AuditEntry>();
            AuditManager.DefaultConfiguration.Exclude<AuditEntryProperty>();
            AuditManager.DefaultConfiguration.IgnorePropertyUnchanged = true;
            AuditManager.DefaultConfiguration.SoftDeleted<User>(x => x.IsDeleted);
        }

        public MyDbContext(DbContextOptions<MyDbContext> options, IDomainEventDispatcher eventDispatcher = null)
            : base(options)
        {
            _eventDispatcher = eventDispatcher;
        }
```

Let me know if that explains correctly the error and if it's fixed when applying the above suggestion.

Best Regards,

Jonathan

**Comment by daveyjay** [comment]
Yes, that seems to do the trick! I didn't realize that the code had to be inside a static constructor.
Thanks again :)

**Comment by asulwer** [comment]
maybe you should place a comment in your examples showing how this could occur?  it happened to me and without this report i would never have guessed
