### ISSUE TITLE
Query Filter By Instance Strange Behaviour 

### ISSUE THREAD

**Issue by mcgri** [zzzprojects/EntityFramework-Plus#183]
Hi
I am having an issue with the Query Filter By Instance and I hope this ticket is appropriate for posting here. I know that the filter by instance is not meant to work with lazy loading...but it does in my setup. It works everywhere, but one model/property.

Here my db context constructor:

         `public MyDB(int companyId) : base("name=DefaultConnection")
        {
 
                this.Filter<BaseModel>(q => q.Where(x =>  (x.CompanyId == companyId || x.IsGlobal==true) && x.IsDeleted == false));
        }`

And here the testing code:

           `var tempDB = new MyDb(1);
            var applicantRep = new ApplicantRep(User.Identity.GetUserId(),tempDB);
            NHUser tempUser = applicantRep.GetById(3);

            var addressDetails = tempUser.AddressDetails;  //filled
            var priviliges = tempUser.Privileges; //filled
      
            var interview = tempUser.ApplicantDetails.Interview; //filled with virtual properties
            var anwsers = interview.InterviewAnwsers; //filled 

            var fieldValues = tempUser.ApplicantDetails.MedicalQuestionnaire.FieldValues; //filled a virtual List
            var zero = tempUser.ApplicantDetails.MedicalQuestionnaire.FieldValues[0].FormField; //even virtual inside of the list is filled

                 

            var form = tempDB.FormTemplates.Where(x=>x.Name==FormTemplate.MEDICALFORMNAME).ToList()[0];
            var formFields = form.FormFields; // Sometimes is null ,sometimes it is filled. (0_0)

           var form2 = tempDB.FormTemplates.FirstOrDefault(x=>x.Name==FormTemplate.MEDICALFORMNAME);
            var formFields2 = form2.FormFields; // Sometimes is null ,sometimes it is filled. (0_0)

            var userListRaw = tempDB.NHUsers.ToList(); // Filters applied just fine
             var userList = tempDB.NHUsers.FirstOrDefault(x=>x.Id==3); // This one works well too
            var firstAnwsers = userList?.ApplicantDetails.Interview.InterviewAnwsers[0].Id; //and Id is displayed 
`

My problem is with the "formFields" variables. Sometimes they load. Sometimes they don't. I am dropping DB  each time I run the code. All navigation properties are virtual (lazy loaded). As you could see, I tested the code with multiple models with a similar setup. 
Each FormTemplates could have multiple FormFields. One to many relationships.  The formFields will always load if I use eager loading ( Include() ). So the problem is definitely with lazy loading. 

I tried to find any difference in the models...but all of them are the same, apart from property names.

It will be appreciated if you could point me in the right direction for digging the issue or even explain why the filtering works with lazy loading for most of the properties....when it not supposed to 
I will provide any extra info about the setup. 

I am using Code first EF6,MVC 5. 

Thank you for your help.

**Comment by JonathanMagnan** [comment]
Hello @mcgri ,

Yes, it's appropriate to post it here ;)

> I know that the filter by instance is not meant to work with lazy loading...but it does in my setup

Be careful, if your filter is different from an instance to another, the first lazy loading query will be compiled and re-used in other context instance no matter the filter.

That's why that's not working since it lead to some error.

> Sometimes they load. Sometimes they don't

Looking at your code, it looks you have exactly the lazy loading behavior I explained. The companyId is not a global variable, so for LazyLoading, only the first companyId value is compiled and all other LazyLoading queries will re-use this plan no matter the companyId.

In the future, we will revamp this feature to make it fully compatible with lazy loading but currently, that will not work with your scenario.

Best Regards,

Jonathan

**Comment by mcgri** [comment]
Thank you for your answer. I will drop using lazy loading for now, as it brings too many issues, and will be monitoring updated to this library for the changes. Thank you for your awesome work :)
