### ISSUE TITLE
Query From Cache Can't Force Clear

### ISSUE THREAD

**Issue by bdjema** [zzzprojects/EntityFramework-Plus#185]
Hi, I write the code need to remove all cached when called SaveChanges() method, but the cached still appears.

`  public override int SaveChanges()
        {
            Z.EntityFramework.Plus.QueryCacheManager.ExpireAll();
            return base.SaveChanges();
        }`

And when I query again after call Savechanges(), it still return from cached.

Any solution for this problem?

Thanks and Regards,
Bahar

**Comment by JonathanMagnan** [comment]
Hello @bdjema ,

Thank you for reporting.

Could you make a simple test like this one and report us the result?

```csharp
// CACHE something
var itemCountAfter = ctx.Entity_Basics.FromCache().ToList();

// REPORT cache count before
var cacheCountBefore = QueryCacheHelper.GetCacheCount();

// EXPIRE the cache
QueryCacheManager.ExpireAll();

// REPORT cache count after
var cacheCountAfter = QueryCacheHelper.GetCacheCount();
```

Are you customizing the cache by example by providing a custom key?

There is some improvement that can be done on our side, we will for sure look at it.

Best Regards,

Jonathan

**Comment by bdjema** [comment]
Hi Jonathan, now it's work, i just change the  "GetCacheKey" method.
To
`
 sb.AppendLine(CachePrefix);
 if(tags == null || tags.Length == 0)
            {
                string name = query.ElementType.Name;
                sb.AppendLine(string.Join(";", name));
                return sb.ToString();
            }
`

And i comment in
`
  //var queryCacheUniqueKeyMethod = query.GetType().GetMethod("GetQueryCacheUniqueKey", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
            //if (queryCacheUniqueKeyMethod != null)
            //{
            //    var queryCacheUniqueKey = (string)queryCacheUniqueKeyMethod.Invoke(query, new object[] { tags });
            //    if (!string.IsNullOrEmpty(queryCacheUniqueKey))
            //    {
            //        return queryCacheUniqueKey;
            //    }
            //}
`

This part generated key very length i think.

Thanks and Best Regards,
Bahar
