### ISSUE TITLE
Future ToList closing the context's reader.

### ISSUE THREAD

**Issue by christiangeorge** [zzzprojects/EntityFramework-Plus#187]
When trying to perform a query via a Context after a Future ToList has been called results in a error of "Invalid attempt to call Read when reader is closed."

```
using(var context = new EntityContext()){
  var _cust = context.Customers.FirstOrDefault(c => c.CustID == 1234);
  var phones = context.Phones.Where(p => p.OwnerID == _cust.CustomerID).Future();
  var addresses = context.Phones.Where(a => a.OwnerID == _cust.CustomerID).Future();
  var _phones = phones.ToList();
  var _addresses = addresses.ToList()
  var _cust2 = context.Customers.FirstOrDefault(c => c.CustID == 1235); // Error happens here
}

```
Is there a way to prevent the reader from being closed or to cause the reader to revert to its original state or otherwise get the context back in the basic working state?

**Comment by JonathanMagnan** [comment]
Hello @christiangeorge ,

Thank you for reporting.

We will look at this issue this week.

Could you tell me which version of EF you are using (EF5, EF6, EF Core) to make sure to test with the right version?

Best Regards,

Jonathan

**Comment by christiangeorge** [comment]
Thank you for taking your time with this.

I am using
Microsoft.EntityFrameworkCore(1.1.2)
Microsoft.EntityFrameworkCore.SqlServer(1.1.2)
Z.EntityFramework.Plus.EFCore (1.6.6)

**Comment by JonathanMagnan** [comment]
Hello @christiangeorge ,

Just to give you a small update. We successfully reproduced this issue and found out what is causing it.

We believe we are very close to finding a permanent solution.

Best Regards,

Jonathan

**Comment by MaklaCof** [comment]
Same error when trying:
```
for (var i = 0; i < 1000; i++)
            {
                var parameter = this.context.ParameterParts
                    .Where(t => t.Id == model.parameterId)
                    .Select(t => new {
                        t.ParameterId
                    })
                    .Future();

                var value = this.context.ParameterValueParts
                    .Where(t => t.Id == model.valueId)
                    .Select(t => new
                    {
                        t.ParameterValueId
                    })
                    .Future();
                var val = value.First();   //error when i = 1 (second loop)
            }
```

**Comment by JonathanMagnan** [comment]
Hello @christiangeorge , @MaklaCof 

The v1.6.8 has been released, we have included a fix for the DataReader.

Please, reopen the issue if you still have the problem.

Best Regards,

Jonathan
