### ISSUE TITLE
Batch Delete not working with Where extension when using expression in predicate

### ISSUE THREAD

**Issue by Gazzo100uk** [zzzprojects/EntityFramework-Plus#188]
`      _context.Activities.Where(a => a.DateCreated < DateTime.UtcNow.AddDays(-7)).Delete();
`

does not generate a where clause in sql however the code below does

    var d = DateTime.UtcNow.AddDays(-7);
    _context.Activities.Where(a => a.DateCreated < d).Delete();

the sql code generated for the first example (a SQL:Batch in profiler as the statement has no parameters)

    
    DECLARE @rowAffected INT
    DECLARE @totalRowAffected INT

    SET @totalRowAffected = 0

    WHILE @rowAffected IS NULL
        OR @rowAffected > 0
        BEGIN
            DELETE TOP (1000)
            FROM    A
            FROM    [W].[tb_Act] AS A
                    INNER JOIN ( SELECT [a].[DateCreated], [a].[ActivityID]
    FROM [W].[tb_Act] AS [a]
                               ) AS B ON A.[ActivityID] = B.[ActivityID]

            SET @rowAffected = @@ROWCOUNT
            SET @totalRowAffected = @totalRowAffected + @rowAffected
        END

    SELECT  @totalRowAffected

the sql generated for the second example (an RPC:Completed in profiler - a statement with a parameter)

    exec sp_executesql N'
    DECLARE @rowAffected INT
    DECLARE @totalRowAffected INT

    SET @totalRowAffected = 0

    WHILE @rowAffected IS NULL
        OR @rowAffected > 0
        BEGIN
            DELETE TOP (4000)
            FROM    A
            FROM    [W].[tb_Act] AS A
                    INNER JOIN ( SELECT [a].[ActivityID]
    FROM [W].[tb_Act] AS [a]
    WHERE [a].[DateCreated] < @__d_0
                               ) AS B ON A.[ActivityID] = B.[ActivityID]

            SET @rowAffected = @@ROWCOUNT
            SET @totalRowAffected = @totalRowAffected + @rowAffected
        END

    SELECT  @totalRowAffected
    ',N'@__d_0 datetime',@__d_0='2017-07-17 11:21:07.277'

**Comment by JonathanMagnan** [comment]
Hello @Gazzo100uk ,

Thank you for reporting, we will look at this issue this week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Gazzo100uk ,

About the first statement:
`_context.Activities.Where(a => a.DateCreated < DateTime.UtcNow.AddDays(-7)).Delete();`

there is nothing we can do for now, this is a limitation from Entity Framework. You will have the same error without using our library:
`var list = ctx.Activities.Where(a => a.DateCreated < DateTime.UtcNow.AddDays(-7)).ToList();`

About the second statements:
```csharp
var d = DateTime.UtcNow.AddDays(-7);
_context.Activities.Where(a => a.DateCreated < d).Delete();
```

It works as expected on our side.

```csharp
using System;
using System.Data.Entity;
using System.Linq;
using System.Windows.Forms;

namespace Z.EntityFramework.Plus.Lab
{
    public partial class Form_Request_BatchDelete : Form
    {
        public Form_Request_BatchDelete()
        {
            InitializeComponent();

            // CLEAN
            using (var ctx = new EntityContext())
            {
                ctx.Activities.RemoveRange(ctx.Activities);
                ctx.SaveChanges();
            }

            // SEED
            using (var ctx = new EntityContext())
            {
                ctx.Activities.Add(new Activitiy {ColumnInt = 1, DateCreated = DateTime.Now.AddDays(-8)});
                ctx.Activities.Add(new Activitiy {ColumnInt = 2, DateCreated = DateTime.Now.AddDays(-7)});
                ctx.Activities.Add(new Activitiy {ColumnInt = 3, DateCreated = DateTime.Now.AddDays(-6)});
                ctx.SaveChanges();
            }

            // TEST
            using (var ctx = new EntityContext())
            {
                //var list = ctx.Activities.Where(a => a.DateCreated < DateTime.UtcNow.AddDays(-7)).ToList();
                var d = DateTime.UtcNow.AddDays(-7);
                ctx.Activities.Where(a => a.DateCreated < d).Delete();
            }
        }

        public class EntityContext : DbContext
        {
            public EntityContext() : base("CodeFirstEntities")
            {
            }

            public DbSet<Activitiy> Activities { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x => x.ToTable(GetType().DeclaringType != null ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class Activitiy
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }
            public DateTime DateCreated { get; set; }
        }
    }
}
```

Do I'm missing something to replicate this issue?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Gazzo100uk ,

Please reopen this issue if you can add more information.

Best Regards,

Jonathan
