### ISSUE TITLE
How to stack deferred values?

### ISSUE THREAD

**Issue by Immelstorn** [zzzprojects/EntityFramework-Plus#190]
Is there any possibility to stack few FutureValues for DeferredCount in the code like this:
```
users.ForEach(x =>
            {
                x.Prospects = db.Prospects.Where(p => p.UserId == x.Id).DeferredCount().FutureValue();
            });
```
I mean now it will produce a lot of queries, but how can I stack them and execute them at once?

**Comment by JonathanMagnan** [comment]
Hello @Immelstorn ,

We could add a `ExecuteBatch` method (or a similar name) to send all query pending.

So a code similar to this could work:

```csharp
users.ForEach(x =>
            {
                x.Prospects = db.Prospects.Where(p => p.UserId == x.Id).DeferredCount().FutureValue();
            });

QueryFutureManager.ExecuteBatch();
```

If you don't have a lot of prospects, I recommend you, however, to get all them at once (including some that you don't need).

```csharp
ctx.Prospects.GroupBy(x => x.Id).Select(x => new {Id = x.Key, Count = x.Count()}).ToDictionary(x => x.Id);
```
We are supposed to release a new version tomorrow. We will try to include this feature in it.

Best Regards,

Jonathan

**Comment by Immelstorn** [comment]
@JonathanMagnan unfortunately I have a lot of prospects, so I can't get them at once. 
If you will release this feature tomorrow - it would be great, thanks, I'll wait for this release. Thanks

**Comment by JonathanMagnan** [comment]
The `ExecuteBatch(DbContext)` method has been added.

It should be released within a few hours.

You will have however to modify a little bit your code. Since you implicitly cast the FutureValue as int, it will get resolved every time.

```csharp
Dictionary<int, QueryFutureValue<int>> dict;

users.ForEach(x =>
{
	dict.Add(int, db.Prospects.Where(p => p.UserId == x.Id).DeferredCount().FutureValue());
});

QueryFutureManager.ExecuteBatch(db); // Not necessary anymore... since the first implicit conversion will resolve all pending queries

users.ForEach(x =>
{
	x.Prospects = dict[x.Id];
})
```

**Comment by JonathanMagnan** [comment]
Hello @Immelstorn 

The v1.6.7 has been released.

Let me know if you still have the issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Immelstorn ,

We will close this issue since we got no confirmation.

Please reopen it if you still have the issue,

Best Regards,

Jonathan
