### ISSUE TITLE
Problem with batch update

### ISSUE THREAD

**Issue by Immelstorn** [zzzprojects/EntityFramework-Plus#191]
Hello again, I have a problem with Update method.
I have something like this
```
 context.Table
        .Where(x => x.Condition == true)
        .Update(x => new TableEntity
        {
            Property1 = x.Property2
        });
```

and this library generates SQL similar to this
```
UPDATE A 
SET A.[Property1] =  B.[Property2] AS [Property2]
FROM [dbo].[Table] AS A
INNER JOIN ( SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Property1] AS [Property1], 
    [Extent1].[Property2] AS [Property2]
    FROM [dbo].[Table] AS [Extent1]
    WHERE (Condition == 1) AS B ON A.[Id] = B.[Id]        
```

it can't be executed because ` AS [Property2]` in the second row. It throws `Incorrect syntax near the keyword 'AS'.`

Can you do something with it?

For example here is SQL that is generated by EF.Extended from the same code:

```
UPDATE [dbo].[Table] SET 
[Property1] = [Property2]  
FROM [dbo].[Table] AS j0 INNER JOIN (
SELECT 
    [Extent1].[Id] AS [Id]
    FROM [dbo].[Table] AS [Extent1]
    WHERE ([Condition == 1)
) AS j1 ON (j0.[Id] = j1.[Id])
```
and it works

**Comment by JonathanMagnan** [comment]
Hello @Immelstorn ,

Thank you for reporting.

We will look at this issue this week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Immelstorn ,

The issue has been successfully fixed.

The fix will be released within a few hours.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Immelstorn 

The v1.6.7 has been released.

Let me know if you still have the issue.

Best Regards,

Jonathan
