### ISSUE TITLE
ToListAsync for QueryFutureEnumerable?

### ISSUE THREAD

**Issue by Immelstorn** [zzzprojects/EntityFramework-Plus#197]
Hi there, do you have plans to implement async for Future Queries?
I can see this issue https://github.com/zzzprojects/EntityFramework-Plus/issues/13 with pullrequest of this feature, but there is no such thing in the latest release. So any chances it will appear later?

**Comment by JonathanMagnan** [comment]
Hello @Immelstorn ,

We will try to look at it during the weekend,

It seems that @mattmaslin already provided us all the code needed as you said.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Immelstorn ,

Just to let you know async method for Future Queries will be part of the next released. So it should be available for next Monday.

Best Regards,

Jonathan

**Comment by Immelstorn** [comment]
Great news, thanks!

**Comment by JonathanMagnan** [comment]
Hello @Immelstorn  

The v1.6.8 has been released, we have included async method in this version.

Best Regards,

Jonathan
