### ISSUE TITLE
BatchDelete Executing Interceptor not being called

### ISSUE THREAD

**Issue by NetMastr5** [zzzprojects/EntityFramework-Plus#198]
the executing interceptor is not being called on Batch Deletes when the database type is one of the known ones (Npgsql, MySql, Oracle, SqlCe) as the Executing Interceptor is called only in the else clause of the if/else block that is handling executing the command correctly per DB type.  This prevents logging executed commands on known DB types.

shared/Z.EF.Plus.BatchDelete.Shared/BatchDelete.cs lines 192-228

**Comment by JonathanMagnan** [comment]
Hello @NetMastr5 ,

You are right. We will fix this issue during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
The code has been fixed,

It will be included in the next release.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @NetMastr5 

The v1.6.8 has been released, we have moved the Executing event at the right place

Please, reopen the issue if you still have the problem.

Best Regards,

Jonathan
