### ISSUE TITLE
Query by JSON

### ISSUE THREAD

**Issue by Ma3yTa** [zzzprojects/EntityFramework-Plus#200]
Add support to query by json type

**Comment by JonathanMagnan** [comment]
Hello @Ma3yTa ,

Could you be a little bit more explicit in your request? Please, try to provide an example if you can.

Thank you,

Best Regards,

Jonathan

**Comment by Ma3yTa** [comment]
Hello @JonathanMagnan ,

Currently Postgres, MSSQL support JSON as column type and allow to query by this columns but there isn't support from ORM.

Maybe those links helps to understand:

https://blogs.msdn.microsoft.com/jocapc/2015/05/16/json-support-in-sql-server-2016/
https://www.postgresql.org/docs/9.3/static/functions-json.html
https://github.com/aspnet/EntityFramework/issues/4021

Thanks

**Comment by JonathanMagnan** [comment]
Thank you for the additional information.

To be honest, I don't think this request will be done soon. We have a lot of issues to fix first soon.

But we will let this request open for the future.

Best Regards,

Jonathan

**Comment by yildizseli** [comment]
Hello @JonathanMagnan ,

This kind of support would be very nice. Is there any improvement for this issue?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @yildizseli ,

Unfortunately, that's not in our short them plan: http://www.zzzprojects.com/roadmap

We are currently working on [.NET FIddle](https://dotnetfiddle.net/) to allows to run `Entity Framework` example on the web.

As said, I don't think this request will be done soon.

Best Regards,

Jonathan
