### ISSUE TITLE
MySql BatchUpdate building/replace sql with wrong alias

### ISSUE THREAD

**Issue by Martin-DC** [zzzprojects/EntityFramework-Plus#201]
when I use mysql, it will building a sql like this:

```mysql
`UPDATE `Cell` AS A
INNER JOIN ( SELECT
`Extent1`.`Id`, 
`Extent1`.`CompartmentId`, 
`Extent1`.`SequenceCode`, 
`Extent1`.`UniqueCode`, 
`Extent1`.`AllowMultipleSku`, 
`Extent1`.`LayerId`, 
`Extent1`.`ShelfId`, 
`Extent1`.`RowId`, 
`Extent1`.`AreaId`, 
`Extent1`.`DisableStatus`
FROM `Cell` AS `Extent1`
 WHERE `Extent1`.`Id` IN ( 'a4574a88-81c8-418f-8f55-8a33e8de899a' )
           ) AS B ON A.`Id` = B.`Id`
SET A.`UniqueCode` = 
`**Extent1**`.`UniqueCode``
```

you will found the alias Extent1 is invalid.
I found in the sourcecode
[master/src/shared/Z.EF.Plus.BatchUpdate.Shared/BatchUpdate.cs](https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.BatchUpdate.Shared/BatchUpdate.cs) at line 875,
 it should repalce the `Extent1` to 'B', but the replace dictionary is set as 
`   var listReplace = new List<string>()
                    {
                        "[Extent1]",
                        "[Extent2]",
                        "[Extent3]",
                        "[Extent4]",
                        "[Extent5]",
                        "[Extent6]",
                        "[Extent7]",
                        "[Extent8]",
                        "[Extent9]",
                        "[Filter1]",
                        "[Filter2]",
                        "[Filter3]",
                        "[Filter4]",
                        "[Filter5]",
                        "[Filter6]",
                    };`
the [Extent1] has replaced to `Extent1` before we do replace, so it can't be found in the dictionary.
I think this maybe is the root reason for mysql.
also remind batch delete.
if this is true, please fix it, thanks

**Comment by JonathanMagnan** [comment]
Hello @Martin-DC ,

Thank you for reporting,

We will look if by removing the square bracket from the dictionary if that additional cause problem.

We hope to release a fix this weekend.

Best Regards,

Jonathan

**Comment by Martin-DC** [comment]
Thanks @JonathanMagnan

**Comment by JonathanMagnan** [comment]
Hello @Martin-DC ,

The v1.6.8 has been released, we have added the same text with escaped character for MySQL. A better fix will be available in V2.x

Please, reopen the issue if you still have the problem.

Best Regards,

Jonathan
