### ISSUE TITLE
Global/Instance Filter with Include Filter against Interface 

### ISSUE THREAD

**Issue by mcgri** [zzzprojects/EntityFramework-Plus#204]
Hi

Since the last issue which I raised, I switched to eager loading and now EF builds one query instead of 20 small ones. Which is great improvement speedwise. 

However, now there is an issue.. My global filter applied only to the top level model and not applied to included children.

The filter:
  `  this.Filter<BaseModel>(q => q.Where(x =>  (x.CompanyId == companyId || x.IsGlobal==true) && x.IsDeleted == false));`

The BaseModel is a model which every model is extending. 

So..I need to have a global filter which will be applied for all Included children as well as parent model.

Something like:

`  this.Filter<BaseModel>(q => q.IncludeFIlter(x=>x.TChild.IsDeleted==false ).Where(x =>  (x.CompanyId == companyId || x.IsGlobal==true) && x.IsDeleted == false));`

Is it possible to apply the global filter on included children if the filter is for Interface/Base model?

My plan B is to rewrite all my Includes into IncludeFilter...but it is 500+ lines of code 

Thank you for your help.

**Comment by JonathanMagnan** [comment]
Hello @mcgri ,

Why not create two filters?

```csharp
this.Filter<BaseModel>(q => q.Where(x => (x.CompanyId == companyId || x.IsGlobal==true) && x.IsDeleted == false));
this.Filter<Children>(q => q.Where(x => x.TChild.IsDeleted==false));
```

Best Regards,

Jonathan

**Comment by mcgri** [comment]
Hi
I found that the filter will work with many-to-many relationships (lists) but won't be applied for one-to-one...
So , we Lest say we  have Student, ClassRoom, Books objects and all of them inherit from BaseModel

Classes:

  `
  
      BaseModel{
           int Id;
           bool IsDeleted;
         }


     Student:BaseModel{
            string Name;
            List<ClassRoom> ClassRooms;
       }


     ClassRoom:BaseModel{
         string Name;
         Book  BookName;
    }

    Book:BaseModel{
         string Name;
    }
`

In the model..a Student could have many Classrooms and each Classroom could have one book.
The filter will be:

```
SchoolContext{

  public SchoolContext(){

           this.Filter<BaseModel>(q => q.Where(x => (x.IsDeleted == false))
   }
   }

```

Query:
`
db.Students.Include(x=>x.Classroom.Select(y=>y.Book)).ToList();
`
The filter, in my reallife scenario,  will ignore all deleted students and all deleted classrooms,but will pull  deleted books (which inherit from the BaseModel too). 

Yes, I could create 50+ custom filters for all models, as you suggested..but I thought to ask if there some kind of setting which will force filter on all children. In end of the day, all models inherit from BaseModel and the filter is for BaseModel.

**Comment by JonathanMagnan** [comment]
Hello @mcgri ,

I have added this request for when we will rewrite the v2 version of this feature.

Unfortunately, we only allow filtering list currently as you have notified.

Best Regards,

Jonathan

**Comment by mcgri** [comment]
I see, thank you for your help.
