### ISSUE TITLE
Unit Testing Z Entity Framework Plus Extensions

### ISSUE THREAD

**Issue by CGBDSAPO** [zzzprojects/EntityFramework-Plus#207]
When using Z.EntityFramework.Plus extensions, I cannot find a way to mock/substitute what the context returns when any of the plus extensions, not just Future(), are being used. Everything I try throws a NullReferenceException within the z extensions future library.

Repository Example:
```
public Task<DocumentDomain> GetDocuments(int id)
{
  var futureQuery1 = _context.ReportTypes.Where(x => x.IsReadOnly).Future();
  var futureQuery2 = _context.Reports.Where(x => x.CreateDate < DateTime.Now.AddDays(-10)).Future();
  var futureQuery3 = _context.Person.DeferredFirstOrDefault(x => x.Id == id).FutureValue();

   return new DocumentDomain(futureQuery1.ToList(), futureQuery2.ToList(), futureQuery3.Value);
}
```

Unit Test Repository:

```
   [Fact]
    public async Task ShouldGetDocumentsForPerson1()
    {
       _context = Substitute.For<IMyDbContext>();
       _context.ReportTypes = new FakeDbSet();
       _context.ReportTypes.AddRange(GetFakeReportTypes());
       // ...etc..arrange for Reports and Person

       var repo = new DocumentRepository(_context);

       // CRASHES HERE ON futureQuery1 at .Future()
       var domain = await repo.GetDocuments(1); // fake id

       Assert.IsTrue(domain.Documents.Count > 0);
    }
```

Without using Futures it works fine. I've tried mocking out a few different ways but always get an error. Most of the time it's a "oops Z extensions encountered an error" exception.

I'm thinking it's because Z extensions is expecting a real ObjectContext but not sure how to overcome this. Has anyone experienced similar issues? Does anyone know of any solutions? Thanks.

**Comment by JonathanMagnan** [comment]
Hello @CGBDSAPO ,

Thank you for reporting, we will look at it during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @CGBDSAPO ,

The v1.6.10 has been released.

We added an `AllowQueryBatch` option.

When disabled, our library will no longer try to batch all queries.

Could you try it and let me know if that work with your muck context?

Best Regards,

Jonathan

**Comment by sztrzask** [comment]
Hi, 

any more general guidelines/options on Unit Testing? E.g. how to UT code that contains .DeleteAsync on FakeDbContext (essentially in-memory context) on EF6?

**Comment by JonathanMagnan** [comment]
Hello @sztrzask ,

Unfortunately no, when we will create the v2.x of our library, we will try to improve it by keeping in mind people that make some unit test with Fake context.

Best Regards,

Jonathan

**Comment by DevelAx** [comment]
How to vote for this issue?
