### ISSUE TITLE
Datetime2 in batch update

### ISSUE THREAD

**Issue by MitaTarp** [zzzprojects/EntityFramework-Plus#209]
When using datetime2 in the database and I try to update it with a value before 1753-01-01 I get an System.Data.SqlTypes.SqlTypeException. My entity model is mapping with correct mapping to the datetime2 sql type.

**Comment by JonathanMagnan** [comment]
Hello @MitaTarp ,

Thank you for reporting,

We will investigate this issue this week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @MitaTarp ,

The v1.6.12 has been released.

You should no longer have this issue.

Please, reopen this issue if it has not been fixed correctly.

Best Regards,

Jonathan

**Comment by MitaTarp** [comment]
Hello @JonathanMagnan 

Thank you for fixing this issue so quickly.
Best regards
Miki
