### ISSUE TITLE
IncludeOptimized vs IncludeFilter

### ISSUE THREAD

**Issue by GFoley83** [zzzprojects/EntityFramework-Plus#21]
Hi there, just discovered this library. Looks great so far!
One thing I'm not clear on is the difference between IncludeOptimized vs IncludeFilter.
Under what scenario should one be used over the other?
Are there scenarios whereby using either of these methods could result in a degraded performance over the regular `include`?

**Comment by zzzprojects** [comment]
Hello Gavin,

That's an excellent question.

Usually, IncludeOptimized will always be faster than IncludeFilter unless you forget to add some index in your database!

## IncludeFilter
Does under the hood a projection.

This code
```csharp
ctx.Blogs
   .Where(x => x.IsActif)
   .IncludeFilter(x => x.Posts.Where(y => y.IsActif));    
```

Will be transformed into this code
```csharp
ctx.Blogs
   .Where(x => x.IsActif)
   .Select(x => {
      Result = x,
      Y => x.Posts.Where(y => y.IsActif)      
   }
   .ToList()
   .Select(x => x.Result);
```

## IncludeOptimized
Does under the hood multiple SQL queries (We batch them using our Query Future feature)

This code
```csharp
ctx.Blogs
   .Where(x => x.IsActif)
   .IncludeOptimized(x => x.Posts.Where(y => y.IsActif));    
```

Will be transformed into this code
```csharp
ctx.Blogs
   .Where(x => x.IsActif)
   .Future();

ctx.Blogs
   .Where(x => x.IsActif)
   .Select(x => x.Posts.Where(y => y.IsActif))
   .Future();
```

## Summary
IncludeFilter does what you should expect exactly from EF6: One big query! 

IncludeOptimized does what Include in EF Core is now exactly doing: Multiple small queries

From my knowledge, neither of these methods will result to a degraded performance over regular **Include**. In fact, you should always have equal or better performance.

We are currently re-written all our documentation (for all our products), we hope to release it at the start of September, we will for sure include a topic about this question.

Let me know if my answer is clear enough or you want more explication.

**Comment by GFoley83** [comment]
Excellent stuff. Exactly what I needed. Thanks!
