### ISSUE TITLE
Update and Delete failure with oracle varchar2 field

### ISSUE THREAD

**Issue by bofuqiang** [zzzprojects/EntityFramework-Plus#210]
I got a error with  oracle operation.
create a table in oracle
```sql
create table DATATEST
(
  id   NUMBER(4) not null,
  str1 VARCHAR2(50) not null,
  str2 VARCHAR2(50)
)
```

insert some datas
```sql
INSERT INTO "DATATEST" VALUES (1, 'a1', 'a1');
INSERT INTO "DATATEST" VALUES (2, 'a2', 'a2');
INSERT INTO "DATATEST" VALUES (3, 'a3', 'a3');
```
then use entityframework 6.1.3 update or delete the table data,

```cs 
 string s_test="asdasd";
	using (ManagerEntities ds=new ManagerEntities())
	{
		ds.DATATEST.Where (p => p.STR1 == s_test).Update (p =>  new DATATEST { STR2=s_test} );
}
```
 

or 

```cs
ds.DATATEST.Where (p => p.STR1 == s_test).Delete();
```

and i got a oracle failed   "OracleException:Unsupported column datatype"
if change the string variable to const.like this

```cs
ds.DATATEST.Where (p => p.STR1 == "123").Delete();
```

the code can run correctly.

isn't a bug for this ?

test environment :
oracle   11g 11.2.0.1.0 
oracel charset  NLS_LANGUAGE：AMERICAN
NLS_CHARACTERSET：ZHS16GBK
vs 2017 
entityframework 6.1.3
Oracle.ManagedDataAccess 12.2.1100
Oracle.ManagedDataAccess.EntityFramewor 12.2.1100
Z.EntityFramework.Plus.EF6 1.6.10

**Comment by JonathanMagnan** [comment]
Hello @bofuqiang ,

Thank you for reporting,

We will look at it this week,

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @bofuqiang  ,

The v1.6.12 has been released.

You should no longer have this issue.

Please, reopen this issue if it has not been fixed correctly.

Best Regards,

Jonathan
