### ISSUE TITLE
Feature request: add support for Sqlite

### ISSUE THREAD

**Issue by fgheysels** [zzzprojects/EntityFramework-Plus#212]
It would be nice to have support for Sqlite in this project.

**Comment by JonathanMagnan** [comment]
Hello @fgheysels ,

Some feature should already be supported for SQLite,

Is there a feature we would like to look in priority?

Best Regards,

Jonathan

**Comment by jandykwan** [comment]
when i use the delete function, it throw the following exception:

System.Data.SQLite.SQLiteException
  HResult=0x80004005
  Message=SQL logic error or missing database
near "DECLARE": syntax error

**Comment by JonathanMagnan** [comment]
Thank you, we will try to add Batch Update && Batch Delete this weekend,

Best Regards,

Jonathan

**Comment by jandykwan** [comment]
thank you very much.

**Comment by Hawxy** [comment]
Am also needing bulk delete support for sqlite. Was just about to implement it in my project before seeing this issue.

**Comment by JonathanMagnan** [comment]
Hello @Hawxy ,

Thank you for the remember.

We will look and implement it today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @fgheysels , @jandykwan , @Hawxy ,

The v.1.6.16 has been released.

The support for BatchDelete && BatchUpdate has been added for EF5 and EF6

Feel free to reopen this issue or open a new issue if you have some problem with it.

Best Regards,

Jonathan

**Comment by Hawxy** [comment]
@JonathanMagnan Thanks! Does this work for EFCore too? I don't use EF5/EF6

**Comment by JonathanMagnan** [comment]
Not yet, I will try to add the support to EF Core later today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello  @Hawxy ,

The v.1.6.17 has been released.

The support for BatchDelete && BatchUpdate has been added for EF Core as well

Feel free to reopen this issue or open a new issue if you have some problem with it.

Best Regards,

Jonathan
