### ISSUE TITLE
Nullable int comparison

### ISSUE THREAD

**Issue by huer12** [zzzprojects/EntityFramework-Plus#214]
This query works without EF Plus:
```
 int? siteId = null;
 var result = _dbContext.Sites.Where(s => siteId == s.SiteId).ToList();
```

if I add this line (from QueryInterceptorFilterExtensions):
         `   this.Filter<ISoftDeletable>(q => q.Where(a => !a.IsDeleted));`
then it does not work anymore, because the generated SQL is something like 'siteId = NULL' instead of 'siteId IS NULL'

As a workaround I can use   
`var result = _dbContext.Sites.Where(m => siteId == null ? m.SiteId == null : siteId == m.SiteId).ToList();`
which is nasty.

**Comment by JonathanMagnan** [comment]
Hello @huer12 ,

Thank you for reporting,

We will try to look at it next week.

Best Regards,

Jonathan

**Comment by huer12** [comment]
Hi Jonathan
Did you already find some time to look at it?
Regards,
Roman

**Comment by JonathanMagnan** [comment]
Hello @huer12 ,

Sorry for the delay and thank you for the remember. I have fixed this issue today.

The problem was because the right DbQueryCommandTree constructors to use was not part of the EF 6.0.0 but added later.

The fix will be available for next Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @huer12 ,

The v1.6.20 has been released.

The issue should be fixed,

Best Regards,

Jonathan

**Comment by huer12** [comment]
Thanks a lot, I verified it and it works.
