### ISSUE TITLE
DeleteAsync() fails with column does not exist

### ISSUE THREAD

**Issue by allanhaywood** [zzzprojects/EntityFramework-Plus#215]
This is the original code:

RemoveRange code (works):

                var generatedRows = _db.PhenoDataPoints
                        .Where(dp => dp.FieldGuid.Equals(phenoFieldGuid) 
                                && dp.DataPointType == PhenoDataPointType.Generated 
                                && affectedRows.Contains(dp.RecordId));
                _db.PhenoDataPoints.RemoveRange(generatedRows);
                await _db.SaveChangesAsync();

and the sql it generates on the first statement (setting generatedRows):
SELECT "Extent1"."record_id" FROM "pheno_prod"."pheno_datapoints" AS "Extent1" WHERE ("Extent1"."field_guid" = @p__linq__0 OR "Extent1"."field_guid" IS NULL AND @p__linq__0 IS NULL) AND 1 = CAST ("Extent1"."datapoint_type" AS int4) AND ("Extent1"."raw_value" IN (E'MINIMALLY CLASSIC') AND "Extent1"."raw_value" IS NOT NULL)

and the sql it generates on the second statement (RemoveRange):
SELECT CAST (NULL AS int8) AS "C1", CAST (NULL AS varchar) AS "C2", CAST (NULL AS varchar) AS "C3", CAST (NULL AS varchar) AS "C4", CAST (NULL AS varchar) AS "C5", CAST (NULL AS varchar) AS "C6", CAST (NULL AS int8) AS "C7", CAST (NULL AS varchar) AS "C8", CAST (NULL AS varchar) AS "C9", CAST (NULL AS numeric) AS "C10", CAST (NULL AS numeric) AS "C11", CAST (NULL AS timestamp) AS "C12", CAST (NULL AS varchar) AS "C13", CAST (NULL AS varchar) AS "C14", CAST (NULL AS varchar) AS "C15", CAST (NULL AS bool) AS "C16", CAST (NULL AS varchar) AS "C17", CAST (NULL AS int4) AS "C18", CAST (NULL AS int4) AS "C19" FROM (SELECT 1 AS "C") AS "SingleRowTable1" WHERE TRUE = FALSE

The above is what works so far.

Below is where I am having the issue.

This is the updated code to use DeleteAsync() instead:

DeleteAsync code (doesn't work):

                await _db.PhenoDataPoints
                        .Where(dp => dp.FieldGuid.Equals(phenoFieldGuid) 
                                && dp.DataPointType == PhenoDataPointType.Generated 
                                && affectedRows.Contains(dp.RecordId)).DeleteAsync(x => x.BatchSize = 5000);
                await _db.SaveChangesAsync();

This is the sql that it generates and runs when there is an error:

DELETE FROM "pheno_prod"."pheno_datapoints" AS A
USING ( SELECT CAST (NULL AS int8) AS "C1" FROM (SELECT 1 AS "C") AS "SingleRowTable1" WHERE TRUE = FALSE ) AS B WHERE A."pheno_data_point_id" = B."pheno_data_point_id"

Failed in 43 ms with error: ERROR: 42703: column b.pheno_data_point_id does not exist

NOTE: I have used DeleteAsync without an issue where the where clause is simpler( just comparing two values).

**Comment by ahaywood79** [comment]
Sorry about the typo in the title. Should be DeleteAsync, it won't let me change it.

**Comment by allanhaywood** [comment]
Sorry about the typo in the title. Should be DeleteAsync, it won't let me change it.

**Comment by allanhaywood** [comment]
@zzzprojects @JonathanMagnan Any chance someone could take a quick look at this one, and at least give an initial take?

Thank you.

**Comment by JonathanMagnan** [comment]
Hello @allanhaywood ,

Sorry I completely forget to assign it to myself and add it to the road map. Thank you for the remember!

I will for sure check it in priority during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @allanhaywood ,

This issue happens when the list `affectedRows` is empty.

We successfully fixed it.

The fix will be part of the release we will make on Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @allanhaywood ,

The v1.6.20 has been released which includes this fix

Please reopen the issue if I have not fixed it correctly.

Best Regards,

Jonathan
