### ISSUE TITLE
Audit: Excluding Entity Relationships 

### ISSUE THREAD

**Issue by LRFalk01** [zzzprojects/EntityFramework-Plus#216]
I have entities excluded successfully as defined in the [wiki](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Audit-%7C-Entity-Framework-Audit-Trail-Context-and-Track-Changes#exclude--include-entity).

My issue is that Relationship changes (RelationshipDeleted/Added) unrelated to included entities are still audited. Is there a way to make this work so that only relationship changes related to included entities are audited?

**Comment by JonathanMagnan** [comment]
Hello @LRFalk01 ,

Thank you for reporting,

We will try to investigate if there is a way this weekend,

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @LRFalk01 ,

We started to investigate this issue. We can now retrieve successfully both entity used in the relationship.

The main question remaining is the default behavior: Should we exclude by default if one side of the relationship is excluded or if both side!

No matter the final decision, we will add an option to allow both case.

Best Regards,

Jonathan

**Comment by LRFalk01** [comment]
Wow. Man, this is awesome news, and super quick turn around. Thank you guys so much for all of your hard work.

**Comment by JonathanMagnan** [comment]
Hello @LRFalk01  ,

The v1.6.12 has been released.

A relationship is now automatically if both sides (left && right) are excluded. 

You can also exclude them for only one side by setting the option `ExcludeRelationshipIfOneExcluded` to true.

Please, reopen this issue if it has not been fixed correctly.

Best Regards,

Jonathan

**Comment by LRFalk01** [comment]
Thanks !

I'll check it out.

**Comment by LRFalk01** [comment]
Works just as I expected to. Thank you so much for this rapid turn around.
