### ISSUE TITLE
Runtime error with future queries in EF Core 2.0 (v1.6.11)

### ISSUE THREAD

**Issue by mtrainham** [zzzprojects/EntityFramework-Plus#218]
I'm using the Future LINQ extension method to run separate queries in one trip to the database. Our tests are running against an in memory database, and we are getting the following runtime error in v1.6.11 using EF Core 2.0:

`
System.NullReferenceException : Object reference not set to an instance of an object.
`

`
at Z.EntityFramework.Plus.InternalExtensions.GetInMemoryContext[T](IQueryable'1 source)
`
`
   at Z.EntityFramework.Plus.QueryFutureExtensions.Future[T](IQueryable'1 query)
`

The query I'm running looks like this:

```csharp
var query = db.Set<MyEntity>().Where(x => false);

var myEntities = query.Include(x => x.Property1).Future();

query.Include(x => x.Property2).Future();

var result = myEntities.ToList();
```

It's blowing up on the first `.Future()` call.

**Comment by JonathanMagnan** [comment]
Hello @mtrainham ,

Thank you for reporting, we will try to look at it during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @mtrainham ,

The issue has been fixed, it should be released along with some other fix before Monday.

Best Regards,

Jonathan

**Comment by mtrainham** [comment]
Thanks @JonathanMagnan ! I can't believe how fast you took care of these issues. It's much appreciated.

**Comment by JonathanMagnan** [comment]
Hello @MitaTarp ,

The v1.6.12 has been released.

You should no longer have this issue.

Please, reopen this issue if it has not been fixed correctly.

Best Regards,

Jonathan

**Comment by mtrainham** [comment]
@JonathanMagnan, I can confirm my tests now pass with future queries. Thanks again for taking care of this so quickly.
