### ISSUE TITLE
.IncludeOptimized() and System.Data.Spatial.DbGeography issue

### ISSUE THREAD

**Issue by Iamcerba** [zzzprojects/EntityFramework-Plus#219]
EntityFramework-Plus version: **1.6.12**

```javascript

DbGeography currentLocation = DbGeography.PointFromText(
    $"Point({longitude} {latitude})",
    DbGeography.DefaultCoordinateSystemId
);

double distance = 10;

using (var context = new UserDbContext())
{
    IList<User> users = await context
        .Users
        .IncludeOptimized(e => e.Location)
        .Where(e => e.Location.LastLocation.Distance(currentLocation) <= distance)
        .ToListAsync();
}

```

**Actual result**: System.Data.SqlClient.SqlException (0x80131904): Operand type clash: sql_variant is incompatible with geography

**Expected result**: Correct result as with regular **.Include()**

**Comment by JonathanMagnan** [comment]
Hello @Iamcerba ,

Thank you for reporting. It looks quite similar to an issue we fixed a few days ago but for Oracle.

It's probably due because we don't correctly copy the type when copying the parameter from the query to our command.

We hope to fix it this weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Iamcerba ,

The v1.6.13 has been released.

All type should now work correctly including spatial type.

Please reopen this issue if we have not fixed it correctly.

Best Regards,

Jonathan
