### ISSUE TITLE
Will you support multiple levels for IncludeOptimized and IncludeFilter?

### ISSUE THREAD

**Issue by grifin85** [zzzprojects/EntityFramework-Plus#22]
Hi

Have you have plane add support multiple levels for IncludeOptimized and IncludeFilter? How in standart inslude

> include("Property.SubProperty")

**Comment by zzzprojects** [comment]
We already support somehow this feature.

You simply have to specify every level to make sure it included.

```csharp
ctx.IncludeFilter(x => x.Property)
   .IncludeFilter(x => x.Property.SubProperty);
```

Let me know if that answer correctly to your question.

**Comment by grifin85** [comment]
It's working it if property is class but not for collections

**Comment by zzzprojects** [comment]
Here is the code for collection

```csharp
ctx.IncludeFilter(x => x.Property)
   .IncludeFilter(x => x.Property.Select(y => y.SubProperty));
```

Let me know if that example is working for your question.

**Comment by grifin85** [comment]
Thank you for quickly answer and help. That help me.
