### ISSUE TITLE
Date format bug

### ISSUE THREAD

**Issue by yanjieyi** [zzzprojects/EntityFramework-Plus#221]
code:
![image](https://user-images.githubusercontent.com/29919408/29757171-7059e4b4-8bdc-11e7-9ebe-546b9171cbce.png)

Z.EntityFramework.Plus.EFCore
![image](https://user-images.githubusercontent.com/29919408/29757176-79204192-8bdc-11e7-89a4-c97ce87335b9.png)

Microsoft.EntityFrameworkCore
![image](https://user-images.githubusercontent.com/29919408/29757255-1188555a-8bdd-11e7-89b1-f26367de8ce9.png)

**Comment by JonathanMagnan** [comment]
Hello @yanjieyi ,

We will investigate this issue today, we recently fixed a very similar issue to it. Perhaps we forget to add this change to the EF Core version.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @yanjieyi  ,

The v1.6.13 has been released.

The issue should be fixed for EF Core.

Please reopen this issue if we have not fixed it correctly.

Best Regards,

Jonathan
