### ISSUE TITLE
Using EF 6, no RelationName is populated in AuditEntryProperty table

### ISSUE THREAD

**Issue by jackjwilliams** [zzzprojects/EntityFramework-Plus#222]
It is always empty, any idea why this may be?

EF 6.1

Using EntityFramework6.Npgsql provider

**Comment by JonathanMagnan** [comment]
Hello @jackjwilliams ,

RelationName is only populated when a relation is added or deleted.

By example, in a one to many scenarios and some child are added to the parent.

Feel free to reopen if you really believe there is an issue or you need more information on it.

Best Regards,

Jonathan
