### ISSUE TITLE
QueryFilterManager.Filter<Entity> not working for related entity 

### ISSUE THREAD

**Issue by sergeu90** [zzzprojects/EntityFramework-Plus#223]
Hi, everyone.I have a problem with QueryFilterManager.Filter when I to want include related entity.
```
 QueryFilterManager.Filter<Report>(q => q.Where(e => !e.IsDeleted));
 QueryFilterManager.Filter<Event>(q => q.Where(e => !e.IsDeleted));
```
Report has Event.
If I get Report child entity Event they not filtering.
Can you help me. Workaround for me.I use Ef core 1.1.2

**Comment by JonathanMagnan** [comment]
Hello @sergeu90 ,

Unlike EF6, EF Core doesn't have interceptor yet which make "impossible" to support included entities.

There is nothing we can really do until interceptor is implemented.

I recommend you to upgrade to EF Core 2.x which has their own filter feature now.

Let me know if that answer successfully to the issue even if no fix is provided.
Best Regards,

Jonathan

**Comment by sergeu90** [comment]
@JonathanMagnan  Thanks.I understood you

**Comment by amit-kumar2** [comment]
Hello @JonathanMagnan ,
I am facing the same issue. Is there a way to solve this using the EF Core 1.x and your library?

**Comment by JonathanMagnan** [comment]
Hello @amit-kumar2 ,

A fix will probably be soon available but only for EF Core 2.x

There is an issue in EF Core 1.x with `Cast` that make it not possible for us to code this features.

Best Regards,

Jonathan

**Comment by amit-kumar2** [comment]
Is there an alternative for me to use? Something as a workaround using the IncludeFilter etc.?

**Comment by JonathanMagnan** [comment]
The only way I know in EF Core 1.x is currently using projection but you will end with the N+1 queries issue. This issue will dramatically affect your application performance so I cannot recommend it.
