### ISSUE TITLE
DI support instead of / in addition to static methods

### ISSUE THREAD

**Issue by vzwick** [zzzprojects/EntityFramework-Plus#231]
Hi there,

I'm looking into using the library in a multitenant setup with tenant-scoped filters. Right now, I'm running into issues with the built-in filter cache that would probably be easily resolved if the EF+ filter decorator for `DbContext` ( or a factory method for it) could be instantiated via DI rather than via the current static class. 

Are there any plans for this? If not, I'll happily look into implementing this functionality and submitting a PR - in that case, a few pointers would be appreciated.

**Comment by JonathanMagnan** [comment]
Hello @vzwick ,

Which version of Entity Framework are you using? The answer may a lot vary depending of it.

For EF6, I would probably recommend you using https://github.com/zzzprojects/EntityFramework.DynamicFilters instead if within the same application, there is several tenant id.

The EF+ filter work well with global filter, but it's limited when using context filter due to not being able to control the Entity Framework execution plan Cache.

Best Regards,

Jonathan

**Comment by vzwick** [comment]
Hi @JonathanMagnan ,

I am indeed using EF6. 

After initially finding EntityFramework.DynamicFilters promising, I have unfortunately found it unusable for our case because of the "all filters are always global" approach. I understand per-tenant value providers could be implemented and `.SetFilterScopedParameterValue()` called, but that seems somewhat overcomplicated.

> it's limited when using context filter due to not being able to control the Entity Framework execution plan Cache.

While toying around with EF+ some more, I have discovered that calling `QueryFilterManager.ClearQueryCache(this);` in the `DbContext` constructor seems to solve the issue described in my opening post. That confirms your Execution Plan Cache suspicion, correct?

**Comment by JonathanMagnan** [comment]
Hello @vzwick ,

The method `QueryFilterManager.ClearQueryCache(this);` you discovered will clear the current cached plan, however, the same issue will eventually happen soon or later if you have your application that run multiple Tenant ID at the same time.

We tried a lot of solution like removing completely the cached plan but this was affecting by too much the performance.

What could be done is re-enabling a cache that will work directly on `DbSet`. It will support perfectly filtering for global and instance context but will not work with Included relation and lazy loading. Do you think this solution could fit in your scenario?

Best Regards,

Jonathan

**Comment by vzwick** [comment]
@JonathanMagnan ,

> however, the same issue will eventually happen soon or later if you have your application that run multiple Tenant ID at the same time.

Just for my understanding: `DbContext` shares the plan cache across instances and will be accessing it from different threads because of this?

> What could be done is re-enabling a cache that will work directly on DbSet. It will support perfectly filtering for global and instance context but will not work with Included relation (The Include method) and lazy loading. Do you think this solution could fit in your scenario?

This would definitely be a good start.

Many thanks for your input so far.
V.

**Comment by JonathanMagnan** [comment]
Hello @vzwick ,

Exactly, the Cached plan is shared across all instances.

I will try to re-add the old query filter probably under another name (not sure yet which one) this weekend or at the beginning of next week.

Best Regards,

Jonathan

**Comment by vzwick** [comment]
@JonathanMagnan

much appreciated, thanks!

**Comment by JonathanMagnan** [comment]
Hello @vzwick ,

Just to let you know we completed the addition of the old Query Filter which we renamed Query DbSetFilter.

We should release it probably on Monday or before.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @vzwick ,

The v1.7.0 has been released with the EF+ Query DbSetFilter

You can find a small documentation here: https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Query-DbSetFilter

Please report us any problem as it's a very big change on our side.

Best Regards,

Jonathan

**Comment by vzwick** [comment]
@JonathanMagnan thank you very much for the stellar support. I'll make sure to check out the changes and report back.

BR,
V.

**Comment by JonathanMagnan** [comment]
Closing Comment: Old filter release
