### ISSUE TITLE
Second level cache over two projects

### ISSUE THREAD

**Issue by SimonHostettler** [zzzprojects/EntityFramework-Plus#233]
Hello,

lets say there are 3 project, Backend, Frontend and a Business Layer. Backend and Frontend are both a Website in the IIS with different App pools which talks with the same business layer. (The DbContext is injected with Ninject)

Is there any strategy to clear the cache in the Backend but also removes the cache from the Frontend? Let say in the backend a user saves something and with e.g. QueryCacheManager.ExpireAll(); the cached is cleared but only in the Backend not Frontend. 

PS: i know this is more a generall problem but not a Entity Framework plus problem but i would really appreciate idea or strategy if something like this is possible

thx simon

**Comment by JonathanMagnan** [comment]
Hello @SimonHostettler ,

Your requirement look like to be a distributed cache.

Honestly, I never used a distributed cache so I'm probably not the right person to give you the right direction. 

I believe `Redis` and `NCache` are some popular caching for it.

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by SimonHostettler** [comment]
Hello Jonathan, 

thx for the answer, i think thats excactly the key word "distributed cache".  Ill start looking into that.
