### ISSUE TITLE
Global Filters not binding to parameters & Context Filter memory leak

### ISSUE THREAD

**Issue by thommo** [zzzprojects/EntityFramework-Plus#234]
There seems to be a bug when using the global filters. If I define a global filter that requires a parameter (such as a date), an exception is thrown when I execute the query. The exception is a null reference exception (QueryFilterInterceptorDbProjectExpression line 57) due to the QueryFilterInterceptorDbProjectExpression.ParameterCollection being null. If the filter contains no parameters then the query executes correctly.

It seems that the ApplyFilter method in QueryFilterInterceptorDbScanExpression fails to assign the ParameterCollection when using a global filter.

If I use a context filter instead, the ApplyFilter method does assign the ParameterCollection and the filter executes correctly. However, there is a memory leak when using context filters, which renders these filters unusable.

I have modified the library to assign the ParameterCollection in the same way as is done for context filters. This seems to work and there are no memory leaks. I cloned line 123 of QueryFilterInterceptorDbScanExpression.cs and inserted it before line 95:

visitor.ParameterCollection = QueryFilterManager.DbExpressionParameterByHook[expression2];

If this is a valid fix could you please apply it to your next release.

**Comment by JonathanMagnan** [comment]
Hello @thommo ,

Thank you for reporting.

I have successfully reproduced it and fixed it with your proposed fix.

It will be included in the next release that will happen this night or tomorrow.

Best Regards,

Jonathan

**Comment by thommo** [comment]
Thanks for the quick update Jonathan! Any luck on the memory leak for the context filters?

**Comment by JonathanMagnan** [comment]
Oops! no, I forget to look at this one ;)

Could you tell me why you believe there is a memory leak? Perhaps that will help me to getting started about this issue.

Best Regards,

Jonathan

**Comment by thommo** [comment]
Hi Jonathan, here is an extract from a test app that leaks.

        public void ExecuteQueryFilter()
        {
            var statusDate = DateTime.Today;

            if (context.Filter("EffectiveDateFilter") == null)
                context.Filter<IDateConstrained>("EffectiveDateFilter", q => q.Where(x => x.StartDate <= statusDate && x.EndDate >= statusDate));

            var qry =
                from c in context.Components
                join cn in context.ComponentNames on c.LinkId equals cn.ComponentId
                select cn;

            var list = qry.ToList();
        }

I put a filter on the IDateConstrained interface. It's leaking about 5k per call. I'm doing a garbage collection after each call to get consistent results. Also, I have to call QueryFilterManager.ClearQueryCache(context) when I dispose the context. Without this the leak is worse (about 35k per call). In our real code we are leaking nearly 500k per request, so we run out of memory pretty quickly.

Let me know if there are any more details I can provide.

**Comment by JonathanMagnan** [comment]
Hello @thommo ,

The v1.6.21 has been released for the Global Filter issue,

I will try to look for the memory leak later this week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @thommo ,

We started to investigate this issue.

`It's leaking about 5k per call`, do you mean it take an additional 5MB of memory per call?

On our side, everything seems fine. It's true that every new query will add a new `Query Plan` in the `QueryCacheManager`. But it's limited to like 1000 `Query Plan` and will make the cleanup by themselves.

By example, should the following code have a memory leak or we are missing something?

```csharp
using System.Data.Entity;
using System.Linq;
using System.Reflection;
using System.Windows.Forms;

namespace Z.EntityFramework.Plus.Lab
{
    public partial class Form_Request_MemoryLeak : Form
    {
        public Form_Request_MemoryLeak()
        {
            InitializeComponent();

            // CLEAN
            using (var context = new EntityContext())
            {
                context.EntitySimples.RemoveRange(context.EntitySimples);
                context.SaveChanges();
            }

            // SEED
            using (var context = new EntityContext())
            {
                // We doesn't need to seed in this scenario?
            }

            // TEST
            for (int i = 0; i < 1000; i++)
            {
                using (var ctx = new EntityContext())
                {
                    ctx.Filter<IObjectWithSoftDelete>(x => x.Where(y => !y.IsDeleted));

                    var list = ctx.EntitySimples.ToList();
                }
            }

            using (var ctx = new EntityContext())
            {
                var objectContext = ctx.GetObjectContext();
                var metaWorkspace = objectContext.MetadataWorkspace;

                var getQueryCacheManagerMethod = metaWorkspace.GetType().GetMethod("GetQueryCacheManager", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                var getQueryCacheManager = getQueryCacheManagerMethod.Invoke(metaWorkspace, null);
            }
        }

        public class EntityContext : DbContext
        {
            public EntityContext() : base("CodeFirstEntities")
            {
            }

            public DbSet<EntitySimple> EntitySimples { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x => x.ToTable(GetType().DeclaringType != null ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public interface IObjectWithSoftDelete
        {
            bool IsDeleted { get; set; }
        }

        public class EntitySimple : IObjectWithSoftDelete
        {
            public int ID { get; set; }

            public int ColumnInt { get; set; }

            public bool IsDeleted { get; set; }
        }
    }
}

```

**Comment by thommo** [comment]
Hi Jonathan, when I run the code you posted, it leaks about 12.5KB (12500 bytes) per query. If I comment out the ctx.Filter line there are no leaks. When I changed the loop to iterate 100000 times it leaked all the way, eventually consuming over 1GB memory.

I'm using EF 6.1.3, which is the latest nuget package and .NET 4.6.2. I ran your code in a simple Console app. Do you not see the same problem? I'm not sure what else I can provide to help -- your code behaves just like my code.

Regards,
Mike.

**Comment by JonathanMagnan** [comment]
Hello @thommo ,

Yes, I get the same behavior than you.

One problem is the Entity Framework `QueryCacheManager` run the `Eviction` every each minute. So if you have a lot of calls, you may run out of memory before the QueryCacheManager cleanup some query plan that has been cached.

That's something that doesn't happen with the old Query Filter (the one used for EF5 and EF Core). Oh well, I should never have modified it to try to support more but now it's too late ;)

As said, I will try to restore under a different name the old Query Filter. I'm not sure what I can really do with the current filter! So many problems with it ;(

Best Regards,

Jonathan

**Comment by thommo** [comment]
Hi Jonathan, thanks for your investigation. One question occurs to me. Why is the EF QueryCacheManager filling up when I'm executing the same query multiple times? Shouldn't it just have one query in the cache?

Regards,
Mike.

**Comment by JonathanMagnan** [comment]
From what I remember and to make it short,

One major problem of Query Filter using interceptor is interceptor are only fired if the caching plan of the query is not yet found in the `QueryCacheManager`

So to apply filter from interceptor in the way I made it, every filtered query are currently unique. Until yesterday, I though the `QueryCacheManager` was auto evicting cached plan when over the limit `1000` but I was wrong.

Unfortunately, I don't count the amount of hundreds hours I tried to improve and fix this features when I introduced Query Filter via `Interceptor` instead of the way I made it in EF5/EF Core. So at one point, I had to give up the way I made it and take a break from it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @thommo ,

Just to let you know we completed the addition of the old Query Filter which we renamed `Query DbSetFilter`.

We should release it probably on Monday or before.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @thommo ,

The v1.7.0 has been released with the EF+ Query DbSetFilter

You can find a small documentation here: https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Query-DbSetFilter

Please report us any problem as it's a very big change on our side.

Best Regards,

Jonathan

**Comment by thommo** [comment]
Hi Jonathan, thanks for the update. We'll give the update a go and let you know how it goes. 
Thanks again for being so responsive.

Cheers,
Mike.

**Comment by JonathanMagnan** [comment]
Closing comment: Old filter released
