### ISSUE TITLE
BatchDelete Where ignored

### ISSUE THREAD

**Issue by wernerbarnard** [zzzprojects/EntityFramework-Plus#240]
Hi,

I have the following:
```
        public virtual async Task<int> DeleteAsync(Expression<Func<TE, bool>> predicate)
        {
            return await DbSet.Where(predicate).DeleteAsync();
        }
```

Used like this:
```
await _repo.DeleteAsync(d => d.DealType.Equals(cmd.Type));
```

Issue is, my where statement is being ignored and all contents of the database is being deleted.  cmd.Type is specific in the above example, and the DB contains 3 different DealType's from the above.... so those aspects shouldn't be an issue.

Am I using it correctly?  Looking for the fastest way to delete a few 100k records without loading them first.

Has anyone experienced this issue?

**Comment by JonathanMagnan** [comment]
Hello @wernerbarnard ,

Which version of Entity Framework are you using? Which database provider?

Do you think you could reproduce the issue using the following code?

```csharp
using System;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Z.EntityFramework.Plus.Lab
{
    public partial class Form_Request_BatchDelete_WhereIgnored : Form
    {
        public enum TypeValue
        {
            A,
            B,
            C
        }

        public Form_Request_BatchDelete_WhereIgnored()
        {
            InitializeComponent();

            // CLEAN
            using (var context = new EntityContext())
            {
                context.EntitySimples.RemoveRange(context.EntitySimples);
                context.SaveChanges();
            }

            // SEED
            using (var context = new EntityContext())
            {
                context.EntitySimples.Add(new EntitySimple {IntValueToDelete = 1, TypeToDelete = TypeValue.A});
                context.EntitySimples.Add(new EntitySimple {IntValueToDelete = 2, TypeToDelete = TypeValue.B});
                context.EntitySimples.Add(new EntitySimple {IntValueToDelete = 1, TypeToDelete = TypeValue.A});
                context.SaveChanges();
            }

            // TEST
            using (var context = new EntityContext())
            {
                var entitySimpleWithValue = new EntitySimple {IntValueToDelete = 1, TypeToDelete = TypeValue.A};

                var r1 = DeleteAsync(context, simple => simple.IntValueToDelete.Equals(entitySimpleWithValue.IntValueToDelete)).Result;

                var list = context.EntitySimples.ToList();
            }
        }

        public virtual async Task<int> DeleteAsync(EntityContext context, Expression<Func<EntitySimple, bool>> predicate)
        {
            return await context.EntitySimples.Where(predicate).DeleteAsync().ConfigureAwait(false);
        }

        public class EntityContext : DbContext
        {
            public EntityContext() : base("CodeFirstEntities")
            {
            }

            public DbSet<EntitySimple> EntitySimples { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x => x.ToTable(GetType().DeclaringType != null ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class EntitySimple
        {
            public int ID { get; set; }

            public TypeValue TypeToDelete { get; set; }

            public int IntValueToDelete { get; set; }
        }
    }
}
```

**Comment by wernerbarnard** [comment]
Hi,
Apologies.  Using .net core 2.0 and the latest ef core thats not pre-release, and using Sql Server.
Will check, thanks
		
		

		
	




On Tue, Sep 19, 2017 at 8:28 PM +0200, "Jonathan Magnan" <notifications@github.com> wrote:












Hello @wernerbarnard ,


Which version of Entity Framework are you using? Which database provider?


Do you think you could reproduce the issue using the following code?
using System;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Z.EntityFramework.Plus.Lab
{
    public partial class Form_Request_BatchDelete_WhereIgnored : Form
    {
        public enum TypeValue
        {
            A,
            B,
            C
        }

        public Form_Request_BatchDelete_WhereIgnored()
        {
            InitializeComponent();

            // CLEAN
            using (var context = new EntityContext())
            {
                context.EntitySimples.RemoveRange(context.EntitySimples);
                context.SaveChanges();
            }

            // SEED
            using (var context = new EntityContext())
            {
                context.EntitySimples.Add(new EntitySimple {IntValueToDelete = 1, TypeToDelete = TypeValue.A});
                context.EntitySimples.Add(new EntitySimple {IntValueToDelete = 2, TypeToDelete = TypeValue.B});
                context.EntitySimples.Add(new EntitySimple {IntValueToDelete = 1, TypeToDelete = TypeValue.A});
                context.SaveChanges();
            }

            // TEST
            using (var context = new EntityContext())
            {
                var entitySimpleWithValue = new EntitySimple {IntValueToDelete = 1, TypeToDelete = TypeValue.A};

                var r1 = DeleteAsync(context, simple => simple.IntValueToDelete.Equals(entitySimpleWithValue.IntValueToDelete)).Result;

                var list = context.EntitySimples.ToList();
            }
        }

        public virtual async Task<int> DeleteAsync(EntityContext context, Expression<Func<EntitySimple, bool>> predicate)
        {
            return await context.EntitySimples.Where(predicate).DeleteAsync().ConfigureAwait(false);
        }

        public class EntityContext : DbContext
        {
            public EntityContext() : base("CodeFirstEntities")
            {
            }

            public DbSet<EntitySimple> EntitySimples { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x => x.ToTable(GetType().DeclaringType != null ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class EntitySimple
        {
            public int ID { get; set; }

            public TypeValue TypeToDelete { get; set; }

            public int IntValueToDelete { get; set; }
        }
    }
}

**Comment by JonathanMagnan** [comment]
Here is the code updated for .NET Core 2.x

```csharp
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Z.Test.EntityFramework.Plus;

namespace Z.EntityFramework.Plus.Lab.EFCore20
{
    public class Request_BatchDelete_WhereIgnored
    {
        public static void Execute()
        {
            // CLEAN
            using (var context = new EntityContext())
            {
                context.EntitySimples.RemoveRange(context.EntitySimples);
                context.SaveChanges();
            }

            // SEED
            using (var context = new EntityContext())
            {
                context.EntitySimples.Add(new EntitySimple {IntValueToDelete = 1});
                context.EntitySimples.Add(new EntitySimple {IntValueToDelete = 2});
                context.EntitySimples.Add(new EntitySimple {IntValueToDelete = 1});
                context.SaveChanges();
            }

            // TEST
            using (var context = new EntityContext())
            {
                var entitySimpleWithValue = new EntitySimple {IntValueToDelete = 1};

                var r1 = DeleteAsync(context, simple => simple.IntValueToDelete.Equals(entitySimpleWithValue.IntValueToDelete)).Result;

                var list = context.EntitySimples.ToList();
            }
        }

        public static async Task<int> DeleteAsync(EntityContext context, Expression<Func<EntitySimple, bool>> predicate)
        {
            return await context.EntitySimples.Where(predicate).DeleteAsync().ConfigureAwait(false);
        }

        public class EntityContext : DbContext
        {
            public DbSet<EntitySimple> EntitySimples { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(new SqlConnection(My.Config.ConnectionStrings.TestDatabase));

                base.OnConfiguring(optionsBuilder);
            }
        }

        public class EntitySimple
        {
            public int ID { get; set; }

            public int IntValueToDelete { get; set; }
        }
    }
}
```

I will wait for your answer

Best Regards,

Jonathan

**Comment by wernerbarnard** [comment]
Hi @JonathanMagnan 

Yeah, that sample works..... so it's specific to my setup.  My bad

**Comment by JonathanMagnan** [comment]
If you find something in which we can help you let us know.

Best Regards,

Jonathan
