### ISSUE TITLE
BulkInsertAsync occasional error

### ISSUE THREAD

**Issue by wernerbarnard** [zzzprojects/EntityFramework-Plus#241]
Hi,

So some context -

- using .net core 2.0
- using hangfire

Getting the below error when using BulkInsertAsync with a couple hundred thousand records.... but only occasionally and only when a few jobs doing the same thing is running concurrently.

Any idea what could be  causing this?

```
An error occured while retrieving the InformationSchemaTable information. 
See the inner exception for details. ---> System.InvalidOperationException: 
Invalid attempt to call CheckDataIsReady when reader is closed.
```

Stack:
```
at System.Data.SqlClient.SqlDataReader.CheckDataIsReady(Int32 columnIndex, Boolean allowPartiallyReadColumn, Boolean permitAsync, String methodName)
   at System.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at .(Boolean , String[] )
   at Z.BulkOperations.BulkOperation.()
   --- End of inner exception stack trace ---
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.()
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DbContextExtensions.`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XXX.<BulkInsertAsync>d__21.MoveNext() in XXXRepository.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XXX.<ExecuteAsync>d__6.MoveNext() in XXX.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XXX.<UpdateFromFileAsync>d__6.MoveNext() in XXX.cs:line 45
```

This happens on this line:
```
await _repo.BulkInsertAsync(dict.Values).ConfigureAwait(false);
```

Where dict is a Dictionary, and dict.Values is a Collection of Entities

**Comment by JonathanMagnan** [comment]
Hello @wernerbarnard ,

Which version of Entity Framework Plus are you using? I remember having fixed a very similar issue a few weeks ago (Issue #187)

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Oh wait, are you using Entity Framework Plus or Entity Framework Extensions?

Entity Framework Plus doesn't have a method called `BulkInsertAsync`

Looking at the stack trace, I believe I already have this answer ;)

Best Regards,

Jonathan

**Comment by wernerbarnard** [comment]
Hi @JonathanMagnan 

Yes, here's the 2 nuget packages I have installed:

![image](https://user-images.githubusercontent.com/6905546/30644945-6cd7458a-9e14-11e7-824f-b45527d5d7d0.png)

**Comment by JonathanMagnan** [comment]
Thank you,

This issue happen in Z.EntityFramework.Extensions.

We will look at it today and give you more information very soon.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @wernerbarnard ,

Looking at the error message, there is a high chance this issue is caused by your code.

Is it possible the connection gets closed before the `BulkInsertAsync` method is completed?

Could you show us an example how you call a method in our library?

Best Regards,

Jonathan

**Comment by wernerbarnard** [comment]
Haai @JonathanMagnan 

I'm thinking it might be in the case where I have 10 concurrent threads doing the same thing (but different data obviously) - all using BulkInsertAsync, and after that BulkSaveChangesAsync.  I noticed I can't use BulkInsertAsync inside an EF Core Transaction - does it manage it's own in some way?  Is BulkSaveChangesAsync not intended to be used here, or is it intended to batch normal EF operations?

Might also be that I need to refresh my memory in how to use DbContext concurrently / optimally in this use case...... although I haven't had issues when i'm not using the Bulk Extensions?

**Comment by wernerbarnard** [comment]
Hi @JonathanMagnan 

I see now i'm in the wrong repository..... Is this issue perhaps related to the concurrency errors in https://github.com/zzzprojects/EntityFramework-Extensions/issues/53 ?

**Comment by JonathanMagnan** [comment]
Hello @wernerbarnard ,

Don't worry, we will do the follow-up in this one since the request is already open here.

Could you provide me an example, or some code even if that doesn't compile? You can send it directly to use here info@zzzprojects.com if you don't want to share it here.

I may be wrong, but the hypothesis on this issue is your code close the connection before the bulk operations are completed. This is a frequent error people do when working with Async method and connection. That's what we want to check first if this is the case.

It seems our code miss the line to set the transaction. It will be fixed today

> Is this issue perhaps related to the concurrency errors

No, they are not related at all.

**Comment by JonathanMagnan** [comment]
Hello @wernerbarnard ,

The v2.0.1 has been released which should fix the issue with the transaction.

We will wait for your example for continuing our investigation on this issue.

Best Regards,

Jonathan

**Comment by wernerbarnard** [comment]
Hi @JonathanMagnan 

Thanks, I upgraded, but I have a feeling my issue was more related to ef core stock standard and concurrency in a console app.  The context was being shared between worker threads, so when the the 1 thread completed a transaction and Disposed the context, it killed the other thread using it.

it works now, by better/properly managing how the DbContext is used (i.e. not 1 scoped instance injected everywhere)

**Comment by JonathanMagnan** [comment]
Oh,

Were you sharing the instance of a DbContext into multiple threads? That's for sure something you must not do and may lead to some error like this one.

That's why I have asked to have a small example, to verify if you do something like this.

**Comment by wernerbarnard** [comment]
Yeah, sorry about that, I figured it out.  First time EF user here, so wasn't sure what the default behavior was until I actually checked!
