### ISSUE TITLE
Collection.Count capability doesn't work

### ISSUE THREAD

**Issue by jrgoeblk** [zzzprojects/EntityFramework-Plus#242]
I found the following issue testing filters with collections.
ctx.Filter<PhysicalUnit>(q => q.Where(pu => pu.Occupancies.Count > 100));

It is throwing the error:
The ResultType of the specified expression is not compatible with the required type. The expression ResultType is 'Transient.collection[EFFiltersTest.Occupancy(Nullable=True,DefaultValue=)]' but the required type is 'Transient.collection[Edm.Int32(Nullable=True,DefaultValue=)]'. 
Parameter name: arguments[0]

I created a separate test using plain EF (no filtering involved), to rule out it could be an EF limitation. 
var physicalUnits = ctx.PhysicalUnits.Where(pu => pu.Occupancies.Count > 100).ToList();
 
…and the plain EF test with the very same query did work.

**Comment by JonathanMagnan** [comment]
Hello @jrgoeblk ,

Which version of Entity Framework are you using?

Best Regards,

Jonathan

**Comment by jrgoeblk** [comment]
Hi Jonathan, we are using Entity Framework v6.1.3
Thanks
Jorge

**Comment by JonathanMagnan** [comment]
Thank you, we will look at it during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @jrgoeblk ,

The issue has been fixed. It should be released before next Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @jrgoeblk ,

The version 1.7.0 has been released.

The filter should now work using this statement.

Please reopen this issue if you still have the problem.

Best Regards,

Jonathan
