### ISSUE TITLE
DateTime in wrong format for sql server to interpret correctly.

### ISSUE THREAD

**Issue by ksmithRenweb** [zzzprojects/EntityFramework-Plus#243]
Query, when ran through future framework inserts date as "2017-09-22T13:47:44.693-05:00"
Which looks like it is putting the timezone offset on the date.

Same Query ran without the future framework generates a date string as "2017-09-22 14:06:28.3795617".

The date is being using in the where clause like this "someDateField > currentDate"

EF Core 2.

**Comment by JonathanMagnan** [comment]
Hello @ksmithRenweb ,

Thank you for reporting.

We fixed a similar issue for EF6 I believe a few weeks ago. We may have missed something for EF Core.

We will look at it during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ksmithRenweb ,

We successfully reproduced the issue but were unable to fix it. The command text is generated by Entity Framework Core itself. So that makes it quite hard to find what we missed.

Is this request really important for your side? Can you live with it?

I believe soon or later it will be fixed but we would prefer the `later` answer ;)

Best Regards,

Jonathan

**Comment by ksmithRenweb** [comment]
Hi @JonathanMagnan ,
Due to a chain in dependencies it is critical to fix a major performance bug in our application. It is impacting customers on production.
The choice is to fix it in your library. Or drop your library till some time in the future. And suffer the db round trip performance hits. I'll be trying to deep dive into your library and ef core 2 today to see if I can fix it myself. Easier than changing 100's of calls.

Further investigation on Friday showed the date string would parse into a datetime2 dbtype . So it provides an starting point.

Thanks,
Kevin

**Comment by JonathanMagnan** [comment]
Hello @ksmithRenweb ,

Thank you, we will for sure look at it then. The major problem in this request is finding in EF Core why the SQL is generated without parameter with our library but executed with parameter without our library.

If you want, you can temporary disable batching in your library without having to make modifications using the following option:

```csharp
QueryFutureManager.AllowQueryBatch = false;
```

Obviously, you will lose all advantage of using `Future` but you will not have to change your code while we investigate this issue.

I will try to check this issue tomorrow.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ksmithRenweb ,

The v1.7.1 is now available,

We issue should have been fixed and parameter like in EF Core 1.1 is now used.

Please reopen this issue if you still have the problem.

Best Regards,

Jonathan

**Comment by ksmithRenweb** [comment]
@JonathanMagnan Thanks, verified fixed.
