### ISSUE TITLE
Audit | Retrieve  Deleted Audit

### ISSUE THREAD

**Issue by tpreglej** [zzzprojects/EntityFramework-Plus#244]
Hello.

Am I doing something wrong or ctx.AuditEntries.Where<Some_Entity>(6) does not return deleted items?

Tino,

**Comment by JonathanMagnan** [comment]
Hello @tpreglej ,

We successfully reproduce the issue. It seems the code was working only with Added && Modified state.

We already fixed it and it should be available in the release we will make later today.

Best Regards

Jonathan

**Comment by tpreglej** [comment]
Thank you.

**Comment by JonathanMagnan** [comment]
Hello @tpreglej ,

The v1.7.1 is now available,

Best Regards,

Jonathan
