### ISSUE TITLE
Unable to use join statement in Filter

### ISSUE THREAD

**Issue by RikWaspcroft** [zzzprojects/EntityFramework-Plus#247]
Hi,

We have entity framework code first model and classes correctly setup, however the following filter gives me an error. I simply want to return BouncedContacts that have an associated UserAccount (by joining on the SubaccountID).

`this.Filter<BouncedContact>(q => q.Join(this.UserAccounts, a => a.SubaccountID, b => b.SubaccountID, (a,b) => a));`

**Error:**
The ResultType of the referenced variable 'LQ6' does not match the type specified in this variable reference expression. Parameter name: query.

**Comment by JonathanMagnan** [comment]
GHello @RikWaspcroft ,

Thank you for reporting. We will look at this during the week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @RikWaspcroft ,

Filtering with join cannot work within our library. The return type must be currently the same as the DbSet type.

Currently, one way to make it work is to use instead `Include` with `DbSetFilter`

```csharp
ctx.DbSetFilter<BouncedContact>(q => q.Include("UserAccounts"));
```

Only the DbSet will be filtered but at least, it will automatically include `UserAccounts` to your BouncedContact set.

Let me know if this workaround can be applied to your scenario.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @RikWaspcroft ,

I will close this issue, feel free to reopen if you have more question about it.

Best Regards,

Jonathan
