### ISSUE TITLE
Mathematical operations inside aggregate functions are broken since version 1.6.7 (EF6)

### ISSUE THREAD

**Issue by rlenders** [zzzprojects/EntityFramework-Plus#249]
I'm using Z.EntityFramework.Plus.EF6 version 1.6.5 right now, which works fine. I tried to update to the latest stable version, but there seems to be an error since version 1.6.7. (I can't find version 1.6.6 on NuGet.)

    BatchUpdateExtensions.Update(DbContext.Parents, p => new Parent {
        SomeInteger = p.Children.Sum(c => 100 * c.AnotherInteger) // multiplication inside SUM
    });

> System.Data.SqlClient.SqlException: 'Incorrect syntax near the keyword 'FROM'.
Incorrect syntax near the keyword 'AS'.'

This also happens when using `Average`, `Min`, `Max`, etc.

---

I just discovered another error, possibly related:

    BatchUpdateExtensions.Update(DbContext.Parents, p => new Parent {
        SomeInteger = p.Children.Sum(c => 100 - 50) // substraction inside SUM
    });

> System.Data.SqlClient.SqlException: 'The multi-part identifier "Project1.C1" could not be bound.'

**Comment by JonathanMagnan** [comment]
Hello @rlenders ,

Thank you for reporting,

I will check this issue with the latest version tomorrow.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @rlenders ,

## First Example
We don't have any code to support that could allow us to support this example currently. Are you sure that was previously worked correctly?

The problem is Entity Framework make some `JOIN` in this case instead of creating subqueries. Our library doesn't support it yet.

## Second Example
The second example seems to work fine

```csharp
ctx.Parents.Where(x => !x.Children.Any())
                    .Update(p => new Parent
                    {
                        TotalChildrenAge = p.Children.Sum(x => 100 - 50)
                    });
```

**Comment by rlenders** [comment]
Hmm, it's seems I've over-simplified my example and failed to capture the problem. I'll do some more investigation, I'll get back to you.

**Comment by JonathanMagnan** [comment]
Anything that will throw an error with the `Project` alias will be unlikely supported for now.

**Comment by rlenders** [comment]
I can't seem to reproduce that `Project` error, it must've been an error on my end. But I'm more interested in the other error (`Incorrect syntax near the keyword`), because that's the one keeping me from upgrading.

> We don't have any code to support that could allow us to support this example currently.

Are you sure? It's a fairly simple example, and it works for mein version 1.6.5.

**Comment by JonathanMagnan** [comment]
You are right.

It works on v1.6.5

It seems on this version, no `Project` query is created but under the latest version yet.

I will investigate it more this week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @rlenders ,

The issue has been fixed.

The version should be released before next Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @rlenders ,

The v1.7.4 has been released.

Let me know if the first BatchUpdate is now working.

Best Regards,

Jonathan

**Comment by rlenders** [comment]
Thanks! It's working now.
