### ISSUE TITLE
Missing IQueryUnwrapper

### ISSUE THREAD

**Issue by samiraguiar** [zzzprojects/EntityFramework-Plus#251]
EntityFramework.Extended used to have [IQueryUnwrapper](https://github.com/zzzprojects/EntityFramework.Extended/blob/master/Source/EntityFramework.Extended/IQueryUnwrapper.cs) to allow custom unwrapping behavior for queries. This was useful when one had a query encapsulated by LinqKit's expandable query type.

Any plans to bring back support for it?

**Comment by JonathanMagnan** [comment]
Hello @samiraguiar ,

Thank you for reporting,

I will look at it this week to see if that's possible or not.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @samiraguiar ,

I have checked this request and we can certainly bring back the support for it.

However, I remember having recently added for some method support for LinqKit.

Are there some features that currently doesn't work? Perhaps supporting it directly inside our library could be a better idea.

Let me know which features that doesn't work and we will look at it.

If for other reasons, you really need this interface, I can add it to the `full version` but not for `standalone version` until we create a common project for this kind of configuration.

Best Regards,

Jonathan

**Comment by samiraguiar** [comment]
Hi @JonathanMagnan,

Thank you for letting me know. I only raised the question since in EntityFramework.Extended the choice was to not couple the unwrapping process to a specific case (LinqKit), but to allow users to customize it as they seemed fit.

However, the current implementation covers my needs, so I'm closing this issue. Thank you again!

Regards,
Samir Aguiar

**Comment by JonathanMagnan** [comment]
Great ;)

I will for sure keep it in mind if someone need this feature later.

Best Regards,

Jonathan
