### ISSUE TITLE
Null Object reference error when auditing child tables

### ISSUE THREAD

**Issue by lengyue201** [zzzprojects/EntityFramework-Plus#253]
I'm new to this EntityFramewrk-Plus. currently I encountered some errors when trying audit child tables and need advice from you experts, any feedback is greatly appreciated, thanks a lot.
**Context Initialization:**
 public partial class BAPContext : DbContext
    {
        public BAPContext()
            : base("name=BAPContext")
        {
            AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
            // ADD "Where(x => x.AuditEntryID == 0)" to allow multiple SaveChanges with same Audit
            {
                audit.CreatedBy = System.Web.HttpContext.Current.User.Identity.Name;
                (context as BAPContext).AuditEntries.AddRange(audit.Entries);
            };
            AuditManager.DefaultConfiguration.DataAnnotationDisplayName();
            AuditManager.DefaultConfiguration.IgnorePropertyUnchanged = true;

        }
 ......
**2 Classes Definition as below:**
 public partial class User
        {
            public User()
            {
                Roles = new HashSet<Role>();
            }
            public int UserId { get; set; }

            [AuditDisplay(name: "User Name")]
            [StringLength(100)]
            [Required]
            public string UserName { get; set; }

            [StringLength(100)]
            [Required]
            [AuditDisplay("User Account")]
            public string UserAccount { get; set; }

            [AuditDisplay(name: "Email")]
            [StringLength(100)]
            [Required]
            public string UserEmail { get; set; }

            public string Designation { get; set; }

            [AuditDisplay("Belong BU ID")]
            public Nullable<int> BusinessUnitId { get; set; }

            [ForeignKey("BusinessUnitId")]
            [AuditDisplay("Belonging BU")]
            public virtual BusinessUnit BU { get; set; }

            [InverseProperty("User")] // <- Navigation property name in EntityA
            public virtual ICollection<BusinessUnit> BUAs { get; set; }

            public virtual ICollection<Role> Roles { get; set; }
        }

        public partial class Role
        {
            public Role()
            {
                Users = new HashSet<User>();
                Functions = new HashSet<Function>();
                Modules = new HashSet<Module>(); ;
            }
            public int RoleId { get; set; }
            [AuditDisplay("Role Name")]
            public string RoleName { get; set; }
            [AuditDisplay("Role Description")]
            public string RoleDescription { get; set; }

            public virtual ICollection<User> Users { get; set; }
            public virtual ICollection<Module> Modules { get; set; }
            public virtual ICollection<Function> Functions { get; set; }
        }
**Coding Calling SaveChanges:**

 using (BAPContext _db = new BAPContext())
            {
                _db.Roles.Attach(currRole);
                currRole.RoleDescription = txbRoleDesc.Text.Trim();
                currRole.RoleName = txbRoleName.Text.Trim();
             
                //remove users from removed list
                foreach (var user in removedUsers)
                {
                    currRole.Users.Remove(user);
                }

                _db.Entry(currRole).State = System.Data.Entity.EntityState.Modified;
                _db.SaveChanges(new Audit());

**Error Details as below:**
Object reference not set to an instance of an object.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 

Line 152:
Line 153:                _db.Entry(currRole).State = System.Data.Entity.EntityState.Modified;
Line 154:                _db.SaveChanges(new Audit());
Line 155:
Line 156:            }

Source File: C:\Users\xulei\Documents\Projects\Internal\BAP\BAPPortal\BAPPortal\AccessControl\RoleUpdate.aspx.cs    Line: 154 

Stack Trace: 

[NullReferenceException: Object reference not set to an instance of an object.]
   System.Object.GetType() +0
   Z.EntityFramework.Plus.AuditEntryProperty.Build(AuditEntry parent, String relationName, String propertyName, Object oldValue, Object newValue) +156
   Z.EntityFramework.Plus.Audit.AuditRelationAdded(Audit audit, AuditEntry entry, ObjectStateEntry objectStateEntry) +581
   Z.EntityFramework.Plus.Audit.PostSaveChanges(Audit audit) +377
   Z.EntityFramework.Plus.AuditExtensions.SaveChanges(DbContext context, Audit audit) +48

**Comment by JonathanMagnan** [comment]
Hello @lengyue201 ,

I'm not sure if this is `The Problem` but you initialize global configuration in a instance constructor which may lead to this kind of error.

Try by using a static constructor instead

```csharp
public partial class BAPContext : DbContext
{
	static BAPContext() 
	{
		AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
		{
			audit.CreatedBy = System.Web.HttpContext.Current.User.Identity.Name;
			(context as BAPContext).AuditEntries.AddRange(audit.Entries);
		}
	}
	public BAPContext()
	: base("name=BAPContext")
	{

	};
	
	AuditManager.DefaultConfiguration.DataAnnotationDisplayName();
	AuditManager.DefaultConfiguration.IgnorePropertyUnchanged = true;
}
```

Best Regards,

Jonathan

**Comment by lengyue201** [comment]
Good evening Jonathan,
Thank you so much for your reply, will try tomorrow and get back to you for
any updates.


Best regards,
Xu Lei


2017年10月17日 下午9:13，"Jonathan Magnan" <notifications@github.com>写道：

Hello @lengyue201 <https://github.com/lengyue201> ,

I'm not sure if this is The Problem but you initialize global configuration
in a instance constructor which may lead to this kind of error.

Try by using a static constructor instead

public partial class BAPContext : DbContext
{
	static BAPContext()
	{
		AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
		{
			audit.CreatedBy = System.Web.HttpContext.Current.User.Identity.Name;
			(context as BAPContext).AuditEntries.AddRange(audit.Entries);
		}
	}
	public BAPContext()
	: base("name=BAPContext")
	{

	};
	
	AuditManager.DefaultConfiguration.DataAnnotationDisplayName();
	AuditManager.DefaultConfiguration.IgnorePropertyUnchanged = true;
}

Best Regards,

Jonathan

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zzzprojects/EntityFramework-Plus/issues/253#issuecomment-337227031>,
or mute the thread

**Comment by lengyue201** [comment]
Hi Jonathan:
I changed the codes accordingly but still got same errors. Any other advice please?

**Comment by JonathanMagnan** [comment]
Hello @lengyue201 ,

Could you provide me a project with the error?

It will be easier for me to check what you have done differently.

You can send it here: info@zzzprojects.com

Best Regards,

Jonathan

**Comment by lengyue201** [comment]
hi Jonathan:
  thank you so much, already sent the sample project for your reference already.

**Comment by JonathanMagnan** [comment]
Hello @lengyue201 ,

Sorry, I completely forget about this request.

I started to look at it when you provided me the example but had to stop since it was not as easy on my side to make it work in my environment and test it since you provided me a full `project` and not only a small example.

If you still need help, do you think you could reduce your example to by example a simple `WinForm` application with one `Form`? It will be easier on my side to get started without spending some hour to try to build the application.

Best Regards,

Jonathan

**Comment by lengyue201** [comment]
OK, will send simple one to you next week.

2017年11月4日 下午10:37，"Jonathan Magnan" <notifications@github.com>写道：

Hello @lengyue201 <https://github.com/lengyue201> ,

Sorry, I completely forget about this request.

I started to look at it when you provided me the example but had to stop
since it was not as easy on my side to make it work in my environment and
test it since you provided me a full project and not only a small example.

If you still need help, do you think you could reduce your example to by
example a simple WinForm application with one Form? It will be easier on my
side to get started without spending some hour to try to build the
application.

Best Regards,

Jonathan

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zzzprojects/EntityFramework-Plus/issues/253#issuecomment-341901556>,
or mute the thread

**Comment by JonathanMagnan** [comment]
Hello @lengyue201 ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
