### ISSUE TITLE
EF Core 2 bug with Future calls.

### ISSUE THREAD

**Issue by ksmithRenweb** [zzzprojects/EntityFramework-Plus#254]
Exception Message:
The specified transaction is not associated with the current connection. Only transactions associated with the current connection may be used.

        static void TransactionError()
        {
            try
            {
                //QueryFutureManager.AllowQueryBatch = false;

                var options = new DbContextOptionsBuilder<FutureTestContext>();

                options.UseSqlServer("Server=(local)\\SQL2016;Database=FutureTest;Trusted_Connection=True;");

                using (var context = new FutureTestContext(options.Options))
                {
                    var future = context.Miscs.Future();
                    var future2 = context.Miscs.OrderByDescending(t => t.ID).Future();

                    var listFuture = future.ToList();

                    var n = new MiscDto { Name = $"test {DateTime.Now.Ticks}" };

                    context.Miscs.Add(n);
                    context.SaveChanges();
                }
            }
            catch (Exception e)
            {
                Console.WriteLine($"{e.Message}\n{e.StackTrace}");
                throw;
            }
        }

I have been working this issue for a day or so now. If you just turn off the future framework, then the code runs fine.

Sample solution.
[FutureTransactionError.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/1392453/FutureTransactionError.zip)

**Comment by JonathanMagnan** [comment]
Hello @ksmithRenweb ,

Thank a lot again,

I have added this issue to the list to check during the weekend.

Best Regards,

Jonathan

**Comment by ksmithRenweb** [comment]
Found a work around that allows future batching to still work, but it turns off an integral part of EF Core 2.

context.Database.AutoTransactionsEnabled = false

**Comment by JonathanMagnan** [comment]
Hello @ksmithRenweb ,

The bug has been fixed, the original connection is now restored once `QueryFuture` complete his logic.

The fix should be available today or tomorrow.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ksmithRenweb ,

The v1.7.5 is now available

The connection should now be restored once `Query Future` finish his job.

Best Regards,

Jonathan

**Comment by ksmithRenweb** [comment]
Jonathan.

Sorry for not letting you know. I confirmed the fix works last week.

Thanks,
Kevin
