### ISSUE TITLE
Transactions with Batch Operations

### ISSUE THREAD

**Issue by gorillapower** [zzzprojects/EntityFramework-Plus#255]
Is it possible to use transaction scope with the batch operations? Im using `Z.Test.EntityFramework.Plus.EF6` 

IE
```
using(var db = new MyContext())
{
	using (var dbContextTransaction = db.Database.BeginTransaction())
	{
		try
		{
			var myEnt = db.MyEntities.Find(1);
			myEnt.Prop = "newValue";
			db.SaveChanges();
			
			db.MyEntities2
			.Where(x => x.SomeProp == 1)
			.Delete();
			
			dbContextTransaction.Commit();
		} 
		catch (Exception ex)
		{
			dbContextTransaction.Rollback();
			throw;
		}
	}
}

```

I didnt see any concrete evidence from the documentation or from previous issues and from the observed behaviour, it seems the operations is executed immediately when it is called. Is there anyway to wrap the operation(s) in a transaction?

**Comment by gorillapower** [comment]
Ah didnt look at the Tests :) According to them this will be possible, I must have done something incorrect

**Comment by JonathanMagnan** [comment]
Hello @gorillapower ,

Let me know if you need more help.

In short, yes transaction are supported.

Best Regards,

Jonathan

**Comment by intergleam** [comment]
But if I understood correctly EntityFramework-Plus doesn't wait for SaveChanges()?

**Comment by JonathanMagnan** [comment]
Hello @intergleam ,

You are right.

`Batch Delete` and `Batch Update` are immediate operation.

**Comment by intergleam** [comment]
right  EntityFramework-Plus is similar to `Database.ExecuteSqlCommand` you need to wrap everything into `Database.BeginTransaction()`
