### ISSUE TITLE
Exception throw when using test EF context

### ISSUE THREAD

**Issue by petriceko** [zzzprojects/EntityFramework-Plus#256]
Hi, when I create unit tests using official MS quide: https://msdn.microsoft.com/en-us/library/dn314431(v=vs.113).aspx , I am getting following exception on batch update:

Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com
   at Z.EntityFramework.Plus.InternalExtensions.GetObjectQuery[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.InternalExtensions.GetDbContext[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)

**Comment by JonathanMagnan** [comment]
Hello @petriceko ,

Could you provide me a project example (info@zzzprojects.com), this kind of issue normally happen when the original ObjectQuery is modified by something else. Such as mocking the DbContext.

It will be easier for me to provide a reason or a solution with a project that I will be able to try.

Best Regards,

Jonathan

**Comment by petriceko** [comment]
Hello,

example solution is attached, please run open InitializeClassTests and run UpdateItemTest. Exception should be thrown in InitializeClass in method UpdateItem.

Regards

[ExampleSolution.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/1404328/ExampleSolution.zip)

**Comment by JonathanMagnan** [comment]
Hello @petriceko ,

Sorry for the long delay, I have been very busy in the past two weeks.

Your example using an `ObservableCollection` under the `DbSet`

```csharp
public class TestDbSet<TEntity> : DbSet<TEntity>, IQueryable, IEnumerable<TEntity>, IDbAsyncEnumerable<TEntity>
	where TEntity : class
{
	ObservableCollection<TEntity> _data;
	IQueryable _query;

	public TestDbSet()
	{
		_data = new ObservableCollection<TEntity>();
		_query = _data.AsQueryable();
	}
```

It doesn't even make database round-trip when performing some operation such as `ToList` since everything happens in the `Memory`

Our library works with `DbSet` that use a database, in your case, everything is done in Memory.

That's why you get this error about the `ObjectQuery` since there is no `ObjectQuery` in your scenario.

Please let me know if that explains correctly why that's not working in your case.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @HolyOne ,

The v1.7.7 has been released.

We could not make it this scenario work by default but we added an option `BatchUpdateManager.IsInMemoryQuery = true`

When enabled, we will no longer try to find the `ObjectQuery` which was caused the error.

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by petriceko** [comment]
Hi,

I have tested provided solution and simple test passes.
Thanks for update.
I suggest also update documentation.

Regards

**Comment by kleky** [comment]
Hi @JonathanMagnan, do you know if `BatchUpdateManager.IsInMemoryQuery = true` will permit using moq library for mocking in unit tests with the ef extensions/plus stuff? I had this issue a short while back and I could well use it at my new job, providing we can unit test our code ok. cheers!

**Comment by JonathanMagnan** [comment]
Hello @kleky ,

I already added a task to my developer tomorrow to look about Moq. We make it compatible with some method recently on EF Classic: https://entityframework-classic.net/

So I guess we will be able to look if there is something we can do about Moq or not. You should get an answer tomorrow or Monday.

**Comment by JonathanMagnan** [comment]
Hello @kleky ,

After some investigation, we will need to abandon to try to support `Moq`.

Unfortunately, our library work with `ObjectQuery` which `Moq` doesn't provide.

We will now always recommend using for unit testing : [Effort](https://entityframework-effort.net/) 

Hope that answer your question even if that's a negative answer.

Best Regards,

Jonathan

**Comment by kleky** [comment]
Thanks Jonathan. It's good to know where things stand with a viable workaround. much appreciated.
