### ISSUE TITLE
Delete() - Table schema not correctly determined on MySQL

### ISSUE THREAD

**Issue by sparkybg** [zzzprojects/EntityFramework-Plus#258]
I have the following convention in my configuration:

```csharp
 class TableAttributeLowerCaseConvention :TypeAttributeConfigurationConvention<TableAttribute>
 {
            public override void Apply(ConventionTypeConfiguration configuration, TableAttribute attribute)
            {
                if (string.IsNullOrWhiteSpace(attribute.Schema) || attribute.Schema.ToLower() == "dbo") attribute.Schema = "common";
                configuration.ToTable(attribute.Name.ToLower(), attribute.Schema.ToLower());
            }
        }
```
this makes all table names lower case and all "dbo" or missing schema to "common"

On MySQL when using "Delete" method to delete all records from table it still looks for "dbo" schema, and because MySql EntityClient does not use "dbo"schema I've got exception that table is not found.

Here is the generated SQL:
`DELETE A
FROM `options` AS A
INNER JOIN ( SELECT
`Extent1`.`ID`
FROM `common.options` AS `Extent1` ) AS B ON A.`ID` = B.`ID`

"common" schema is missing in the delete statement while it still remains in the join's select statement.

Maybe you are comparing the schema from TableAttribute, and when it is "dbo" the mysql generator is not using the schema from mapping model, despite it is there and it is corrent.

**Comment by JonathanMagnan** [comment]
Hello @sparkybg ,

Thank you for reporting.

I have added this task to issue to look. I'm not sure I will have time this weekend however.

Best Regards,

Jonathan

**Comment by sparkybg** [comment]
Thanks for the fast response. 

I'll also try to dig into it myself. I will let you know my findings if any.

**Comment by sparkybg** [comment]
Hi,

Spotted it. It is a mistake in tableName evaluation in BatchUpdate.cs and BatchDelete.cs.

BatchDelete.cs also had a bug for postgresql regardind tablename. It was missing at all from tableName if-else chain, so I've added it and corrected it in both files. Now everything works in MySQL, PostgreSQL and SQLServer.

I am not completely sure, but I think there is similar errors for SQLite and SQLCE - schema is completely ignored when tableName is evaluated. I've never used these two so I cannot test or say from personal experience if schema should be taken into account when these database engines are used.

Here are the update files. No other modifications are made to them:
[BatchUpdate-BatchDelete.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/1404465/BatchUpdate-BatchDelete.zip)

**Comment by JonathanMagnan** [comment]
Thank a lot for your help @sparkybg ,

As said, I will try to look at it at the beginning of the week.

Best Regards,

Jonathan

**Comment by sparkybg** [comment]
By the way, there is exactly the same problem in Entity Framework Extensions, at least in MySQL - table schema is absolutely ignored, no matter if it is "dbo" or not.

**Comment by JonathanMagnan** [comment]
Hello @sparkybg ,

It seems I have a hard time to add the convention, perhaps you could help me and point me what I'm doing wrong:

```csharp
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Configuration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Windows.Forms;
using MySql.Data.Entity;

namespace Z.EntityFramework.Plus.Lab.EF6.MySql
{
    public class TableAttributeLowerCaseConvention : TypeAttributeConfigurationConvention<TableAttribute>
    {
        public override void Apply(ConventionTypeConfiguration configuration, TableAttribute attribute)
        {
            if (string.IsNullOrWhiteSpace(attribute.Schema) || (attribute.Schema.ToLower() == "dbo"))
            {
                attribute.Schema = "common";
            }
            configuration.ToTable(attribute.Name.ToLower(), attribute.Schema.ToLower());
        }
    }

    public partial class Form_Request_Batch_WithSchema : Form
    {
        public Form_Request_Batch_WithSchema()
        {
            InitializeComponent();

            // CLEAN
            using (var ctx = new EntityContext())
            {
                ctx.AccountItemSchemas.RemoveRange(ctx.AccountItemSchemas);
                ctx.SaveChanges();
            }

            // SEED
            using (var ctx = new EntityContext())
            {
                ctx.AccountItemSchemas.Add(new AccountItemSchema { ColumnInt = 1});
                ctx.AccountItemSchemas.Add(new AccountItemSchema { ColumnInt = 2});
                ctx.AccountItemSchemas.Add(new AccountItemSchema { ColumnInt = 1});
                ctx.SaveChanges();
            }

            // TEST
            using (var ctx = new EntityContext())
            {
                ctx.AccountItemSchemas.Delete();
                var list = ctx.AccountItemSchemas.ToList();
            }
        }

        [DbConfigurationType(typeof(MySqlEFConfiguration))]
        public class EntityContext : DbContext
        {
            public EntityContext() : base("CodeFirstEntities")
            {
                Database.SetInitializer(new DropCreateDatabaseAlways<EntityContext>());
            }

            // ... context code ...
            public DbSet<AccountItemSchema> AccountItemSchemas { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Conventions.Add<TableAttributeLowerCaseConvention>();

                base.OnModelCreating(modelBuilder);
            }
        }

        public class AccountItemSchema
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }
            public int SearchProfileId { get; set; }
            public bool IsDeleted { get; set; }
        }
    }
}
```

Best Regards,

Jonathan

**Comment by sparkybg** [comment]
Before adding the custom convention, remove the original convention:
```c#
            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                //add these two lines
                modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
                modelBuilder.Conventions.Remove<TableAttributeConvention>();

                modelBuilder.Conventions.Add<TableAttributeLowerCaseConvention>();

                base.OnModelCreating(modelBuilder);
            }
```

Then add TableAttribute to your entity type like this:
```c#
        [Table("TestEntity", Schema = "TestSchema")]
        public class AccountItemSchema
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }
            public int SearchProfileId { get; set; }
            public bool IsDeleted { get; set; }
        }
```

Now this entity must be saved to "testentity" table (in lower case, because of the convention we added) in "testschema" schema (again in lower case).

The problem is here (Z.EntytFramework.Plus - BatchDelete.cs):
```c#
            if (isMySql)
            {
                tableName = string.Concat("`", store.Table, "`"); //schema is ignored here!
            }
            else if (isSqlCe)
            {
                tableName = string.Concat("[", store.Table, "]");
            }
            else if (isSQLite)
            {
                tableName = string.Concat("\"", store.Table, "\"");
            }
            else if (isOracle)
            {
                tableName = string.IsNullOrEmpty(store.Schema) || store.Schema == "dbo" ?
string.Concat("\"", store.Table, "\"") :
string.Concat("\"", store.Schema, "\".\"", store.Table, "\"");
            }
            else
            {
                tableName = string.IsNullOrEmpty(store.Schema) ?
    string.Concat("[", store.Table, "]") :
    string.Concat("[", store.Schema, "].[", store.Table, "]");
            }

           //There is not PosgreSql statement at all (there is such in BatchUpdate.cs, but there are also problem there.

```

I've corrected this to:
```c#
            if (isMySql)
            {
                tableName = string.IsNullOrEmpty(store.Schema) || store.Schema == "dbo" ?
                string.Concat("`", store.Table, "`") :
                string.Concat("`", store.Schema, ".", store.Table, "`");
            }
            else if (isOracle)
            {
                tableName = string.IsNullOrEmpty(store.Schema) || store.Schema == "dbo" ?
                    string.Concat("\"", store.Table, "\"") :
                    string.Concat("\"", store.Schema, "\".\"", store.Table, "\"");
            }
            else if (isPostgreSQL)
            {
                tableName = string.IsNullOrEmpty(store.Schema) ?
                    string.Concat("\"", store.Table, "\"") :
                    string.Concat("\"", store.Schema, "\".\"", store.Table, "\"");
            }
            else if (isSQLite)
            {
                tableName = string.Concat("\"", store.Table, "\"");
            }
            else if (isSqlCe)
            {
                tableName = string.Concat("[", store.Table, "]");
            }
            else
            {
                tableName = string.IsNullOrEmpty(store.Schema) ?
                string.Concat("[", store.Table, "]") :
                string.Concat("[", store.Schema, "].[", store.Table, "]");
            }
```

Now it works like a charm.

There are the same problem in Z.EntytFramework.Extensions - it will work on MySql database only if all your tables is located in the default "dbo" schema. I have not checked it on PostgreSql but I suspect the same problems will be there also.

If I can help with something else - just say.

**Comment by JonathanMagnan** [comment]
Thank a lot @sparkybg ,

I will try it tomorrow

**Comment by JonathanMagnan** [comment]
Hello @sparkybg ,

There is something weird in this that I'm not able to understand.

If we use `Code First` and the code you provided me, Entity Framework will create a table named `testschema.testentity`. However, even Entity Framework will not be compatible and will try to search for the table `testentity` since there is not really any `schema` concept in MySQL unless I'm wrong.

Of course, if I rename this table to `testentity`, everything will work including our library but then you expect us to use the table instead `testschema.testentity`. However, we renamed this table `testentity`...

There is something I don't understand, it may look and obvious on your side but I'm still trying to figure how you use this `schema` on mine.

Obviously the code you provided fix your case but I need to be sure to understand to avoid some side impact for other people using the libraries.

```csharp
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Configuration;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Windows.Forms;
using MySql.Data.Entity;

namespace Z.EntityFramework.Plus.Lab.EF6.MySql
{
    public class TableAttributeLowerCaseConvention : TypeAttributeConfigurationConvention<TableAttribute>
    {
        public override void Apply(ConventionTypeConfiguration configuration, TableAttribute attribute)
        {
            if (string.IsNullOrWhiteSpace(attribute.Schema) || (attribute.Schema.ToLower() == "dbo"))
            {
                attribute.Schema = "common";
            }
            configuration.ToTable(attribute.Name.ToLower(), attribute.Schema.ToLower());
        }
    }

    public partial class Form_Request_Batch_WithSchema : Form
    {
        public Form_Request_Batch_WithSchema()
        {
            InitializeComponent();

            using (var ctx = new EntityContext())
            {
                // FAIL HERE! No method from EF+ has been called yet
                var list = ctx.AccountItemSchemas.ToList();
            }

            //// CLEAN
            //using (var ctx = new EntityContext())
            //{
            //    ctx.AccountItemSchemas.RemoveRange(ctx.AccountItemSchemas);
            //    ctx.SaveChanges();
            //}

            //// SEED
            //using (var ctx = new EntityContext())
            //{
            //    ctx.AccountItemSchemas.Add(new AccountItemSchema { ColumnInt = 1});
            //    ctx.AccountItemSchemas.Add(new AccountItemSchema { ColumnInt = 2});
            //    ctx.AccountItemSchemas.Add(new AccountItemSchema { ColumnInt = 1});
            //    ctx.SaveChanges();
            //}

            //// TEST
            //using (var ctx = new EntityContext())
            //{
            //    ctx.AccountItemSchemas.Delete();
            //    var list = ctx.AccountItemSchemas.ToList();
            //}
        }

        [DbConfigurationType(typeof(MySqlEFConfiguration))]
        public class EntityContext : DbContext
        {
            public EntityContext() : base("CodeFirstEntities")
            {
                Database.SetInitializer(new DropCreateDatabaseAlways<EntityContext>());
            }

            // ... context code ...
            public DbSet<AccountItemSchema> AccountItemSchemas { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                //add these two lines
                modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
                modelBuilder.Conventions.Remove<TableAttributeConvention>();

                modelBuilder.Conventions.Add<TableAttributeLowerCaseConvention>();

                base.OnModelCreating(modelBuilder);
            }
        }

        [Table("TestEntity", Schema = "TestSchema")]
        public class AccountItemSchema
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }
            public int SearchProfileId { get; set; }
            public bool IsDeleted { get; set; }
        }
    }
}
```

**Comment by sparkybg** [comment]
> If we use Code First and the code you provided me, Entity Framework will create a table named testschema.testentity. However, even Entity Framework will not be compatible and will try to search for the table testentity since there is not really any schema concept in MySQL unless I'm wrong.

Yes, you are wrong! There are schemas both in MySQL and Postgres. And I am using them in my current project without any problem. Only "dbo" schema is ignored in MySql.

Take a look:
![mysqlschema](https://user-images.githubusercontent.com/4700835/32070809-1f8e6152-ba96-11e7-9a89-c74fc22e04b1.png)

**Comment by JonathanMagnan** [comment]
Hello @sparkybg ,

Sorry for the delay, it has been a quite busy week recently.

Your fix has been added and will be part of next release (for Monday or before).

I honestly find it look more like a table prefix than a `schema` such as how `SQL Server` handle it but that's maybe because my background is way more on `SQL Server`.

I will let you know when this new version will be available.

Best Regards,

Jonathan

**Comment by sparkybg** [comment]
Yes, it takes the schema as table name prefix. Sorry for not  explaining it this way.

...and bear in mind that the same problem is present in your "Entity Framework Extentions" and "Bulk Operations" projects. I don't remember which one of the two I've tested.

**Comment by JonathanMagnan** [comment]
Hello @sparkybg ,

Yup, it's here everywhere. I will make sure to fix it as well if no one report us anything about it after the fix has been released for two week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @sparkybg ,

The version 1.7.6 has been released:
https://github.com/zzzprojects/EntityFramework-Plus/releases/tag/v1.7.6

Let me know if schema works as you expect.

Best Regards,

Jonathan

**Comment by sparkybg** [comment]
It seems that everything works now. At least on MySQL and PostgreSQL.

**Comment by JonathanMagnan** [comment]
Great ;)

As said, I will wait a few days before moving it to the other library `Entity Framework Extensions` to see if someone report an issue causing by this change.

Best Regards,

Jonathan
