### ISSUE TITLE
Enable/Disable Query Filter

### ISSUE THREAD

**Issue by saurabh-shelgaonkar** [zzzprojects/EntityFramework-Plus#264]
Hi,

The document suggests this method for disabling filters. 
`ctx.Filter<BaseDog>(MyEnum.EnumValue).Disable();`
However, I was not able to find this method.
Instead, the method I found was : 
`ctx.Filter(MyEnum.EnumValue).Disable();` //Without the generic "BaseDog" 

Did I miss something?

Note: I am using EF6.

Regards,
Saurabh

**Comment by JonathanMagnan** [comment]
Hello @saurabh-shelgaonkar,

Thank you for reporting. You are missing nothing, it's an error in the documentation.

The documentation has been updated.

Best Regards,

Jonathan
