### ISSUE TITLE
Unit Test with entity framework for cache

### ISSUE THREAD

**Issue by truongphamxuan** [zzzprojects/EntityFramework-Plus#267]
Hi guys,
I have used this extension as second layer cache for my project. And now, I'm writing unit test for these cached method. Unfortunately, it caused error "Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com". I have investigated, my mock query cannot be converted to DBQuery or DBSet while it is generating cache key. Does anyone have any suggestion? Thanks

**Comment by JonathanMagnan** [comment]
Hello @truongphamxuan ,

Perhaps you can try for your unit test to create your own cache key using the `CacheKeyFactory` ?

Let me know if you need some help for using it.

Best Regards,

Jonathan

**Comment by truongphamxuan** [comment]
Hi @JonathanMagnan ,
Thank you for your quick reply. I have applied your solution to my project and it worked. 
In the test project we use custom cachekeyfactory instead of auto-generated cachekey.
Many Thanks

**Comment by truongphamxuan** [comment]
`
