### ISSUE TITLE
Bulk Delete throws exception if there is nothing to delete

### ISSUE THREAD

**Issue by aFuerst** [zzzprojects/EntityFramework-Plus#268]
If I have a query like this:
```C#
ctx.Users.Where(u => u.UserId == forUserId).Delete();
```
But the `Where` clause ends up returning nothing I get the following exception:
`Object reference not set to an instance of an object.`
And the stacktrace
```C#
at EntityFramework.Batch.SqlServerBatchRunner.<InternalDelete>d__0`1.MoveNext()
```
Is this expected behavior or something I need to put an `Any()` check in front of?

**Comment by JonathanMagnan** [comment]
Hello @aFuerst ,

No, it's not an expected behavior.

Just to be sure, which version for Entity Framework are you suing?

Best Regards,

Jonathan

**Comment by aFuerst** [comment]
I'm on version 6.1.0.168

**Comment by aFuerst** [comment]
After doing some digging it appears that the problem is not with your framework but with something else, thanks for the help

**Comment by JonathanMagnan** [comment]
Great,

Thank to letting me know.

Best Regards,

Jonathan
