### ISSUE TITLE
Exception when updating Many to Many relation with context instance Filter set

### ISSUE THREAD

**Issue by thebruno** [zzzprojects/EntityFramework-Plus#270]
I am experiencing very strange behavior and I suspect possible bug in the library

Scenario
* Entity Framework 6.1.3 with Entity Framework Plus 1.7.6 (tested also on 1.6.4) with .net 4.6.2
* table Users and Units, they are in Many to Many relation (two collections User.Units and Unit.Users)
* instance filter for tenant, where tenant is just int number
context.Filter<ITenant>(q => q.Where(x => x.TenantCode == tenantCode));
* both User and Units are ITenant, linking table is autogenerated
* the application is windows service which runs through tenants one by one and executes some logic
* each tenant receives new instance of context, the filter is set on the context after creation

The scenario is that first tenant (TenantCode =1) is processed (which succeeds) and then execution moves to next tenant. When updating the Units collection for user in tenant 2 I experience the following issue:

_An error occurred while saving entities that do not expose foreign key properties for their relationships. The EntityEntries property will return null because a single entity cannot be identified as the source of the exception. Handling of exceptions while saving can be made easier by exposing foreign key properties in your entity types. See the InnerException for details._

_Violation of PRIMARY KEY constraint 'PK_dbo.UserUnits'. Cannot insert duplicate key in object 'dbo.UserUnits'. The duplicate key value is (1, 4).
The statement has been terminated._

The insert to linking table is generated in SQL

The issue does not exist if:
* I switch to old API DbSetFilter<ITenant>(q => q.Where(x => x.TenantCode == tenantCode))
* filter manually (with Where(...)) instead of Filter?

I think that somehow setting filter for first tenant for different context impacts somehow context for different tenants. Or maybe I am doing something wrong

Any help?

**Comment by JonathanMagnan** [comment]
Hello @thebruno ,

There is some documented limitation with instance filter for `LazyLoading` and `contextSet<T>`.

Since the `QueryCacheManager` is global to all context, the way the library is built doesn't work in these situation.

It works when the filter is a `global` filter but not when it's an `instance` filter.

For tenant scenario, I suggest you to move to [EntityFramework.DynamicFilters](https://github.com/zzzprojects/EntityFramework.DynamicFilters). This library work perfectly with this kind of scenario.

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by thebruno** [comment]
Hi Jonathan,

thank you for you answer. It seems that solution you have provided works for me.

I have
            modelBuilder.Filter(nameof(ITenant), (ITenant d) => d.TenantCode, 0);
            modelBuilder.DisableFilterGlobally(nameof(ITenant));

and when I create db context I set:

                this.SetFilterScopedParameterValue(nameof(ITenant), CurrentTenant);
                this.EnableFilter(nameof(ITenant));

Thank you for you help. Much appreciated.
