### ISSUE TITLE
NullReferenceException while unit testing DeferredCount

### ISSUE THREAD

**Issue by kristijan-ujevic-typeqast** [zzzprojects/EntityFramework-Plus#275]
Hello,

i'm trying to write unit tests for a `DeferredCount` implementation and i'm getting `NullReferenceException`:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Z.EntityFramework.Plus.InternalExtensions.GetObjectQuery[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.QueryDeferredExtensions.DeferredCount[TSource](IQueryable`1 source)
```

This is my test code, i'm using Moq.

```
var testEntities = new FakeDbSet<SomeEntity>();
            
_dbContext.Setup(x => x.Entities).Returns(testEntities);

var result = _entityStatusService.CountEntities();
result.Should().NotBeNull();
```

Thanks

**Comment by JonathanMagnan** [comment]
Hello @kristijan-ujevic-typeqast ,

Thank you for reporting,

This issue obviously happens because you use an external library `Moq` and not a real database.

I have added this issue to our `todo` list to at least check if there is something we can do. We will try to check it during the weekend.

Best Regards,

Jonathan

**Comment by kristijan-ujevic-typeqast** [comment]
Thank you for the quick response, looking forward to your answer.

Regards

**Comment by marcbernal** [comment]
Hi ! I am having the same issue, do you have found any solution ? 

Thanks !

**Comment by kleky** [comment]
Would be nice if these products worked with moq. It's a blocker

**Comment by JonathanMagnan** [comment]
Hello @kleky ,

After some investigation, we will need to abandon to try to support `Moq`.

Unfortunately, our library work with `ObjectQuery` which `Moq` doesn't provide.

We will now always recommend using for unit testing : [Effort](https://entityframework-effort.net/) 

Hope that answer your question even if that's a negative answer.

Best Regards,

Jonathan
