### ISSUE TITLE
IncludeFilter complicates SQL query

### ISSUE THREAD

**Issue by xr280xr** [zzzprojects/EntityFramework-Plus#277]
I'm just trying out EFP for the purpose of using `IncludeFilter` and am reviewing the generated SQL queries. I started with a simple filter and a nested include and the resulting query made me go cross-eyed so I reduced it down to just using a simple include that does not do any filtering. It just includes all records from a related table/navigation property. Using `Include`, it joins my two tables into "Project1" and then selects from that. Using `IncludeFilter`, it joins my tables into "Project1" and then joins that on the base table again ON 1=1 which results in a Cartesian product.

Example:
```
IQueryable<Facility> dbQuery = DBContext.Set<Facility>();
Expression<Func<Facility, object>> navProp = f => f.People;

var where = FilterDeleted(where);
dbQuery = dbQuery.IncludeFilter(f => f.People);

if (where != null)
    dbQuery = dbQuery.Where(where);

 return dbQuery;
```

```
SELECT 
    [Extent1].[pk_FacilityID] AS [pk_FacilityID], 
    [Extent1].[CreatedDate] AS [CreatedDate], 
    [Extent1].[LastModifiedDate] AS [LastModifiedDate], 
    [Extent1].[fk_CultureID] AS [fk_CultureID], 
    [Project1].[C2] AS [C1], 
    [Project1].[pk_FacilityID] AS [pk_FacilityID1], 
    [Project1].[C1] AS [C2], 
    [Project1].[pk_PersonID] AS [pk_PersonID], 
    [Project1].[FirstName] AS [FirstName], 
    [Project1].[LastName] AS [LastName], 
    [Project1].[CreatedDate] AS [CreatedDate1], 
    [Project1].[LastModifiedDate] AS [LastModifiedDate1], 
    [Project1].[IsDeleted] AS [IsDeleted]
    FROM  [dbo].[Facilities] AS [Extent1]
    LEFT OUTER JOIN  (SELECT 
        [Extent2].[pk_FacilityID] AS [pk_FacilityID], 
        [Extent3].[pk_PersonID] AS [pk_PersonID], 
        [Extent3].[FirstName] AS [FirstName], 
        [Extent3].[LastName] AS [LastName], 
        [Extent3].[fk_FacilityID] AS [fk_FacilityID], 
        [Extent3].[CreatedDate] AS [CreatedDate], 
        [Extent3].[LastModifiedDate] AS [LastModifiedDate], 
        [Extent3].[IsDeleted] AS [IsDeleted], 
        CASE WHEN ([Extent3].[pk_PersonID] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1], 
        1 AS [C2]
        FROM  [dbo].[Facilities] AS [Extent2]
        LEFT OUTER JOIN [dbo].[People] AS [Extent3] ON [Extent2].[pk_FacilityID] = [Extent3].[fk_FacilityID] ) AS [Project1] ON 1 = 1
    ORDER BY [Extent1].[pk_FacilityID] ASC, [Project1].[C2] ASC, [Project1].[pk_FacilityID] ASC, [Project1].[C1] ASC
```
In reality this code is in a generic class where Facility is a type parameter and an array of navigation property expressions is passed in as a parameter. The resulting C# Facility objects have the correct # of people each so it seems to be sorting it all out in code, but for two facilities with 10,000 people, this query gives a result set of 20,000 records. That doesn't seem like it's going to be scalable. Is this the expected result or am I using it in an unsupported way?

**Comment by JonathanMagnan** [comment]
Hello @xr280xr ,

You use exactly `IncludeFilter` as you do with `Include`.

The benefit to `IncludeFilter` is to allow filtering such as: 

```csharp
dbQuery = dbQuery.IncludeFilter(f => f.People.Where(x => x.IsActif));
```

If you want to have some performance benefit, try to use `IncludeFilterOptimized` instead. It allows also to filter but in a more optimized ways (may be slower in very very complex scenario).

Let me know if that successfully answer to your question.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by xr280xr** [comment]
Thanks for your reply, Jonathan. So is selecting the Cartesian product the expected result? It looks like maybe that is the outcome of the projection that IncludeFilter uses behind the scenes? The problem is, using my example above, if I'm querying 100 facilities each with 1000 people, it would select a result set of 10,000,000 million rows in order to retrieve only 100,100 records (100,000 people and 100 facilities). So should IncludeFilter not be used against a query that returns a collection but only against a query that returns a single row (e.g. only if I'm querying one facility)?

**Comment by JonathanMagnan** [comment]
Hello @xr280xr ,

This is not a cartesian product. In your scenario, you will more likely return 100,000 records. The facilities will be duplicated multiple time.

That's how `Include` work in EF6.

In EF Core, it works like our features `IncludeOptimized`. It will return all facilities and all peoples. So it's faster since facilities are not duplicated in multiple rows.

I recommend trying `IncludeOptimized` instead to see the SQL output and performance.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @xr280xr  ,

We are currently making some issue cleanup.

Feel free to reopen if you believe we closed it by mistake

Best Regards,

Jonathan


---
