### ISSUE TITLE
NullReferenceException when using FromCache with a ObjectSet

### ISSUE THREAD

**Issue by peto268** [zzzprojects/EntityFramework-Plus#278]
Hi,

i noticed, that when i try to call FromCache on a ObjectSet (in contrast to ObjectQuery) i get a NullReferenceException in InternalExtensions.GetCommandTextAndParameters

The line numbers in the stacktrace don't match the source, but i suspect the problem is in:
https://github.com/zzzprojects/EntityFramework-Plus/blob/9eae40540f50762fd9499f012d4fc204b365fd6c/src/shared/Z.EF.Plus._Core.Shared/EF6/ObjectQuery/GetCommandTextAndParameters.cs#L24

for the ObjectSet there needs to be one more .BaseType

as i workaround i currently use a dummy Select to create a ObjectQuery from the ObjectSet:
```
set.Where(i => true).FromCache()
```

Thanks

**Comment by JonathanMagnan** [comment]
Hello @peto268 ,

Thank you for reporting, I will try to reproduce this issue on my side. I believe you are right about the source of the problem so thank you for the fix ;)

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @peto268 ,

The v1.7.10 has been released.

We added the fix about BaseType

Let me know if the new version is working correctly.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by peto268** [comment]
Sorry to say, but i had to remove the zzz cache from our project. The fact, that the cache returns untracked instances renders it useless for our us.
Thnx though.

**Comment by JonathanMagnan** [comment]
No problem,

We will for sure try to improve our features over the time.

Best Regards,

Jonathan
