### ISSUE TITLE
IncludeOptimized not working with complicated includes

### ISSUE THREAD

**Issue by MrZander** [zzzprojects/EntityFramework-Plus#280]
There are certain scenarios where `IncludeOptimized` is not including data properly.
I've only really noticed it on the more complicated includes I am doing.

For instance, these three do not work.  The resulting navigation properties are empty:
```
await query
	.IncludeOptimized(f => f.ItemGroup.ItemGroupLinks.Select(v => v.Category))  
	.IncludeOptimized(f => f.Locations.Select(v => v.Area.Site)) 
	.IncludeOptimized(f => f.Shipment.Destination)
	.LoadAsync();
```

However, if I run these with `Include`, they work just fine.

The first two, I can understand not working, they are pretty complex, but `f.Shipment.Destination` surprised me.

Is this just a limitation of `IncludeOptimized`?  Can I only use it for single-navigation includes?
If so, are there plans to support more complicated include statements?

**Comment by JonathanMagnan** [comment]
Hello @MrZander ,

One limitation to `IncludeOptimized` is the feature doesn't support by default `SubPath`.

You must include them yourself.

By example, the following query will probably work

```csharp
await query
	.IncludeOptimized(f => f.ItemGroup)
	.IncludeOptimized(f => f.ItemGroup.ItemGroupLinks)  
	.IncludeOptimized(f => f.ItemGroup.ItemGroupLinks.Select(v => v.Category))  
	.IncludeOptimized(f => f.Locations) 
	.IncludeOptimized(f => f.Locations.Select(v => v.Area.Site)) 
	.IncludeOptimized(f => f.Shipment.Destination)
	.LoadAsync();
```

There is also an options `QueryIncludeOptimizedManager.AllowIncludeSubPath = true;` that you can enabled to automatically include it but there is some complex scenario that this options may not support.

Let me know if I answered correctly to your question.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by MrZander** [comment]
Ahh I see.
Including all the paths manually worked.
It's incredible how much this has sped up my application.

Thank you so much.
