### ISSUE TITLE
Will Caching work in LinqPAD?

### ISSUE THREAD

**Issue by jebcrum** [zzzprojects/EntityFramework-Plus#283]
Doing some testing of caching in linqpad but I'm not getting the expected results.
Code:
```
var highwayCodes = HighwayCodes.FromCache().ToList();

var highwayCodesAgain = HighwayCodes.FromCache().ToList();
```
When I go to the SQL tab, it shows that the database is hit twice. Is the underlying cache that FromCache() uses incompatible with the way linqpad runs?

**Comment by JonathanMagnan** [comment]
Hello @jebcrum ,

Thank you for reporting, we will look at it during the week.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by jebcrum** [comment]
Hi Jonathan,

Did some more digging, and it seems that in LinqPAD, the SQL tab is just displaying what SQL is generated regardless of whether or not the queries are sent to the db. I ran a profiler on the database and can confirm that it's not executing the queries and that the cache is indeed working!

Leaving this comment in case someone else runs into the same.
