### ISSUE TITLE
SoftDelete filter not working - Abp v3.2.5 (EFCore)

### ISSUE THREAD

**Issue by ramiglez30** [zzzprojects/EntityFramework-Plus#284]
Global filters not working properly. Dont know the cause.  I was using v3.2.1 and was not working, after upgrading the problem remains.

After checking if filter was enabled, everything was fine.... result keep coming with deleted rows. 

Solved by hard-coding the DbContext: 

            modelBuilder.Entity<Role>()
                .HasQueryFilter(r => !r.IsDeleted);

            modelBuilder.Entity<User>()
                .HasQueryFilter(r => !r.IsDeleted);

I guess this solution is not optimal, 'cause I cannot disable the Filter using Abp tools, right?

Best, 

Rami.

**Comment by JonathanMagnan** [comment]
Hello @ramiglez30 ,

I'm not sure you target the right library.

`HasQueryFilter` are filter from `Entity Framework Core` and not from our library.

Unless I misunderstand the issue, your code doesn't use our `EF+ Query Filter` feature but the one provided by EF Core.

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by ramiglez30** [comment]
Sorry, you're are completely right...Im using EFCore.

**Comment by JonathanMagnan** [comment]
No problem ;)

I will close this request since it's not related to our library.

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
