### ISSUE TITLE
Batch Update fails for enum columns, when the enum derives from long

### ISSUE THREAD

**Issue by StasPerekrestov** [zzzprojects/EntityFramework-Plus#285]
DB Batch Update fails when an entity has an enum property and the enum derives from a type that isn't Int32, e.g. long

<img width="942" alt="screen shot 2017-12-06 at 9 44 15 pm" src="https://user-images.githubusercontent.com/838093/33681939-a45ba6a8-dace-11e7-892d-84c21840de33.png">

System.InvalidCastException
  HResult=0x80004002
  Message=Specified cast is not valid.
  Source=Z.EntityFramework.Plus.EF6
  StackTrace:
   at Z.EntityFramework.Plus.BatchUpdate.CreateCommand[T](ObjectQuery query, SchemaEntityType`1 entity, List`1 values) in D:\Projects\EntityFramework-Plus\src\shared\Z.EF.Plus.BatchUpdate.Shared\BatchUpdate.cs:line 579

**Comment by StasPerekrestov** [comment]
`enum MyColumnTypeEnum: long {
        Item2 = 1<<2,
        Item3 = 1<<3,
        Item4 = 1<<4,
      ///...
}`

**Comment by JonathanMagnan** [comment]
Hello @StasPerekrestov ,

I will close this issue since it should be solved.

Feel free to reopen it if there is something else.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
