### ISSUE TITLE
Delete fail netcore

### ISSUE THREAD

**Issue by giangcoi48k** [zzzprojects/EntityFramework-Plus#289]
`context.Table1.Where(t => t.CreatedDate.Date == DateTime.Today).Delete();`
It delete all record from Table1. LOL

**Comment by JonathanMagnan** [comment]
Hello @giangcoi48k ,

Which provider are you using? Is it possible to provide us the SQL statement executed?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @giangcoi48k ,

I will close this issue since we cannot go further in our investigation.

Feel free to reopen it if you can provide us more information.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
