### ISSUE TITLE
Audit.GetRelationshipEntryKey0 has Core code in EF5/6 conditional

### ISSUE THREAD

**Issue by jonmholt** [zzzprojects/EntityFramework-Plus#295]
`
#if EF5 || EF6

        private static Func<ObjectStateEntry, object> RelationshipEntryKey0;
        private static Func<ObjectStateEntry, object> RelationshipEntryKey1;

        public static object GetRelationshipEntryKey0(ObjectStateEntry entry)
        {
            var relationshipEntryType = typeof(ObjectStateEntry).Assembly.GetType("System.Data.Entity.Core.Objects.RelationshipEntry");

`

"System.Data.Entity.Core.Objects.RelationshipEntry" should be "System.Data.Objects.RelationshipEntry" in EF5/6

**Comment by JonathanMagnan** [comment]
Hello @jonmholt ,

Thank you, we will try to include your pull in the next release (Pull #296 )

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @jonmholt ,

Sorry for the delay, it looks we made the fix last week but forget to release it ;(

The v1.7.13 has been released.

Best Regards,

Jonathan


---
_Help us to support this library: [Donate](http://www.zzzprojects.c

**Comment by JonathanMagnan** [comment]
Hello @jonmholt ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
