### ISSUE TITLE
NotSupportedException happens with simple update

### ISSUE THREAD

**Issue by feafarot** [zzzprojects/EntityFramework-Plus#297]
Exception info:
> An exception of type 'System.NotSupportedException' occurred in EntityFramework.dll but was not handled in user code
> 
> Additional information: Creating a DbModelBuilder or writing the EDMX from a DbContext created using Database First or Model First is not supported. EDMX can only be obtained from a Code First DbContext created without using an existing DbCompiledModel.

Code where I'm getting it is:
```csharp
public void UpdateDescription(int id, string description)
{
    ItemFileSet.Where(x => x.Id == id).Update(x => new ItemFile { DisplayName = description });
}
```

Also, I use `edmx` context generated from EF Code First Model. Sounds like madness but it's the necessity. (:
To do so you can use:
```csharp
using System.Data.Entity.Infrastructure;

void GenerateEdmx()
{
    using (var ctx = new DbContext())
    {
        const string path = @"Context\DbData.edmx";
        using (var writer = XmlWriter.Create(path, 
            new XmlWriterSettings { Encoding = Encoding.UTF8, Indent = true }))
        {
            EdmxWriter.WriteEdmx(ctx, writer);
        }
    }
}
```
With normal EF updates everything works just fine.

**Comment by JonathanMagnan** [comment]
Hello @feafarot ,

Do you think you could send us a project with this error?

It will allow my developer to get started more easily with your issue.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by feafarot** [comment]
@JonathanMagnan Unfortunately it's impossible. It's around 1 Gb and I can't share code according to NDA.
I'll try to reproduce it in a simpler project.

**Comment by feafarot** [comment]
@JonathanMagnan Sorry for the late reply. Here is the project https://drive.google.com/open?id=1WwKWh4hyEDTJ0o3Jqpnmq6Q8SxAeEiBO

**Comment by JonathanMagnan** [comment]
Hello @feafarot ,

Thank you, we will try to check it this week.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @feafarot ,

My developer investigated this issue.

He has come with a solution about how to fix it for our library and perhaps some other third party library you might use.

We normally check if a model is code first and database first using the following line:
`metadataWorkspace.TryGetEntityContainer("CodeFirstDatabase", true, DataSpace.SSpace, out entityContainer);`

However, in your case, the `CodeFirstDatabase` exists but you are `Database First`.

So by replacing all `CodeFirstDatabase` for by example `DatabaseFirstDatabase` when generating your `EDMX` file, our library should work again normally.

Could you try it and let me know if that worked?

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by feafarot** [comment]
@JonathanMagnan Thank you for the solution! I'll try it next week and come back with results.
Have a nice weekend!

**Comment by feafarot** [comment]
@JonathanMagnan Thanks again for the provided solution! Everything works like a charm.
