### ISSUE TITLE
Is support oracle batch update bool field

### ISSUE THREAD

**Issue by FanVon** [zzzprojects/EntityFramework-Plus#298]
Info
  Database : oracle 11gR2
  EntityFramework-Plus : 1.7.11
  Official Oracle ODP.NET, Managed Entity Framework Driver : 12.1.2400
  Database First

Is there any missing configuration? why the update bool field throw expcetion，but the time is right。

Code:
```Csharp
    // right
    var faq = ctx.Set<ZM_ZNKF_FAQ>().First(x => x.ID == 3);
    faq.ISDEFAULT = true;
    ctx.SaveChanges();

    // right
    ctx.Set<ZM_ZNKF_FAQ>()
      .Where(x => x.ID == 3)
      .Update(x => new ZM_ZNKF_FAQ() { UPDATETIME = DateTime.Now });

    // error : value does not fall within the expected range 
    ctx.Set<ZM_ZNKF_FAQ>()
      .Where(x => x.ID == 3)
      .Update(x => new ZM_ZNKF_FAQ() { ISDEFAULT = true });
```

**Comment by JonathanMagnan** [comment]
Hello @FanVon ,

Thank you for reporting.

We will try this scenario to see what's causing it.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @FanVon ,

The v1.7.14 has been released.

`Bool` type should now be supported for Oracle

Let me know if that now work correctly.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
