### ISSUE TITLE
Where(filter).Delete() clears the whole table 

### ISSUE THREAD

**Issue by DevelAx** [zzzprojects/EntityFramework-Plus#308]
The next C# code which is supposed to delete only one row with Id = 16 deletes all the rows in the table.

```
var ids = new List<Tuple<int, string>> { new Tuple<int, string>(16, "Tag16") };
await _dbContext.PostTags.Where(p => ids.Select(i => i.Item1).Contains(p.Id)).DeleteAsync();
```

Generated SQL (incorrect):

```
DECLARE @rowAffected INT
DECLARE @totalRowAffected INT

SET @totalRowAffected = 0

WHILE @rowAffected IS NULL
    OR @rowAffected > 0
    BEGIN
        DELETE TOP (4000)
        FROM    A 
        FROM    [PostTags] AS A
                INNER JOIN ( SELECT [p].[Id]
FROM [PostTags] AS [p]
                           ) AS B ON A.[Id] = B.[Id]

        SET @rowAffected = @@ROWCOUNT
        SET @totalRowAffected = @totalRowAffected + @rowAffected
    END

SELECT  @totalRowAffected
```

**Comment by JonathanMagnan** [comment]
Hello @DevelAx ,

You are right.

This could throw the following exception on EF6 (`Only primitive types or enumeration types are supported in this context.`) but work on EF Core.

The problem comes because the way you write your code, all items will be normally loaded and the filter will be applied to the server since it cannot be translated to SQL. So the `WHERE` clause is hidden from our library since it doesn't apply to SQL but on the server.

Here is how you should do it:

```csharp
var ids = new List<Tuple<int, string>> { new Tuple<int, string>(16, "Tag16") };
var ids2 = ids.Select(i => i.Item1).ToList();
context.EntitySimples.Where(p => ids2.Contains(p.ID)).Delete();
```

Let me known if the explanation is clear and if the fix work.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Yes, be careful.

If you do some select statement like this:
`_dbContext.PostTags.Where(p => ids.Select(i => i.Item1).Contains(p.Id)).ToList()`

If your table has 100k rows, all rows would have been loaded first on your server before getting filtered. Obviously, this could lead very fast to some performance and memory issue.

Best Regards,

Jonathan

**Comment by DevelAx** [comment]
@Jonathan,  thank you for reminding me that. 
I found out that this code can be translated to SQL correctly for both 'Delete':
```
var tagIndexesQuery =
    from pt in _rep.PostTags
    join pti in _rep.PostTagIndexes
    on pt.Id equals pti.PostTagId
    join p in _rep.Posts
    on pti.PostId equals p.Id
    where p.Id == 5
    select pti;

_rep.PostTagIndexes.Delete(tagIndexesQuery);
var tagsQuery = tagIndexesQuery.Select(pti => pti.PostTagId);
_rep.PostTags.Delete(t => tagsQuery.Contains(t.Id));
```
So, it shouldn't be an issue even with 100k rows or more, if I'm not mistaken. 
On the other hand, if I use something like from your example above:

`_dbContext.PostTags.Where(p => ids.Select(i => i.Item1).Contains(p.Id)).ToList();`

where `ids` is already a `List<int>` I could run into a limitation for WHERE...IN clause in some databases, so it should be used carefully because of this reason too.

In my configuration, the number of tags is very limited, so it shouldn't be an issue in both cases.
