### ISSUE TITLE
Batching IncludeOptimized subselects

### ISSUE THREAD

**Issue by NetTecture** [zzzprojects/EntityFramework-Plus#309]
I have a query in the form

Set<A>
.Include( "b.c.d")
.Include("b.f")

b.c.d is to one (i.e. b has one c has one d)
b.f is to one, too.

Can I somehow have those two includes being optimiezd in ONE separate query?

If I replace Include with IncludeOptimized, I get 3 sql submissions. But there is nothing gained by the 3ed query. As both c.d and f are to one, there is no repetitive data.

At least the documentation gives no hint how to batch IncludeOptimized elements again.

**Comment by JonathanMagnan** [comment]
Hello @NetTecture ,

IncludeOptimized work diffently from Include. You must include every path.

Could you try something like this:

```csharp
Set
.IncludeOptimized("b")
.IncludeOptimized("b.c")
.IncludeOptimized("b.c.d")
.IncludeOptimized("b.f);
```

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @NetTecture ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
