### ISSUE TITLE
BatchUpdate when passing a data object in with an enum on it.

### ISSUE THREAD

**Issue by sereeth** [zzzprojects/EntityFramework-Plus#310]
We're doing a simple batch update on an object that has a enum on it and whenever it runs it errors with the following: 

 The CLR enum type MyEnum must be registered with Npgsql before usage, please refer to the documentation.

Sample code: 

```
t.MyObjects.Where(r => r.CreatedDate < date).Update(u => new MyObject()
                {
                    ModifiedDate = DateTime.UtcNow,
                    Status = MyEnum.Expired
                });
```

**Comment by JonathanMagnan** [comment]
Hello @sereeth ,

Thank you for reporting.

We will try to reproduce your scenario with CLR enum type.

Best Regards,

Jonathan

**Comment by SonicGD** [comment]
Hi, i have the same problem. Any news on fix?

**Comment by JonathanMagnan** [comment]
Hello @SonicGD ,

I believe this request has been lost from our tracker.

We will try to check it Friday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @SonicGD ,

Is it possible to get a test project with this issue and including steps to register CLR enum type?

My developer tried it yesterday but none of us are enough familiar with PostgreSQL, so we didn't manage to reproduce the issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @SonicGD ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan
