### ISSUE TITLE
Batch Delete with MySQL provider and EF Core 2

### ISSUE THREAD

**Issue by neumartin** [zzzprojects/EntityFramework-Plus#313]
Hi!

Can I use batch delete with MySQL and EF Core 2?
Thanks!

**Comment by JonathanMagnan** [comment]
Hello @neumartin ,

If you are using `Pomelo` than not yet.

We have a task this weekend to add support to it: https://github.com/zzzprojects/EntityFramework-Plus/issues/311

Best Regards,

Jonathan

**Comment by neumartin** [comment]
Thanks!

**Comment by JonathanMagnan** [comment]
Hello @neumartin ,

Can you tell me which package you are using?

We have made some test and it seems I forget that we already support `Pomelo`.

Best Regards,

Jonathan

**Comment by neumartin** [comment]
Hi!

I never try, I just asking about compatibility.
Thanks @JonathanMagnan !!!
