### ISSUE TITLE
Error when updating-from-query in TPH: "The destination column could not be found" (EF6)

### ISSUE THREAD

**Issue by cjmairair** [zzzprojects/EntityFramework-Plus#315]
Example of problem:

Let's say I have a base class, Animal, and there are different subclasses, in an EF TPH (Table per Hierarchy) setup.

```
var age = 123;
context.Animals.Where(...).Update(a => new Animal() { Age = age });  // throws Exception
```

The exception is "The destination column could not be found: age".

FYI: The property name "age" is the same as the column name in the DB ("age").

So, after reading Issue #238 , I though that my problem would be fixed by downloading the latest version:

Z.EntityFramework.Plus.EF6.dll - 1.7.14.0
Z.EntityFramework.Extensions.dll - 3.14.7.0

But it's not.

I also tried novamxd's forked code (from his repository) (see Issue #245), which supposedly fixed this problem, but it doesn't.

I know that this problem is related to "updating from query" and not "batch updating", but still, I was hoping that novamxd's code would fix this.

**Comment by JonathanMagnan** [comment]
Hello @cjmairair ,

Thank you for reporting,

We will try this scenario this week and see what's missing.

Best Regards,

Jonathan

**Comment by ch-rob** [comment]
+1 Same issue...

`DbSet.Where(whereClause).Update(update);`
`where update is {p => new AssetFileRecord() {NetProceeds = Round(1.1, 2)}}`

AssetFileRecord (our base class in the hierarchy) contains NetProceeds, as does the child class. This worked until I made AssetFileRecord part of a TPH hierarchy.

* EF6
* .Net 4.6.2
* Z.EntityFramework.Plus.EF6 1.7.19

**Comment by JonathanMagnan** [comment]
Hello @cjmairair , @ch-rob ,

The v1.8.0 has been released.

A lot of files has been added/modified for reading the model, so make sure to report me errors if something occurs.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @cjmairair , @ch-rob ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
