### ISSUE TITLE
How to use Audit for SoftAdded

### ISSUE THREAD

**Issue by HowardHoulston** [zzzprojects/EntityFramework-Plus#317]
Hi I am using your wiki example for SoftDeleted with:

`AuditManager.DefaultConfiguration.SoftDeleted<ISoftDeleted>(x => x.IsDeleted);`

I expected that this would create an EntitySoftAdded when I changed IsDeleted to false, but actually it created an EntityModified.

And then I added this for SoftAdded:

`AuditManager.DefaultConfiguration.SoftAdded<ISoftDeleted>(x => !x.IsDeleted);`

So that works OK, except now whenever I do an edit the Audit is flagged as SoftAdded, rather than modified.

Is there a neat way of handling SoftAdd, SoftDelete and Modified?  Basically I want the audit to be Modified if IsDeleted is unchanged, and SoftAdd/SoftDelete if IsDeleted is changed.

I can think of a way to handle this with adding another boolean field (say IsSoftAdd) and setting that to true on a SoftAdd, and false on an Edit, but this seems a bit clunky.

**Comment by JonathanMagnan** [comment]
Hello @HowardHoulston ,

Unfortunately, the library doesn't support it.

The library knows about which field has been modified but doesn't know about the function you provide for the `SoftAdded` or `SoftDeleted` methods. So we cannot check if the field is modified or not.

I believe one way to do it is with your clunky solution.

We will for sure try to provide a better solution when we will re-write our library.

Best Regards,

Jonathan

**Comment by HowardHoulston** [comment]
Hi Jonathan

On reflection I think it is probably best that your library works as it does - this provides maximum flexibility to the user in how they implement these functions.  If anyone is interested this is how I have implemented the functionality (this could be added as an example to the docs as I don't think it's immediately obvious):

```
public interface ISoftDelete
{
    bool IsDeleted { get; set; }
    bool IsSoftAdd { get; set; }
}
```
Edit entity:
```
public void EditMyEntity(MyEntity entity) 
{
    ... update entity properties ...
    entity.IsSoftAdd = false;
    .... save changes ....
}
```
Delete entity (used for soft delete and soft add):
```
public void DeleteMyEntity(int id) 
{
    ... get entity with id ...
    if (entity.IsDeleted) entity.IsSoftAdd = true;
    entity.IsDeleted = !entity.IsDeleted;
    .... save changes ....
}
```
Note: I do not allow editing of a Soft Deleted Entity in my application.

Audit Configuration:
```
AuditManager.DefaultConfiguration.SoftDeleted<ISoftDelete>(x => x.IsDeleted);
AuditManager.DefaultConfiguration.SoftAdded<ISoftDelete>(x => !x.IsDeleted && x.IsSoftAdd);
```
Now I get EntityModified, EntitySoftAdded and EntitySoftDeleted as expected.

Thank you for this excellent library - it is a great contribution to the community.

**Comment by JonathanMagnan** [comment]
Thank you for sharing your solution ;)
