### ISSUE TITLE
Query Filter Memory Usage

### ISSUE THREAD

**Issue by dcomartin** [zzzprojects/EntityFramework-Plus#318]
I have a project that only utilizes Filter<T> functionality.  We do this in the ctor when creating the DbContext for multi-tenancy.   

After running JetBrains dotMemory, here are the top for instances of the largest retained instances.  Is this by design that it's caching the expressions and dbparameters?  Is there anyway to reduce the memory usage?

![capture](https://user-images.githubusercontent.com/1577098/36316009-1d6a3c1a-1307-11e8-80de-5bf2ccb4705d.PNG)

**Comment by JonathanMagnan** [comment]
Hello @dcomartin ,

Could you provide us a test project with this issue? I will have one of my developers look at it and check why so much memory is required.

You can send it here: info@zzzprojects.com

Best Regards,

Jonathan

**Comment by dcomartin** [comment]
Yes, I'll try and come up with a sample project to repro that mimics as closely as I can to our usage.

**Comment by JonathanMagnan** [comment]
Hello @dcomartin 

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan
