### ISSUE TITLE
Use with ef6 1.2.3 ObjectContext

### ISSUE THREAD

**Issue by federicopede** [zzzprojects/EntityFramework-Plus#319]
This useful library is compatible with EF6 ObjectContext? I need use a .Update() function but it throw a 
 NullReferenceException

Thanks

**Comment by JonathanMagnan** [comment]
Hello @federicopede ,

Could you provide us a test project with this error? I will have one of my developers look at it and check if there is some code we can change to support it.

You can send it here: info@zzzprojects.com

Best Regards,

Jonathan

**Comment by federicopede** [comment]
I've sent you the project test ready to run.

Many thanks

**Comment by JonathanMagnan** [comment]
Hello @federicopede ,

The v1.7.15 has been released.

Let me know if that works correctly with ObjectContext.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @federicopede ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by federicopede** [comment]
It works, very thanks!!

-- 
Federico Pederzani

Da: Jonathan Magnan <notifications@github.com> <notifications@github.com>
Rispondi: zzzprojects/EntityFramework-Plus
<reply@reply.github.com>
<reply@reply.github.com>
Data: 18 marzo 2018 at 23:26:17
A: zzzprojects/EntityFramework-Plus
<entityframework-plus@noreply.github.com>
<entityframework-plus@noreply.github.com>
CC: federicopede <federicopede@gmail.com> <federicopede@gmail.com>, Mention
<mention@noreply.github.com> <mention@noreply.github.com>
Oggetto:  Re: [zzzprojects/EntityFramework-Plus] Use with ef6 1.2.3
ObjectContext (#319)

Hello @federicopede <https://github.com/federicopede> ,
