### ISSUE TITLE
Null reference exception when field is nullable datetime and using custom formatType 

### ISSUE THREAD

**Issue by runnerman261** [zzzprojects/EntityFramework-Plus#320]
To reproduce the issue. 
Have a simple

```csharp
class EntityP
{
        public Nullable<System.DateTime> DateTimeDbField
        {
            get;
            set;
        }
}

// Add a custom audit format type  to Format all datetime in ISO format
AuditManager.DefaultConfiguration.FormatType<DateTime>(x => x.ToString("o"));
```

Start with empty value for the first save. Then set the value to a valid datetime and save. One the 2nd  save, the following exception is raised.

Object reference not set to an instance of an object.
at Z.EntityFramework.Plus.AuditConfiguration.<>c__DisplayClass100_0`1.<FormatType>b__0(Object o)
at Z.EntityFramework.Plus.AuditConfiguration.FormatValue(Object entity, String propertyName, Object currentValue)

Exception is occuring in 
public AuditConfiguration FormatType<T>(Func<T, object> formatter)
        {
            Func<object, object> func = o => formatter((T) o); 

-- due to 'o' being null. 

Please suggest a fix or work around.

**Comment by JonathanMagnan** [comment]
Hello @runnerman261 ,

That's your responsibility to check if the value is null or not since a user may when to "format" a null value.

By example:

```csharp
AuditManager.DefaultConfiguration.FormatType(x => {
	if(x == null) {
		return null;
	}
	return x.ToString("o");
}
```

Best Regards,

Jonathan

**Comment by runnerman261** [comment]
Hello Jonathan, 

Thank you for taking the time to look into this issue and respond.
 
This is how i register to format datetime fields. 
    **AuditManager.DefaultConfiguration.FormatType<DateTime>(x => x.ToString("o"));**

Since DateTime is a value type, there really is no point in me checking for null. 
Further more, based on the stack trace, the exception is happening even before the control gets to the code to custom format the field. 

Exception is  System.NullReferenceException: Object reference not set to an instance of an object.
   at Z.EntityFramework.Plus.AuditConfiguration.<>c__DisplayClass100_0`1.<FormatType>b__0(Object o)
   at Z.EntityFramework.Plus.AuditConfiguration.FormatValue(Object entity, String propertyName, Object currentValue)
   at Z.EntityFramework.Plus.AuditEntryProperty.get_OldValueFormatted()
   at lambda_method(Closure , Object )

Thank you.

**Comment by JonathanMagnan** [comment]
Hello @runnerman261 ,

Could you help us to reproduce this issue?

```csharp
using System;
using System.Data.Entity;
using System.Windows.Forms;

namespace Z.EntityFramework.Plus.Lab.EF6
{
    public partial class Form_Request_Audit_DateTimeNullable : Form
    {
        public Form_Request_Audit_DateTimeNullable()
        {
            InitializeComponent();

            // CLEAN
            using (var context = new EntityContext())
            {
                context.EntitySimples.RemoveRange(context.EntitySimples);
                context.SaveChanges();
            }

            // SEED
            using (var context = new EntityContext())
            {
                context.EntitySimples.Add(new EntitySimple {ColumnInt = 1});
                context.EntitySimples.Add(new EntitySimple {ColumnInt = 2});
                context.EntitySimples.Add(new EntitySimple {ColumnInt = 3});
                context.SaveChanges();
            }

            AuditManager.DefaultConfiguration.FormatType<DateTime>(x => x.ToString("o"));
            AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
                // ADD "Where(x => x.AuditEntryID == 0)" to allow multiple SaveChanges with same Audit
                    (context as EntityContext).AuditEntries.AddRange(audit.Entries);

            // TEST
            using (var context = new EntityContext())
            {
                var audit = new Audit();
                context.EntitySimples.Add(new EntitySimple {ColumnInt = 1});
                context.EntitySimples.Add(new EntitySimple {ColumnInt = 2});
                context.EntitySimples.Add(new EntitySimple {ColumnInt = 3});
                context.SaveChanges(audit);
            }
        }

        public class EntityContext : DbContext
        {
            public EntityContext() : base("CodeFirstEntities")
            {
            }

            public DbSet<EntitySimple> EntitySimples { get; set; }

            // ... context code ...
            public DbSet<AuditEntry> AuditEntries { get; set; }
            public DbSet<AuditEntryProperty> AuditEntryProperties { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x =>
                    x.ToTable(GetType().DeclaringType != null
                        ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name
                        : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class EntitySimple
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }
            public DateTime? ColumnDateTime { get; set; }
        }
    }
}
```

Best Regards,

Jonathan

**Comment by runnerman261** [comment]
Yes. 
To reproduce this issue, all i had to do was add the following block of code to update one of the items in the db. 

//Reproduces NULLReference
            using (var context = new EntityContext())
            {
                var entity = context.EntitySimples.First();

                var audit = new Audit();
     //Update the datetime field.        
   entity.ColumnDateTime = DateTime.UtcNow;
                context.Entry(entity).State = EntityState.Modified;
//Fails on this line. 
                **_context.SaveChanges(audit);_**
            }
Please let me know if you need any more info on reproducing this issue. 
Hope this helps. 

Thanks

**Comment by JonathanMagnan** [comment]
Hello @runnerman261 ,

Sorry for the long delay.

The v1.7.17 has been released.

You should no longer have the issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @runnerman261 ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
