### ISSUE TITLE
Any Help for "IQueryable is possibly unintentionally used as IEnumerable"

### ISSUE THREAD

**Issue by spinxdigital** [zzzprojects/EntityFramework-Plus#322]
I am using code like below.

```
public IEnumerable<EmailTemplate> GetCachedEmailTemplates()
{
     return AsNoTracking.FromCache().ToList();
}
```

On parent Repository class I have code for `AsNoTracking`

```
public IQueryable<T> AsNoTracking => _dbSet.AsNoTracking();
```

I am getting below warning from Resharper but not sure how to fix that with AsNoTracking dbset.

![2018-03-11_1427](https://user-images.githubusercontent.com/24282035/37258713-04e526fc-2539-11e8-99f8-3d7ab14d67de.png)

Thank you for any suggestion.

**Comment by JonathanMagnan** [comment]
Hello @spinxdigital ,

Thank you for reporting.

I believe that's an issue with Resharper + Extension methods

If we change the following line

from:
```csharp
return query.FromCache(QueryCacheManager.DefaultCacheItemPolicy, tags);
```

to:
```csharp
return FromCache(query, QueryCacheManager.DefaultCacheItemPolicy, tags);
// return Z.EntityFramework.Plus.QueryCacheExtensions.FromCache(query, QueryCacheManager.DefaultCacheItemPolicy, tags);
```

The warning goes away and obviously, that's the same method that has been invoked... Just differently.

Could you try it on your side and let us know if the warning goes away?

Best Regards,

Jonathan

**Comment by spinxdigital** [comment]
@JonathanMagnan 

I tried that one but now other warning about using Extensions method `FromCache` .

![2018-03-12_0847](https://user-images.githubusercontent.com/24282035/37294084-4c32be5e-25d2-11e8-99d4-1a067a3d6027.png)

I personally like this approach `return query.FromCache("CsCategories").ToList();`

**Comment by JonathanMagnan** [comment]
Yes, this is the approach I prefer as well ;)

Unfortunately, it looks to be an issue with ReSharper && extension methods so there is nothing we can do on our side. You can disable this warning but I don't recommend it either.

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by spinxdigital** [comment]
Great. Thank you for all quick answers and you made really awesome library.
