### ISSUE TITLE
Query Cache - How to: after Insert, I want to get new data?

### ISSUE THREAD

**Issue by somjetsomjet** [zzzprojects/EntityFramework-Plus#323]
Query Cache - How to: after Insert, I want to get new data?

example
key value
1 a
2 b
3 c

1. EF select * from table -> have 3 record
2. EF insert record "4 d"
3. EF select * from table -> have 3 record (How to: I want 4 records of data?)

Help me please
thank

**Comment by JonathanMagnan** [comment]
Hello @somjetsomjet ,

Please check `ExpireAll` and  ExpireTag: http://entityframework-plus.net/query-cache#ef-query-cache-tag--expiretag

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by somjetsomjet** [comment]
Have auto expire like https://blog.3d-logic.com/2014/03/20/second-level-cache-for-ef-6-1/ or not?

**Comment by JonathanMagnan** [comment]
A memory cache is used under the hood,

So you do whatever you want such as adding your SlidingExpiration

See: http://entityframework-plus.net/query-cache#ef-query-cache-control

**Comment by somjetsomjet** [comment]
thank you

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
