### ISSUE TITLE
Question: Cache Manager

### ISSUE THREAD

**Issue by spinxdigital** [zzzprojects/EntityFramework-Plus#324]
Hi,

You guys made really awesome library and we just started using it.

I have question about Cache manager that what we use from entity framework queries `FromCache`
Is that any way can we use that out side without using those query object?

I really like Tagging and Expiration cache time feature and want to use other place like cache page source or may be complex queries or other things.

Thank you.

**Comment by JonathanMagnan** [comment]
Hello @spinxdigital ,

Unfortunately no, there is probably some existing packages better than our library to handle this kind of scenario.

Best Regards,

Jonathan
