### ISSUE TITLE
Query Cache - How to: Set Query Cache for all query?

### ISSUE THREAD

**Issue by somjetsomjet** [zzzprojects/EntityFramework-Plus#325]
Have method to set Query Cache for all table or all query or not?
set 1 place can use all places

**Comment by JonathanMagnan** [comment]
Hello @somjetsomjet ,

I'm not sure to understand the question,

Could you try to explain it better?

Best Regards,

Jonathan

**Comment by somjetsomjet** [comment]
normally we msut set .FromCache() for every LINQ 
Have method to set it on 1 place like default policy or not?

**Comment by JonathanMagnan** [comment]
Hello @somjetsomjet ,

Please check the following docs: http://entityframework-plus.net/query-cache#ef-query-cache-control

For example:

```csharp
// (EF5 | EF6) The query is cached for 2 hours of inactivity
var options = new CacheItemPolicy() { SlidingExpiration = TimeSpan.FromHours(2)};
QueryCacheManager.DefaultCacheItemPolicy = options;
```

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @somjetsomjet ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
