### ISSUE TITLE
Support for EF6 Standard

### ISSUE THREAD

**Issue by hirre** [zzzprojects/EntityFramework-Plus#329]
https://github.com/paulirwin/EntityFramework6-DotNetStandard

Provide a Nuget package which uses above library (EF6 Standard)

**Comment by JonathanMagnan** [comment]
Hello @hirre ,

Thank you for reporting. We will look at it once it will get published on NuGet and if enough people start using it.

Look very promising but I'm not sure if people will really adopt it over EF Core that's supported by Microsoft.

Best Regards,

Jonathan

**Comment by hirre** [comment]
Yes, the problem with EF Core is that it will take too long time to get important festures such as many-to-many automatic relationship support (used alot with web-APIs and e.g. OData)...

**Comment by cunnpole** [comment]
As someone who is currently fighting a loosing battle trying to move from vs2015 to 2017 with EF6.2, a nuget package of this would be very handy. Apparently the add-migrations/update-database commands within visual studio gets very confused if you use model annotations such as Required and have .Net Standard 2.0 dependencies (it picks up the wrong version of ComponentModel). Fluent works but I have hundreds of entities to I haven't got time to change for no good reason. Automigrations and Migrate.exe work also. This package looks like it might work around the problem entirely.
