### ISSUE TITLE
Cache extension installation

### ISSUE THREAD

**Issue by mehmetilker** [zzzprojects/EntityFramework-Plus#33]
According to your documentation it is enough to just installing (nuget page) "Z.EntityFramework.Plus.QueryCache.EFCore" library. When I try to call FromCache() method I could not compile project and got warning  and had to install "Z.EntityFramework.Plus.QueryDeferred.EFCore" library as well.

Is there specific situation we need to install QueryDeferred or is it a must install with Cache extensio ?

**Comment by zzzprojects** [comment]
Currently, EF Cache && EF Query Future require also Query Deferred.

We added a task to remove the dependencies in both libraries. This should be completed in one or two weeks.
