### ISSUE TITLE
EFPlus for EFCore Update function inserts a short date

### ISSUE THREAD

**Issue by VyacheslavSulimov** [zzzprojects/EntityFramework-Plus#330]
We have a next code 
`var now = DateTime.UtcNow;`
           ` await this.dbContext.Orders.Where(x => x.Status == OrderStatus.Created).UpdateAsync(x => new Order() { Status = OrderStatus.Collected, LastUpdatedAt = now }); `
![image](https://user-images.githubusercontent.com/9913905/37447788-b4827fc6-2834-11e8-9e03-d5fd7ebbafe9.png)

            var items = this.dbContext.Orders.Where(x => x.Status == OrderStatus.Collected && x.LastUpdatedAt == now)
                .ToList();` 
![image](https://user-images.githubusercontent.com/9913905/37447810-cbf5f2fa-2834-11e8-8455-6154377b45f9.png)

When  we see the query for update orders in sql profiler we look what date is short with  and next query return is empty collection.

**Comment by JonathanMagnan** [comment]
Hello @VyacheslavSulimov ,

Thank you for reporting.

We will look at this issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @VyacheslavSulimov ,

The v1.7.16 has been released

Let me know if you still have the issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @VyacheslavSulimov ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
