### ISSUE TITLE
Bach update with mysql throwing table donesn't exists error

### ISSUE THREAD

**Issue by spksac** [zzzprojects/EntityFramework-Plus#331]
Hello,

I have tried to use the EF-Plus(Version 1.7.15) to BulkUpdate to Mysql db. code look like below

var keys= new List<long>{ 100, 200, 300, 400, 500};
ctx.Users.Where(x => keys.Contains(x.Id))
         .UpdateAsync(x => new User() { IsSoftDeleted = 1 });

im getting the error message as table doesn't exists  and the table name is showing as 
"schema.schema.Users". schema name is appending twice with the table name.
kindly check and update.
thanks

**Comment by JonathanMagnan** [comment]
Hello @spksac ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @spksac ,

My developer tried it but didn' successfully reproduced the problem.

Could you provide us a test project with this issue including the MySQL table creation?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @spksac ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan
