### ISSUE TITLE
FromCache() crashes in EFCore 2.1 Preview

### ISSUE THREAD

**Issue by vpikalev** [zzzprojects/EntityFramework-Plus#332]
While the following query works perfectly with EFCore 2.0 it leads to NullReferenceException with EFCore 2.1 Preview:

**`var result = new TestContext().Set<Agent>().Where(x => x.Id == 1).FromCache().FirstOrDefault();`**

Exception details:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Z.EntityFramework.Plus.EFCore
  StackTrace:
   at Z.EntityFramework.Plus.InternalExtensions.CreateCommand(IQueryable source, RelationalQueryContext& queryContext)
   at Z.EntityFramework.Plus.QueryCacheManager.GetCacheKey(IQueryable query, String[] tags)
   at Z.EntityFramework.Plus.QueryCacheExtensions.FromCache[T](IQueryable`1 query, MemoryCacheEntryOptions options, String[] tags)
   at EfCache21.Program.Main(String[] args) in x:\Projects\Temp\EF7\EfCache21\Program.cs:line 12

```

Project file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0-preview1-final" />
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="1.7.15" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.1.0-preview1-final" />
  </ItemGroup>
</Project>
```

**Comment by JonathanMagnan** [comment]
Hello @vpikalev ,

Thank you for reporting, however, we do not support preview version since some internal code keeps getting modified which make it hard on our side to keep our library up to date.

Once the stable version is released, feel free to ask for a fix if none has been provided yet.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @vpikalev ,

Could you try the v1.7.18?

We finally choose to add some support to `preview1` and `preview2`

Best Regards,

Jonathan

**Comment by vpikalev** [comment]
Hi Jonathan,

Have tried the following:
- EFCore 2.1 Preview 2 and v1.7.18
- EFCore 2.1 Preview 2 and v1.7.15

Both run the above query without any issues.

Thanks
Vlad

**Comment by vpikalev** [comment]
Hi Jonathan,

Have tried the following:

EFCore 2.1 Preview 2, EntityFrameworkCore 2.1.0-preview2-final and v1.7.18

The above query runs without any issues.

Thanks
Vlad

**Comment by JonathanMagnan** [comment]
Hello @vpikalev ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan.
