### ISSUE TITLE
UpdateAsync not working in EF Core 2.1

### ISSUE THREAD

**Issue by MaklaCof** [zzzprojects/EntityFramework-Plus#334]
I read your response in 2 other threads not supporting stable releases, still I am cornered here, because I need EF Core 2.1, official version not coming out for at least several months.  I really like idea not to query data just so I can call update.
So this statement:
```
await this.Context.Set<MyTable>().Where(t => t.Id == id).UpdateAsync(t => new DbMyTable() { Status = Statuses.NotProcessed });
```
throws:

> Object reference not set to an instance of an object.

Callstack:
```
   at Z.EntityFramework.Plus.InternalExtensions.CreateCommand(IQueryable source, RelationalQueryContext& queryContext)
   at Z.EntityFramework.Plus.BatchUpdate.CreateCommand(IQueryable query, IEntityType entity, List`1 values)
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
```

I hope you will take the time to have a look, since this is really basic staff. That said, I understand you quote:

> Thank you for reporting, however, we do not support preview version since some internal code keeps getting modified which make it hard on our side to keep our library up to date.
> 
> Once the stable version is released, feel free to ask for a fix if none has been provided yet.
> 

Like I said, stable release is coming out in a few months and if fix is not provided I wouldn't have any choice but to comment code until fix is provided which I really don't want to do it.

**Comment by MaklaCof** [comment]
One additional note. Delete raise same exception.

**Comment by JonathanMagnan** [comment]
Hello @MaklaCof ,

Thank you for reporting, we will take your opinion into consideration.

One problem we have to support `preview` is some internal code `is modified` from one to another one which makes the support very hard. It's already enough hard to support multiple stables at the same time.

We don't want to support multiple preview version and supporting only the latest preview version may introduce bugs to people that upgrade our library but not their previous version. We are just not sure yet how to handle it correctly beside supporting only stable version.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @MaklaCof ,

Could you try the v1.7.18?

We finally choose to add some support to preview1 and preview2

Best Regards,

Jonathan

**Comment by MaklaCof** [comment]
Hi, I am unable. I had also problems with ImageSharp and I had to downgrade back to 2.0. I will close this thread and reopen, if problem is not solved.
