### ISSUE TITLE
Audit deadlock

### ISSUE THREAD

**Issue by knopa** [zzzprojects/EntityFramework-Plus#336]
I have an issue with audit table deadlock, when I am trying to calculate stats during someone is doing some changes on tracked objects. 

As I understand it got deadlock because audit has table lock while adding new items. Is there any idea how to improve that way?

**Comment by JonathanMagnan** [comment]
Hello @knopa ,

Which version of Entity Framework are you using? The answer will vary depending on it.

Best Regards,

Jonathan

**Comment by knopa** [comment]
@JonathanMagnan 

I am using ef 6.2 with 4.7.1

**Comment by JonathanMagnan** [comment]
Hello @knopa ,

Unless you modified some transaction configuration, `EF6` should not lock the table. It uses a transaction but everything should be fine.

You can use our paid library to improve the performance: http://entityframework-extensions.net/

Perhaps I misunderstood the problem, is the look happening in the `AuditEntries` and `AuditEntryProperties` table or somewhere else?

Best Regards,

Jonathan

**Comment by knopa** [comment]
I use paid version.
and usually has issue with lock

SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM  [dbo].[AuditEntries] AS [Extent1]
        INNER JOIN [dbo].[AuditEntryProperties] AS [Extent2] ON ([Extent1].[AuditEntryID] = [Extent2].[AuditEntryID]) AND (([Extent2].[PropertyName] = @p__linq__4) OR (([Extent2].[PropertyName] IS NULL) AND (@p__linq__4 IS NULL))) AND (([Extent2].[NewValue] = @p__linq__5) OR (([Extent2].[NewValue] IS NULL) AND (@p__linq__5 IS NULL)))
        WHERE (([Extent1].[EntityTypeName] = @p__linq__0) OR (([Extent1].[EntityTypeName] IS NULL) AND (@p__linq__0 IS NULL))) AND ([Extent1].[CreatedDate] >= @p__linq__1) AND ([Extent1].[CreatedDate] <= @p__linq__2) AND ( NOT ((N'System' = [Extent1].[CreatedBy]) AND ([Extent1].[CreatedBy] IS NOT NULL))) AND (([Extent1].[CreatedBy] = @p__linq__3) OR (([Extent1].[CreatedBy] IS NULL) AND (@p__linq__3 IS NULL)))
    )  AS [GroupBy1]

**Comment by JonathanMagnan** [comment]
Hello @knopa ,

Just for the fun, how much time it takes to execute the current query?

It looks to take several seconds depending on your table size.

What's the goal of this query? Returning the number of changes to a specific date range? If yes, perhaps adding an index on the `CreatedDate` may help.

Best Regards,

Jonathan

**Comment by knopa** [comment]
I use that as stats table per user perfomance in updates object by specific field and date range.
For createddate index of course I will add it, but it doesn't relate.  What about lock? As i know select used read commited isolation level, so no page lock should be in that case.

**Comment by JonathanMagnan** [comment]
Hello @knopa ,

`read commited` may cause lock. 

For example: https://social.msdn.microsoft.com/Forums/sqlserver/en-US/34791531-2a64-4e22-8c5d-84606a46788b/how-can-a-select-statement-result-in-being-chosen-as-deadlock-victim?forum=transactsql

If your query takes a long time and there is some change during the statement, it must wait that all changes are committed.

I'm probably not the best person to explain it but it can certainly cause some lock and lead to deadlock.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @knopa ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
