### ISSUE TITLE
FromCache call sometimes results in "Index was outside the bounds of the array."

### ISSUE THREAD

**Issue by john-luke-laue** [zzzprojects/EntityFramework-Plus#338]
I got this error after doing an iisreset.
I don't remember getting this error ever before. 

Strange that it doesn't happen consistently. Sometimes it works fine, and sometimes I get the error. Makes me think this a multi-threading issue or something similar. 

```
var additionalTags = new List<string>(tags);
additionalTags.Add(CacheTags.All);

//Error here
query.FromCache(additionalTags.ToArray());
```

**StackTrace:**
Exception Message: Index was outside the bounds of the array. 
Stack trace: 

```
   at System.Collections.Generic.List`1.Contains(T item)
   at Z.EntityFramework.Plus.QueryCacheManager.<>c__DisplayClass40_0.b__1(String x, List`1 list)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at Z.EntityFramework.Plus.QueryCacheManager.AddCacheTag(String cacheKey, String[] tags)
   at Z.EntityFramework.Plus.QueryCacheExtensions.FromCache[T](IQueryable`1 query, MemoryCacheEntryOptions options, String[] tags)
   at Z.EntityFramework.Plus.QueryCacheExtensions.FromCache[T](IQueryable`1 query, String[] tags)

```

**Comment by JonathanMagnan** [comment]
Hello @john-luke-laue ,

Honestly, I don't think there is anything we can do.

Looking at the stack trace, it happens on this line:

```csharp
if (!list.Contains(cacheKey))
```

which call the contain method from the list.

At this point, these are some internal method that we don't have access.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @john-luke-laue ,

This issue will be closed since it has been answered and there is nothing we can really do about it.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @nathan-hitchman ,

I don't think it should have been closed either.

We will look at it.

**Comment by JonathanMagnan** [comment]
Hello @nathan-hitchman ,

We added two locks to solve this issue: https://github.com/zzzprojects/EntityFramework-Plus/commit/296a3cddff2a3c73da2e89b0d892339944d1ce78

We will closely check it to make sure we don't create any eventual deadlock since we actually locked the object instead of creating a global lock.

**Comment by nathan-hitchman** [comment]
Thanks @JonathanMagnan !

**Comment by john-luke-laue** [comment]
Thank you @JonathanMagnan !
