### ISSUE TITLE
src\shared\Z.EF.Plus.Audit.Shared\Extensions\DbContext\SaveChanges.cs.bak

### ISSUE THREAD

**Issue by dsidirop** [zzzprojects/EntityFramework-Plus#345]
And also the file:

src\shared\Z.EF.Plus.Audit.Shared\Extensions\DbSet`AuditEntry\SaveChanges - Copy (2).cs.bak

Do these files serve any real purpose? They are both marked as content and the only difference I could spot compared to SaveChanges.cs was:

"using Microsoft.Data.Entity;"   vs    "using Microsoft.EntityFrameworkCore;"

I'm reporting this because when someone attempts to generate a nuget package from the source code the "nuget-ification" mechanism embeds these files as "Content" in the resulting nuget package (your official nuget packages don't suffer from this probably because you follow a different packaging mechanism). I just though to bring this quirk to your attention given that if these file are there by mistake the fix should be fairly trivial:

Either delete these files all together or set their type to "None" (instead of "Content" which is the currently employed setting for this file).

Thanks again for this awesome library and keep up the good work.

**Comment by JonathanMagnan** [comment]
Hello @dsidirop ,

Thank you for reporting.

We will look at it and fix it during the weekend probably.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @dsidirop ,

It seems we forget to deploy this fix. We have merged the fix today to remove this .bak file

Best Regards,

Jonathan
