### ISSUE TITLE
Subquery with another table in BatchUpdate 

### ISSUE THREAD

**Issue by Hauptsatana** [zzzprojects/EntityFramework-Plus#346]
I have 2 tables: **Assets** and **MaximoAssets**, linked by **MaximoAssetID** column in Assets table.
I want to set **MaximoAssetID** for each record based on custom criteria:

`asset.SerialNumber = maximoAsset.AssetNum`

So the actual SQL query can look like this:
```
UPDATE A 
SET A.[MaximoAssetID] = B.ResourceID
FROM [Assets] AS A
INNER JOIN maximo.Assets AS B 
ON A.[SerialNumber] = B.[AssetNum]
```

I have done many attempts with EF+ and got mainly invalid SQL and at the least erroneous LINQ query was
```
context.Assets.Update(x => new Asset()
    {
        MaximoAssetId = context.MaximoAssets
            .Where(ma => ma.AssetNum == x.FinanceNumber)
            .Select(ma => ma.ResourceId)
            .SingleOrDefault()
    }
);
```
which produced this SQL query (some columns from JOIN are removed):
```
UPDATE A 
SET A.[MaximoAssetID] = B.[SerialNumber]
FROM [Assets] AS A
INNER JOIN (
    SELECT [a].[AssetID], [a].[FinanceNumber], [a].[MaximoAssetID], [a].[PlateNumber], [a].[SerialNumber]
    FROM [Assets] AS [a]
) AS B ON A.[AssetID] = B.[AssetID]
```

As you see there is no appearance of **MaximoAssets** table, but **SerialNumber** value used in == is assigned. When I tried other columns (e.g. **FinanceNumber**) in ==, they appeared in Update statement.

As far as I learned from LINQ syntax and generated SQL, BatchUpdate can be used to update columns based only on current table values. **Is it possible in general to use other tables data?** 

For instance, this is LINQ query which EF Core translates to single valid SQL squery:
```
context.MaximoPM
    .Where(x => context.Assets.Any(a => a.SerialNumber == x.AssetNum))
    .ToList();
```
You see, inside WHERE clause I am able to access any table.

**Comment by JonathanMagnan** [comment]
Hello @Hauptsatana ,

I don't think your scenario is possible. You are using the `context` inside the `Update` method and that's something we do not support.

Inside the Update, you should use your `x` with Navigation Properties:

```csharp
context.Assets.Update(x => new Asset()
    {
        MaximoAssetId = x.MaximoAssets
            .Where(ma => ma.AssetNum == x.FinanceNumber)
            .Select(ma => ma.ResourceId)
            .SingleOrDefault()
    }
);
```

I'm not sure if it will work either if you have a navigation property but it worth a try.

If you can provide us a test project with this scenario, I will be happy to look a little to it to determine if there is something we can do.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Hauptsatana ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan

**Comment by psyren89** [comment]
Using a navigation property does not appear to work:
```c#
var foos = context.Foos.Where(f => f.DeletedAt == null);
foos.Update(f => new Foo { Sum = f.Bars.Sum(b => b.Value) });
```

Produces:
```
System.Data.SqlClient.SqlException : Incorrect syntax near 'Id'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
...
```

**Comment by JonathanMagnan** [comment]
Hello @psyren89 ,

Could you open a new thread about this issue?

Best Regards,

Jonathan

**Comment by psyren89** [comment]
Done: #416
