### ISSUE TITLE
System.Exception: Invalid Cast. The update expression must be of type MemberInitExpression

### ISSUE THREAD

**Issue by MeTitus** [zzzprojects/EntityFramework-Plus#357]
Hi, I am getting the following error using 

    System.Exception: Invalid Cast. The update expression must be of type MemberInitExpression. at Z.EntityFramework.Plus.BatchUpdate.ResolveUpdateFromQueryDictValues[T](Expression`1 updateFactory)

And this is what I am doing:

            public void Update(Expression<Func<CustomerConsentEntity, bool>> expression, CustomerConsentEntity entity)
        {
            DbContext.CustomerConsents.Where(expression).Update(x => entity);
        }

        public void Update(Expression<Func<CustomerConsentEntity, bool>> expression, CustomerConsentEntity entity)
        {
            DbContext.CustomerConsents.Where(a => a.TrackingId == Guid.Parse("4D8214D5-3D43-4A3E-9572-BCDCEA6F3BF9")).Update(x => entity);
        }

I am using the Z.EntityFramework.Plus and have done this a couple of times, but this time it seems to be failing for some strange reason.

**Comment by MeTitus** [comment]
https://stackoverflow.com/questions/50415932/z-entityframework-plus-memberinitexpression-error

**Comment by JonathanMagnan** [comment]
Hello @MeTitus ,

The parameter for the `Update` method must be an expression. You currently pass an entity!

Our method doesn't know which field should be updated and thrown that error.

You can find some example here: http://entityframework-plus.net/batch-update

Let me know if that helped you to understand the current problem.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by MeTitus** [comment]
Thanks for your repply @JonathanMagnan.

I do understand what you say but I can't get this to work either, my post on stack had a few more examples:

`    public void Update(Expression<Func<CustomerConsentEntity, bool>> expression, CustomerConsentEntity entity)
    {
        Expression<Func<CustomerConsentEntity, CustomerConsentEntity>> updateEntity = x => entity;

        DbContext.CustomerConsents.Where(expression).Update(updateEntity);
    }`

**Comment by MeTitus** [comment]
Thanks for your repply @JonathanMagnan.

I do understand what you say but I can't get this to work either, my post on stack had a few more 


public void Update(Expression<Func<CustomerConsentEntity, bool>> expression, CustomerConsentEntity entity)
    {
        Expression<Func<CustomerConsentEntity, CustomerConsentEntity>> updateEntity = x => entity;

        DbContext.CustomerConsents.Where(expression).Update(updateEntity);
    }

**Comment by JonathanMagnan** [comment]
Using your expression,

Which property should I update? All of them?

That's the current question the method asks which that it had no answer. The method doesn't know which properties to update since you pass an entity and not a properties list.

**Comment by MeTitus** [comment]
Using the example bellow, I don't see how this is using a list of properties, it is using the object itself and setting one of its properties.

```
var date = DateTime.Now.AddYears(-2);
ctx.Users.Where(x => x.LastLoginDate < date)
         .UpdateAsync(x => new User() { IsSoftDeleted = 1 });
```

**Comment by JonathanMagnan** [comment]
Exactly,

Since that's an expression, our method have access to the MemberInitExpression `{ IsSoftDeleted = 1 }` and know that the property `IsSoftDeleted` should be updated to `1`.

The expression has all informations required for the method.

In your case, you pass an entity, so we don't know which properties to changes.

**Comment by MeTitus** [comment]
Ok to give a bit more context, cause I am feeling a bit lost:

This is the caller method

```
                DbContextUnitOfWork.CustomerConsentRepository.Update(x => x.TrackingId == message.TrackingId,
                    x => new CustomerConsentEntity
                    {
                        Sms = message.Sms,
                        Post = message.Post,
                        Email = message.Email,
                        Telephone = message.Telephone,
                        TrackingId = message.TrackingId,
                        FeedbackSourceId = (int)message.FeedbackSource
                    });
```
which works fine the this implementation:

```
        public void Update(Expression<Func<CustomerConsentEntity, bool>> expression, Expression<Func<CustomerConsentEntity, CustomerConsentEntity>> updateExpression)
        {
            DbContext.CustomerConsents.Where(expression).Update(updateExpression);
        }
```

The question is, why wouldn't something like this work too?
```

                DbContextUnitOfWork.CustomerConsentRepository.Update(x => x.TrackingId == message.TrackingId,
                    x => new CustomerConsentEntity
                    {
                        Sms = message.Sms,
                        Post = message.Post,
                        Email = message.Email,
                        Telephone = message.Telephone,
                        TrackingId = message.TrackingId,
                        FeedbackSourceId = (int)message.FeedbackSource
                    });
```

**Comment by JonathanMagnan** [comment]
The short answer is one is a parameter of type `Expression<Func<CustomerConsentEntity, CustomerConsentEntity>>` and the other is a parameter of type `CustomerConsentEntity`.

In the first case, the expression is not compiled and our library can access to all the codes that may be later compiled. We can retrieve anything from an expression.

In the second case, the customer instance is created (the code is already compiled), so it cannot be used in the same way in an expression. We cannot retrieve properties from it.

You probably have some reason that you cannot do it but the easiest solution would be to change your method:

```csharp
Update(x => x.ID > 0, x => new EntitySimple() { ColumnInt = 2 });

public void Update(Expression<Func<EntitySimple, bool>> expression, Expression<Func<EntitySimple, EntitySimple>> updateEntity)
```

Let me know if you understand better.

Best Regards,

Jonathan

**Comment by MeTitus** [comment]
I would have thought that this:

`Expression<Func<CustomerConsentEntity, CustomerConsentEntity>> updateEntity = x => entity;`

would be the same as:

`Expression<Func<CustomerConsentEntity, CustomerConsentEntity>> updateEntity = x => new CustomerConsentEntity{ Property = ""}`

But that doesn't seem to be the case, I just wonder why.

Thanks for your help.

**Comment by JonathanMagnan** [comment]
Hello @MeTitus ,

Both are pretty much the same but in your first example, we don't know which property for the Entity need to be updated since you pass the whole entity.

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
