### ISSUE TITLE
Key property not saved when all properties are ignored

### ISSUE THREAD

**Issue by iamkintetic** [zzzprojects/EntityFramework-Plus#36]
I'm not sure if this is by design or not.  I'm using this configuration :

     audit.Configuration.Exclude(a => true);
     audit.Configuration.Include<IAuditable>();
     audit.Configuration.ExcludeProperty();

What I was trying to do was to save my audit without having anything in AuditEntryProperties beside the key properties.

What I'm getting is only data in AuditEntry and nothing in AuditEntryProperties, not even keys.  Do I really have to include manually all key to get the wanted result?

**Comment by zzzprojects** [comment]
Thank you for reporting,

We are supposed to make some modification to the audit feature this week,

I will look at this issue at the same time. 

The issue is you exclude all property (including key property)

```csharp
audit.Configuration.ExcludeProperty();
```

However, key property should probably never be excluded

**Comment by iamkintetic** [comment]
Yes, because AuditEntries without the key are pretty much useless.

**Comment by zzzprojects** [comment]
The v1.4.0 is now released.

Key property is not longer excluded when all properties are excluded like in your example.

Let me know if this issue is now fixed.

**Comment by iamkintetic** [comment]
Yep, it's now working like a charm!
