### ISSUE TITLE
Download page broken

### ISSUE THREAD

**Issue by Jogai** [zzzprojects/EntityFramework-Plus#360]
See http://entityframework-plus.net/download

Its linked on http://entityframework-plus.net/installing

**Comment by JonathanMagnan** [comment]
Hello @Jogai ,

Thank a lot for reporting, the issue has been fixing.

We are currently making some major changes to the website so feel free to re-open it if we make again this mistake.

_(Yes that's normal the layout is still ugly for the download, it will be improved today)_

Best Regards,

Jonathan
