### ISSUE TITLE
Batch Delete() with separate transaction for each DELETE command.

### ISSUE THREAD

**Issue by smzinovyev** [zzzprojects/EntityFramework-Plus#362]
Hi Team,

I need to delete millions records from a table using some condition. (Truncate table is not an option for me). But I cannot run Delete command in one transaction as transaction log file will grow too much. I want to run batch delete and wrap each delete command in a separate transaction to control size of transaction log file.

Your lib is great. And I wonder if you support such case.

Currently, if I run this
```
ctx.Tbl
    .Where(x => x.StateCode == "CA" && x.Version == "V1")
    .Delete();
```

It produces this sql commands:
```
SELECT 
    [Extent1].[Id] AS [Id]
    FROM [dbo].[Tbl] AS [Extent1]
    WHERE (N'CA' = [Extent1].[StateCode]) AND (N'V1' = [Extent1].[Version])

-- Executing at 5/27/2018 10:07:14 AM -04:00
-- Completed in 0 ms with result: null

DECLARE @rowAffected INT
DECLARE @totalRowAffected INT

SET @totalRowAffected = 0

WHILE @rowAffected IS NULL
    OR @rowAffected > 0
    BEGIN
        DELETE TOP (4000)
        FROM    A 
        FROM    [dbo].[Tbl] AS A
                INNER JOIN ( SELECT 
    [Extent1].[Id] AS [Id]
    FROM [dbo].[Tbl] AS [Extent1]
    WHERE (N'CA' = [Extent1].[StateCode]) AND (N'V1' = [Extent1].[Version])
                           ) AS B ON A.[Id] = B.[Id]

        SET @rowAffected = @@ROWCOUNT
        SET @totalRowAffected = @totalRowAffected + @rowAffected
    END

SELECT  @totalRowAffected

-- Executing at 5/27/2018 10:07:14 AM -04:00
-- Completed in 5 ms with result: 1
```

Why do you have `SELECT` while deleting rows?
```
SELECT 
    [Extent1].[Id] AS [Id]
    FROM [dbo].[Tbl] AS [Extent1]
    WHERE (N'CA' = [Extent1].[StateCode]) AND (N'V1' = [Extent1].[Version])
```

And actually what I am looking for is something like below:
```
-- No parent transaction as we use separate transaction for each batch inside loop
DECLARE @rowAffected INT
DECLARE @totalRowAffected INT

SET @totalRowAffected = 0

WHILE @rowAffected IS NULL
    OR @rowAffected > 0
    BEGIN
        BEGIN TRANSACTION
		
        DELETE TOP (4000)
        FROM    A 
        FROM    [dbo].[Tbl] AS A
                INNER JOIN ( SELECT 
    [Extent1].[Id] AS [Id]
    FROM [dbo].[Tbl] AS [Extent1]
    WHERE (N'CA' = [Extent1].[StateCode]) AND (N'V1' = [Extent1].[Version])
                           ) AS B ON A.[Id] = B.[Id]

        SET @rowAffected = @@ROWCOUNT
        SET @totalRowAffected = @totalRowAffected + @rowAffected
		
        COMMIT
    END

SELECT @totalRowAffected
```

--
Sergiy

**Comment by JonathanMagnan** [comment]
Hello @smzinovyev ,

The first `SELECT` doesn't hit the database. It's a trick on our side to get the `SELECT` to include in the `INNER JOIN`

The `INNER JOIN` is required because we use some Entity Framework. We are aware the query can be optimized but we will no longer be able to support as much as we do currently.

We will eventually try to remove the `INNER JOIN` when that's not needed but currently, that is too much effort for the time we are able to pass on this library.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @smzinovyev ,

This issue will be closed since it has been answered.

However, we still have an open task on our to-do list on our side to eventually fix it.

Best Regards,

Jonathan
