### ISSUE TITLE
Problems with Auditing.

### ISSUE THREAD

**Issue by mardon1975** [zzzprojects/EntityFramework-Plus#363]
Hello,

I am trying to configure your plug in for my project to simplify auditing. I am struggling right now with getting the library to log anything to the database. Here are the details.

1. Database First using the schema from your website.
2. I am trying to override the SaveChanges method for the full application. My application structure i have created a repository class for each section of functionality. All of this is being injected using Microsoft.Practices.Unity. In the unity configurator file we create a new instance of the entity framework context. It is then injected into the repository method constructors.
3. I have abstracted a partial class to override the save changes default method of the dbcontext. The problem i am running into is around setting up the configuration, and saving the any values into the database.

**Comment by JonathanMagnan** [comment]
Hello @mardon1975 ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan

**Comment by mardon1975** [comment]
Hello @JonathanMagnan. Can I get your email address. I am finally getting a chance to work on a demo project for you guys to see how we can use your product.

**Comment by JonathanMagnan** [comment]
Hello @mardon1975 ,

info@zzzprojects.com
