### ISSUE TITLE
Batch Delete does not work with DateTimeOffset condition.

### ISSUE THREAD

**Issue by SamHuo213** [zzzprojects/EntityFramework-Plus#367]
Hi All,

I have a project that is running on .Net Core 2.1, EF Core 2.1 and PostgreSql.  I am using EntityFramework-plus to perform a batch delete on one of my Entity that has a DateTimeOffset column.  I am trying to Delete all rows that has a saved time that is less than current time.  Instead of checking the condition all rows are deleted.  I recently updated to EF Core 2.1 and change the column to use DateTimeOffset instead of Datetime and it was working before.  The following code is what I am trying todo.

context.Entity
    .Where(x => x.ExpirationTime <= DateTimeOffset.UtcNow)
    .Delete();

Please let me know if you need anymore detail.

Sam

**Comment by SamHuo213** [comment]
Thanks for the quick reply.

**Comment by JonathanMagnan** [comment]
Hello @SamHuo213 ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
