### ISSUE TITLE
Query Filter Global cache initialization problem with EF6

### ISSUE THREAD

**Issue by ipetrushevskiy** [zzzprojects/EntityFramework-Plus#368]
Hello. Starting with version 1.6.21 I noticed a problem on my services startup: there were exceptions when at the same moment service responds multiple HTTP-requests which were reading the data where "Global Query Filter" was used. I made a simple project example with such behavior.
[QueryFilterGlobal.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/2088515/QueryFilterGlobal.zip)

**Comment by JonathanMagnan** [comment]
Hello @ipetrushevskiy ,

Thank you for reporting, we successfully reproduced it.

I will assign a developer tomorrow to check what's happening.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ipetrushevskiy ,

The issue has finally been found and fixed.

The fix will be part of the next release.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ipetrushevskiy ,

Sorry for the long delay, we should have released it when the fix was ready.

The v1.8.3 has been released, it should contains this fix.

Let me know if the multi-thread scenario is now working.

Best Regards,

Jonathan
