### ISSUE TITLE
Cannot build the Z.EntityFramework.Plus.EFCore project

### ISSUE THREAD

**Issue by terryaney** [zzzprojects/EntityFramework-Plus#37]
I downloaded the latest source and when I open it up in VS 2015 Community, I get the following errors in project.json:

The dependency Microsoft.Extensions.Logging 1.0.0 in project Z.EntityFramework.Plus.EFCore does not support framework .NETFramework,Version=v4.5.1.

The dependency Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0 in project Z.EntityFramework.Plus.EFCore does not support framework .NETFramework,Version=v4.5.1.	

The dependency Microsoft.Extensions.DependencyInjection 1.0.0 in project Z.EntityFramework.Plus.EFCore does not support framework .NETFramework,Version=v4.5.1.

The dependency Microsoft.Extensions.Options 1.0.0 in project Z.EntityFramework.Plus.EFCore does not support framework .NETFramework,Version=v4.5.1.

The dependency Microsoft.Extensions.Caching.Abstractions 1.0.0 in project Z.EntityFramework.Plus.EFCore does not support framework .NETFramework,Version=v4.5.1.

The dependency Microsoft.NETCore.Platforms 1.0.1 in project Z.EntityFramework.Plus.EFCore does not support framework .NETFramework,Version=v4.5.1.

And am unable to build the project.  Is there something I'm missing?

**Comment by zzzprojects** [comment]
Hello Terry,

That's very strange, do you think you could provide me a project sample with this issue?

That is probably the fastest and easiest way for me to discover what's missing.

Best Regards,

Jonathan

**Comment by terryaney** [comment]
I just opened your solution file. All other variants if there project could build.

**Comment by zzzprojects** [comment]
Hello Terry,

Is this possible this issue only happen because you do not have the latest version of .NET Core installed?

All I found similar to this is thread about people not having the latest version

**Comment by terryaney** [comment]
Possible.  Totally green in .NET Core.  I'll go look to see how to install the latest version (unless you know a quick command).

**Comment by zzzprojects** [comment]
Probably simply removing the project from the solution will be the best thing to do since you don't need it ;)

**Comment by terryaney** [comment]
Yeah, except I would rather make jump to CORE instead of EF6 I think.  Will investigate more.

**Comment by zzzprojects** [comment]
That's strictly my opinion, but I don't recommend using EF Core yet...

**Comment by terryaney** [comment]
You definitely would know better than me...any blog posts or anything with your commentary to read?

**Comment by zzzprojects** [comment]
I have not read any blog talking about it but here is a short list of irritants:

- DO NOT support Complex Type
- DO NOT support TPC
- DO NOT support TPT
- DO NOT support [Cast by Inheritance](https://github.com/aspnet/EntityFramework/issues/5774)
- ISSUE with Include and N+1 queries sometimes
- ALMOST NO third party library exists yet except mine (not a big issue here 👍 )
- And a lot of more...

You can see the EF Core Roadmap [here](https://github.com/aspnet/EntityFramework/wiki/Roadmap)

If you look at the [Issue Tracker](https://github.com/aspnet/EntityFramework/issues) for EF Core, you will discover a lot of issues that may happen in a common scenario.

EF6 is not perfect, but at least it's pretty stable.

**Comment by zzzprojects** [comment]
Closing: The issue has nothing to do with our library, the latest version of .NET Core is not installed (Feel free to re-open the issue if I'm wrong)

**Comment by terryaney** [comment]
Closer.  Could you give me a little guidance.  I installed VS .NET Core Tooling and now I get:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		C:\Users\terry.aney\Documents\Visual Studio 2015\Projects\EntityFramework-Plus\src\Z.EntityFramework.Plus.EFCore\error CS7027: Error signing output with public key from file 'C:\Users\Jonathan\OneDrive\Documents\Release\zzzproject.snk' -- Could not find a part of the path 'C:\Users\Jonathan\OneDrive\Documents\Release\zzzproject.snk'.	Z.EntityFramework.Plus.EFCore	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	262	
```

Should I just remove signing?  Or is there a snk file I should be using?

**Comment by zzzprojects** [comment]
Yes, you should remove the signing since the snk file will never be public.
