### ISSUE TITLE
So now bulk operations are paid.... 

### ISSUE THREAD

**Issue by MeTitus** [zzzprojects/EntityFramework-Plus#375]
Do you remenber ServiceStack, expect the same fate.

**Comment by JonathanMagnan** [comment]
Hello @MeTitus ,

I'm not sure to understand your title or your description.

Bulk Operations has always been paid.

If you are talking about `Batch Delete` and `Batch Update`, they are still free.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since we haven't heard back from you and anyway, these extensions are still free.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Jogai ,

I don't think, the EF Classic library was not even existing in June.
