### ISSUE TITLE
UpdateAsync not working in EF Core 2.1

### ISSUE THREAD

**Issue by jeffvannijlen** [zzzprojects/EntityFramework-Plus#377]
Has the problem in https://github.com/zzzprojects/EntityFramework-Plus/issues/334 been resolved?
I have just upgraded to EF Core 2.1, but experiencing the same problem.

`            await _unitOfWork.GetRepository<InMessage>().UpdateAsync(x => x.Id == inMessage.Id, message => new InMessage { MessageStateId = (byte)messageStateEnum });
`

throws 
> Object reference not set to an instance of an object.>

StackTrace:

> at Z.EntityFramework.Plus.InternalExtensions.CreateCommand(IQueryable source, RelationalQueryContext& queryContext)
   at Z.EntityFramework.Plus.BatchUpdate.CreateCommand(IQueryable query, IEntityType entity, List`1 values)
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---

Can you advice?

**Comment by JonathanMagnan** [comment]
Hello @jeffvannijlen ,

Yes, that has been fixed.

I have no doubt that this exception is caused by our library but we are not able to reproduce it with EF Core 2.1 and EF Core 2.1.1

Do you think you could provide us a project sample/unit test with this error?

That will help us to get started to fix the issue.

Here is a scenario we tried on our side:

```csharp
using System;
using System.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Z.Test.EntityFramework.Plus;
using System.Linq;
namespace Z.EntityFramework.Plus.Lab.EFCore20
{
    public class Request_BatchUpdate_WithDateTime
    {
        public static void Execute()
        {
            // CLEAN
            using (var context = new EntityContext())
            {
                context.EntitySimple_WithDateTimes.RemoveRange(context.EntitySimple_WithDateTimes);
                context.SaveChanges();
            }

            // SEED
            using (var context = new EntityContext())
            {
                context.EntitySimple_WithDateTimes.Add(new EntitySimple_WithDateTime {ColumnDateTime = DateTime.Now});
                context.SaveChanges();
            }

            // TEST
            using (var context = new EntityContext())
            {
                var date = DateTime.Now;
                var count = context.EntitySimple_WithDateTimes.UpdateAsync(x => new EntitySimple_WithDateTime {ColumnDateTime = date }).Result;

                var list = context.EntitySimple_WithDateTimes.Where(x => x.ColumnDateTime == date).ToList();
            }
        }

        public class EntityContext : DbContext
        {
            public DbSet<EntitySimple_WithDateTime> EntitySimple_WithDateTimes { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(new SqlConnection(My.Config.ConnectionStrings.TestDatabase));

                base.OnConfiguring(optionsBuilder);
            }
        }

        public class EntitySimple_WithDateTime
        {
            public int ID { get; set; }

            public DateTime ColumnDateTime { get; set; }
        }
    }
}
```

Best Regards,

Jonathan
