### ISSUE TITLE
FromCache: Share query cache between multiple web apps on the same web server?

### ISSUE THREAD

**Issue by RudeySH** [zzzprojects/EntityFramework-Plus#379]
As the title implies, I'm wondering if it is possible to share the cache (`FromCache`) between multiple apps.

I have a MVC app and a Web API. The MVC app reads from the same database as the Web API. The Web API also writes to that database. Is it possible to share the cache between these two apps? My plan is for the Web API to expire various tags using `ExpireTag`. The MVC app queries using these tags for caching.

**Comment by JonathanMagnan** [comment]
Hello @RudeySH ,

If I understand well, you want a distributed cache?

I believe this concept goes beyond what EF+ can offer. However, if you use an external library that supports distributed cache, it's possible to include it in EF+.

For example, you can set any cache that inherits from Object Cache: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryCache.Shared/QueryCacheManager.cs#L54

It may require you some tweak but the library can already handle this kind of scenario.

You can see some more comment about it here:
- https://github.com/zzzprojects/EntityFramework-Plus/issues/93#issuecomment-264718693
- https://github.com/zzzprojects/EntityFramework-Plus/issues/233#issuecomment-328679430

Best Regards,

Jonathan

---
Looking for EF6 on Steroid + .NET Core support?
Check out: [Etntiy Framework Classic](http://entityframework-classic.net/)

**Comment by RudeySH** [comment]
Thanks for getting me started on this. I'm not quite sure if a distributed cache is what I really need. I'm currently looking into moving all database reads and writes to a single application to keep it simple.
