### ISSUE TITLE
IncludeOptimizedByPath doesn't work for SqlServerCe.4.0 (Compact)

### ISSUE THREAD

**Issue by LeanderClappaert** [zzzprojects/EntityFramework-Plus#380]
**Setup**
EF Plus (version 1.8.4)
.NET Framework 4.0
SqlServerCe 4.0 (Sql Compact)

**Case**
The following exception is thrown if I want to execute my query with a SQL Compact connection, which has been built with IncludeOptimizedByPath:

**Part of the code being executed**
```CSharp
var fullQuery = query
                    .IncludeOptimizedByPath("Datastores")
                    .IncludeOptimizedByPath("Datastores.Disks")
```

**Exception thrown**
`There was an error parsing the query. [ Token line number = 91,Token line offset = 1,Token in error = SELECT ]`

SQL Server doesn't have this issue. It only happens while using SQL Compact.

**Comment by JonathanMagnan** [comment]
Hello @LeanderClappaert ,

Thank you for reporting. Could you try the same code by disabling the `AllowQueryBatch` option:

```csharp
QueryIncludeOptimizedManager.AllowQueryBatch = false;
```

We are currently re-visiting all features in our new library: http://entityframework-classic.net/

So once it's done here, we will also port the code in this library to include the fix to make it work by default.

Let me know if that work when disabling `AllowQueryBatch`.

Best Regards,

Jonathan

**Comment by LeanderClappaert** [comment]
Hi @JonathanMagnan ,

It works on SQL Compact 4.0 when disabling `AllowQueryBatch` !
To be sure, I've retested my code also on SQL server and this still works.
--> **The fix works**.

Thanks,
Kind regards,
Leander

**Comment by JonathanMagnan** [comment]
Great :)

I will not recommend to disable this option on SQL Server since you want your queries to run in one database round-trip.

When you disable it, it will make a database run-trip for every query it has to perform.

Best Regards,

Jonathan
