### ISSUE TITLE
Batch delete does not work with DelegateDecompiler

### ISSUE THREAD

**Issue by NetMastr5** [zzzprojects/EntityFramework-Plus#386]
I use DelegateDecompiler (https://github.com/hazzik/DelegateDecompiler) to allow computed properties on my entities and EntityFramework-Plus for batch deletions.  I recently tried to mix the two by deleting entities based on a computed property (in this case, the property calculates the status of a record based on several fields).  When attempting to do so, an error is generated.

context.IT_METADATA.Where(x => x.interviewType == Interview.InterviewType.UNKNOWN).Decompile().Delete();

[stack trace.txt](https://github.com/zzzprojects/EntityFramework-Plus/files/2225126/stack.trace.txt)
[Computed definition.txt](https://github.com/zzzprojects/EntityFramework-Plus/files/2225114/Computed.definition.txt)

Would be great if these two libraries could be used together.

**Comment by JonathanMagnan** [comment]
Hello @NetMastr5 ,

Thank you for reporting.

This kind of issue is usually easy to fix. We just need to add a new way to retrieve the query if none of the following worked: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus._Core.Shared/EF5_EF6/IQueryable%60/IQueryable%60.GetObjectQuery.cs

In that case, I believe they store it in the `inner` private field.

We will look at it very soon.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @NetMastr5 ,

The v1.8.6 has been released.

The `inner` field logic that was already been added in some other method has been added to the `GetObjectQuery` as well.

We talked about your solution but we choose for now to handle it on our side. People often want a library that already handles it, they don't want to configure to much code. We will keep in mind your solution.

Let me know if that's now working with DelegateDecompiler library.

Best Regards,

Jonathan

**Comment by NetMastr5** [comment]
Thanks for the quick response Jonathan!  Just for clarification, I was not suggesting that users have to configure it, I envisioned it coming with a default configuration that matches what is there today.  This would just give the flexibility to add configurations if the need would arise.

Thanks again!

**Comment by JonathanMagnan** [comment]
Oh I understand, that's for sure something we will look in our new library: http://entityframework-classic.net/

We will face the same kind of issue, so doing it with your suggestion will make everything more generic.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @NetMastr5 ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
