### ISSUE TITLE
BatchUpdate and BatchDelete errors if an .OrderBy(..) was included in query

### ISSUE THREAD

**Issue by terryaney** [zzzprojects/EntityFramework-Plus#39]
Sometimes, you might have a IQueryable that has an OrderBy specified in it.  As a simple example, given something like:

```
ctx.Jobs.Where( j => j.DateCreated > EntityFunctions.AddDays( DateTime.Today, -1 ) && j.Package != "null" )
		.OrderBy( j => j.DateCreated )
		.Delete();
```

When attempted to run, you get the exception:

> The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.

I've written a similar set of extensions as this library for Linq to Sql and to get around problem for me, I did some string searching/parsing.  Not sure if that is best solution, but something like the following would work in the BatchDelete.CreateCommand.

```
var querySelect = query.ToTraceString();

var queryParts = querySelect.Split( '\r' );
var selectClause = queryParts[ 0 ];
var needsTopClause = selectClause.IndexOf( " TOP " ) < 0 && querySelect.IndexOf( " ORDER BY " ) > 0;

if ( needsTopClause )
{
	querySelect =
		string.Join(
			"\r",
			new[] { selectClause.Replace( "SELECT ", "SELECT TOP 100 PERCENT " ) }.Concat( queryParts.Skip( 1 ) )
		);
}

```
I'm not sure if there is a more clever way to do it via Expression tree parsing or not.  Also, I'm not sure of the different variants the command text might be for different database providers.  Let me know if you want me to implement ( and something similar in BatchUpdate) and issue a pull request or if you think you'll have a 'better' way of fixing.

Thanks.

**Comment by zzzprojects** [comment]
Thank you, Terry, for the bug and solution.

We will for sure use a solution very similar to yours. Unfortunately, we cannot use IndexOf(" TOP ") since someone could want from the batchUpdate to update a value using this constant.

```csharp
ctx.Jobs.Where( j => j.DateCreated > EntityFunctions.AddDays( DateTime.Today, -1 ) && j.Package != "null" )
        .OrderBy( j => j.DateCreated )
        .Update(x => new { JobDescription = "WHY TOP IS HERE!!!");
```

I will try to look and fix this issue this week otherwise; a fix will be available at the beginning of next week.

**Comment by zzzprojects** [comment]
We will probably use a DbExpressionVisitor or convert the expression to a string instead of using IndexOf from the final query string.

**Comment by terryaney** [comment]
Note that I only searched for TOP in the 'first line' of the query...seems EF does the 'select clause' then a line feed.  So should only have SELECT or SELECT TOP ( N ) or SELECT TOP 100 PERCENT I'd think.  But if you have a visitor pattern you can use, probably safer.

**Comment by zzzprojects** [comment]
We are currently testing our implementation.

In short, we only create an Expression Visitor to check if a method using "OrderBy" is used.

If we found one, we use Take with int.MaxValue (unless you want delete billions of records, that will cover the scenario).

```csharp
if (visitor.HasOrderBy)
{
	query = query.Take(int.MaxValue);
}
```

While this fix is still not perfect, that will cover almost every scenario & database without having any impact.

**Comment by zzzprojects** [comment]
I will wait for answers about your other threads, otherwise I will release the fix Thursday or Friday.

**Comment by zzzprojects** [comment]
This issue has been fixed in v1.4.4

Let me know if this is now working for you.

**Comment by zzzprojects** [comment]
Closing: Issue Fixed

**Comment by terryaney** [comment]
Sorry for the late response.  This does appear to work.  Interesting tho

1) Shouldn't your if (visitor.HasOrderBy) check be if (visitor.HasOrderBy && !visitor.HasTake)?  Because if I have a Take, I think things would work as is.

2) I see the Take( int.MaxValue )...how come I don't see anything about that in the generated SQL?  

Here is the LINQ statement:
```
	ctx.Jobs.Where( j => j.DateCreated > DbFunctions.AddDays( DateTime.Today, -1 ) && j.Package != "null" )
			.OrderBy( j => j.DateCreated ).Where( j => j.Group != "null" )
			.Delete();
```

Here is the SQL generated:
```
DECLARE @rowAffected INT
DECLARE @totalRowAffected INT

SET @totalRowAffected = 0

WHILE @rowAffected IS NULL
    OR @rowAffected > 0
    BEGIN
        DELETE TOP (4000)
        FROM    A
        FROM    [dbo].[Job] AS A
                INNER JOIN ( SELECT TOP (2147483647) 
    [Project1].[Key] AS [Key]
    FROM ( SELECT 
        [Extent1].[Key] AS [Key], 
        [Extent1].[DateCreated] AS [DateCreated]
        FROM [dbo].[Job] AS [Extent1]
        WHERE ([Extent1].[DateCreated] > (DATEADD (day, -1, @p__linq__0))) AND (N'null' <> [Extent1].[Package]) AND (N'null' <> [Extent1].[Group])
    )  AS [Project1]
    ORDER BY [Project1].[DateCreated] ASC
                           ) AS B ON A.[Key] = B.[Key]

        SET @rowAffected = @@ROWCOUNT
        SET @totalRowAffected = @totalRowAffected + @rowAffected
    END

SELECT  @totalRowAffected

```

**Comment by zzzprojects** [comment]
1) Yes and no, the take could be used from a join query and to make the fix more simple, we choose to always add the Take.

By example, 

- if the query already does a Take(10), adding a Take(int.MaxValue) will change nothing to the result
- if the order by is from a subquery, adding a Take(int.MaxValue) will change nothing to the result

We did it by simplicity.

2) I didn't see it either but after looking 3 times at the query, I finally found it ;)

```SQL
INNER JOIN ( SELECT TOP (2147483647) 
```

Let me know if I answered correctly to your question
