### ISSUE TITLE
Using FromCache with EF InMemory provider for Integration tests

### ISSUE THREAD

**Issue by fdbva** [zzzprojects/EntityFramework-Plus#391]
I think it's similar as this issue [Using EF InMemory provider #86](https://github.com/zzzprojects/EntityFramework-Plus/issues/86)

I use a repository pattern and use FromCache on several places.
I want to do an Integration test using EF InMemory provider. 

I thought it would require a lot of code to reproduce it, but I managed it in a simple way, maybe oversimplifying it a lot, and while it will not pass the full scenario, it does raise the same exception.

[Github repository of the reproduction code](https://github.com/fdbva/ZzzFromCacheInMemoryDbError)

As I said in the other thread:

> Is there an way to disable FromCache that I could call inside my integration test method?

That would solve it for me as well.

**Comment by JonathanMagnan** [comment]
Hello @fdbva ,

The v1.8.8 has been released.

You can now disable the cache by using the following option:

```csharp
QueryCacheManager.IsEnabled = false
```

Let me know if everything is working as expected.

Best Regards,

Jonathan

**Comment by fdbva** [comment]
Hi, I'm sorry taking so long to answer (besides the thumbs up).
At the time I couldn't test because I had to move on to other tasks.

I created some new Integration tests using the `QueryCacheManager.IsEnabled = false;` and it worked really easy.
This is great if you want to use `optionsBuilder.UseInMemoryDatabase`.

There's also another alternative that I'll write here in case anyone finds this issue.
You can use `.UseSqlite(new SqliteConnection($"Mode=Memory"))`.
It seems to me it's a slower alternative but you don't need to disable cache and you can find errors that would only happen in a relational DB.

@JonathanMagnan 
Thanks a lot for creating this option and, again, sorry for taking so long to answer.
