### ISSUE TITLE
Audit entries not being inserted with EF Core 2.1

### ISSUE THREAD

**Issue by Deilan** [zzzprojects/EntityFramework-Plus#393]
Using an [example from the docs](http://entityframework-plus.net/audit) audit entries are not being inserted in SQLite database via EF Core 2.1 in a .NET Core 2.1 project and `Z.EntityFramework.Plus.Audit.EFCore` 1.8.5. No exceptions, the audit records are just not there.

```csharp
var student = new Student();
var audit = new Audit { CreatedBy = "ZZZ Projects" }; // Optional
_dbContext.Students.Add(student);

await _dbContext.SaveChangesAsync(audit);
```

```csharp
public class AppDbContext : DbContext
{
    public DbSet<AuditEntry> AuditEntries { get; set; }
    public DbSet<AuditEntryProperty> AuditEntryProperties { get; set; }
    public DbSet<Student> Students { get; set; }
}
```

**Comment by Deilan** [comment]
@JonathanMagnan Here you are: https://github.com/deilan-issues-samples/Z.EntityFramework.Plus.Issues/tree/master/Z.EntityFramework.Plus.Issues.N393

**Comment by JonathanMagnan** [comment]
Hello @Deilan ,

Thank for the example, you are missing the `AutoSavePreAction` in the static constructor

```csharp
    public sealed class AppDbContext : DbContext
    {
        static AppDbContext()
        {
            AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
                // ADD "Where(x => x.AuditEntryID == 0)" to allow multiple SaveChanges with same Audit
                (context as AppDbContext).AuditEntries.AddRange(audit.Entries);
        }

        public DbSet<AuditEntry> AuditEntries { get; set; }
        public DbSet<AuditEntryProperty> AuditEntryProperties { get; set; }
        public DbSet<Student> Students { get; set; }

        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {

        }
    }
```

Some online example since today is now available. So it will be soon easier to get started with this libraries: https://dotnetfiddle.net/BfkqWm

Let me know if that work.

Best Regards,

Jonathan

**Comment by Deilan** [comment]
@JonathanMagnan Thank you for the correction, this works. Having an online sample is also very helpful, thank you also for that! Looking forward to have a link to it from the docs. :)

**Comment by JonathanMagnan** [comment]
It's already in the docs since yesterday ;)

http://entityframework-plus.net/audit

Check all "Try it online" link.

A lot of more improvement will come to the docs over the weeks but that's already a very big step.

**Comment by JonathanMagnan** [comment]
I will close this issue since it seems to be solved.

Have a great day,

Best Regards,

Jonathan
