### ISSUE TITLE
Delete async on DB2 tables returning error "An DB2Parameter with ParameterName '@totalRowAffected' is not contained by this DB2ParameterCollection."

### ISSUE THREAD

**Issue by MIKEPArA** [zzzprojects/EntityFramework-Plus#394]
Hi i am trying to run the following command on my ef 6 edmx context:
cnt.[tbl].Where(c=>c.condition).DeleteAsync(x => { x.Executing = command => commandText = command.CommandText; })

i get the following Error:
An DB2Parameter with ParameterName '@totalRowAffected' is not contained by this DB2ParameterCollection.

Here is the commandText:
DECLARE @rowAffected INT
DECLARE @totalRowAffected INT

SET @totalRowAffected = 0

WHILE @rowAffected IS NULL
    OR @rowAffected > 0
    BEGIN
        DELETE TOP (4000)
        FROM    A 
        FROM    [table] AS A
                INNER JOIN ( SELECT 
FROM [table]
WHERE [condition] ) AS B ON [join condition]
AND [condition]

        SET @rowAffected = @@ROWCOUNT
        SET @totalRowAffected = @totalRowAffected + @rowAffected
    END

SELECT  @totalRowAffected

IBM specified the error as two parameters having the same name but i only see 2 parameters at the top declared and they are different names?

**Comment by JonathanMagnan** [comment]
Hello @MIKEPArA ,

Our library is not yet compatible with `DB2`.

We might add the support later but we currently have no short-term plan until our new library : http://entityframework-classic.net/ become more mature

Best Regards,

Jonathan

**Comment by MIKEPArA** [comment]
Hi, thanks Jonathan.

**Comment by JonathanMagnan** [comment]
I added a task to our "wish-list"

Since that's something we will do in short-term plan, I will close this issue.
