### ISSUE TITLE
Query Cache Bug

### ISSUE THREAD

**Issue by jx-qyj** [zzzprojects/EntityFramework-Plus#4]
Hello, I ask why (Query Cache Entity Framework) to add the data can not immediately update the cache?

**Comment by zzzprojects** [comment]
I’m not sure to understand the question.

Do you want an overloaded method which allows forcing to update the cache?

**Example**

```
// Cache data
var countries1 = ctx.Countries.FromCache().ToList();

// FORCE the cache to be updated
var countries2 = ctx.Countries.FromCache(true);
```

**Comment by zzzprojects** [comment]
Closing issue due to no answer and bug fixed in unit tests

(Probably duplicate of: https://github.com/zzzprojects/EntityFramework-Plus/issues/5)

**Comment by jx-qyj** [comment]
@zzzprojects  Thank you, I have resolved
