### ISSUE TITLE
execute AsNoFilter then  How to enable specified filter

### ISSUE THREAD

**Issue by wulaiwei** [zzzprojects/EntityFramework-Plus#402]
hello,
 I want to start the specified filter after AsNoFilter execution.
like this

```csharp
var query = DbSet.AsNoFilter();
foreach (var filterString in filterStrings)
 {
        //TODO   Enable  the  filter  
       query.Enable(filterString);
}
```

I want to know if it is supported.  thank you 

Environment:
.NET Core 2.1
Microsoft.EntityFrameworkCore 2.1.2
Z.EntityFramework.Plus.EFCore 1.8.8

**Comment by JonathanMagnan** [comment]
Yes, I would think so.

Have you got an error?

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
You can also enable it this way:

```csharp
query.Enable(filterStrings.ToArray());
```

**Comment by wulaiwei** [comment]
Sorry, maybe I didn't describe my problem clearly.
query.Enable() is not supported.
IQueryable<T> There is no Enable extension method.
I would like to know if there is such an expansion method or way to deal with this demand.

Thanks very much.

**Comment by wulaiwei** [comment]
Thank you very much for your reply.
I processed it in the following way. I think he is feasible and passed my test.
`  
        /// <summary>
        ///     AsWorkDataNoFilter
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="query"></param>
        /// <param name="context"></param>
        /// <param name="filterStrings"></param>
        /// <returns></returns>
        public static IQueryable<T> AsWorkDataNoFilter<T>(this DbSet<T> query, DbContext context,
            params object[] filterStrings) where T : class
        {
            var asNoFilterQueryable = query.AsNoFilter();

            object query1 = asNoFilterQueryable;
            var items = CacheGenericDynamicFilter.Where(x => filterStrings.Contains(x.Key));

            query1 = items.Select(key => context.Filter(key.Key))
                .Where(item => item != null)
                .Aggregate(query1, (current, item) => (IQueryable) item.ApplyFilter<T>(current));
            return (IQueryable<T>) query1;
        }
`

**Comment by wulaiwei** [comment]
Thank you very much for your reply.
I processed it in the following way. I think he is feasible and passed my test.
`
public static IQueryable AsWorkDataNoFilter(this DbSet query, DbContext context,params object[] filterStrings) where T : class
{
        var asNoFilterQueryable = query.AsNoFilter();
        object query1 = asNoFilterQueryable;
        var items = CacheGenericDynamicFilter.Where(x => filterStrings.Contains(x.Key));
        query1 = items.Select(key => context.Filter(key.Key))
            .Where(item => item != null)
            .Aggregate(query1, (current, item) => (IQueryable) item.ApplyFilter<T>(current));
        return (IQueryable<T>) query1;
    }
`

**Comment by wulaiwei** [comment]
Thank you very much for your reply.
I processed it in the following way. I think he is feasible and passed my test.
` public static IQueryable<T> AsWorkDataNoFilter<T>(this DbSet<T> query, DbContext context,
            params object[] filterStrings) where T : class
        {
            var asNoFilterQueryable = query.AsNoFilter();

            object query1 = asNoFilterQueryable;
            var items = CacheGenericDynamicFilter.Where(x => filterStrings.Contains(x.Key));

            query1 = items.Select(key => context.Filter(key.Key)).Where(item => item != null)
                .Aggregate(query1, (current, item) => (IQueryable) item.ApplyFilter<T>(current));
            return (IQueryable<T>) query1;
        }`

**Comment by JonathanMagnan** [comment]
Hello @wulaiwei ,

My bad, the method should be `Filter` and not `Enable`.

```csharp
var query = DbSet.AsNoFilter();
query = query.Filter(filterStrings.ToArray())
```

Let me know if this one work ;)

Best Regards,

Jonathan

**Comment by wulaiwei** [comment]
Hello  @JonathanMagnan 
  
![qq 20180831091529](https://user-images.githubusercontent.com/16910820/44887334-69b5e880-acfe-11e8-8995-afa6761e578f.png)
He still can't work.

But ,I have achieved my needs by extending ApplyFilter.

Thank you very much for your reply.

**Comment by JonathanMagnan** [comment]
That's weird but let close it if you solved it ;)
