### ISSUE TITLE
Logging generated sql queries

### ISSUE THREAD

**Issue by szilardd** [zzzprojects/EntityFramework-Plus#419]
Hi,

Does the library support logging generated sql queries using default EF Core logging functionality, as described here:

https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging

Or do we need to implement custom logging using Executing Interceptor like this ?

```csharp
context.Customers.Update
(
    x => new Customer { IsActive = false, Description = "Updated"},
    x => { x.Executing = command => Console.WriteLine(command.CommandText); }
);
```

Thanks

**Comment by JonathanMagnan** [comment]
Hello @szilardd ,

We support logging for `EF6` but I do not believe anything has been done yet for `EF Core`.

So yes, you will need to implement your own logging meanwhile.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Yes,

Using the `BatchUpdateBuilder` options from the `BatchUpdateManager`

Source: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.BatchUpdate.Shared/BatchUpdateManager.cs#L21

```csharp
BatchUpdateManager.BatchUpdateBuilder = builder => {
   // ...code...
};
```

**Comment by szilardd** [comment]
thanks

**Comment by czmamed** [comment]
Hello I would like to log all generated SQL and also time it takes to process it in my DB. For both EF Core queries and also for z.ef.plus queries. For standard EF core I can use existing interceptors, but they do not log z.ef.plus generated sql. I can use suggested BatchUpdateBuilder to get generated sql for batchUpdate, but I cannot get how long does it take to process. Can you please suggest a way how to catch and log all SQL generated by z.ef.plus and time it takes to process it in my DB?

**Comment by JonathanMagnan** [comment]
Hello @czmamed ,

There is currently no easy way to log all queries.

For the EF Plus Batch Update, you can use the following code: https://dotnetfiddle.net/BxSMrM

```csharp
Z.EntityFramework.Extensions.BatchUpdateManager.BatchUpdateBuilder = builder => {
	var originalCommandExecuteAction = builder.CommandExecuteAction;
	builder.CommandExecuteAction = (command, batchSize) => {
		Console.WriteLine(command.CommandText);
		
		var clock = new Stopwatch();
		clock.Start();
		var rowAffecteds = originalCommandExecuteAction(command, batchSize);
		clock.Stop();
		
		Console.WriteLine($"Time Taken: {clock.ElapsedMilliseconds}ms");
		
		return rowAffecteds;
	};
};
```

Same for BatchDelete but by using the `BatchDeleteManager`.

Best Regards,

Jon

**Comment by czmamed** [comment]
Thank you for reply, something similar I have but I think that the time is not correct. I have a wrapper on UpdateAsync where I measure time of the original UpdateAsync from BatchUpdateExtensions and the time is significantly different. And when calling a endpoint repeatedly, the time measured in your example is 0ms. In an example calling a first call the UpdateAsync time is 51ms, but the time from the example is only 4ms. On second call it is 40 ms vs 0ms. Is really the time from this example the time of execution the request to db?

**Comment by JonathanMagnan** [comment]
Hello @czmamed ,

The `var rowAffecteds = originalCommandExecuteAction(command, batchSize);` in my code only contains the time it takes to execute in the database. This part contains only a "if" block with directly the `command.ExecuteScalar()` method.

Everything else such as creating the query through the LINQ you provided is not included which could explain why the first time is longer. EF Core creates and caches a plan that takes time, which he can reuse later if the same query is executed. So the additional time is not related to the time it takes to execute the query in the database but more related about the time EF Core needs to create the plan (or whatever this is called).

Let me know if that explain correctly.

Best Regards,

Jon
