### ISSUE TITLE
Audit | Where vs GetAudits

### ISSUE THREAD

**Issue by zzzprojects** [zzzprojects/EntityFramework-Plus#42]
Currently, it's possible (Code First), to retrieve audit using Where extension methods (from EF+ library)

``` csharp
using (var ctx = new TestContext())
{
    ctx.AuditEntries.Where(item);
    ctx.AuditEntries.Where<Entity_Basic>(item.ID);
    ctx.AuditEntries.Where<Entity_Basic>(101);
}
```

However, using the same method name as LINQ add some confusion like discussed in issue #23 

Another solution could be to use a method named GetAudits (or support both!)

**Comment by maharatha** [comment]
I am unable to implement this. Can you provide a sample implementation.

**Comment by zzzprojects** [comment]
Hello @maharatha ,

You want an example how to implement it for Database First right?

**Comment by maharatha** [comment]
Yes please

**Comment by maharatha** [comment]
I am using repository pattern to get the data. Below are few issues 👍 
1) It's doesn't provide the data for deleted item. I changed an entity thrice and softdeleted it. But it doesn't show up the deleted history. I have enabled only track changed property

2) Can you suggest how I can send the Entity_Basic as a parameter

**Comment by maharatha** [comment]
I need example for Code first.

**Comment by zzzprojects** [comment]
Hello @maharatha ,

Can you contact me directly? info@zzzprojects.com

If you can, provide me an example of the code so I could try to reproduce this.

This will make easier to understand your problem since it doesn't look related to this issue.

Best Regards,

Jonathan

**Comment by maharatha** [comment]
Hi Jonathan -

I was able to make it work. But I am struggling with one thing here  :

1) On my EF 6 code first , I have created a base entity and a derived
entity. So when I start logging the base entity it's logging the derived
entity which is amazing. But when I pass the base entity id to get the
audit log it's returning zero always, ie.,it's not returning the changes.

Let me know if you could help.

Note : We also bought a license from you for the Bulk Insert and it's
working amazing.

Keep up the good work.

Thanks,
Partha

**Comment by zzzprojects** [comment]
Hello Maharatha,

We successfully reproduce this issue. We will for sure try to fix it very soon.

As you probably noticed, there is a lot of open issues currently so we cannot promise any date for now but I will try to check it this weekend if time permit.

Thank you for bought a license ;) This certainly contributes to help us to provide the best support as we can.

Best Regards,

Jonathan

**Comment by maharatha** [comment]
Hi Jonathan -

Thank you for a quick reply. I appreciate the work you are doing. Just so
as you know we are heavily relying on you to fix the issue as it would help
us on building the audit log screen sooner. Until you fix it we have to
wait.

Thanks
Partha

**Comment by zzzprojects** [comment]
Hello @maharatha,

We successfully fixed it. We are currently making some other fixes before release it, but it should be available on Monday.

**Comment by maharatha** [comment]
Thank You so much

**Comment by zzzprojects** [comment]
The v1.4.4 has been released

If you got another issue, please create a new thread since it's not related to the main issue.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Closing: Fixed in v1.4.4

If some work is still remaining, please re-open it.

**Comment by khoait** [comment]
Hi,

I use a custome class that inherits the AuditEntry, how can I retrieve audit entries easily?
Here are my dbsets:
```
public DbSet<MyAuditEntry> AuditEntries { get; set; }
public DbSet<MyAuditEntryProperty> AuditEntryProperties { get; set; }
```
When I use `ctx.AuditEntries.Where<Clients>(1)` , it can't find the `Where` extensions

Thanks

**Comment by AsankaMawilmada** [comment]
@khoait I am having the same issue, with custom class, did you find a solution ? Thanks
