### ISSUE TITLE
BatchUpdate has prombles when deal tph Model

### ISSUE THREAD

**Issue by fengshi19888** [zzzprojects/EntityFramework-Plus#424]
When I Use `Context.Set<TEntity>().Where(predicate).Update(updateFactory);` to Excute BatchUpdate Method,I Found that It return a null object expection. At last I found that My Class is a TphClass and in this  DbModelPlus.cs code ,it do not containe the baseType key and Propites. so i add the code follow.

```csharp
 public SchemaEntityType<T> Entity<T>() where T : class
        {
            var type = typeof(T).Name;

            if (!ConceptualModel.Index_EntityTypes_Name.ContainsKey(type))
            {
                throw new InvalidOperationException(ExceptionMessage.GeneralException);
            }

            var conceptual = ConceptualModel.Index_EntityTypes_Name[type];
            var entityContainer = new SchemaEntityType<T> { Info = conceptual };
           // to solve the exception
            //if (entityContainer.Info.Key == null && entityContainer.Info.IsTPH && entityContainer.Info.BaseType != null)
            //{
            //    entityContainer.Info.Key = entityContainer.Info.BaseType.Key;
            //    entityContainer.Info.Properties.AddRange(entityContainer.Info.BaseType.Properties);
            //} 
            return entityContainer;
        }
```
is there any other method to solve the question?

**Comment by JonathanMagnan** [comment]
Hello @fengshi19888 ,

Thank you for reporting, we will look soon at it.

We are supported to complete relook on the `Batch Update` and `Batch Delete` feature next month to support inheritance and complex type.

Best Regards,

Jonathan
