### ISSUE TITLE
QueryFutureValue.ValueAsync: Missing CancellationToken parameter

### ISSUE THREAD

**Issue by antoinebj** [zzzprojects/EntityFramework-Plus#428]
Hi,

Would it be possible to add support for a cancellation token on the `QueryFutureValue.ValueAsync()` method?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @antoinebj ,

Sure, we will try to add it this week.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @antoinebj,

The v1.8.12 has been released.

`CancellationToken` has been added in some method that was still missing it.

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by antoinebj** [comment]
Hi @JonathanMagnan,

From the looks of it, the support for a cancellation token is there. I ran couple of tests which completed as expected. However I cannot cover all the possible cancellation exit points within the library's code.

I'll raise another ticket if anything arises later. For now, consider me satisfied with the resolution of this issue. If nobody else wants or has to chime in, feel free to close this issue.

Best regards
Antoine

**Comment by JonathanMagnan** [comment]
So let close it as you suggest ;)

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Just to let you know @antoinebj ,

We did the same change on EF Classic: https://entityframework-classic.net/ and improved the code since we had access to the source code (so it was easier to make everything async).

Best Regards,

Jonathan
