### ISSUE TITLE
Possible translation bug using negatives

### ISSUE THREAD

**Issue by dotnetshadow** [zzzprojects/EntityFramework-Plus#433]
I recently reached out to the EF Core team about a possible translation bug with one of the queries involving a negative sign. I'm using **DeferredSum** from **Future Query** which have the problem.

Please see the following issue for details
https://github.com/aspnet/EntityFrameworkCore/issues/13919

**Comment by JonathanMagnan** [comment]
Hello @dotnetshadow ,

We will close the issue as I do not believe it's related to our library and it has been confirmed that it can be reproduced without our library: https://github.com/aspnet/EntityFrameworkCore/issues/13919#issuecomment-438505459

Best Regards,

Jonathan
