### ISSUE TITLE
Batch update generates faulty query

### ISSUE THREAD

**Issue by Crossbow78** [zzzprojects/EntityFramework-Plus#434]
I have a similar issue to https://github.com/zzzprojects/EntityFramework-Plus/issues/426 but there's no inheritance involved.

This is my model, generated from an edmx:

```
public class GroupMembership
{
	public int Id { get; set; }
	public int GroupId { get; set; }
	public int UserId { get; set; }
	public bool Changed { get; set; }
	public System.DateTime EntryStamp { get; set; }
	public Nullable<System.DateTime> ArchivedDate { get; set; }
}
```
Id is the primary key, and GroupId and UserId are foreign keys.

---
Using **Entity Framework Extensions** 3.6.11:
```
_db.GroupMemberships
	.Where(x => !x.ArchivedDate.HasValue && groupIds.Contains(x.GroupId))
	.UpdateFromQuery(x => new EF.Entities.GroupMembership { Changed = true });
```
this is the generated query (slightly reformatted) that I see in SQL Server Profiler:
```
MERGE INTO [dbo].[GroupMemberships] AS DestinationTable
USING
(
	SELECT 
		CAST([Extent1].[Id] AS int) AS [C1]
	FROM [dbo].[GroupMemberships] AS [Extent1]
	WHERE ([Extent1].[ArchivedDate] IS NULL)
		AND (CAST([Extent1].[GroupId] AS int) IN (1, 2))
		AND (CAST([Extent1].[GroupId] AS int) IS NOT NULL)
) AS StagingTable
ON 
WHEN MATCHED THEN
	UPDATE 
	SET [Changed] = 1;
```
which results in the following SqlException:
`System.Data.SqlClient.SqlException: Incorrect syntax near the keyword 'WHEN'.`

And indeed, there is no key selection to join the StagingTable with the DestinationTable.
It would work with this: `ON [DestinationTable].[Id] = [StagingTable].[C1]`

---
Using **Entity Framework Plus** 1.8.13:
```
_db.GroupMemberships
	.Where(x => !x.ArchivedDate.HasValue && groupIds.Contains(x.GroupId))
	.Update(x => new EF.Entities.GroupMembership { Changed = true });
```
this is the generated query (slightly reformatted) that I see on SQL Server Profiler:
```
UPDATE A 
SET A.[Changed] = 1
FROM [dbo].[GroupMemberships] AS A
INNER JOIN (
	SELECT 
		CAST([Extent1].[Id] AS int) AS [C1], 
		CAST([Extent1].[GroupId] AS int) AS [C2], 
		CAST([Extent1].[UserId] AS int) AS [C3], 
		[Extent1].[Changed] AS [Changed], 
		[Extent1].[EntryStamp] AS [EntryStamp], 
		[Extent1].[ArchivedDate] AS [ArchivedDate]
	FROM [dbo].[GroupMemberships] AS [Extent1]
	WHERE ([Extent1].[ArchivedDate] IS NULL)
		AND (CAST([Extent1].[GroupId] AS int) IN (1, 2))
		AND (CAST([Extent1].[GroupId] AS int) IS NOT NULL)
) AS B ON A.[Id] = B.[Id]
```
which results in the following error:
`System.Data.SqlClient.SqlException: Invalid column name 'Id'`

And indeed, there is a faulty key selection to join A with B.
It would work with this: `AS B ON A.[Id] = B.[C1]`

_Originally posted by @Crossbow78 in https://github.com/zzzprojects/EntityFramework-Plus/issues/426#issuecomment-438992282_

**Comment by Crossbow78** [comment]
Jonathan, thanks for taking the time to look into this.

I first tried to reproduce this with a minimal console application and minimal model, but found that that worked just fine. And even when importing the full database to edmx that showed the problem originally, it worked fine.

After some closer comparison between the two imported models I found that the datatype of the keys were not in sync with the database (Int64 vs Int32). I can't explain how this got out of sync with the database, and apparently it was not a problem for EF6 itself.

When I applied the same datatype change in my minimal model, the batch update error was reproducible, and probably also explainable.

I'll go and fix the datatypes in my model.
Thanks again.

**Comment by Crossbow78** [comment]
So just to clarify:
* The database uses `long` as datatype for primary/foreign keys
* When importing the model as edmx, it will automatically use `Int64` for these key columns
* Then change the datatype for these columns in the table mapping to `Int32` and save the model to regenerate the entities.

**Comment by JonathanMagnan** [comment]
Hello @Crossbow78 ,

Just to let you know, we will abandon that issue since you can fix it on your side by making your `EDMX` valid.

However, we are starting soon a full code rewrite of that features, so we will for sure add that case in our unit test.

Let me know if we can close this issue.

Best Regards,

Jonathan
