### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by lidaliu** [zzzprojects/EntityFramework-Plus#436]
Hi,sir . When i call   Delete Method in Z.EntityFramework.Plus.EF Core,  get the error : Object reference not set to an instance of an object. It works fine when i use sqlserver  ,after swith it from sqlserver to mysql (Pomelo.EntityFrameworkCore.MySql) .

 at Z.EntityFramework.Plus.BatchDelete.CreateCommand(IQueryable query, IEntityType entity)
at Z.EntityFramework.Plus.BatchDelete.Execute[T](IQueryable`1 query)

**Comment by lidaliu** [comment]
i have sent an email to this address: info@zzzprojects.com,  please confirm it soon , thank you !

**Comment by JonathanMagnan** [comment]
Thank you,

We got it but unfortunately, your project is not straightforward to reproduce the issue.

We successfully modified the config and found the url to start the application, but what's the next step to cause the issue?

**Comment by lidaliu** [comment]
step 1. create  databse in mysql ,and cteate table :User.   then insert piece of data

step2 . start the application  Url:  https://localhost:44366/User/delete?id=1

**Comment by lidaliu** [comment]
Finally, the problem fixed when i update my Z.EntityFramework.Plus.EF Core version from 1.7.20  to 1.8.14.
So,this issue can closed . Thank you !
