### ISSUE TITLE
Does Update()/UpdateAsync() refresh the cache of current DbContext?

### ISSUE THREAD

**Issue by a-a-k** [zzzprojects/EntityFramework-Plus#437]
Lets say I inserted some data by `DbContext`, after that I updated that data by `Update()` (it uses `ExecuteSqlCommand`, as my understanding), right after that I retrieved the data and it is came the same as inserted. Adding `AsNoTracking()` helps me to retrieve actual, fresh data.

So, does it work as expected? And do need I to use `AsNoTracking()` alsways for a such cases?

**Comment by JonathanMagnan** [comment]
Hello @a-a-k ,

`Update` doesn't refresh the change tracker. It works as expected.

If the data is already loaded and you try to load it again in the Change Tracker, it will take the entity that has already been loaded, no matter change that's has been done on database or application side. When you specify `AsNoTracking`, it doesn't use the `ChangeTracker`, so you get fresh data.

Let me know if that explains correctly the current situation.

Best Regards,

Jonathan
