### ISSUE TITLE
BatchUpdate number increment failing in Oracle

### ISSUE THREAD

**Issue by FranklinBai** [zzzprojects/EntityFramework-Plus#440]
Info
Database : Oracle 11gR2
EntityFramework: 6.2.0
Z.EntityFramework.Plus.EF6: 1.8.16
Official Oracle ODP.NET, Managed Entity Framework Driver : 18.3.0
Database First

I need to increment number in EF6 using Batch update in Oracle database. Something like this:

update PERSONS set AGE = AGE + 1;

I tried:

dbContext.PERSONS.Where(p => p.AGE < 20).Update(p => new PERSONS { AGE = p.AGE + 1 });

But it is failing in Oracle database I'm using. Simple number update works though.

dbContext.PERSONS.Where(p => p.AGE < 20).Update(p => new PERSONS { AGE = 21 });

Can you please have a look on it? Maybe I'm doing something wrong.

Thank you!

**Comment by JonathanMagnan** [comment]
Hello @FranklinBai ,

Unfortunately, our library doesn't support this kind of syntax for Oracle yet.

However, we will look at it since it could be done via this technique: https://stackoverflow.com/a/7031405/5619143

I will assign this task to my developer to look at it and get back to you at the beginning of next week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @FranklinBai ,

The v1.8.19 has been released.

My developer looked at it today and successfully implemented a solution.

Could you try it and let me know if that's fixed on your side?

Best Regards,

Jonathan

**Comment by FranklinBai** [comment]
Hello @Jonathan,

I have tried this feature on my side base on the version v1.8.19 and it works fine.

Thank you

Best Regards,

FranklinBai

**Comment by JonathanMagnan** [comment]
Hello @brunom ,

If you have the same problem, please open a new issue.

Best Regards,

Jonathan
