### ISSUE TITLE
IncludeOptimized duplicates queries?

### ISSUE THREAD

**Issue by PhilPJL** [zzzprojects/EntityFramework-Plus#442]
This is just a question at the moment. I'll try to create a repro project if you think necessary.

This is my query

RawMaterials.IncludeOptimized(rm => rm.ExtendedFreezerMoves)
	.Where(rm => rm.BatchNumber == "92M0049048")
	.Where(rm => rm.SerialNumber == "92M0049048011")
	.Where(rm => rm.Item.Name == "106739/CFM")
	.SingleOrDefault(rm => rm.Clone == 6);

Which I'm testing in LinqPad.  LinqPad shows me the generated SQL below.  The trouble is if I run that in SSMS I get the same result sets twice.  Is there an issue?

I'm using VS 2017 latest + EF 6.3 + EF-Plus 1.8.19.

SELECT TOP (2) 
    [Extent1].[Id] AS [Id], 
    [Extent1].[ClonedFromId] AS [ClonedFromId], 
    [Extent1].[IsActive] AS [IsActive], 
    [Extent1].[Company] AS [Company], 
    [Extent1].[Receipt] AS [Receipt], 
    [Extent1].[ItemId] AS [ItemId], 
    [Extent1].[SerialNumber] AS [SerialNumber], 
    [Extent1].[BatchNumber] AS [BatchNumber], 
    [Extent1].[Clone] AS [Clone], 
    [Extent1].[HoursInitialExposure] AS [HoursInitialExposure], 
    [Extent1].[HoursAllowableExposure] AS [HoursAllowableExposure], 
    [Extent1].[HoursExposureAdjustment] AS [HoursExposureAdjustment], 
    [Extent1].[ExpirationOriginal] AS [ExpirationOriginal], 
    [Extent1].[ExpirationAdjusted] AS [ExpirationAdjusted], 
    [Extent1].[CreatedBy] AS [CreatedBy], 
    [Extent1].[CreatedOn] AS [CreatedOn]
    FROM  [dbo].[RawMaterial] AS [Extent1]
    INNER JOIN [dbo].[Item] AS [Extent2] ON [Extent1].[ItemId] = [Extent2].[Id]
    WHERE (N'92M0049048' = [Extent1].[BatchNumber]) AND (N'92M0049048011' = [Extent1].[SerialNumber]) AND (N'106739/CFM' = [Extent2].[Name]) AND (6 = [Extent1].[Clone])
GO

SELECT 
    [Project1].[Id] AS [Id], 
    [Project1].[Id1] AS [Id1], 
    [Project1].[C1] AS [C1], 
    [Project1].[Id2] AS [Id2], 
    [Project1].[RawMaterialId] AS [RawMaterialId], 
    [Project1].[Date] AS [Date], 
    [Project1].[UserId] AS [UserId], 
    [Project1].[Type] AS [Type], 
    [Project1].[IsOut] AS [IsOut]
    FROM ( SELECT 
        [Extent1].[Id] AS [Id], 
        [Extent2].[Id] AS [Id1], 
        [Extent3].[Id] AS [Id2], 
        [Extent3].[RawMaterialId] AS [RawMaterialId], 
        [Extent3].[Date] AS [Date], 
        [Extent3].[UserId] AS [UserId], 
        [Extent3].[Type] AS [Type], 
        [Extent3].[IsOut] AS [IsOut], 
        CASE WHEN ([Extent3].[Id] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1]
        FROM   [dbo].[RawMaterial] AS [Extent1]
        INNER JOIN [dbo].[Item] AS [Extent2] ON [Extent1].[ItemId] = [Extent2].[Id]
        LEFT OUTER JOIN [dbo].[ExtendedRawMaterialFreezerMove] AS [Extent3] ON [Extent1].[Id] = [Extent3].[RawMaterialId]
        WHERE (N'92M0049048' = [Extent1].[BatchNumber]) AND (N'92M0049048011' = [Extent1].[SerialNumber]) AND (N'106739/CFM' = [Extent2].[Name]) AND (6 = [Extent1].[Clone])
    )  AS [Project1]
    ORDER BY [Project1].[Id] ASC, [Project1].[Id1] ASC, [Project1].[C1] ASC
GO

-- EF+ Query Future: 1 of 2
SELECT TOP (2) 
    [Extent1].[Id] AS [Id], 
    [Extent1].[ClonedFromId] AS [ClonedFromId], 
    [Extent1].[IsActive] AS [IsActive], 
    [Extent1].[Company] AS [Company], 
    [Extent1].[Receipt] AS [Receipt], 
    [Extent1].[ItemId] AS [ItemId], 
    [Extent1].[SerialNumber] AS [SerialNumber], 
    [Extent1].[BatchNumber] AS [BatchNumber], 
    [Extent1].[Clone] AS [Clone], 
    [Extent1].[HoursInitialExposure] AS [HoursInitialExposure], 
    [Extent1].[HoursAllowableExposure] AS [HoursAllowableExposure], 
    [Extent1].[HoursExposureAdjustment] AS [HoursExposureAdjustment], 
    [Extent1].[ExpirationOriginal] AS [ExpirationOriginal], 
    [Extent1].[ExpirationAdjusted] AS [ExpirationAdjusted], 
    [Extent1].[CreatedBy] AS [CreatedBy], 
    [Extent1].[CreatedOn] AS [CreatedOn]
    FROM  [dbo].[RawMaterial] AS [Extent1]
    INNER JOIN [dbo].[Item] AS [Extent2] ON [Extent1].[ItemId] = [Extent2].[Id]
    WHERE (N'92M0049048' = [Extent1].[BatchNumber]) AND (N'92M0049048011' = [Extent1].[SerialNumber]) AND (N'106739/CFM' = [Extent2].[Name]) AND (6 = [Extent1].[Clone])
;

-- EF+ Query Future: 2 of 2
SELECT 
    [Project1].[Id] AS [Id], 
    [Project1].[Id1] AS [Id1], 
    [Project1].[C1] AS [C1], 
    [Project1].[Id2] AS [Id2], 
    [Project1].[RawMaterialId] AS [RawMaterialId], 
    [Project1].[Date] AS [Date], 
    [Project1].[UserId] AS [UserId], 
    [Project1].[Type] AS [Type], 
    [Project1].[IsOut] AS [IsOut]
    FROM ( SELECT 
        [Extent1].[Id] AS [Id], 
        [Extent2].[Id] AS [Id1], 
        [Extent3].[Id] AS [Id2], 
        [Extent3].[RawMaterialId] AS [RawMaterialId], 
        [Extent3].[Date] AS [Date], 
        [Extent3].[UserId] AS [UserId], 
        [Extent3].[Type] AS [Type], 
        [Extent3].[IsOut] AS [IsOut], 
        CASE WHEN ([Extent3].[Id] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1]
        FROM   [dbo].[RawMaterial] AS [Extent1]
        INNER JOIN [dbo].[Item] AS [Extent2] ON [Extent1].[ItemId] = [Extent2].[Id]
        LEFT OUTER JOIN [dbo].[ExtendedRawMaterialFreezerMove] AS [Extent3] ON [Extent1].[Id] = [Extent3].[RawMaterialId]
        WHERE (N'92M0049048' = [Extent1].[BatchNumber]) AND (N'92M0049048011' = [Extent1].[SerialNumber]) AND (N'106739/CFM' = [Extent2].[Name]) AND (6 = [Extent1].[Clone])
    )  AS [Project1]
    ORDER BY [Project1].[Id] ASC, [Project1].[Id1] ASC, [Project1].[C1] ASC
;

**Comment by JonathanMagnan** [comment]
Hello @PhilPJL ,

Yes, I believe a small project will be necessary.

We made some test on this features and we didn't notice this behavior.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by PhilPJL** [comment]
[Repro.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/2660673/Repro.zip)

Simple project duplicates the issue.  I haven't checked if it's limited to LinqPAD (5.36.03) or not.

This query -

RawMaterials.IncludeOptimized(rm => rm.FreezerMoves)
	.Where(rm => rm.Serial == "92M0049048011")
	//.SingleOrDefault(rm => rm.Clone == 6)

Results in

SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Serial] AS [Serial], 
    [Extent1].[Clone] AS [Clone]
    FROM [dbo].[RawMaterials] AS [Extent1]
    WHERE N'92M0049048011' = [Extent1].[Serial]
    ORDER BY [Extent1].[Id] ASC
GO

SELECT 
    [Project1].[Id] AS [Id], 
    [Project1].[C1] AS [C1], 
    [Project1].[Id1] AS [Id1], 
    [Project1].[Date] AS [Date], 
    [Project1].[RawMaterialId] AS [RawMaterialId]
    FROM ( SELECT 
        [Extent1].[Id] AS [Id], 
        [Extent2].[Id] AS [Id1], 
        [Extent2].[Date] AS [Date], 
        [Extent2].[RawMaterialId] AS [RawMaterialId], 
        CASE WHEN ([Extent2].[Id] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1]
        FROM  [dbo].[RawMaterials] AS [Extent1]
        LEFT OUTER JOIN [dbo].[FreezerMoves] AS [Extent2] ON [Extent1].[Id] = [Extent2].[RawMaterialId]
        WHERE N'92M0049048011' = [Extent1].[Serial]
    )  AS [Project1]
    ORDER BY [Project1].[Id] ASC, [Project1].[C1] ASC
GO

-- EF+ Query Future: 1 of 2
SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Serial] AS [Serial], 
    [Extent1].[Clone] AS [Clone]
    FROM [dbo].[RawMaterials] AS [Extent1]
    WHERE N'92M0049048011' = [Extent1].[Serial]
    ORDER BY [Extent1].[Id] ASC
;

-- EF+ Query Future: 2 of 2
SELECT 
    [Project1].[Id] AS [Id], 
    [Project1].[C1] AS [C1], 
    [Project1].[Id1] AS [Id1], 
    [Project1].[Date] AS [Date], 
    [Project1].[RawMaterialId] AS [RawMaterialId]
    FROM ( SELECT 
        [Extent1].[Id] AS [Id], 
        [Extent2].[Id] AS [Id1], 
        [Extent2].[Date] AS [Date], 
        [Extent2].[RawMaterialId] AS [RawMaterialId], 
        CASE WHEN ([Extent2].[Id] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1]
        FROM  [dbo].[RawMaterials] AS [Extent1]
        LEFT OUTER JOIN [dbo].[FreezerMoves] AS [Extent2] ON [Extent1].[Id] = [Extent2].[RawMaterialId]
        WHERE N'92M0049048011' = [Extent1].[Serial]
    )  AS [Project1]
    ORDER BY [Project1].[Id] ASC, [Project1].[C1] ASC
;

**Comment by JonathanMagnan** [comment]
Hello @PhilPJL ,

My developer looked at it today.

The SQL you took seems to be from the `Entity Framework` log and not from the profiler.

That's true the SQL is logged twice. The first time because we need to generate it (So we call the `Interceptor` and the second time when it's really executed in the database.

If you use SQL Profiler, you will see that only the SQL generated with the Query Future is executed.

Let me know if that explains correctly the current behavior.

Best Regards,

Jonathan
