### ISSUE TITLE
Is there any plan to support Oracle.EntityFrameworkCore?

### ISSUE THREAD

**Issue by NepPure** [zzzprojects/EntityFramework-Plus#446]
It seems does not support it now.

_The EF Core for Oracle is now in private test, you can email dotnet_us@oracle.com for the package._

**Comment by JonathanMagnan** [comment]
Hello @NepPure ,

We have sent a request to get access to the package.

We might try to support their `BETA` but if too much issue occurs, we will wait that a final version is released.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @NepPure ,

Sorry for the long delay,

The latest release v1.8.25 finally support Oracle starting from their beta3

Let me know if everything works as expected.

**Comment by NepPure** [comment]
@JonathanMagnan Thank you very much, I will try it!
