### ISSUE TITLE
Audit: customizing AuditEntry by adding an EntityId property

### ISSUE THREAD

**Issue by JohanHeyvaert** [zzzprojects/EntityFramework-Plus#448]
Hello,

Does anyone know how to add an EntityId property in the **AuditEntry** data? Every entity in our project a PK (the Id, which is alvays an int - autoincremented by the DB) and I would like to make this field available on AuditEntry level.

In the default setup of the Audit functionality, this Id is stored among all other property modifications, in the AuditEntryProperties. As the values are stored in nvarchar(max) fields (which do not support indexing) retrieving data for a given entity is extremely slow. Making that PK available on AuditEntry level (with a none-unique index of course) would enormously boost the performance.

Thank you for your help!

Best regards,
Johan

**Comment by JonathanMagnan** [comment]
Hello @JohanHeyvaert ,

You can extend the `AuditEntry` by inhering from the class. Online example: https://dotnetfiddle.net/xazeGj

In the `AuditManager.DefaultConfiguration.AutoSavePreAction` action, you will be able to set the id to the new property you created.

Let me know if that helps you.

Best Regards,

Jonathan

**Comment by JohanHeyvaert** [comment]
Hi Jonathan,

Thanks a lot for your swift reply. 

We have already tried to implement that solution, but encountered difficulties with the Entity Framework migration (error “Sequence contains no matching element"). It looks like EF is not able to figure out how to handle the inheritance of our CustomAuditEntry class. I guess we will to give it another try.

We also found this alternative though: [EF.Plus - Audit - Custom AuditEntry & Database First Approach](https://dotnetfiddle.net/9XjCSM) - here the custom AuditEntry and AuditEntryProperty classes do not inherit from the default classes. I think this would be better, in order to avoid that extra AuditEntries.Discriminator column (or is there another way to avoid this?).
At first sight this approach looked like it worked, but at closer inspection most of the audit is no longer saved. When debugging, in the AutoSavePreAction, we see that all changes are correctly audited, but only the relation audit entries are saved in the database. Very weird.
Any idea what could be going wrong here?

I am sorry if my explanation is quite vague, but we have tried a lot of different things so I got a bit lost. :-s  I can send you example code of our attempts, but for the moment I don't have access to the code.

By chance, do you know how we could populate the desired EntityId field? You write: 
> In the AuditManager.DefaultConfiguration.AutoSavePreAction action, you will be able to set the id to the new property you created.
But how can we get hold of the entity's Id at that moment? (at creation, that Id is generated by the database)
I guess we'll need to retrieve it elsewhere, but I don't know where as I don't really understand the purpose of / difference between:
- the AuditManager.DefaultConfiguration.AutoSavePreAction
- the DbContext.SaveChanges() overloads with Audit class
- Audit.PreSaveChanges(DbContext)
- Audit.PostSaveChanges()  
- Audit.Configuration.AutoSavePreAction(DbContext, AuditEntry)

Thank you for your help - if any... ;-)

Best regards,
Johan

**Comment by JohanHeyvaert** [comment]
Hi Jonathan,

Your example looks very promising. We will give it a try and let you know if it worked out. 

Thanks a lot for your help!

Best regards,
Johan

**Comment by JohanHeyvaert** [comment]
It turns out that our earlier attempt, following the example of [EF.Plus - Audit - Custom AuditEntry & Database First Approach](https://dotnetfiddle.net/9XjCSM), in fact was working! I did something wrong when checking the result. 

We didn't know how to populate the EntityId though, so thanks a lot for showing us how to do this. It works really wel. Retrieving an audit history for a given entity (by its Id) is now very fast. :-)

Best regards,
Johan

**Comment by JonathanMagnan** [comment]
Great ;)

I will close this issue since everything seem to be solved.

Best Regards,

Jonathan
