### ISSUE TITLE
Delete with byte as primary key does not work

### ISSUE THREAD

**Issue by ChristianPeters-HF** [zzzprojects/EntityFramework-Plus#449]
Hi,

we just discovered that this code won't work.

```
var _ids = new List<byte>{1, 2, 3};

Set<ReportWrite>()
   .Where(i => _ids.Contains(i.Id)) // Presuming i.Id is of type byte
   .Delete(i => i.BatchSize = 0);
```

Changing it to 
```
var _ids = new List<int>{1, 2, 3};

Set<ReportWrite>()
   .Where(i => _ids.Contains(i.Id)) // Presuming i.Id is of type byte
   .Delete(i => i.BatchSize = 0);
```

does the job, even if i.Id is of type byte.

**Comment by JonathanMagnan** [comment]
Hello @ChristianPeters-HF ,

Which provider are you using?

**Comment by ChristianPeters-HF** [comment]
Hi @JonathanMagnan,

I'm using the SQL-Server-Provider-

**Comment by JonathanMagnan** [comment]
Thank, we will look at it.

**Comment by JonathanMagnan** [comment]
Hello @ChristianPeters-HF ,

My developer looked at it but he cannot reproduce the issue.

Here is an online example with a similar scenario as your: https://dotnetfiddle.net/fNNpjq

Could you let us know what we are missing?

Best Regards,

Jonathan
