### ISSUE TITLE
Audit Batch Delete and Batch Update operations

### ISSUE THREAD

**Issue by EdsonMiranda** [zzzprojects/EntityFramework-Plus#453]
I am auditing overriding SaveChanges method.
But can I audit batch delete and batch update operations?

**Comment by JonathanMagnan** [comment]
Hello @EdsonMiranda ,

Unfortunately no,

The `Audit` feature use data from the ChangeTracker. `Batch Delete` and `Batch Update` directly execute SQL in a database so it doesn't use the `Change Tracker` to load entities.

Let me know if that answer successfully to your question.

Best Regards,

Jonathan
