### ISSUE TITLE
Batch Update (with private set)

### ISSUE THREAD

**Issue by AdrianoAE** [zzzprojects/EntityFramework-Plus#454]
Hello,

I'm trying to do this:
```
var updated = await _context.Categories.Where(c => c.Id == command.Id)
          .UpdateAsync(c => new Category(command.Name, command.ImageUrl));
```
My Category class have private sets. So I can only set the fields via constructor or methods. How can I use the Update?

Best regards,
Adriano AE.

**Comment by JonathanMagnan** [comment]
Hello @AdrianoAE ,

Unfortunately, our library doesn't support this scenario ;(

So you currently cannot.

Best Regards,

Jonathan

**Comment by AdrianoAE** [comment]
Ok, thank you very mutch. I'll try to get a workaround or just do a plain sql query
