### ISSUE TITLE
FromCache for primitive Types like Int or Guid

### ISSUE THREAD

**Issue by oiBio** [zzzprojects/EntityFramework-Plus#457]
Hello everyone,

is it possible to use the FromCache() with primitiv datatypes like int or guids?
At the moment the FromCache() only works if the Result is a class.

You could work around this with following code, it works but does not look very good. 

`var result1 = db.MyEntity.Select(e => e.GUID).FromCache();    // Does not Work`
`var result2 = db.MyEntity.Select(e => new { e.GUID }).FromCache().Select(e => e.GUID);    // Works`

Is there another way to archive that?

**Comment by JonathanMagnan** [comment]
Hello @oiBio ,

Thank you for reporting.

We currently have too many requests but we will try to look at it this week.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @oiBio ,

We have tried to support it but unfortunately, it's a little bit harder for the primitive type. A lot of code has been modified when we testing it which lead us to some side impact error.

The anonymous type work since it satisfy with our "T: class" constraint.w

I believe at this moment, we prefer to leave it like it since it's already possible via anonymous type.

We might try again eventually but at this moment, nothing will be done for it.

Best Regards,

Jonathan

**Comment by oiBio** [comment]
Okay to bad... a landed up using this little helper method... it works for me so far.

```
public static IEnumerable<TResult> SelectPrimitive<TResult>(Expression<Func<T, TResult>> select, Expression<Func<T, bool>> whereExpression = null)
            {
                using (var db = GetDbContext())
                {
                    IQueryable<TResult> originalQuery;
                    if (whereExpression == null)
                    {
                        originalQuery = db.Set<T>().Select(select);
                    }
                    else
                    {
                        originalQuery = db.Set<T>().Where(whereExpression).Select(select);
                    }

                    return (from row in originalQuery
                            select new { r = row })
                               .FromCache()
                               .Select(e => e.r);
                }
            }
```

**Comment by JonathanMagnan** [comment]
Yup,

I will close this request since you find out an alternative solution.

Thank for sharing.

Best Regards,

Jonathan
