### ISSUE TITLE
QueryCache | ExpireAll 

### ISSUE THREAD

**Issue by zzzprojects** [zzzprojects/EntityFramework-Plus#46]
Currently, a cache entry can be expired used ExpireTag method.

However, there is no functionality to expire all entries.

Add ExpireAll functionality to flush all entries from the cache

```csharp
QueryCacheManager.ExpireAll();
```

**Comment by zzzprojects** [comment]
Added in v1.4.3

**Comment by petrosmm** [comment]
Why does this feature only exist in EF5 and EF6 and not EF Core?

**Comment by JonathanMagnan** [comment]
Hello @petrosmm ,

Probably because we had no way to iterate through the cache used in for .NET Core ;( so we could not make it as simple as the `MemoryCache` used in the .NET Framework.

**Comment by petrosmm** [comment]
Ahh I see, I saw some sealed classes and I could not access the `MemoryCache` as you had mentioned. So would the 'solution' be to tag all of my entries that enter into the cache and forEach expire from the list of tag names?

**Comment by JonathanMagnan** [comment]
The best solution might be to create and set your cache on your side

See:
- https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryCache.Shared/QueryCacheManager.cs#L44
- https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryCache.Shared/QueryCacheManager.cs#L138

If you want to clear all cache entries, you could then create a new MemoryCache instance and dispose of the old one and let the GC to his job.

**Comment by petersmm** [comment]
> The best solution might be to create and set your cache on your side
> 
> See:
> 
> * https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryCache.Shared/QueryCacheManager.cs#L44
> * https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryCache.Shared/QueryCacheManager.cs#L138
> 
> If you want to clear all cache entries, you could then create a new MemoryCache instance and dispose of the old one and let the GC to his job.

Exactly what I was wondering if I could do this, thank you!!!!!!!!
