### ISSUE TITLE
Could you please support Devart.Data.Oracle.EFCore

### ISSUE THREAD

**Issue by chrsas** [zzzprojects/EntityFramework-Plus#460]
I found that this library doesn't support Devart.Data.Oracle.EFCore. Could you please support it?

**Comment by JonathanMagnan** [comment]
Hello @chrsas ,

We are currently completing our test with Oracle for EF Core,

We will soon start to look at this one as well.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @chrsas ,

Sorry for the long delay,

The latest release v1.8.25 finally support Devart.Data.Oracle.EFCore

Let me know if everything works as expected.

**Comment by chrsas** [comment]
@JonathanMagnan Thank you very much.
