### ISSUE TITLE
Future Query with Concat does not work (EF Core)

### ISSUE THREAD

**Issue by magdadziemianowicz** [zzzprojects/EntityFramework-Plus#461]
Hi,

When I create future query with concat, for example:

```
var userIds = context.Users
              .Select(u => u.UserId)
              .Concat(context.Tenants.Select(t => t.UserId))
              .Future();
				
var userIdsResult = await userIds.ToListAsync();
```

The userIdsResult should contain UserId from Users and Tenants but it contains only UserId from Users.
It was working on EF6.

Microsoft.EntityFrameworkCore Version 2.2.2
Z.EntityFramework.Plus.EFCore Version 1.8.18

**Comment by JonathanMagnan** [comment]
Is that working in EF Core without `Future()`?

If yes, do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by magdadziemianowicz** [comment]
Sorry for delay but I was on vacation. 

[https://github.com/magdadziemianowicz/FutureQueryFailReproduction](url)

FutureQuery does not work with Concat and OrderBy together.
FutureQuery works fine with only Concat or with only OrderBy.
It is working in EF Core without Future() properly. 
It works in EF 6 for the same query.

**Comment by adamblok** [comment]
I also have this issue :(. What's the status?

**Comment by JonathanMagnan** [comment]
Hello @adamblok ,

My developer didn't get time to look at it last week, we should be able this week.

**Comment by KarolStosikPowel** [comment]
I can see that you're busy there, so I wanted to fix it myself. Unfortunately I can't run EFCore Unit tests (Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational (...)) exception.

But here is reproduction unit test, that you can just paste to your projects. It works fine in Z.Test.EntityFramework.Plus.EF6 unit tests, but I'm 100% sure that it will fail when pasted into Z.Test.EntityFramework.Plus.EFCore project.

```
[TestMethod]
public async Task Queryable_ConcatWithOrderBy_AsNoTracking()
{
    TestContext.DeleteAll(x => x.Entity_Basics);
    TestContext.Insert(x => x.Entity_Basics, 10);

    TestContext.DeleteAll(x => x.Entity_Guids);
    TestContext.Insert(x => x.Entity_Guids, 10);

    using (var ctx = new TestContext())
    {
        var future1 = ctx.Entity_Basics
            .Select(eb => eb.ID)
            .Concat(ctx.Entity_Guids.Select(i => i.ColumnInt))
            .OrderBy(x => x)
            .Future();

        var future2 = ctx.Entity_Basics
            .Select(eb => eb.ID)
            .Concat(ctx.Entity_Guids.Select(i => i.ColumnInt))
            .OrderBy(x => x)
            .Future();

        var noFutureResult = await ctx.Entity_Basics
            .Select(eb => eb.ID)
            .Concat(ctx.Entity_Guids.Select(i => i.ColumnInt))
            .OrderBy(x => x)
            .ToListAsync();

        Assert.AreEqual(2, QueryFutureManager.AddOrGetBatch(ctx.GetObjectContext()).Queries.Count);

        var futureResult1 = await future1.ToListAsync();
        var futureResult2 = await future2.ToListAsync();

        Assert.AreEqual(0, QueryFutureManager.AddOrGetBatch(ctx.GetObjectContext()).Queries.Count);

        Assert.IsTrue(future1.HasValue);
        Assert.IsTrue(future2.HasValue);

        CollectionAssert.AreEqual(noFutureResult, futureResult1);
        CollectionAssert.AreEqual(noFutureResult, futureResult2);
    }
}
```

Can you confirm that it fails for you?

**Comment by JonathanMagnan** [comment]
Hello all,

Sorry for the delay, the v1.8.24 has been finally released.

It should be now possible to use `concat` with query future. However, all query that are concatened will need to call query future as well.

Example:

```csharp
var userIds = context.Users
              .Select(u => u.UserId)
              .Concat(context.Tenants.Select(t => t.UserId).Future())
              .Future();
```

**Comment by JonathanMagnan** [comment]
Hello @KarolStosikPowel ,

Unfortunately, we didn't success to make it perfectly work yet.

With this trick (to append a second future in the contact), 2 different query as in the `QueryBatch` instead of one.

When using with `async`, this might lead to the following error with your test:

> System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
