### ISSUE TITLE
Global filter caching in same query

### ISSUE THREAD

**Issue by kemalbirinci** [zzzprojects/EntityFramework-Plus#462]
I have following line in my db context constructer

`this.Filter<IMustHaveTenant>(q => q.Where(a => a.TenantId == tenantId));`

in first query tenantId =1 
in second query tenantId=2

But when I look at the sql profiler I saw it always send tenantId=1 to sql server.

So I changed to my constructer like following line to handle this for now.

`QueryFilterManager.ClearQueryCache(this);`
`this.Filter<IMustHaveTenant>(q => q.Where(a => a.TenantId == tenantId));`

I use Z.EntityFramework.Plus.EF6 v.1.8.21

is there any advice about this?

**Comment by JonathanMagnan** [comment]
Hello @kemalbirinci ,

Unfortunately, this is a limitation of our library (https://entityframework-plus.net/query-filter#limitations in the section "Context Filter").

There is 3 alternatives you can use:
- [Query DbSetFilter](https://entityframework-plus.net/query-db-set-filter): Doesn't have this limitation but cannot filter included entities or lazy loading.
- [Entity Framework - Dynamic Filters](https://entityframework-dynamicfilters.net/overview)
- [Entity Framework Classic](https://entityframework-classic.net/): This library is an EF6 fork (so it replace EF6) with performance improvement and new features. The `Query Filter` in this library doesn't have the issue.

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by kemalbirinci** [comment]
Hello @JonathanMagnan 

 - "Entity Framework Classic" is not correct for me. I use third party package that has dependency on the EntityFramework (Microsoft.AspNet.Identity.EntityFramework)

- I tried "Entity Framework - Dynamic Filters". It is working very well.  Page load decrased %50. There is no same issue as you said.

Thank you very much
