### ISSUE TITLE
BatchDelete Mysql

### ISSUE THREAD

**Issue by ladome** [zzzprojects/EntityFramework-Plus#464]
When I create batch delete query, for example:
```
ctx.users.Where(c => c.idUser >= min && c.idUser < max).Delete();
```

Query is translated in this way:
```
DELETE A
FROM `project.users` AS A
INNER JOIN ( SELECT
`Extent1`.`idUser`
FROM `users` AS `Extent1`
 WHERE (`Extent1`.`idUser` >= 10) AND (`Extent1`.`idUser` < 20) ) AS B ON A.`idUser` = B.`idUser`
```
 
And i got this error from MySql:
```
Table project.project.users doesn't exist
```

### Details:
- Package: "Z.EntityFramework.Plus.EF6" version="1.8.22"
-  Mysql version: 5.7.25
-  EF: 6.2.0

**Comment by JonathanMagnan** [comment]
Thank you for reporting,

We will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @ladome ,

We are currently re-visiting some request we forget to answer last month.

Unfortunately, we tried on our side but could not make it works.

The logic should have already checked if your table name starts with the schema name and handle it without adding it:
https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.BatchDelete.Shared/BatchDelete.cs#L435

We have made several tests on our side but we never succeeded to get your error.

Is it possible to provide a runnable project/solution or a Fiddle with the issue you describe?

Best Regards,

Jonathan

**Comment by ladome** [comment]
Below is an example of a project and the script for creating the db:

[EFPlus_BatchDelete.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/3152904/EFPlus_BatchDelete.zip)

### Details:
- Package: "Z.EntityFramework.Plus.EF6" version="1.8.6"
-  Mysql version: 5.7.25
-  EF: 6.2.0

**Comment by PatriceDargenton** [comment]
Hello, this bug has been added from version 1.7.5 to 1.7.6.
Here is the bug found in the source code : BatchDelete.cs

            // GET mapping

            if (isMySql)
            {
                tableName = string.IsNullOrEmpty(store.Schema) ||
                    store.Schema == "dbo" || store.Table.StartsWith(store.Schema + ".")?
                    string.Concat("`", store.Table, "`") :
                    string.Concat("`", store.Schema, ".", store.Table, "`");

                -> I fixed the bug going back to the 1.7.5 version :

                tableName = string.Concat("`", store.Table, "`");

**Comment by JonathanMagnan** [comment]
Hello @PatriceDargenton ,

You can turn off the option to add the schema in the latest version by disabling the `UseMySqlSchema` option.

See here: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.BatchDelete.Shared/BatchDeleteManager.cs#L26

Unfortunately, I don't think the code you mentioned should have been ever added but to keep being backward compatible, we never removed it since some people rely on it.

**Comment by PatriceDargenton** [comment]
Ok, thanks, I will try it, but I still think it's a bug, because there should be no case where the database name should be prefixed twice, it does not make sense, does it? May be the code should be fixed using UseMySqlSchema boolean.

**Comment by JonathanMagnan** [comment]
I agree with you @PatriceDargenton ,

But you will be surprised how strangely some people use Entity Framework and a few people asked for it.

For example, what is your current schema? We only add it if it's not "dbo" or doesn't start with your table name. The code should normally doesn't affect you since there is no schema in MySQL.

**Comment by PatriceDargenton** [comment]
I can not test until some days, but I think both store.Schema and store.Table contains database name. I will check this as soon as possible and put a reply there.

**Comment by PatriceDargenton** [comment]
I did not found how I can set this option : (???).BatchDeleteManager.UseMySqlSchema = false;
I found nothing about it on the web either.

**Comment by JonathanMagnan** [comment]
Please see the following Fiddle: https://dotnetfiddle.net/xpItpp

**Comment by PatriceDargenton** [comment]
Ok, thank you ! With the last version (EntityFramework-Plus-1.10.2) it works fine, I can set :
BatchDeleteManager.UseMySqlSchema = false;
(I was using previouly the EntityFramework-Plus-1.7.6 version with no UseMySqlSchema boolean).
