### ISSUE TITLE
Global filter or instance filter is not working

### ISSUE THREAD

**Issue by csensoft** [zzzprojects/EntityFramework-Plus#466]
Is there any solution for this?

I see the filter works but it bring all the records to the table.

Suppose Lets say I have customer with orders and order has IsDeleted Column,
when I use global filter or instance filter on IsDeleted and query non deleted orders for a particular customer then I see a query generated for filter which bring all order which are not deleted.
Since our system is big, it bring billions of record before applying the customer id filter.
I use Query Future to query for a particular customer the end query result looks fine but the query takes forever to execute and wastes lot of memory because it loads tons of data upfront.

Is there something I am doing wrong? Let me know if you need more information to understand the problem.

This is my code in DbContext. All of the filter I have tried and none of it works for my case. 
I use Query Future which works just fine. I do not understand what is the problem. 
We are using database first approach. 
Query Filter is not working with query future and normal queries without future

```csharp
 public CustomerEntities()
            : base("name=Customer")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;


            QueryFilterManager.InitilizeGlobalFilter(this);

            this.Database.Log = s => Debug.Write(s);
        }

 static class Program
    {

        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        static void Main(string[] args)
        {
      
            QueryFilterManager.Filter<Customer>(q => q.Where(b => !b.IsDeleted));
        }
    }
```

**Comment by csensoft** [comment]
Is there any solution for this? 

I see the filter works but it bring all the records to the table. 

Suppose Lets say I have customer with orders and order has IsDeleted Column, 
when I use global filter or instance filter on IsDeleted and query non deleted orders for a particular customer then I see a query generated for filter which bring all order which are not deleted. 
Since our system is big, it bring billions of record before applying the customer id filter. 
I use Query Future to query for a particular customer the end query result looks fine but the query takes forever to execute and wastes lot of memory because it loads tons of data upfront. 

Is there something I am doing wrong? Let me know if you need more information to understand the problem.

**Comment by JonathanMagnan** [comment]
Hello @csensoft ,

Can you provide a runnable project/solution with the issue?

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by csensoft** [comment]
This has the sample project and DB script to create the db. 
We are using DB First approach. 

I have put the generated query inside the code for your reference. only the last two set of query
we would expect to execute but  there are few more queries that are generated for the filter which does not have filter by customer id when it is executed in DB it will take lot of time to give results but in code it is not taking that much time but still takes 3 seconds which is so much for a real application. 

Please do let me know what you find out.

Thanks in advance. 


[Filter.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/3048910/Filter.zip)

**Comment by JonathanMagnan** [comment]
Hello @csensoft ,

I might be wrong but the following query are not executed in the database. They are however Intercepted by the logged (We need to generate them for our library).

```csharp
//SELECT TOP(1)
//    [Extent1].[Id] AS[Id], 
//    [Extent1].[Description] AS[Description], 
//    [Extent1].[CustomerId] AS[CustomerId], 
//    [Extent1].[IsDeleted]
//AS[IsDeleted]
//FROM[dbo].[SalesOrder]
//AS[Extent1]
//WHERE 1000000 = [Extent1].[Id]
//-- Executing at 4/5/2019 12:41:28 PM -04:00
//-- Completed in 11 ms with result: SqlDataReader

//SELECT TOP(2)
//    [Extent1].[Id] AS[Id], 
//    [Extent1].[Name]
//AS[Name]
//FROM[dbo].[Customer]
//AS[Extent1]
//WHERE 1 = [Extent1].[Id]
//-- Executing at 4/5/2019 12:41:33 PM -04:00
//-- Completed in 0 ms with result: null

//SELECT
//    [Extent1].[Id] AS[Id], 
//    [Extent1].[Description] AS[Description], 
//    [Extent1].[CustomerId] AS[CustomerId], 
//    [Extent1].[IsDeleted]
//AS[IsDeleted]
//FROM[dbo].[SalesOrder]
//AS[Extent1]
//WHERE(N'Z.EntityFramework.Plus.QueryFilterInterceptor.FilterID;' = N'Z.EntityFramework.Plus.QueryFilterInterceptor.FilterID;') AND(N'Z.EntityFramework.Plus.QueryFilterInterceptor.FilterID;11994ad1-cf2c-41c1-b5df-4ebd3c1bd2fdbb6dc60f-8de7-4704-a7b7-f1a49ce80792False' = N'Z.EntityFramework.Plus.QueryFilterInterceptor.FilterID;11994ad1-cf2c-41c1-b5df-4ebd3c1bd2fdbb6dc60f-8de7-4704-a7b7-f1a49ce80792False') AND([Extent1].[IsDeleted] <> 1) AND(N'Z.EntityFramework.Plus.QueryFilterInterceptor.Hook;Filter.CustomerInventoryEntities, Filter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null;Filter.SalesOrder, Filter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null;bb6dc60f-8de7-4704-a7b7-f1a49ce80792' = N'Z.EntityFramework.Plus.QueryFilterInterceptor.Hook;Filter.CustomerInventoryEntities, Filter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null;Filter.SalesOrder, Filter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null;bb6dc60f-8de7-4704-a7b7-f1a49ce80792')
//-- Executing at 4/5/2019 12:41:33 PM -04:00
//-- Completed in 0 ms with result: null

//SELECT
//    [Extent1].[Id] AS[Id], 
//    [Extent1].[Description] AS[Description], 
//    [Extent1].[CustomerId] AS[CustomerId], 
//    [Extent1].[IsDeleted]
//AS[IsDeleted]
//FROM[dbo].[SalesOrder]
//AS[Extent1]
//WHERE([Extent1].[IsDeleted] <> 1) AND(1 = [Extent1].[CustomerId])
//-- Executing at 4/5/2019 12:41:33 PM -04:00
//-- Completed in 0 ms with result: null
```

The only SQL that's really executed in the database (Taken from SQL Profiler) is:

```sql
-- EF+ Query Future: 1 of 2
SELECT TOP (2) 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Name] AS [Name]
    FROM [dbo].[Customer] AS [Extent1]
    WHERE 2 = [Extent1].[Id]
;

-- EF+ Query Future: 2 of 2
SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Description] AS [Description], 
    [Extent1].[CustomerId] AS [CustomerId], 
    [Extent1].[IsDeleted] AS [IsDeleted]
    FROM [dbo].[SalesOrder] AS [Extent1]
    WHERE ([Extent1].[IsDeleted] <> 1) AND (2 = [Extent1].[CustomerId])
;
```

Which contains the filter.

**Comment by JonathanMagnan** [comment]
The current query take around 1.5s on my desktop.

However, you are returning 100001 entities, so I guess that's expected? Entity Framework need to materialize all thoses entities which take some times

Let me know if I'm missing something.

**Comment by csensoft** [comment]
Thanks for looking into this problem. I do agree with you on the loading entities part. 
Our real world app does not load these much entities but it has million of data. 
We went with instance filter to PROD environment and then noticed that memory usage hiked like never before and the only thing we could find is the generated query which has no filter based on the Id we supplied but it had only the soft delete filter. After we removed the instance filter everything worked fine. To be honest we did not check the SQL Profiler for the logged quires. 

Is there any issue when we use Query Filter with Queue Future for this issue to happen? 

Also, from your website I learned that "Include Filter" does not work with "Query Future", is it still true? Will there be any addition in the future. 

Thanks for your effort on this. Greatly appreciated!!.

**Comment by JonathanMagnan** [comment]
Hello @csensoft ,

Yes, is still true that Query Filter doesn't work with Query Future.

This feature will be looked soon in [EF Classic](https://entityframework-classic.net/). When we will re-write the code, we will for sure make it compatible with Query Future. Depending on the complexity, we make import back the code in EF+ for EF6.

Unless you come with a real example that have the issue, there is no so much we can do at this moment ;(

**Comment by csensoft** [comment]
Good to know that. 
I will reopen this if I can give you something solid to work on.
