### ISSUE TITLE
Support for .Net 4.7.2 framework?

### ISSUE THREAD

**Issue by ooples** [zzzprojects/EntityFramework-Plus#467]
Is there a timeline on when this project will add support for the latest .net framework? Apparently I'm getting the following error message when I try to run it in a project that uses .net framework 4.7.2

Package Z.EntityFramework.Extensions.EFCore 2.2.1 is not compatible with net451 (.NETFramework,Version=v4.5.1) / win. Package Z.EntityFramework.Extensions.EFCore 2.2.1 supports: netstandard2.0 (.NETStandard,Version=v2.0)

What is the latest version this project supports?

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

Your issue seems weird. You talk about the v4.7.2 but the issue looks to happen in a project using v4.5.1

Our library already supports the latest version.

It's possible to provide a project with this issue? You can send it in private here: info@zzzprojects.com

**Comment by ooples** [comment]
I tried a bunch of different fixes but I only seemed to make it worse. I just emailed you with my project files

**Comment by JonathanMagnan** [comment]
Had to comment around 30k line in your `Program` file but your project worked flawlessly.

It compiles without any issue.

Besides you are using EF6, so the package `Z.EntityFramework.Extensions.EFCore` should never be added but instead `Z.EntityFramework.Extensions` as your project had in reference.

Anyway, I added  `Z.EntityFramework.Extensions.EFCore` without problem either.

In short, we had no problem with the project provided ;(

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

Should we close this issue?

**Comment by ooples** [comment]
I'm not able to replicate what you did. Which lines did you comment out?

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

The part with all your case statements.

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

If you are able to reproduce it, please provide us a project and we will re-open this issue.

Best Regards,

Jonathan
