### ISSUE TITLE
Example adding ip address

### ISSUE THREAD

**Issue by Jogai** [zzzprojects/EntityFramework-Plus#473]
### Description
https://entityframework-plus.net/audit#custom-class
This example is using an ip address, but where does the variable 'address' come from?

Am I on the right track if I do this:

```c#
    public class Context
    {
        private string address;

        public Context()
            : base("DefaultConnection")
        {            
        }

        public Context(string ipAddress)
            : this()
        {
            address = ipAddress;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
            {
                Context activitiesContext = context as Context;
                if (activitiesContext != null) activitiesContext.AuditEntries.AddRange(audit.Entries);
            };
            AuditManager.DefaultConfiguration
                .AuditEntryFactory = 
                args => new CustomAuditEntry() {IpAdress = address};

            AuditManager.DefaultConfiguration.Exclude(o => true); // Exclude All
            AuditManager.DefaultConfiguration.IncludeDataAnnotation();
            AuditManager.DefaultConfiguration.ExcludeDataAnnotation();
            AuditManager.DefaultConfiguration.IgnorePropertyUnchanged = true; // audit only changed fields
        }
    }
```

### Further technical details
- EF version: 6.1.3
- EF Plus version: 1.8.21
- Database Provider: System.Data.SqlClient (.net 4.7.2)

**Comment by Jogai** [comment]
I see 😃 Because I wasn't sure where the variable came from I thought I create what might be how it is supposed to work. My question is then:

Is instantiating a custom context the way to supply your own variables or is there a better way?

**Comment by JonathanMagnan** [comment]
It all depends on how your application is built.

For example, on my side, I often use the HttpContext to store some information about the current page or user. So I take value from it.

There is no specific way I would recommend more than another. I guess, you are maybe in better place to take this choice then me ;)
