### ISSUE TITLE
IncludeOptimized maps less elements

### ISSUE THREAD

**Issue by Ronosho** [zzzprojects/EntityFramework-Plus#474]
### Description
I'm using IncludeOptimized() feature to include customer email addresses.
The query that is produced in the Debug output yields the correct results.

But when I'm viewing the results in the Watch only 1 element is present instead of the expected 2.

```
  public Relatie GetCustomerInfo(int customerId)
        {
            try
            {
                using (var context = new CentralDatabaseEntities(ConnectionString))
                {
                    var customer = context.Customers
                        .IncludeOptimized(c => c.EmailAddresses.Where(p => p.ContactId == 0))
                        .FirstOrDefault(k => k.RelatieId == customerId);
                      

                    return AutoMapper.Map<Relatie>(customer);

                }
            }
            catch (DbEntityValidationException dbEntityValidationException)
            {
                Log.Error(GetEntityValidationMessage(dbEntityValidationException));
                Log.Error(GetObjectErrorMessage(dbEntityValidationException));
                return default;
            }
        }
```

### Further technical details
- EF version: 6.2
- EF Plus version: 1.8.25
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @Ronosho ,

Can you provide a runnable project/solution or a Fiddle with the issue you describe?

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Ronosho** [comment]
@JonathanMagnan I can Fiddle around a bit more.
The method in question is a bit more complex actually.

since im using 4 includes instead of 1 in the provided example.

Phonenumbers, addresses and emailaddresses are fetched.

The strange thing is, the customer has 2 address which are loaded, but just 1 email address.
Maybe you have some pointers.

**Comment by JonathanMagnan** [comment]
The only thing in my mind is that unlike the `Include` method, you need to specify all path at least once.

You can also automatically do it with `QueryIncludeOptimizedManager.AllowIncludeSubPath = true`.

For example, this query with compile but yield a wrong result:

```csharp
context.Blogs.IncludeOptimized(x => x.Posts.SelectMany(x => x.Users));
```

That's caused because the `Posts` has never been included once.
This query will yield the correct result:

```csharp
context.Blogs.IncludeOptimized(x => x.Posts)
			 .IncludeOptimized(x => x.Posts.SelectMany(x => x.Users));
```

**Comment by Ronosho** [comment]
Hi @JonathanMagnan,

So after spending some more hours checking and trying different things.
I managed to find the culprit.

A co worker of mine changed the Dto class and moved the attributes annotations to a seperate EntityTypeConfiguration file.

But failed to convert the PK correctly.

**OLD:**
   ```
ToTable("tblEmailAdressen", "dbo");
HasKey(e => e.Volgnummer);
HasKey(e => e.RelatieId);
HasKey(e => e.ContactId);

```
`NEW`
```
ToTable("tblEmailAdressen", "dbo");
HasKey(e => new { e.Volgnummer, e.RelatieId, e.ContactId });
```

After this change the code started working as normal again.
Sorry to waste your time on this.

**Comment by JonathanMagnan** [comment]
Don't worry, thank for sharing the solution.

That's exactly why we now ask for a runnable project/solution ;) So many time we tried to reproduce an issue to finally find out that it was outside of our library.

Have a great day,

Best Regards,

Jonathan
