### ISSUE TITLE
Invalid SQL generated on Delete operation of entity with composite primary key

### ISSUE THREAD

**Issue by msvprogs** [zzzprojects/EntityFramework-Plus#476]
### Description
I have the following entities with custom column names (PostgreSQL naming convention)
```
public class RelatedTestEntity
{
	[Column("id")]
	public int Id { get; set; }

	[Column("some_name")]
	public string SomeName { get; set; }
}

public class TestEntity
{
	[Column("id")]
	public int Id { get; set; }

	[Column("some_name")]
	public string SomeName { get; set; }

	[Column("related_id")]
	public int RelatedTestEntityId { get; set; }

	public RelatedTestEntity RelatedTestEntity { get; set; }
}

// model builder in DbContext
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
	modelBuilder.Entity<TestEntity>()
		.HasKey(x => new {x.Id, x.RelatedTestEntityId});
}
```

When I try to delete all TestEntities with RelatedTestEntityId = 1, EF Plus generates an invalid SQL query:
```
context.TestEntities
    .Where(x => x.RelatedTestEntityId == 1)
    .Delete();
```
```
DELETE FROM "TestEntities" AS A
USING ( SELECT x.id, x.related_id AS "RelatedTestEntityId"
FROM "TestEntities" AS x
WHERE x.related_id = 1 ) AS B WHERE A."id" = B."id"
AND A."related_id" = B."related_id"
```
As you can see, custom column names are ignored inside USING statement.

### Fiddle or Project
Test project is attached
[TestProject.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/3102689/TestProject.zip)

### Further technical details
- EF version: 2.2.0, EF Core
- EF Plus version: 1.8.25
- Database Provider: PostgreSQL, Npgsql.EntityFrameworkCore.PostgreSQL

**Comment by JonathanMagnan** [comment]
Hello @msvprogs ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @msvprogs ,

The v1.8.26 has been released.

The issue caused by alias name & composite key should now be fixed in this version.

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by msvprogs** [comment]
Yes, everything is working great. Thanks!
