### ISSUE TITLE
Collection.Contains very slow

### ISSUE THREAD

**Issue by Dringo87** [zzzprojects/EntityFramework-Plus#478]
Hello,

I have a problem with query:
 DbContext.Documents.Where(x =>updatableDocument.DocIds.Contains(x.DocumentId))
                         ....
The problems comes from the where part. In fact, the Contains is translated in my sql query by a check of the id is in a collection of Ids and a null check at the end as following :
 ... WHERE ([Extent1].[ID_DOC] IN (N''1212'',N''1313'',....) **AND ([Extent1].[ID_DOC] IS NOT NULL)**

the second part is redundant and by removing it, the query take 40 seconds less to execute.
Is there any way to not have the null check when i use contains in my query ?

Thank you for your help

I'm using

    EntityFramework: 6.2.0
    Z.EntityFramework.Plus.EF6: 1.7.7
    .NET Framework 4.7.1

**Comment by JonathanMagnan** [comment]
Hello @Dringo87 ,

I don't think on our side we can do anything.

We don't generate those queries but use those generated by Entity Framework.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
