### ISSUE TITLE
BatchDelete Mysql - Table doesn't exist

### ISSUE THREAD

**Issue by ladome** [zzzprojects/EntityFramework-Plus#480]
Related to closed issue #464.

Below is an example of a project and the script for creating the db:

[EFPlus_BatchDelete.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/3152879/EFPlus_BatchDelete.zip)

### Details:
- Package: "Z.EntityFramework.Plus.EF6" version="1.8.6"
-  Mysql version: 5.7.25
-  EF: 6.2.0
- Visual Studio Community 2017
- Mysql dor Visual Studio 1.2.7 (Mysql Installer)
- Connector/NET 6.9.10 (Mysql Installer)

**Comment by ladome** [comment]
Duplicated #464

**Comment by JonathanMagnan** [comment]
Hello @ladome ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @ladome ,

There is still something I don't understand with `MySQL` and `Schema` name.

If we use your project and just make a `SaveChanges`

```csharp
using (var ctx = new testEntities())
{
    ctx.users.Add(new user() { name = "test" });
    ctx.SaveChanges();
}
```

It throws the following error:

```
MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(SELECT
`users`.`idUser`, 
`users`.`name`
FROM `users` AS `users`)(
`idUser`, 
' at line 1
```

So how do you use `SaveChanges`? I mean I don't expect our library to work if the model doesn't work either with `SaveChanges`.

**Comment by ladome** [comment]
There was an error in the creation of the test db model.
I have re-attached the project. The insertion should now work.

[EFPlus_BatchDelete.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/3187065/EFPlus_BatchDelete.zip)

**Comment by JonathanMagnan** [comment]
Hello @ladome ,

The v1.8.29 has been released.

We added two options:
- `BatchUpdateManager.UseMySqlSchema`
- `BatchDeleteManager.UseMySqlSchema`

If you set it to false, the schema will not be longer appended.
