### ISSUE TITLE
Need support Devart.Data.Oracle.EFCore OracleEntityProviderConfig.

### ISSUE THREAD

**Issue by chrsas** [zzzprojects/EntityFramework-Plus#481]
EF core plus does not support `Devart.Data.Oracle.EFCore OracleEntityProviderConfig`.
For example , when I use batch delete, the generated SQL is 
```sql
Delete "Abc" where ...
```
But In `OracleEntityProviderConfig`, I have set `OracleEntityProviderConfig.Instance.Workarounds.DisableQuoting = true`, the expected SQL is 
```sql
Delete Abc where ...
```

**Comment by JonathanMagnan** [comment]
Hello @chrsas ,

Thank you for reporting, we will look at it if we want to support it or not.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @chrsas ,

The v1.9.0 has been released.

Our library should now support `DisableQuoting`, let me know if everything is working as expected.

**Comment by chrsas** [comment]
@JonathanMagnan Thank you for your help, I will try it.

**Comment by chrsas** [comment]
It works fine, Thank you @JonathanMagnan .
