### ISSUE TITLE
Query AuditEntries in different contexts

### ISSUE THREAD

**Issue by EdsonMiranda** [zzzprojects/EntityFramework-Plus#482]
I am using Audit tables in a different context of the tables being audited.
It works fine! But when I try to retrieve audit entries I receive the following error:

**The entity type Customer is not part of the model for the current context.**

Here is part of the code:
var item = _db.Customer.Where(w => w.CustomerId = 1).FirstOrDefault();
var auditEntries =_dbAudit.AuditEntries.Where(item).ToList(); //at this line the error occurs.

Customer is at _db context and Audit is at _dbAudit context.

**Comment by JonathanMagnan** [comment]
Hello @EdsonMiranda ,

Thank you for reporting, unfortunately that's currently a limitation of our library when you are using different contexts ;(

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by EdsonMiranda** [comment]
Any workaround or suggestion to retrieve audit data on situations like this?

**Comment by JonathanMagnan** [comment]
One way is to directly retrieve it using LINQ syntax: https://dotnetfiddle.net/5AfB7e

**Comment by EdsonMiranda** [comment]
Thanks for the sample, I was just writing a code like that.
