### ISSUE TITLE
BatchUpdate generate wrong column name

### ISSUE THREAD

**Issue by ZeekoZhu** [zzzprojects/EntityFramework-Plus#488]
### Description

I try to update  PostTag(mapped to"blog_tags" table) in this way
```csharp
await _dbContext.Set<PostTag>()
                .Where(tag => addTagIds.Contains(tag.Id))
                .UpdateAsync(x => new PostTag
                {
                    UseCount = x.UseCount + 1
                });
```

### Exception

```
Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'no such column: tag.UseCount'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory) in C:\Users\Jonathan\Desktop\Z\TFS\EFPlus\Z.EntityFramework.Plus\shared\Z.EF.Plus.BatchUpdate.Shared\BatchUpdate.cs:line 407
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
```

It looks like the `Where` expression's parameter name is used as the table name

### Further technical details
- EF version: EF Core 2.2.4
- EF Plus version: EF.Plus.EFCore 1.8.27
- Database Provider: EF Core Sqlite 2.2.4

**Comment by JonathanMagnan** [comment]
Hello @ZeekoZhu ,

Could you provide a runnable project/solution? It will help my developer to get started faster with this issue.

You can send private file here: info@zzzprojects.com

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by ZeekoZhu** [comment]
@JonathanMagnan  Here is simple reproduce: https://github.com/ZeekoZhu/EFCorePlusSQLiteUpdateIssue

**Comment by ZeekoZhu** [comment]
https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.BatchUpdate.Shared/BatchUpdate.cs#L1434

This line add a table prefix for column `ViewCount`

**Comment by JonathanMagnan** [comment]
Thank you for the project,

I have re-opened the issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ZeekoZhu ,

We tried to solve it last week but unfortunately, we were not able to find a good solution.

Unlike SQL Server, a `JOIN` is not used so it's not easily possible for us to take the current column value. Those kinds of expression `UseCount = x.UseCount + 1` is only supported for providers that allows us to use a JOIN  

I believe you will need to write yourself the SQL queries for this one ;(
