### ISSUE TITLE
Add option SkipInitialValues

### ISSUE THREAD

**Issue by Jogai** [zzzprojects/EntityFramework-Plus#491]
I misunderstood IgnoreEntityAddedDefaultValue, because I want to actually skip these values, and also anything with NULL as OldValue.

So I propose a setting for SkipInitialValues. Like others it would never skip the primary key(s), but skip the rest if the entity is new.

My reasoning is that on creating an entity the old values are always null, and on the first update the initial value will be in the OldValue of the Modified entry. In our case we're more interested in what has changed as opposed to what is created.

**Comment by JonathanMagnan** [comment]
Hello @Jogai ,

So if I understand correctly,

When the option `SkipInitialValues` is set to true, ONLY values from the primary key will be inserted?

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Jogai** [comment]
On insert yes. On update, whatever is changed.

So given this (and I also assume IgnorePropertyUnchanged = true because I want to make everything as terse as I could).

	public class Customer
	{
		public int Id { get; set; } // Primary Key
		public string Name { get; set; }
		public string Description { get; set; }
		public Boolean IsActive { get; set; }
		public int Calls { get; set; }
	}

Insert:

	context.Customer.Add(new Customer() { Name ="Client A", Description = "Great", IsActive = true, Calls = 0 });

The audit would have the entry EntityAdded and only the Id in the audit properties table.

This is the main portion of my request. But to make it uniform I think the update case is going to be like this:

Update with: 

	listToModify.First().Description = "Client declined"
	listToModify.First().IsActive = false;
	listToModify.First().Calls = 1;

It would have the EntityModified entry with in the property table the old & new value for Description and IsActive (and Id of course). Since the Calls field goes from initial (0) to something (1 in this case) its not listed.

**Comment by JonathanMagnan** [comment]
Thank for the additional info,

We will certainly look at it.

**Comment by JonathanMagnan** [comment]
Hello @Jogai ,

The options `IgnorePropertyAdded` has been added in the v1.9.3

Let me know if that's what you were looking for.
