### ISSUE TITLE
Performance of reading audit info

### ISSUE THREAD

**Issue by Jogai** [zzzprojects/EntityFramework-Plus#493]
I have a stored procedure helping me read back the audit info along with the object. The performance really suffers on joining the audit info. Is there a certain way to query it in a performant way? Now I join the info like this:

	LEFT OUTER JOIN AuditEntryProperties aep ON (
			aep.NewValue = sn.Id
			AND aep.OldValue is null
			AND aep.PropertyName = 'Id'
			)
	LEFT OUTER JOIN AuditEntries ae ON (
			ae.AuditEntryID = aep.AuditEntryID
			AND ae.State = 0
			)

**Comment by JonathanMagnan** [comment]
Hello @Jogai ,

I'm not sure to understand the question.

Perhaps you are missing some index on your table?
