### ISSUE TITLE
SQLite and Batch Delete deletes all intems in table

### ISSUE THREAD

**Issue by WebDucer** [zzzprojects/EntityFramework-Plus#494]
### Description

We use EF Core in our mobile application (Xamarin) and use EF-Plus primary for cleanup tables.

Now we wanted to use this for filtered deletes. It seems, that the generated SQL is not applicable for SQLite and instead of deleting filtered data, it deletes the whole table content.

### Fiddle or Project

Here is our C# code (want to delete an Item by ID):

```csharp
Context.UploadData
    .Where(w => w.Id == uploadDataId)
    .DeleteAsync();
```

Here is the generated SQL (from `command.TextCommand`:

```sql
DELETE
FROM    "upload"
WHERE EXISTS ( SELECT 1 FROM (SELECT "w"."id"
FROM "upload" AS "w"
WHERE "w"."id" = @__uploadDataId_0) B
               WHERE "id" = B."id"
           )
```

This leads with SQLite to deletion of the entire table.

As I can see, there is missing table alias for the first `FROM`. Because the following SQL works then as expected:

```sql
DELETE
FROM    "upload" AS "o"
WHERE EXISTS ( SELECT 1 FROM (SELECT "w"."id"
FROM "upload" AS "w"
WHERE "w"."id" = @__uploadDataId_0) B
               WHERE "o"."id" = B."id"
           )
```

### Further technical details
- EF version: 2.2.4
- EF Plus version: 2.0.0
- Database Provider: SQLite

**Edit**

The `UPDATE` statement with the same condition generates the following `WHERE` clause:

```sql
UPDATE "ulpod"
SET "name" = "NewName"
WHERE EXISTS ( SELECT 1 FROM (SELECT "w"."id"
FROM "upload" AS "w"
WHERE "w"."id" = @__uploadDataId_0) B
               WHERE "upload"."id" = B."id"
           )
```

**Comment by JonathanMagnan** [comment]
Hello @WebDucer ,

Thank for reporting.

We will look at it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by WebDucer** [comment]
Fiddle example: http://sqlfiddle.com/#!5/8f1f3/5

**Comment by JonathanMagnan** [comment]
Hello @WebDucer ,

A new version has been released: https://www.nuget.org/packages/Z.EntityFramework.Plus.EFCore/2.0.3

Could you try it and let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by WebDucer** [comment]
@JonathanMagnan 2.0.3 works as expected by deletion now.


```sql
DELETE
FROM    "upload"
WHERE EXISTS ( SELECT 1 FROM (SELECT "w"."id"
FROM "upload" AS "w"
WHERE "w"."id" = @__uploadDataId_0) B
               WHERE "upload"."id" = B."id"
           )
```

**Comment by JonathanMagnan** [comment]
Great ;)
