### ISSUE TITLE
How to keep native transaction?

### ISSUE THREAD

**Issue by happydaily** [zzzprojects/EntityFramework-Plus#495]
UserEntity user1 = new UserEntity();
		 	user1.Id = Guid.NewGuid().ToString("N");
			user1.Account = "AAAAA";
			user1.MobilePhone = "1234124214141";

			UserEntity user2 = new UserEntity();
			user1.Id = "d9c21cedd2124a3da2fcd5d32b3a3127";

			_userService.Delete(user2);
			_userService.Add(user1);// here will cause exception
			_userService.SaveChanges();
provide by ef
` public void Delete(T entity)
        {
			DataSet.Attach(entity);
			DataSet.Remove(entity);
	}`
provide by efplus
` public void Delete(T entity)
        {
			DataSet.Where(u=>u.Id==entity.Id).Delete();
	}`
if Delete(user2) method invoke by efplus delete,it will immediate execution ignore error later from add methed，how to be consistent with the native?

**Comment by JonathanMagnan** [comment]
Which version of Entity Framework has this `Delete` method?

Seem I cannot find it in my case.

**Comment by happydaily** [comment]
Entity Framework 6

**Comment by JonathanMagnan** [comment]
Unless I don't check the good thing, there is no `Delete` method on the `DbSet`.

Is it possible to provide a runnable example with this issue?

**Comment by happydaily** [comment]
Entity Framework automatically wrap a submt into a transaction,when add method cause exception,the delele will not submit too;but use ef plus will  still submit delete.
Dataset is efcontext.set<T>(),

**Comment by JonathanMagnan** [comment]
Oh I better understand now what you are saying.

However, the `Delete` method on the `IQueryable` is a direct operation. It doesn't wait that you call `SaveChanges` or `SubmitChanges?` before being executed. It's executed as soon as you call it.

If you want it inside a transaction, you will need to handle the transaction on your side by starting it before calling the delete method.

**Comment by happydaily** [comment]
thank you for reply
