### ISSUE TITLE
When using a class that inherits from ICollection the list won't be filled with an empty list but with NULL

### ISSUE THREAD

**Issue by pvervaet** [zzzprojects/EntityFramework-Plus#496]
### Description
When using a property ICollection<Step> on an entity, EF and EF+ will return an empty list in case there are no results. This is expected behavior.

When changing the property to a class StepCollection, which inherits from List<Step>, EF will still return an empty list when no results are found. But EF+ will return NULL. This behavior is not expected.

### Technical details
When looking at the code in QueryIncludeOptimizedNullCollection. We can see that only the following is checked:

> if (property.PropertyType.GetGenericArguments().Length == 1)
{
    ...
}
return;

But in fact it should also check it's base classes.

Could this change be implemented?

Thank you

Peter

**Comment by JonathanMagnan** [comment]
Hello @pvervaet ,

Thank you for reporting, we will look at it.

Could you first let us know what is the signature of `StepCollection` class to make sure we release a fix that will work for you

```csharp
public class StepCollection : List<Something>
{
}

// or

public class StepCollection<Something> : List<Something>
{
}

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
```

**Comment by pvervaet** [comment]
Tnx!
We use your first example:

public class StepCollection : List<Something> { }

I guess your other class will be covered by the current code.

**Comment by pvervaet** [comment]
Not sure why the comment changes my text. But like this:

public class StepCollection : List < Step >
{
}

**Comment by pvervaet** [comment]
Jonathan, any idea on ETA? Thanks!

**Comment by JonathanMagnan** [comment]
Hello @pvervaet ,

A new version has been released v1.9.4

The issue should be fixed in this version.

Let me know if everything now works as expected.

**Comment by pvervaet** [comment]
It seems to work, however as a side effect, I now seem to need a public empty constructor on all my entities.
We don't really want this, nor do I understand why this would be needed.
I can understand the entity who implements the collection would need an public empty constructor, but the rest not...

Any way to change this?

**Comment by JonathanMagnan** [comment]
Hello @pvervaet ,

I'm probably missing something. Was not already the case? https://stackoverflow.com/questions/31543255/why-must-i-have-a-parameterless-constructor-for-code-first-entity-framework

**Comment by pvervaet** [comment]
Well without EF+ everything works fine because I have protected empty constructors on all my classes.
When looking at the stacktrace it seems to be something triggered from EF+.


System.MissingMethodException
No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.CheckAndSetCollection(PropertyOrFieldAccessor accessor, Object currentItem, Type propertyType, Type originalType)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.CheckAndSetCollection(PropertyOrFieldAccessor accessor, Object currentItem, Type propertyType, Type originalType)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.CheckNullRecursive(Object currentItem, List`1 paths, Int32 index)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.CheckNullRecursive(Object currentItem, List`1 paths, Int32 index)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.CheckNullRecursive(Object currentItem, List`1 paths, Int32 index)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.NullCollectionToEmpty(Object item, List`1 childs)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedProvider`1.Execute[TResult](Expression expression)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)

**Comment by JonathanMagnan** [comment]
Oh now I understand, It's me that missed something in your last reply.

You are right, the way we create the instance of your collection probably require a public empty constructor at this moment.

Just to make sure, everything will be fine even if we use your protected empty constructor?

**Comment by pvervaet** [comment]
Yes I think so.

**Comment by JonathanMagnan** [comment]
Great, we will look at it

**Comment by pvervaet** [comment]
tnx!

**Comment by JonathanMagnan** [comment]
Hello @pvervaet ,

Could you provide a runnable solution with this issue?
(info@zzzprojects.com if you need to send it in private)

I believe we are missing a step as we have an error somewhere else when trying to reproduce your scenario.

**Comment by pvervaet** [comment]
I can, but can't give you my current solution. i'll try to set a new project up in the coming days...

**Comment by pvervaet** [comment]
So I've tried to recreate this issue in a separate small solution today. I can't for the life of me recreate this problem outside of my solution.

I've got it pinpointed to where it is a complex structure with at its deepest 2 optional entities (LA and SF).
Underneath the linq query i use:

```
var qry = iQueryable
  .IncludeOptimized(x => x.RR)
  .IncludeOptimized(x => x.S)
  .IncludeOptimized(x => x.S.Select(y => y.SOperations))
  .IncludeOptimized(x => x.S.Select(y => y.SFacilities))
  .IncludeOptimized(x => x.S.Select(y => y.SRemarks))
  .IncludeOptimized(x => x.S.Select(y => y.Polies))
  .IncludeOptimized(x => x.IntProds)
  .IncludeOptimized(x => x.WS)
  .IncludeOptimized(x => x.WS.SelectMany(y => y.WC))
  .IncludeOptimized(x => x.WS.SelectMany(y => y.WC.Where(z => z.LA != null).Select(z => z.LA)))
  .IncludeOptimized(x => x.WS.SelectMany(y => y.WC.Where(z => z.SF != null).Select(z => z.SF)));
```

The issue is with the last 2 lines. I can't get the LA or SF property filled.
I've analyzed the queries it creates and that all seems to be fine.

Again the error and stacktrace:

> System.MissingMethodException
> No parameterless constructor defined for this object.
>    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
>    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
>    at System.Activator.CreateInstance(Type type)
>    at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.CheckAndSetCollection(PropertyOrFieldAccessor accessor, Object currentItem, Type propertyType, Type originalType)
>    at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.CheckAndSetCollection(PropertyOrFieldAccessor accessor, Object currentItem, Type propertyType, Type originalType)
>    at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.CheckNullRecursive(Object currentItem, List`1 paths, Int32 index)
>    at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.CheckNullRecursive(Object currentItem, List`1 paths, Int32 index)
>    at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.CheckNullRecursive(Object currentItem, List`1 paths, Int32 index)
>    at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.CheckNullRecursive(Object currentItem, List`1 paths, Int32 index)
>    at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.CheckNullRecursive(Object currentItem, List`1 paths, Int32 index)
>    at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.NullCollectionToEmpty(Object item, List`1 childs)
>    at Z.EntityFramework.Plus.QueryIncludeOptimizedProvider`1.Execute[TResult](Expression expression)
>    at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)

The error tells me to Add a public constructor, however this is neither a solution. 
When I do this I and in the database there is no value for LA or SF, I just get a new default instance of these entities, where in fact I would expect a value NULL for these properties.

I suspect there is a bug somewhere in the EF-Plus libraries, but I don't know why I can't seem to reproduce this behavior... :(
With all the info I gave now, do you have a better understanding of my issue?

**Comment by JonathanMagnan** [comment]
Hello @pvervaet ,

We 100% understand the issue but we are not able either to reproduce it (which make it hard to fixes).

If you cannot provide the project, could you try the EF Plus source on your side and check what is happening? The issue should happen here: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryIncludeOptimized.Shared/QueryIncludeOptimizedNullCollection.cs#L97-L109

Perhaps if you could give more information by debugging it, we will find a way to reproduce and fix it.

**Comment by pvervaet** [comment]
Eureka! I was finally able to reproduce the issue.

The issue is that we have a base class for our entities that requires a generic. In this case you assume this is a list, however it is not, so it should default to NULL.

Maybe you can add a check on IEnumerable?

Attached the demo project.

[EF6-Code-First-Demo.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/3405283/EF6-Code-First-Demo.zip)

**Comment by pvervaet** [comment]
Indeed, it is fixed by changing this:

```
private static void CheckAndSetCollection(PropertyOrFieldAccessor accessor, object currentItem, Type propertyType, Type originalType)
	    {
            if (propertyType.GetGenericArguments().Length == 1))
...
```

in this:

```
private static void CheckAndSetCollection(PropertyOrFieldAccessor accessor, object currentItem, Type propertyType, Type originalType)
	    {
            if (propertyType.GetGenericArguments().Length == 1 && typeof(IEnumerable).IsAssignableFrom(propertyType))
...
```

**Comment by JonathanMagnan** [comment]
Oh great ;)

We will look at it and try to apply the fix today.

**Comment by pvervaet** [comment]
Any luck with this Jonathan?

**Comment by JonathanMagnan** [comment]
My developer didn't success to reach this request yesterday.

I will make him start with it request today (he stars in a few hours), so you should get news very soon.

**Comment by JonathanMagnan** [comment]
Hello @pvervaet ,

The v1.9.7 has been released.

Let me know if everything works as expected.
