### ISSUE TITLE
Context filter caching issue

### ISSUE THREAD

**Issue by jrgoeblk** [zzzprojects/EntityFramework-Plus#498]
### Description
As it's documented in https://entityframework-plus.net/query-filter#context-filter, this kind of filters run into caching issued if the Set method is called. We have a huge project going on and unfortunately, we have tons of legacy code calling our DbContext.Set methods directly. It'd be very time consuming to fix this. Is there any plan in future versions to solve the context filters caching issue? Another alternative could be to provide a global switch to completely disable caching.

**Comment by JonathanMagnan** [comment]
Hello @jrgoeblk ,

At this moment, there is no plan for this feature for `EF6`. However, for `EF Core` maybe something could be done.

Let us know which version of Entity Framework you are using.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
