### ISSUE TITLE
Include Optimize Load Data To Much

### ISSUE THREAD

**Issue by bdjema** [zzzprojects/EntityFramework-Plus#500]
Hi, i use Include Optimize to replace Include from Entity Framework, but Include Optimize load much data and when serialize to JSON Object get a big data (exceeded to length).
Before use Include Optimize, it's working use Include from Entity Framework.

I was setting JSON Serialize to ignore the Loop Handling and format to Indent (Work perfectly use Include from Entity Framework)

Thanks,

bjema

**Comment by JonathanMagnan** [comment]
Hello @bdjema ,

Could you provide a runnable solution that shows this issue?

Best Regards,

Jonathan

**Comment by bdjema** [comment]
Hello Jonathan, thanks for your reply.
I'm use this include use Entity Framework like this:
`Db.PurchaseOrder.AsNoTracking()
                .Include(_ => _.ProductType)
                .Include(_ => _.Warehouse)
                .Include(_ => _.PurchaseOrderDetails)
                .Include(_ => _.PurchaseOrderApprovals)
                .Include(_ => _.PurchaseOrderDetails.Select(x=>x.Product))
                .Include(_ => _.PurchaseOrderDetails.Select(x => x.Uom))
                .Include(_ => _.PurchaseOrderApprovals.Select(x => x.User))`

And then i change it use Z Entity Framework Plus like this:
`Db.PurchaseOrder
                .IncludeOptimized(_ => _.ProductType)
                .IncludeOptimized(_ => _.Warehouse)
                .IncludeOptimized(_ => _.PurchaseOrderDetails)
                .IncludeOptimized(_ => _.PurchaseOrderApprovals)
                .IncludeOptimized(_ => _.PurchaseOrderDetails.Select(x=>x.Product))
                .IncludeOptimized(_ => _.PurchaseOrderDetails.Select(x => x.Uom))
                .IncludeOptimized(_ => _.PurchaseOrderApprovals.Select(x => x.User))`

And the data just 3 row,
but i get very big string data when serialize use Newtonsoft JSON  with setting 
ReferenceLoopHandling = ReferenceLoopHandling.Ignore and 
Formatting = Formatting.Indented

Before use Z Entity Framework Plus, it's work when serialize.

Thanks,
Bahar

**Comment by JonathanMagnan** [comment]
Hello @bdjema ,

As said, we need a runnable example if you want we look at it.

Everything seems fine in the first case with your code.
