### ISSUE TITLE
.net core 3.0 preview 7

### ISSUE THREAD

**Issue by dotnetshadow** [zzzprojects/EntityFramework-Plus#501]
### Description
A few errors when trying to use version 2.0.7

I had to manually reference 
` <PackageReference Include="Remotion.Linq" Version="2.2.0" />   `

Query trying to run:

`var cashQuery = _context.Transactions.AsNoTracking().Where(x => x.Id== Id).DeferredSum(x => x.Amount).FutureValue<decimal>();`

### Exception
`FileNotFoundException: Could not load file or assembly 'Remotion.Linq, Version=2.1.0.0, Culture=neutral, PublicKeyToken=fee00910d6e5f53b'. The system cannot find the file specified.`

Once I got past that and tried to run something I got the following:
`InvalidCastException: Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[System.Decimal]' to type 'Remotion.Linq.QueryableBase`1[System.Decimal]'.`

### Further technical details
- EF version: 3.0 preview7
- EF Plus version: 2.0.7
- Database Provider: sql server 2016

**Comment by JonathanMagnan** [comment]
Hello @dotnetshadow ,

At this moment, we only support EF version 3.0 preview5: https://www.nuget.org/packages/Z.EntityFramework.Plus.EFCore/3.0.7-preview5

However, we have made **a major** progress to be able to support preview7 last week (a lot of internal code we were used was modified).

So at this moment, we still doesn't support the preview7 but we highly believe that we will be able to release a new version next week that support it.

I will keep you updated.

Best Regards,

Jonathan

**Comment by dotnetshadow** [comment]
Great to hear, thanks for your prompt response

**Comment by dotnetshadow** [comment]
Any luck with getting this to work?

**Comment by JonathanMagnan** [comment]
Hello @dotnetshadow ,

We do our best, but unfortunately, it has been WAY harder than we thought.

At this moment, we are currently cleaning up all the code to see if we can find another issue.

Only the `Query IncludeFilter` feature doesn't work on our side due to this issue: https://github.com/aspnet/EntityFrameworkCore/issues/17150

It looks that we cannot do anymore some basic `SelectMany`. We will wait for the official answer from the EF team since I believe that's an issue on their side that they will fix.

If everything goes well during our cleanup, we might release a version with the preview 8 but throw a temporary error for the IncludeFilter features explaining the situation.

**Comment by dotnetshadow** [comment]
Thank you for all your efforts, much appreciated 
It seems the EF team might of fixed your issue with the current daily build?

**Comment by JonathanMagnan** [comment]
Yup it's probably fixed on their daily build

We will test it tomorrow and use a temporary try/catch and explain the situation in the catch about the daily build.

Anyway, we already have planned to make a release for next Monday (with or without IncludeFilter) if no more issue is found.

One of my developers is at this moment testing all our latest changes.

**Comment by JonathanMagnan** [comment]
Hello @dotnetshadow ,

The 3.0.8-preview8 has been released. As specified, this version throws an error for the IncludeFilter temporary. However, all other features should work.

Be careful, this version has now a dependency on `Z.EntityFramework.Extensions`. We will make an announcement about it this week.

Even if `EF Extensions` is a commercial library, features inside `EF Plus` stay 100% free, so don't worry with this.

**Comment by dotnetshadow** [comment]
@JonathanMagnan Thank you so much for your prompt build.

I will give it a go this week and report back if I find any issues.

**Comment by dotnetshadow** [comment]
@JonathanMagnan just updated to 3.0.8-preview8 and working well for me great job.
Thanks, appreciate your efforts

**Comment by OzBob** [comment]
Have you seen the long running open EFcore issue (https://github.com/aspnet/EntityFrameworkCore/issues/1833#issuecomment-517699346) on EF core about not having a native IncludeFilter.

Have you considered pulling together a merge request of EF+ into EF Core?

**Comment by JonathanMagnan** [comment]
Hello @OzBob ,

The goal of a third party library is to offer features the main library doesn't offer.

If they still have added the feature on their side, they probably got their reason.

**Comment by OzBob** [comment]
Fair comment. Thanks for replying and for doing a great job on EF+.

**Comment by JonathanMagnan** [comment]
Hello,

We will close this issue, if you want to follow about when preview-9 will be available I guess you can follow this issue: https://github.com/zzzprojects/EntityFramework-Plus/issues/515

We should work on it during the weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
FYI: The v3.0.9-preview9-01 has been released.

The `IncludeFilter` is now back ;)
