### ISSUE TITLE
EF Plus stays FREE but now depend on EF Extensions

### ISSUE THREAD

**Issue by JonathanMagnan** [zzzprojects/EntityFramework-Plus#510]
We have chosen to make Entity Framework Plus (EF Plus) dependent on [Entity Framework Extensions](https://entityframework-extensions.net/) (EF Extensions).

That’s a major decision since as most of you know, EF Plus is free and open-source, but EF Extensions is a commercial library. 

Don’t worry, **EF Plus will remain 100% free and will always be**. We just added a dependency to be able to continue to provide good support to our libraries.

This dependency will be added in a few weeks.

## Will EF Plus continue to evolve?
Yes, and faster!

In the past, we sometimes restricted ourselves to keep intellectual property inside EF Extensions. For example, TPC and TPT are already supported for Batch Update in EF Extensions but not yet supported in EF Plus. By adding this dependency, we can now easily add it to EF Plus.

## Why this decision?
EF Plus has been very fun to create a few years ago, don’t get me wrong. 

However, maintaining this library was not amusing at all since we had to support:
- Different versions of Entity Framework
- Different versions of Entity Framework Core itself!
- Different versions of .NET Standard
- Different versions of Database Provider
- Many weird special cases 😉

EF Plus doesn’t use public API but mostly internal API that is subject to change from a version to another and hell, EF Core proved that’s true from a preview version to another! Our code now looks so messy and need some love with a big cleanup.

EF Plus has reached a point that we cannot close our eyes anymore about the maintaining cost.

### What’s the cost of maintaining a free library?
EF Plus is indeed **FREE for you**, but that’s a money pit for our company [ZZZ Projects](https://zzzprojects.com/).

Over the past 3 years, we answered more than **500 issues** on GitHub and more than **1000 emails**. 

We invested way **more than $300,000 USD** in development and maintenance and received **less than $1,000 USD** in donations.

People usually make free library on their free time for fun and eventually stop supporting it to move to something else. However, on our side, we created EF Plus to show you can trust a free library that keeps getting supported over the years.

For example, simply upgrading EF Core 3.0 from a preview to the latest preview version took us more than 100h due to many internal methods modified. These hours have a cost as we need to pay developers to code it. (labor is not cheap in Canada)

Let be honest, adding a dependency to EF Extensions allow us to show our PAID library through our **FREE offer (EF Plus)**. So, it gives us additional reasons and motivation to keep supporting EF Plus. Also, it allows us to reduce the cost to maintain both libraries.

## Will EF Plus remain 100% Free?
YES, EF Plus continues to be **100% free and will always be!**

## Question or Comment?
Please let us know if you have any concerns.

We understand that not everyone will be happy with this decision, but we believe that’s the best decision for the future of EF Plus and our company.

**Comment by jasho** [comment]
First of all, thanks for announcing this upfront.
I have a few questions to clarify:

1. How exactly will EF Plus work "100% Free" with a dependency on a paid library. Will we be needed to have a license for the library once it becomes dependent on it even if we don't use the features from the paid library anywhere?
1. If it's not required to have a paid license - will we get the future updates even without the paid library?
1. If it is required required to have a paid license - is the [Starter edition](https://entityframework-extensions.net/pricing-limited) enough to keep the EF Plus running going forward? Or is it necessary to buy the whole [Full edition](https://entityframework-extensions.net/pricing)? We're specifically interested in using it with EF Core (the Starter edition states that it requires EF 6).

**Comment by JonathanMagnan** [comment]
Thank you @jasho for those questions.

> Will we are needed to have a license for the library

No, you will **not need a license**.

EF Plus will use methods from EF Extensions that don't require a license. For example, the `GetModel` method in EF Extensions is way more complete than the light version in EF Plus.

We will make very clear in the documentation when a license would be required. For example, to improve performance when saving audit entries.

> Will we get the future updates even without the paid library?

Yes, nothing changes. In fact, it now gives us more reason to keep EF Plus up to date.

We started to add some free features recently in EF Extensions such as `ToSelfHierarchy` and `DeleteByKey` which doesn't make sense if we have a free library.  By having this dependency, it now give us a reason to add future features such as `Query Hint` in EF Plus instead. 

By improving EF Plus, we promote at at same time EF Extensions even if that's not required to make it works. So it will give us a motivation to keep creating features in EF Plus.

Let me know if you have more questions.

**Comment by MyEidos** [comment]
As a EF Plus (free version) consumer, in which way will be  I able to check: am I using free functionality or not?

**Comment by JonathanMagnan** [comment]
> will be I able to check: am I using free functionality or not?

That's a very good question.

We will add something such as `EntityFrameworkManager.IsCommunity` (we are not sure yet about the option name). When enabling, it will throw an error right away when using a paid functionalities.

At this moment, the only paid functionalities are:
- BatchSaveChanges
- BulkSaveChanges
- BulkInsert
- BulkUpdate
- BulkMerge
- BulkDelete
- BulkSynchronize

All other methods are already free. It will be very clear in the documentation about what's free and what's not and we will make a comparative table like we did on [EF Classic](https://entityframework-classic.net/download).

**Comment by RudeySH** [comment]
Why not do it the other way around, and let the commercial library depend on the free library? As far as I know, the commercial library has all the features of the free one plus more, so it would make more sense to reverse the dependency in my opinion. This way you'll also won't exposes premium functions to free users and have them throw exceptions during runtime.

Either way, what will happen to the batch operations from EF Plus (`Update` and `Delete`) and the operations from EF Extensions ('UpdateByQuery` and `DeleteByQuery`)? Or are they the same?

**Comment by JonathanMagnan** [comment]
Hello @RudeySH ,

> Why not do it the other way around, and let the commercial library depend on the free library

It could be an alternative but cannot happen for at least 3 reasons:

---

**Intellectual Property**
EF Plus doesn't use the full potential of the `Model` or some other method at this moment (just a light version of what exists in EF Extensions).

So if EF Plus doesn't depend on EF Extensions, we will need to continue to use those light versions as we don't want to disclose some private code.

---

**Major Breaking Change**
No one like breaking change.

Forcing people using free features seeing paid features is somewhat not cool, we understand it. 

However, forcing paid customers to see free features is not cool either.

The choice of who should be impacted is an easy decision here.

---

**Marketing**
If we make EF Plus depend on EF Extensions, on the marketing side, it makes sense to hire a developer dedicated to EF Plus features, it makes sense to pay for better documentation. Every time we bring something, it now makes sense to add it to EF Plus since people at least see our paid library as well.

Otherwise, we will need to continue to add some free features directly in EFE such as: [ToSelfHierarchyList](https://entityframework-extensions.net/to-self-hierarchy-list) or [DeleteByKey](https://entityframework-extensions.net/delete-by-key) that should have been added in EF Plus

Staying like we are in the moment just makes this project a money pit and hard for myself to continue to invest in it.

Ask to yourself: Will you invest 100k of your own money in the next year to improve EF Plus with almost no return on investment? Without a doubt, no one will answer yes to this question. I did it in the past 3 years, but I don't wanna longer unless the ROI makes sense.

---

As this is a big decision, I'm trying to be 100% honest and transparent in all my answers.

I hope you will understand this decision through it.

**Comment by ZarPeter** [comment]
Hey sorry for reopening this, but I have an issue/question.
I use Z.EntityFramework.Plus.EFCore in my project. It says it is free and always will be. Still I have to download the latest version of the library every month in order to have my application working.
In the docs for the Extentions-library (https://entityframework-extensions.net/trial-period-expired-exception) I can see that this is due to no "free" license being available.
I assume this is the intended behavior in order to gently nudge more people into buying the full package? ( I am totally fine with this by the way!)
If not am I doing something wrong?

**Comment by JonathanMagnan** [comment]
Hello @ZarPeter ,

No that's not intended to force people to download the latest version of EFE every month. If that's the case, that's for sure a mistake and we will fix it.

Are you using one feature such as `BulkSaveChanges` or `BulkInsert` which are not free?

I just made the test with a 5 months old version and didn't get any error when using `DeleteFromQuery`.

Do you have the full stack trace or know on which method our library is asking for the trial?

Best Regards,

Jon

**Comment by ZarPeter** [comment]
Hey @JonathanMagnan, 
many thanks for your reply! I just double-checked and I am 100% sure we are not using either feature.
We only use following operations:
DeleteFromQueryAsync
SingleInsertAsync
UpdateFromQueryAsync

Or is there any "hidden" usage of BulkSaveChanges or BulkInsert in there that I am not aware of?

Best Regards,

Robert

**Comment by JonathanMagnan** [comment]
The issue is caused by this method: `SingleInsertAsync`.

We never announced it as a free or paid feature and it uses the same logic as `BulkInsertAsync` so, therefore, require a license at this moment (so currently a paid one).

I will speak with my team next week about what we should do with this situation and if we should make all `single[Action]` method free.

**Comment by JonathanMagnan** [comment]
Hello @ZarPeter ,

Just to let you know, starting from the v5.1.10, all `Single[Action]` methods are now free to use (will only work with one entity, but you can call the method multiple times).

We will add some documentation about it very soon and announce that since versions released in 2021, those methods are free.

If you still have a problem, please open a new issue.

Best Regards,

Jon

**Comment by ZarPeter** [comment]
Hello Jon,

many thanks for your reply and hard work! I am grateful for the news and am looking forward to see the change coming. All the best for you and your kin in 2021!

Best Regards,

ZarPeter

Von: Jonathan Magnan <notifications@github.com>
Gesendet: Mittwoch, 30. Dezember 2020 19:38
An: zzzprojects/EntityFramework-Plus <EntityFramework-Plus@noreply.github.com>
Cc: ZarPeter <RobertSchlaeger@hotmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [zzzprojects/EntityFramework-Plus] EF Plus stays FREE but now depend on EF Extensions (#510)


Hello @ZarPeter<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FZarPeter&data=04%7C01%7C%7C811c4900362d4396760008d8acf1fc33%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637449502604382500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lpOHAvwKGy2Y86jsDbwGOjF3G5ltn7A16qLFHoIMz9U%3D&reserved=0> ,

Just to let you know, starting from the v5.1.10, all Single[Action] methods are now free to use (will only work with one entity, but you can call the method multiple times).

We will add some documentation about it very soon and announce that since versions released in 2021, those methods are free.

If you still have a problem, please open a new issue.

Best Regards,

Jon

-

**Comment by cwilby** [comment]
This thread convinced me to write stored procedures with user-defined table types instead of installing this package.

I'm not confident paying for the software would alleviate the likely future bugs from having to account for all of this.
