### ISSUE TITLE
Unable to cast object when use EntityFramework InMemoryDatabase

### ISSUE THREAD

**Issue by diegobrum** [zzzprojects/EntityFramework-Plus#52]
Hi!

When I configure EF Core to use InMemoryDatabase and use FromCache(), throws **"Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.Internal.InMemoryQueryContext' to type 'Microsoft.EntityFrameworkCore.Query.RelationalQueryContext'."**

In class **[CreateCommand](https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/Z.EntityFramework.Plus.EFCore/_Internal/EFCore/IQueryable%60/CreateCommand.cs)**, line **36:** (_queryContext = (RelationalQueryContext)queryContextFactory.Create();_)

Use sample:

```csharp
// In unit test class constructor
var serviceProvider = new ServiceCollection()
	.AddEntityFrameworkInMemoryDatabase()
	.BuildServiceProvider();

var builder = new DbContextOptionsBuilder<MyContext>();

builder
	.UseInMemoryDatabase()
	.UseInternalServiceProvider(serviceProvider);
	
builder
	.UseInMemoryDatabase()
	.UseInternalServiceProvider(serviceProvider);

contextInstance = new MyContext(builder.Options);
	
// In unit test
var list = contextInstance
	.Table
	.Where(q => q.IsActive)
	.FromCache() // <- Error happens here
	.ToList();

return list.FirstOrDefault(q => q.Id == requestedId);
```

**Comment by zzzprojects** [comment]
Thank you for reporting,

We will try to fix this issue this weekend. 

The CreateCommand is used to generate a unique key. We will try to see if we can generate a unique key for InMemoryDatabase from the expression.

Be careful, not all features in this library will work with InMemoryDatabase.

**Comment by zzzprojects** [comment]
Hello @diegobrum ,

Currently, by default, the cache key can only be generated from RelationDatabase query. However, we want to change this in the future.

Meanwhile, we added two new properties to allow to customize the cache key generation

**CacheKeyFactory**
Allow to create yourself the key from the queriable and tags provided.
```csharp
QueryCacheManager.CacheKeyFactory = (queryable, strings) => queryable.ToString() + string.Join(";", strings);
```

**ForceFirstTagAsCacheKey**
Allow to use the first tag as cache key.
```csharp
QueryCacheManager.ForceFirstTagAsCacheKey = true;
var list = ctx.Entity_Basics.Where(x => x.ColumnInt < value).FromCache("MyCacheKey", "tag1", "tag2");
```

**Comment by diegobrum** [comment]
Hi!
I think that **CacheKeyFactory** feature will work to me ^^
Thanks a lot!

**Comment by zzzprojects** [comment]
Closing Comment: Confirmed it worked.
