### ISSUE TITLE
Translation regression since updating to EF Core 3

### ISSUE THREAD

**Issue by Looooooka** [zzzprojects/EntityFramework-Plus#525]
### Description
Just Updated to EF Core 3 and I get the following exception in a query that worked fine before:
When called from 'VisitLambda', rewriting a node of type 'System.Linq.Expressions.ParameterExpression' must return a non-null value of the same type. Alternatively, override 'VisitLambda' and change it to not visit children of this type.

the query that doesn't work:

                                var queryResult = context.data_Transactions.Where(ct => ct.TransactionID == info.Info.TransactionId).Update(cx => new data_Transactions()
                                {
                                    Notification = info.Info.NotificationStatus,
                                    NotificationDateTime = info.Info.NotificationDateTime,
                                    NotificationRetryCount = context.data_Transactions.Where(ct => ct.TransactionID == info.Info.TransactionId).Select(ct2 => ct2.NotificationRetryCount + 1).First(),
                                    //NotificationReturnMessage = notificationReturnMessage
                                });

to make it work i have to get rid of the "NotificationRetryCount = context..... "
part.
So somehow evaluation and translating that part of the query no longer works

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).
"System.InvalidOperationException: When called from 'VisitLambda', rewriting a node of type 'System.Linq.Expressions.ParameterExpression' must return a non-null value of the same type. Alternatively, override 'VisitLambda' and change it to not visit children of this type.\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](T node, String callerName)\r\n   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitParameters(ExpressionVisitor visitor, IParameterProvider nodes, String callerName)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)\r\n   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)\r\n   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.Visit(Expression expression)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)\r\n   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)\r\n   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.Visit(Exp
ression expression)\r\n   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)\r\n   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.Visit(Expression expression)\r\n   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)\r\n   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)\r\n   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at Microsoft.EntityFrameworkCore
.Query.ReplacingExpressionVisitor.Visit(Expression expression)\r\n   at Microsoft.EntityFrameworkCore.Query.ReplacingExpressionVisitor.Replace(Expression original, Expression replacement, Expression tree)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.RewriteAndVisitLambda(LambdaExpression lambda, EntityReferenceExpression source)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitSelectMethodCall(MethodCallExpression methodCallExpression)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)\r\n   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)\r\n   at Microsoft.EntityFrameworkCore.Query.Internal.EntityEqualityRewritingExpressionVisitor.Rewrite(Expression expression)\r\n   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)\r\n   at .(IQu
eryable , RelationalQueryContext& )\r\n   at Z.EntityFramework.Plus.BatchUpdate.GetInnerValues[T](IQueryable`1 query, Expression`1 updateFactory, IEntityType entity)\r\n   at Z.EntityFramework.Plus.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)\r\n   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)\r\n   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)\r\n   at MC2API.Shared.Implementation.TransactionNotificationFunctions`6.SendNotification(LoggingServiceOptions serviceOptions, NotificationPoster poster, SendNotificationInfo info, Int32 notificationRetryDelaySeconds) in ***"

**Comment by Looooooka** [comment]
NotificationRetryCount =  cx.NotificationRetryCount +1,
fixes it...but i figure that if I wanted to get that result from some other table I'd probably have the same problem(which didn't exist before) so I'm gonna leave this open

**Comment by JonathanMagnan** [comment]
Hello @Looooooka ,

I don't think we can do anything here.

We take the query generated by Entity Framework. So if the latest version has some issue to generate it, we are unfortunately also limited by it.

Unless you believe we can do something, I believe we should probably close this issue since nothing will be done on it from what I understand.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by Looooooka** [comment]
Closing issue as advised.
