### ISSUE TITLE
SaveChanges.cs.bak (and SaveChanges - Copy (2).cs.bak) strikes back!

### ISSUE THREAD

**Issue by Kir-Antipov** [zzzprojects/EntityFramework-Plus#526]
### Description
So, there is nothing special to describe here: the same problem as in #345 ¯\\_(ツ)_/¯

New NuGets contain these extra lines in their .nuspec, which lead to the addition of “undeletable” files to the project:

```xml
<contentFiles>
  <files include="any/netstandard2.0/SaveChanges.cs.bak" buildAction="Content" />
  <files include="any/netstandard2.0/SaveChanges - Copy (2).cs.bak" buildAction="Content" />
</contentFiles>
```

**Comment by JonathanMagnan** [comment]
Hello @Kir-Antipov ,

Took us a lot of time but file are now gone from the project. Let hope that's forever this time.

We also fixed a few things like EF Core in 1.3 that's no longer compatible with the new code.
