### ISSUE TITLE
HasConversion not used when executing BatchUpdate

### ISSUE THREAD

**Issue by gbilodeau** [zzzprojects/EntityFramework-Plus#528]
When executing a Update where a property of the entity has an "HasConversion", the conversion is not happening.

Repro code:

```
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Console;
using Z.EntityFramework.Plus;

namespace BatchUpdateRepro
{
    class Program
    {
        [Obsolete]
        static void Main(string[] args)
        {
            var connectionString = "{your_connection_string}";
            var options = new DbContextOptionsBuilder<ExampleDbContext>()
                .UseLoggerFactory(new LoggerFactory(new[] {
                    new ConsoleLoggerProvider((_, level) => level >= Microsoft.Extensions.Logging.LogLevel.Debug, true)
                }))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors()
                .UseNpgsql(connectionString, b => b.EnableRetryOnFailure())
                .Options;

            var rnd = new Random();

            // adding new entities: success
            using (var dbContext = new ExampleDbContext(options))
            {
                var examples = new[]
                {
                    new Example { Id = rnd.Next(), Value = GenerateGuid() },
                    new Example { Id = rnd.Next(), Value = GenerateGuid() },
                    new Example { Id = rnd.Next(), Value = GenerateGuid() }
                };

                dbContext.Examples.AddRange(examples);
                dbContext.SaveChanges();
            }

            // loading entity and updating it: success
            using (var dbContext = new ExampleDbContext(options))
            {
                var example = dbContext.Examples.First();
                example.Value = GenerateGuid();

                dbContext.SaveChanges();
            }

            // bulk updating entities: error
            using (var dbContext = new ExampleDbContext(options))
            {
                var value = GenerateGuid();

                // Npgsql.PostgresException: 42804: column "value" is of type uuid but expression is of type text
                dbContext.Examples.Where(e => e.Id > 0).Update(e => new Example { Value = value });
            }
        }

        private static string GenerateGuid()
        {
            return Guid.NewGuid().ToString("N").ToUpperInvariant();
        }
    }

    public class ExampleDbContext : DbContext
    {
        private readonly ValueConverter<string, Guid> _guidConverter = new ValueConverter<string, Guid>(v => new Guid(v), v => v.ToString("N").ToUpperInvariant());
        public DbSet<Example> Examples { get; set; }

        public ExampleDbContext(DbContextOptions<ExampleDbContext> options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.HasDefaultSchema("efplus");

            var model = builder.Entity<Example>();
            model.ToTable("example");
            model.HasKey(e => e.Id);
            model.Property(e => e.Id).HasColumnName("id");
            model.Property(e => e.Value).HasColumnName("value").HasConversion(_guidConverter);
        }
    }

    public class Example
    {
        public int Id { get; set; }
        public string Value { get; set; }
    }
}

```

Database table:

```
    create schema efplus
    create table efplus.example
    (
      id int not null primary key,
      value uuid null
    )
```

When executing the code for the last context, the string is not converted to a uuid and the database is rejecting the request with error: "Npgsql.PostgresException: 42804: column "value" is of type uuid but expression is of type text"

Thank you.

[EFPlusRepro.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/3683287/EFPlusRepro.zip)

**Comment by gbilodeau** [comment]
An exception is also thrown when a conversion should be done in the where clause:

```
using (var dbContext = new ExampleDbContext(options))
{
    var value = dbContext.Examples.First().Value;
    var newValue = GenerateGuid();

    // System.InvalidCastException: Can't write CLR type System.String with handler type UuidHandler
    dbContext.Examples.Where(e => e.Value == value).Update(e => new Example { Value = newValue });
}

```

**Comment by JonathanMagnan** [comment]
Hello @gbilodeau ,

You are right. The `Batch Update` currently doesn't support value conversion.

We will look at the difficulty to add the support to it.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @gbilodeau ,

A new version of EF Extensions has been released with this fix: https://www.nuget.org/packages/Z.EntityFramework.Extensions.EFCore/2.7.8

The `DeleteFromQuery` and `UpdateFromQuery` method in this library is free. As most people already know by now, very soon EF Plus will have a dependency to EF Extensions (See [discussion](https://github.com/zzzprojects/EntityFramework-Plus/issues/510)) and EF Plus `Delete` and `Update` method will call under the hood those `DeleteFromQuery` and `UpdateFromQuery` so that's why we didn't add the code on EF Plus since everything was already coded to make this request on EF Extensions.

Let me know if that's working as expected.

Best Regards,

Jonathan

**Comment by gbilodeau** [comment]
Merci, that was quick! We will look into this today and let you know how it works out.

**Comment by JonathanMagnan** [comment]
Awesome!

Looking forward to hearing from you!

Jon

**Comment by JonathanMagnan** [comment]
Hello @gbilodeau,

A simple follow up to see if you are satisfied with the latest version of EF Extensions!

Don't hesitate to contact us for questions, issues or feedback!

Looking forward to hearing from you, 

Jon

**Comment by gbilodeau** [comment]
Hi, sorry we didn't have time to test this as we've run into some production issues. As soon as we're done with this, I'll post back here. Thanks for following up!

**Comment by JonathanMagnan** [comment]
Hello @gbilodeau 

No worries! We all have unexpected tasks! 

Looking forward to hearing from you!

Jon

**Comment by JonathanMagnan** [comment]
Hello @gbilodeau,

A quick follow up to see if you are still satisfied with the latest version of EF Extensions. 

Looking forward to hearing your feedback.

Best regards,

Jon

**Comment by gbilodeau** [comment]
Works as expected, thank you!
