### ISSUE TITLE
Audit table - primary key (int)

### ISSUE THREAD

**Issue by k-schneider** [zzzprojects/EntityFramework-Plus#53]
May I ask why int was used instead of bigint/long?  It seems to me that a LOT of data can be generated very fast and that 2 billion could be reached quite quickly in a busy system (at which point this library would start failing).

Thanks.

**Comment by zzzprojects** [comment]
Thank you for this suggestion.

We agree BigInt should have been used instead.

Since it's a breaking change, we will need to evaluate if we prefer to code & release this suggestion once we will re-write the library (Milestone 2.0) or right now.

**Comment by k-schneider** [comment]
Ok, thanks for the response.

**Comment by zzzprojects** [comment]
I will close this issue to make easier to track other request. The next major version will for sure use a BigInt instead of a Int
