### ISSUE TITLE
"The destination column could not be found" on collection types

### ISSUE THREAD

**Issue by burak-tarhanli** [zzzprojects/EntityFramework-Plus#535]
Hi. 
When I try this simple code, I'm getting this error: "**The destination column could not be found:Categories**".
```c#
db.Posts.Include("Categories")
.Where(p => p.ID == 1)
.Update(p => new Post()
{
  Categories = Enumerable.Range(5, 3).Select(i =>
               new PostCategory() { ID = i })
               .ToList()
});
```
I'm using EF6. And the other classes are like these:
```c#
public class Post
{
  public int ID { get; set; }
  public string Title { get; set; }
  public virtual ICollection<PostCategory> Categories { get; set; }
}
```
```c#
public class PostCategory
{
  public int ID { get; set; }
  public string Name { get; set; }
  public virtual ICollection<Post> Posts { get; set; }
}
```
I'm just trying delete a Post's existing categories and replacing them with new ones by giving new category ID's.
I also readed these:
#315 
#238 
Can you please help?

**Comment by JonathanMagnan** [comment]
Hello @burak-tarhanli ,

What you currently trying to do is simply not supported by our library. You could update column from Post table but you cannot delete and insert a list of new/existing categories (related table).

If you wish to make some operation in Bulk, I suggest our paid libraries: [EF Extensions](https://entityframework-extensions.net/). We will be happy to help you make it works.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
