### ISSUE TITLE
Future Queries Causes Intermittent RelationalShapedQueryCompilingExpressionVisitor Exceptions

### ISSUE THREAD

**Issue by arex388** [zzzprojects/EntityFramework-Plus#536]
### Description

Rather than duplicating content, please read the description at issue [#18145 on the Entity Framework Core repo](https://github.com/aspnet/EntityFrameworkCore/issues/18145).

### Exception

The following issue began to occur after upgrading to .NET Core 3.0 and EF Core 3.0 from 2.2.

```
ArgumentException: Expression of type 'Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor+QueryingEnumerable`1[System.String]' cannot be used for return type 'System.String'

System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, ref Expression body, ReadOnlyCollection<ParameterExpression> parameters, string paramName)
System.Linq.Expressions.Expression.Lambda<TDelegate>(Expression body, string name, bool tailCall, IEnumerable<ParameterExpression> parameters)
System.Linq.Expressions.Expression.Lambda<TDelegate>(Expression body, bool tailCall, IEnumerable<ParameterExpression> parameters)
Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor<TResult>(Expression query)
Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery<TResult>(Expression query, bool async)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore<TResult>(IDatabase database, Expression query, IModel model, bool async)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler+<>c__DisplayClass9_0<TResult>.<Execute>b__0()
Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore<TFunc>(object cacheKey, Func<Func<QueryContext, TFunc>> compiler)
Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery<TResult>(object cacheKey, Func<Func<QueryContext, TResult>> compiler)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute<TResult>(Expression query)
Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute<TResult>(Expression expression)
Z.EntityFramework.Plus.QueryFutureValue<TResult>.GetResultDirectly()
Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueries()
Z.EntityFramework.Plus.QueryFutureValue<TResult>.get_Value()
lambda_method(Closure , Projection , View , ResolutionContext )

AutoMapperMappingException: Error mapping types. Mapping types: Projection -> View REDACTED.Web.Admin.Features.Countries.Add+Projection -> REDACTED.Web.Admin.Features.Countries.Add+View Type Map configuration: Projection -> View REDACTED.Web.Admin.Features.Countries.Add+Projection -> REDACTED.Web.Admin.Features.Countries.Add+View Destination Member: Country

lambda_method(Closure , Projection , View , ResolutionContext )
lambda_method(Closure , object , object , ResolutionContext )
AutoMapper.Mapper.Map<TDestination>(object source)
REDACTED.Web.AsyncProjectionHandlerBase<TRequest, TProjection, TResult>.GetResultAsync(TRequest request) in AsyncProjectionHanderlBase`TRequest`TProjection`TResult.cs
+
			var result = Mapper.Map<TResult>(projection);
REDACTED.Web.AsyncProjectionHandlerBase<TRequest, TProjection, TResult>.Handle(TRequest request, CancellationToken cancellationToken) in AsyncProjectionHanderlBase`TRequest`TProjection`TResult.cs
+
			return await GetResultAsync(request);
MediatR.Pipeline.RequestPostProcessorBehavior<TRequest, TResponse>.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
MediatR.Pipeline.RequestPreProcessorBehavior<TRequest, TResponse>.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
REDACTED.Web.Admin.Features.Countries.CountriesController.Add() in CountriesController.cs
+
			var view = await Mediator.Send(new Add.ViewQuery());
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask<IActionResult> actionResultValueTask)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
REDACTED.Web.ApplicationUserMiddleware.InvokeAsync(HttpContext context, IApplicationUserServices services) in ApplicationUserMiddleware.cs
+
			await Next(context);
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Arex388.AspNetCore.HtmlMinifierMiddleware.InvokeAsync(HttpContext context)
Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in MiniProfilerMiddleware.cs
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Fiddle or Project

It is frankly not possible for me to send any project files. Creating a minimal solution does not trigger the issue, but it is ever present in the real solution. Sending the solution also would require you to setup AWS credentials with PowerShell, and import an SSL certificate for Data Protection APIs. I can't really give you AWS credentials or the SSL certificate...

Would it be possible to do a private remote session with Team Viewer, AnyDesk, or something, anything?

### Further technical details

- EF version: 3.0
- EF Plus version: 3.0.13
- Database Provider: SQL Server

Halp please! There's some sort of an incompatibility with EF Core 3.0 and EF Plus and it's making my life a nightmare after I upgraded to it. Going back to 2.2 is no longer an option either.

**Comment by arex388** [comment]
I just noticed that it's saying `QueryingEnumerable'1[System.String]` which to me implies that I requested a `QueryFutureEnumerable<string>` when I in-fact requested a `QueryFutureValue<string>`. Not sure if the two share code somewhere and it's not translating correctly?

**Comment by JonathanMagnan** [comment]
Hello @arex388 ,

I don't think a remote session will help either. If you are not able to reproduce the issue in a minimal solution, all we will do is pressing `F5` to execute the code. We will not know either when the bug is coming.

Is this possible for you to try the same query without AutoMapper? We can see that you currently use it because of this exception `AutoMapperMappingException`.

If you still get the error (which will probably happen), is it possible for you to share your project here: info@zzzprojects.com, even if we cannot run it due to setup difficulty, we might find some useful information that could lead us to reproduce it. Sharing your minimal solution will be also very helpful even if that doesn't throw the error, at least we will not have to start from scratch ;)

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by arex388** [comment]
Hey @JonathanMagnan,

I tried it without AutoMapper and as you said I still got the error. I'm sending two RAR files with the example solution and the real solution. I don't care what happens with the example solution, but please keep the real solution as confidential as possible.

The offending class (that I've tested with) is in the Admin project in Features > Countries > Add. I've left it as is without AutoMapper.

I appreciate you taking the time to help me and I look forward to any discoveries you might have. Thanks!

P.S. Again, as a reference, this worked in .NET Core 2.2 just fine.

**Comment by JonathanMagnan** [comment]
Let me know when your files will be sent.

Don't worry, we keep everything very confidential.

**Comment by arex388** [comment]
Sorry, I had to step away for a bit, and then Gmail was being rude with the attachments. Anyway, it's sent.

**Comment by arex388** [comment]
I have some more clues to share. I can consistently trigger the exception if I do only a single `FutureValue` call. If I happen to have additional `Future` calls along with the `FutureValue` then everything works correctly.

This explains why it was not working before. In the solution I sent you, the `Device.Edit` class has multiple future calls and it had no issues, but the `Countries.Add` class only had a single future (value) call and was throwing the exception.

**Comment by JonathanMagnan** [comment]
Hello @arex388 ,

The v3.0.14 has been released.

Could you try it and let us know if everything now works as expected.

We will look next week if a similar issue can happen in some other methods. There is a high chance since the `provider.Execute` method does no longer return the same result as before (was a `string` but now a `Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor+QueryingEnumerable'1[System.String]` like the error message said.

**Comment by arex388** [comment]
Hey @JonathanMagnan,

Thanks for getting back to me so quickly. I have updated to 3.0.14 and I can confirm that the problem has been resolved.

A big thank you to you and your developers!

**Comment by JonathanMagnan** [comment]
Awesome! 

We are glad everything is working out for you!

Don't hesitate to contact us for questions, issues or feedback!

Best regards, 

jon

**Comment by arex388** [comment]
Will do, thanks again!
