### ISSUE TITLE
Comparing Query Cache to EFCache - can we get best of both worlds?

### ISSUE THREAD

**Issue by RudeySH** [zzzprojects/EntityFramework-Plus#541]
Query Cache is great. [EFCache](https://github.com/moozzyk/EFCache) is great, too.

The thing that EFCache has going for it, is that it works unobtrusive. There's no `FromCache`, query results will automatically be cached. It also automatically expires cache when you create, update or delete (CUD) entities in any table using DbContext, which is really awesome if you think about it.

However, EFCache does not have cache tags unlike Query Cache. In my opinion Query Cache is a clear winner here, because cache tags allow for much more control over when cache gets expired. In theory, you could mimic EFCache's CUD-expiry feature by simply using table names as cache tags, but you would have to do it manually, everywhere. There's one big caveat when doing this however...

EFCache's killer feature is that cache gets expired automatically **when the transaction completes**. I think it uses a transaction interceptor to achieve this. Consider the following code that uses Batch Update and Query Cache:

```
public void UpdateAllUsers()
{
    context.Users.Update(...);
    QueryCacheManager.ExpireTag("users");
}
```

What if this method is executed within a transaction? The cache is expired prematurely. It's even possible that another thread runs a query that will populate the "users" cache again before this transaction completes, leaving the cache in an inconsistent state. Suddenly, I need my code to know about it's parent context and let it deal with transactions. With EFCache, I don't need to worry about that.

Where I'm going with this: both libraries have their pros and cons. Query Cache seems to be ahead of EFCache, because it has better features and seems to be actively maintained. Could you consider using some ideas from EFCache to make Query Cache even better? Namely it's support for transactions.

**Comment by JonathanMagnan** [comment]
Hello @RudeySH ,

We will look at it and propose to you something.

Is this for EF6 or EF Core? (If we do something, we will do probably both but we will probably start with a prototype on only one before doing the other).

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by RudeySH** [comment]
Good question. I'm currently still on EF6 in all my projects, so I'd prefer EF6.

**Comment by JonathanMagnan** [comment]
Hello @RudeySH ,

Just to let you know, we started to investigate this request and already took a few decisions:
- This feature will be optional (will be automatically enabled by adding the interceptor)
- Like `EFCache`, we will try it by using the Transaction Interceptor. We thought first to make people override the `SaveChanges` method but it might be "too complex" this way since people have a few methods to override so they might miss one.
- Like `EFCache`, all list using the set will be expired. We thought first about expiring lists that contain one item that has been modified or deleted but then some list would be invalid since they have not been refreshed.

TBD:
- We are not sure yet the best way to support query that uses the `Include` method. However, we believe `EFCache` already support it when visiting the `CommandTree`, so we will look at it.

**Comment by JonathanMagnan** [comment]
Hello @RudeySH ,

The v1.12.1 has been finally released.

## QueryCacheManager.IsAutoExpireCacheEnabled

Online Example: https://dotnetfiddle.net/3WHMGk

```csharp
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
	QueryCacheManager.IsAutoExpireCacheEnabled = true;
}
```

We took a different approach in the code then `EFCache` but so far so good in our unit tests.

It's currently compatible with `SaveChanges`. We will work next week to make it compatible with `BatchSaveChanges` and `BulkSaveChanges` from EF Extensions.

Let me know if that works as expected. Meanwhile, we will start to look for EF Core

**Comment by nilesh-shah** [comment]
@JonathanMagnan I am using standard `EF6` with `EFCache (L2 cache)` (Internally it is `Redis`). Recently I have got a use case where I would like to do bulk updates/deletes to database using `EF6`. For that I am planning to use `EF-Plus`. However, by reading this thread, I am still not clear if I do not use "`QueryCache`" way, would `EF-Plus` fallback to default `L2 cache` configured with `EF6`? If not, can it be achieved somehow and if yes, can you please share some example with me here?

Many Thanks.
Nilesh

**Comment by JonathanMagnan** [comment]
Hello @nilesh-shah ,

By default, `EF Plus` use the memory cache: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryCache.Shared/QueryCacheManager.cs#L41

It's possible to use a `Redis` cache or another cache by setting the `Cache` value
```csharp
var connectionMultiplexer =  ConnectionMultiplexer.Connect("127.0.0.1:6379,allowAdmin=true");
QueryCacheManager.Cache = new RedisObjectCache(connectionMultiplexer.GetDatabase(), Newtonsoft.Json.JsonConvert.SerializeObject, (type, s) => Newtonsoft.Json.JsonConvert.DeserializeObject(s, type));
```

> I am still not clear if I do not use "QueryCache" way, would EF-Plus fallback to default L2 cache configured with EF6

Yes, it will use whatever is already configured if you do not use our cache. We just added extension methods, we didn't modified how Entity Framework work.

Best Regards,

Jon

**Comment by nilesh-shah** [comment]
@JonathanMagnan Thank you very much for your prompt response. Very much appreciate the same.
Just to double check before I start integrating `EF Plus` in my application test, It means that if I do not configure any cache for `EF Plus`, it will automatically use whatever is configured for `EF`.. This is what I interpreted.. Hope we are on same page here..

Thanks again for helping me here understand small nuances.

Best Regards,
Nilesh

**Comment by JonathanMagnan** [comment]
Exactly @nilesh-shah ,

Our cache is only used when you use the `FromCache` extension methods.

Otherwise, this is still Entity Framework and we do not change how it works.
