### ISSUE TITLE
Audit - Cascading Delete

### ISSUE THREAD

**Issue by joejarvis64** [zzzprojects/EntityFramework-Plus#55]
I have found that when I delete a parent object that has a child list (1 to many relationship), EF deletes the parent and all of the children because I set it up to cascade delete all of the child objects.  However the only thing that is written to the audit tables as a EntityDeleted is the parent object (no child objects).  Given this, I would never actually be able to recreate the object from the audit trail or see what it was prior to deletion.

The only way I can see to get around this is to add code that will manually delete all of those child rows.  I can do that but it seems like a lot of extra coding to handle this one case.

Is there a better way to deal with this scenario?

**Comment by zzzprojects** [comment]
Hello @joejarvis64,

Unfortunately, cascade delete happen on database side, so there is nothing we can do here.

I have answered a similar question this week on StackOverflow: [EF Core audits for cascade deleted values](http://stackoverflow.com/a/39799802/5619143)

> Cascade Delete happen on the database side. Entity Framework doesn't need to be aware which entity will be deleted.
> 
> Entity Framework only tracks changes and delete the base object.
> 
> Edit: Answer subquestions
> 
> You are right. I'm the owner of EF+. 
> 
> Technically, a library could handle this, but this will come with a severe performance drawback. I'm not aware of any feature or library which handle the cascade delete scenario for auditing.
> 
> Suggestion?
> 
> There is some suggestion, but I'm pretty sure you will not like any of them, and I don't either recommend them for performance reason:
> 
> •Do not use cascade delete (force you also retrieving/deleting related entities)
> 
> 
> •Create ON DELETE Trigger and Log at database side.
> 
> 
> I don't think a good solution exists for this scenario.
> 

Unfortunately, we have no plan currently to support cascade delete for our auditing library since it may cause some performance issue (retrieving all related entities!)

Let me know If I answered correctly to your question.

**Comment by joejarvis64** [comment]
Thanks for the reply.

Maybe another option would be to recreate the object and all of its children from the audit trail?  It seems like all of the info would be there so it "should" be possible.  Although I could see that getting a little complex.

**Comment by zzzprojects** [comment]
Yes, it can be complex very fast.

If you have by example 100 parents, how to you retrieve all child value efficiently for each of them? And if the child also has some cascade delete enabled on their child's...

Unless the database size is very small, this features will become in no time a performance bottleneck.

**Comment by zzzprojects** [comment]
Hello @joejarvis64 ,

I will close this issue since it's not really related to our library but how cascade delete work (on database side). I don't think either we will ever support it.

Let me know if you still have some questions
