### ISSUE TITLE
How to include siblings and nephews with Include/ThenInclude

### ISSUE THREAD

**Issue by randellhodges** [zzzprojects/EntityFramework-Plus#550]
How would I include the data where I have the `??` below? If I try to use `Include` the value is `user` and not the previous value from `ThenInclude`.

```
context.User
	   .Include(user => user.Layouts)
			.ThenInclude(layout => layout.Pages)
				.??(page => page.Something)	
				.??(page => page.SomethingElse)
				.ThenInclude(page => page.Configuration)
					.??(configuration => configuration.Prop1)
					.??(configuration => configuration.Prop2)
					.ThenInclude(configuration => configuration.Colors)
```

**Comment by JonathanMagnan** [comment]
Hello @randellhodges ,

How this question is related to our library EF Plus? Perhaps you are in the wrong forum

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by randellhodges** [comment]
Is ThenInclude yours or a EF core function? I was playing with both it and IncludeFilter. I had the same question with IncludeFilter but I found that if I basically duplicated it and then changed the one thing, it worked. Unwieldy, but works.

**Comment by JonathanMagnan** [comment]
Nope, `ThenInclude` is part of `EF Core`.

We added it in [EF Classic](https://entityframework-classic.net/then-include) but I don't think this is the one you are looking for.

The `IncludeFilter` still doesn't have the `ThenIncludeFilter` but we hope to find eventually the time to code it.

**Comment by randellhodges** [comment]
Thanks. I am able to use IncludeFilter but it is cumbersome with siblings. I'll check out the documentation for ThenIncludeFilter to see if, when it gets into EF Core that will help. 

When I get a chance, I'll post a more complete example of what I'm trying to do.
