### ISSUE TITLE
Chained IncludeFilter invalid result for last level

### ISSUE THREAD

**Issue by omatrot** [zzzprojects/EntityFramework-Plus#556]
### Description
Loading a graph of objects with chained IncludeFilter does not work for last level.

An AlertDetail object has a TrackedVehicule which as an Array of FleetDetail which has a Fleet.

So were are dealing with 1-1-n-1 relationships.

The following query:

```
context.AlertDetailsDbSet
.IncludeFilter(ad => ad.TrackedVehicule)
.IncludeFilter(ad => ad.TrackedVehicule.FleetDetail.Where(fd => fd.RowEnabled == true))
.IncludeFilter(ad => ad.TrackedVehicule.FleetDetail.Select(u => u.Fleet).Where(f => f.RowEnabled == true && f.CompanyId == companyId))
```
Brings back all entities in the graph except the last one **Fleet**. I've removed the last restriction to make sure that it was not the problem.

I think that it might be a usage issue on my side but I can't figure it out right now.

### Further technical details
- EF version: 3.1
- EF Plus version: Core 3.0.24
- Database Provider: MS SQL

**Comment by JonathanMagnan** [comment]
Hello @omatrot ,

Perhaps that's not the problem but you must continue to chain where clause as well if you re-use the navigation properties.

You are missing the `.Where(fd => fd.RowEnabled == true)` part in your third IncludeFilter

```csharp
context.AlertDetailsDbSet
.IncludeFilter(ad => ad.TrackedVehicule)
.IncludeFilter(ad => ad.TrackedVehicule.FleetDetail.Where(fd => fd.RowEnabled == true))
.IncludeFilter(ad => ad.TrackedVehicule.FleetDetail.Where(fd => fd.RowEnabled == true).Select(u => u.Fleet).Where(f => f.RowEnabled == true && f.CompanyId == companyId))
```

If you still have the issue, please try to provide a project sample or Fiddle that shows the issue. We already have a unit test with multiple Include level which works fine.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by omatrot** [comment]
I still have the issue. A dotnet fiddle is on its way.

**Comment by omatrot** [comment]
I have a problem with a wrong column used as a foreign key which explains the behavior I'm experiencing. This has nothing to to with EFPlus. Closing.
