### ISSUE TITLE
IncludeWhere feature ? :)

### ISSUE THREAD

**Issue by mRmEEeZ** [zzzprojects/EntityFramework-Plus#562]
### Description
Feature that i think is better for data grid binding to database context
that will include navigation under a condition

something like 

`dbContext.Set<TModel>().IncludeWhere(a=>a.Property,comparableValue,ignoreCondition).ToList()`
`dbContext.Set<TModel>().IncludeWhereByPath("Property",comparableValue,ignoreCondition).ToList()`

**Comment by JonathanMagnan** [comment]
Hello @mRmEEeZ ,

What's the `comparableValue`?

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @mRmEEeZ 

Since our last conversation, we haven't heard from you. 

as mentioned in my previous answer, What's the comparableValue?

Looking forward to hearing from you, 

Jon
