### ISSUE TITLE
How to use WhereDynamic with EF.Function.ILike

### ISSUE THREAD

**Issue by kenzouno1** [zzzprojects/EntityFramework-Plus#564]
### Description
I have a query `.Where(x => EF.Functions.ILike(x.FullName, "123"))`.
 So how to convert this query to `WhereDynamic`. I'm tried use `WhereDynamic(x => "EF.Functions.ILike(x.FullName, \"123\")"` but it throw Error
### Exception

```
Exception message: Oops! No applicable member has been found for the expression. The error occurred for expression \".\" at position 3 near \".Where(x => EF.Functions.\"."
Stack trace: "   at .(ExpressionScope , Expression , Type , String , List`1 , Boolean , List`1 , SyntaxNode , Expression& )\r\n   at .(ExpressionScope , SyntaxNode , Type , Expression , List`1 )\r\n   at .(ExpressionScope , SyntaxNode , Expression , Boolean )\r\n   at .(ExpressionScope , SyntaxNode , Expression , Boolean )\r\n   at .(ExpressionScope , SyntaxNode , Expression , Boolean )\r\n   at Z.Expressions.CodeCompiler.CSharp.ExpressionParser.ParseSyntax(ExpressionScope scope, SyntaxNode node, Type resultType)\r\n   at .[](EvalContext , String , IDictionary`2 , Type , EvalCompilerParameterKind , ExpressionScope , String , Boolean , Boolean )\r\n   at .[](EvalContext , String , IDictionary`2 , Type , EvalCompilerParameterKind , Boolean , Boolean )\r\n   at Z.Expressions.EvalLinq.Execute(String code, Expression exp, Object[] parameters)\r\n   at System.Linq.QueryableDynamic.WhereDynamic[TSource](IQueryable`1 source, Expression`1 predicate, Object parameter)\r\n   at System.Linq.QueryableDynamic.WhereDynamic[TSource](IQueryable`1 source, Expression`1 predicate)\r\n   at Redsand.Site.Api.A.Index() in D:\\ECRM-2018\\Api\\TestController.cs:line 26\r\n   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()"
```

### Further technical details
- EF version: 2.2
- EF Plus version: 2.0 lasted
- Database Provider: postgresql

**Comment by JonathanMagnan** [comment]
Hello @kenzouno1 ,

Thank you for reporting,

This error happens because our library doesn't know about external types such as this one.

It can be solved by registering it once:

```csharp
EvalManager.DefaultContext.RegisterType(typeof(Microsoft.EntityFrameworkCore.EF));
```

We will look at it to automatically register it on our side.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by kenzouno1** [comment]
i'm tried but not working.
 ```            EvalManager.DefaultContext.RegisterType(typeof(EF));
            var query = db.Customers.AsQueryable();
            query = query.WhereDynamic(x => "EF.Functions.ILike(x.FullName, \"123\")");
```

**Comment by JonathanMagnan** [comment]
Thank you for letting us know @kenzouno1 ,

I will have my developer look at it next Monday and provide you a runnable solution.

This is probably happening because `PostgreSQL` has his own extension method.

So while you register the one from `EF Core`, that's not enough since the one from `PostgreSQL` is not added.

**Comment by JonathanMagnan** [comment]
Hello @kenzouno1 ,

As expected, both following types need to be registered since they contain both extension methods

```csharp
EvalManager.DefaultContext.RegisterType(typeof(EF));
EvalManager.DefaultContext.RegisterType(typeof(NpgsqlDbFunctionsExtensions));
```

Here is a working project:
[WhereDynamic.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/4031010/WhereDynamic.zip)

Let me know if that helps you

**Comment by kenzouno1** [comment]
It's worked. Thank you very much.

**Comment by mhosman** [comment]
Hey @JonathanMagnan I'm here with the same issue. Where is the best place to put those extension methods?

**Comment by Kasta11111** [comment]
Hi, I have same exception

`.WhereDynamic(o => "EF.Functions.ILike(o.Id, \"3\")")`

`"Oops! No applicable member has been found for the expression. The error occurred for expression \".\" at position 3 near \".Where(o => EF.Functions.\"."`

but I am using `Microsoft SQL Server`.

Probably have to register correct type. I tried 

`EvalManager.DefaultContext.RegisterType(typeof(EF));
 EvalManager.DefaultContext.RegisterType(typeof(Microsoft.EntityFrameworkCore.DbFunctionsExtensions));` 

and 

`EvalManager.DefaultContext.RegisterType(typeof(EF));
 EvalManager.DefaultContext.RegisterType(typeof(Microsoft.EntityFrameworkCore.SqlServerDbFunctionsExtensions));`

 without any success.

Thank you for help.

**Comment by JonathanMagnan** [comment]
Hello @Kasta11111 ,

Could you open a new issue and provide a runnable project with the minimum information required to reproduce it? We will look at it.

Since you use C# Eval, I recommend you to open the issue here: https://github.com/zzzprojects/Eval-Expression.NET/issues

**Comment by nelaren** [comment]
Helo,
Could i use subqueries in WhereDynamics?

**Comment by JonathanMagnan** [comment]
Hello @nelaren ,

`WhereDynamic` should also you what you can do in `LINQ` but dynamically (using a string).

So it depends what you mean by `subqueries`. If that's supported in `LINQ`, then the `WhereDynamic` will likely support it unless we have an issue in the library.

Let me know if that answer correctly to your question.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by nelaren** [comment]
Hi, Jon,
It was my mistake. It works fine, sorry. 
Thank you for help.
Best Regards,
Nelson
