### ISSUE TITLE
Update the Child entity value in EF core with EntityFramework.Plus for Audit Tracking

### ISSUE THREAD

**Issue by admin2210** [zzzprojects/EntityFramework-Plus#568]
Hi I am using the  Z.EntityFramework.Plus with enityframework in my blazor app for audit Tracking.
I have one parent class Client and and onother child  Address in same entity.

But when I change the address object value in Client and I'll try to save it, it's doesn't work.If I don't use below forrmt then 
it's difficlut for me to track the enityt update because  Z.EntityFramework.Plus reuireq manually update entry for audit login for every enity which i updated.

Only update Client object if I used below approch and only track the client modification which I did.

```csharp
 using (var scope = _ServiceScopeFactory.CreateScope())
                {
                    var referenceContext = scope.ServiceProvider.GetService<ApplicationDbContext>();

                    // Use for Audit Logging
                    var audit = new Audit();
                    audit.CreatedBy = client.LastModifiedBy;
                    var originalClient = client;

                    client.LastModifiedAt = DateTime.UtcNow;
                    referenceContext.Entry(originalClient.Address).CurrentValues.SetValues(client.Address);
                    referenceContext.Entry(originalClient).CurrentValues.SetValues(client);
                   
                    //Pass Audit Insatnce for Audit Logging
                    referenceContext.SaveChanges(audit);				
					}
```

It's work if I follow below approch but using this i don't able to track the audit of any entity. 

```csharp
 using (var scope = _ServiceScopeFactory.CreateScope())
                {
				  var referenceContext = scope.ServiceProvider.GetService<ApplicationDbContext>();
				   referenceContext.Entry(Address).State = EntityState.Modified;
				  referenceContext.Entry(Client).State = EntityState.Modified;
				  referenceContext.SaveChanges();
				}


 public class Client : AuditInfo
    {
        [Required]
        public int Id { get; set; }

        [Required, MaxLength(35, ErrorMessage = "Sorry You are Exceeding the chracter Limit for First Name.")]
        [RegularExpression("^([a-zA-Z]+[,.]?[ ]?|[a-zA-Z]+['-]?)+$", ErrorMessage = "First Name must contain charcter only.")]
        public string FirstName { get; set; }

        [MaxLength(35, ErrorMessage = "Sorry You are Exceeding the chracter Limit for Middle Name.")]
        [RegularExpression("^([a-zA-Z]+[,.]?[ ]?|[a-zA-Z]+['-]?)+$", ErrorMessage = "Middle Name must contain charcter only.")]
        public string MiddleName { get; set; }

        [Required, MaxLength(35, ErrorMessage = "Sorry You are Exceeding the chracter Limit for Last Name.")]
        [RegularExpression("^([a-zA-Z]+[,.]?[ ]?|[a-zA-Z]+['-]?)+$", ErrorMessage = "Last Name must contain charcter only.")]
        public string LastName { get; set; }

        [Required, MaxLength(35)]
        public string Gender { get; set; }

        [Required]
        [DataType(DataType.Date), Column(TypeName = "date")]
        public DateTime DateOfBirth { get; set; }

        [ValidateComplexType]
        public Address Address { get; set; }
		
	}
	
	 public class Address : AuditInfo
    {
        [Required]
        public int Id { get; set; }

        [Required, MaxLength(1024, ErrorMessage = "Sorry You are Exceeding the chracter Limit for First Line.")]
        public string FirstLine { get; set; }

        public string SecondLine { get; set; }

        [Required(ErrorMessage = "Please select the Province"), MaxLength(256, ErrorMessage = "Sorry You are Exceeding the chracter Limit for Province.")]
        public string Province { get; set; }

        [Required, MaxLength(256, ErrorMessage = "Sorry You are Exceeding the chracter Limit for City.")]
        [RegularExpression("^([a-zA-Z]+[,.]?[ ]?|[a-zA-Z]+['-]?)+$", ErrorMessage = "City Name contain charcter only.")]
        public string City { get; set; }

        [Required, MaxLength(256, ErrorMessage = "Sorry You are Exceeding the chracter Limit for PostalCode.")]
        public string PostalCode { get; set; }

        [Required]
        public bool IsActive { get; set; }
 }
```

**Comment by JonathanMagnan** [comment]
Hello @admin2210 ,

I'm not 100% sure to understand the issue. But it looks similar to one that we often answer.

To track old values, the entity must be loaded first from the database otherwise the ChangeTracker doesn't know about those values.

So attaching your entity and setting the state to `Modified` is not enough. It really needs to be loaded from the database to get the `Old` value.

**Comment by admin2210** [comment]
Hi, can you please help me to create one demo application that will help me that how we can able to track the updated entity.  if i have one parent object and another child object too.Supposed in below Demo entity I modified the  ChildObject .Name from old to new how we can able to track it ?

Public class Demo
{
Public int Id { get; set; }
Public string Name { get; set; }
public ChildObject ChildObject { get; set; }
}

Public Class ChildObject 
{
Public int Id { get; set; }
Public string Name { get; set; }
}

**Comment by admin2210** [comment]
using (var scope = _ServiceScopeFactory.CreateScope())
                {
                    var referenceContext = scope.ServiceProvider.GetService<ApplicationDbContext>();

                    var originalClient = referenceContext.Clients.Find(client.Id);
                    originalClient.Address = client.Address;
                    // Use for Audit Logging
                    var audit = new Audit();
                    audit.CreatedBy = client.LastModifiedBy;

                    client.LastModifiedAt = DateTime.UtcNow;

                    referenceContext.Entry(originalClient.Address).State = EntityState.Modified;

                    referenceContext.Entry(originalClient).CurrentValues.SetValues(client);

                    //Pass Audit Insatnce for Audit Logging
                    referenceContext.SaveChanges(audit);
                }
Using Above code I able to track the changes if someone did   in parent but I don't able to track the changes of  Child object. That value value for child table is updated in db table but not in the audit table.

**Comment by JonathanMagnan** [comment]
Hello @admin2210 ,

If you want a demo, please provide us a small runnable demo project with your scenario. I will be happy to have one of my developers look at it.
