### ISSUE TITLE
Receiving "The provider for the source IQueryable doesn't implement IAsyncQueryProvider" when using IncludeOptimized() and FirstOrDefaultAsync().

### ISSUE THREAD

**Issue by mgraf1** [zzzprojects/EntityFramework-Plus#579]
### Description
Similar to #572 

When using `FirstOrDefaultAsync` after using `IncludeOptimized` an error is thrown.

```
System.InvalidOperationException: 'The provider for the source IQueryable doesn't implement IAsyncQueryProvider. Only providers that implement IAsyncQueryProvider can be used for Entity Framework asynchronous operations.'
```

### Fiddle or Project
[EFPlusRepro.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/4160581/EFPlusRepro.zip)

### Further technical details
- EF version: 3.11
- EF Plus version: 3.0.35
- Database Provider: Sql Server

**Comment by JonathanMagnan** [comment]
Hello @mgraf1 ,

Thank you for reporting,

I believe someone else has already reported it and my developer was working on it this morning.

I will let you know as soon as we have more information,

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @mgraf1 ,

A new version has been released.

Could you try it and let us know if everything works as expected?

Best Regards,

Jon

**Comment by mgraf1** [comment]
Yes, this resolves my issue. Thanks!
