### ISSUE TITLE
Specify batch Size and Batch Interval for Batch Delete

### ISSUE THREAD

**Issue by saad749** [zzzprojects/EntityFramework-Plus#58]
How can we specify both parameters for the Delete command. I have something like:

`_dbContext.Set<T>().Where(predicate).Delete(x => x.BatchSize = 10000);`

How can I add BatchDelayInterval as well?

`_dbContext.Set<T>().Where(predicate).Delete(x => x.BatchSize = 10000, x => x. BatchDelayInterval = 1000);
`
doesn't seem to work

**Comment by zzzprojects** [comment]
Hello @saad749 ,

You must use a statement block

```csharp
_dbContext.Set<T>().Where(predicate).Delete(x => {
	x.BatchSize = 10000;
	x.BatchDelayInterval = 1000;
});
```

Let me know if that worked.

**Comment by saad749** [comment]
Thanks, I will try it tomorrow.

**Comment by saad749** [comment]
It works perfectly fine. Thank you :)
