### ISSUE TITLE
Exception when mocking with Effort - Stream not found (Conceptual)

### ISSUE THREAD

**Issue by Jonno12345** [zzzprojects/EntityFramework-Plus#580]
Background - We were previously using the now deprecated package 'Z.EntityFramework.Plus.BatchUpdate.EF6' v 1.8.6 in our projects, however this started clashing with the full version of Z.EntityFramework.Plus.EF6 after moving to package reference. We use EF6.4.0 and Effort in order to create unit tests. Our EF6.4.0 models are created as EDMX, database first.

We have now updated to using the full Z.EntityFramework.Plus.EF6 package, latest version of it and all dependencies. In doing this, our unit tests are now failing with the below exception.

```
  Message: 
    Test method X.X.X threw exception: 
    System.Exception: Stream not found (Conceptual).
  Stack Trace: 
    .(DbContext this, String )
    .(DbContext this, List`1 , String )
    .(DbContext )
    .(DbContext )
    DbContextExtensions.GetModel(DbContext this)
    DbContextExtensions.[](IQueryable`1 , Expression`1 , Action`1 , Boolean )
    DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression, Action`1 bulkOperationFactory)
    BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
    BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)
```

I can see that a very similar issue exists on the previous Z.EntityFramework.Classic Github (here: https://github.com/zzzprojects/EntityFramework-Classic/issues/7) however I can't seem to find any way to resolve this issue. It seems to happen consistently on any recent versions of Plus.EF6, however going back to the Z.EntityFramework.Plus.BatchUpdate.EF6 package it works without issue again.

This only seems to occur in the Effort inmemory version of the EntityFramework model. Using it directly on the database functions correctly.

**Comment by JonathanMagnan** [comment]
Hello @Jonno12345 ,

It seems that our library cannot found your stream file (you are probably database first).

Could you provide a project sample that throws this error, we will check what's happening and support it.

You can send it in private here: info@zzzprojects.com

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @Jonno12345 ,

A new version has been released.

It should now work as expected with Effort.

Let us know if you still have an issue.

**Comment by Jonno12345** [comment]
> Hello @Jonno12345 ,
> 
> A new version has been released.
> 
> It should now work as expected with Effort.
> 
> Let us know if you still have an issue.

Hi @JonathanMagnan,

Thank you, this appears to have addressed the issue. I will let you know if we have any further problems.

Many thanks for the quick turn around!

Jonno

**Comment by tiesont** [comment]
I'm seeing this same exception, using Effort.EF6 (2.2.13) and Z.EntityFramework.Plus.EF6 (5.1.39), when attempting to use `BulkSaveChanges()` - is this a related problem, or would it make sense to open a new issue?

**Comment by JonathanMagnan** [comment]
Hello @tiesont ,

I recommend you open a new issue, add a link to this one, and to provide us a small runnable project with the minimum code required to reproduce the issue.

That's usually the fastest way to get your issue fixed ;)

Best Regards,

Jon
