### ISSUE TITLE
AuditExtensions support for Audit - Customization

### ISSUE THREAD

**Issue by parloti** [zzzprojects/EntityFramework-Plus#584]
https://github.com/zzzprojects/EntityFramework-Plus/blob/fed66e4dc63b327e90cba782f4639d2fa33a431f/src/shared/Z.EF.Plus.Audit.Shared/Extensions/DbSet%60AuditEntry/DbSet%60AuditEntry.cs#L23-L25

At the moment it is not possible to do this:

```
ctx.CustomAuditEntries.Where (item);
ctx.CustomAuditEntries.Where<Entity_Basic>(item.ID);
ctx.CustomAuditEntries.Where<Entity_Basic>(101);
```

But I believe that if the code above is replaced by:

```
public static partial class AuditExtensions
{
    public static IQueryable<U> Where<T,U>(this DbSet<U> set, T entry, bool diff) where T : class where U: AuditEntry
```

then it will be possible.

**Comment by JonathanMagnan** [comment]
Hello @parloti ,

Thank you for your good suggestion,

At first sight, I agree with you and this will make our library more extensible.

One of my developers will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @parloti ,

A new version has been released.

It's now possible to use custom `DbSet`

```csharp
var audit1 = context.AuditEntries.Where(simple).ToList();
var audit2 = context.AuditEntries.Where<DbAuditEntry, EntitySimple>(a.First().ID).ToList();
```

Let me know if that's what you were looking for.

**Comment by parloti** [comment]
yes, exactly, thanks for the quick reply.
