### ISSUE TITLE
Field '_queryCompiler' defined on type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider' is not a field on the target object which is of type 'Z.EntityFramework.Plus.QueryIncludeOptimizedProvider`1[DE.ZA.MobilePickingApp.Database.ViewerRole]'.

### ISSUE THREAD

**Issue by AnReZa** [zzzprojects/EntityFramework-Plus#586]
For now, I only used IncludeOptimized. For a translation table, I only want to join the relevant language for the current user. Therefore I added the following code:

````c#
ViewerRole role = await db.ViewerRoles
  .Where(vr => vr.ID == 1)
  .IncludeOptimized(vr => vr.ViewerColumns)
  .IncludeOptimized(vr => vr.ViewerColumns.Select(vc => vc.SourceColumn))
  .IncludeFilter(vr => vr.ViewerColumns.Select(vc => vc.SourceColumn.DefaultNames.Where(dn => dn.Language == "de-DE")))
  .SingleOrDefaultAsync();
````

However, this throws this enormous error:

> System.ArgumentException: Field '_queryCompiler' defined on type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider' is not a field on the target object which is of type 'Z.EntityFramework.Plus.QueryIncludeOptimizedProvider`1[DE.ZA.MobilePickingApp.Database.ViewerRole]'.
>    at System.Reflection.RtFieldInfo.GetValue(Object obj)
>    at Z.EntityFramework.Plus.InternalExtensions.IsInMemoryQueryContext[T](IQueryable`1 query)
>    at Z.EntityFramework.Plus.QueryIncludeFilterProvider`1.Execute[TResult](Expression expression)
>    at Z.EntityFramework.Plus.QueryIncludeFilterProvider`1.<>c__DisplayClass15_0`1.<ExecuteAsyncTask>b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location where exception was thrown ---
>    at DE.ZA.QualityComplaintsProcessing.Controllers.PickingController.GetColumns() in C:\Users\Reichelt\source\repos\DE.ZA.MobilePickingApp\DE.ZA.MobilePickingApp\Controllers\PickingController.cs:line 55
>    at lambda_method(Closure , Object )
>    at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

If I replace the IncludeFilter with a simple IncludeOptimized and put the filtering into my code, it works just file. What am I doing wrong?

**Comment by JonathanMagnan** [comment]
Nothing probably,

The `IncludeFilter` and `IncludeOptimized` are not compatible.

Historically, both features were working on different `dll`, so one could not use the type of the other.

When we will re-write this features, we will make sure that both methods could work together but for now, if you use `IncludeOptimized`, continue to use this method all the way even if you filter.

Let me know if that answer to your question

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by AnReZa** [comment]
Hi Jon,

I just realized, that it also works with the `IncludeOptimized` method, even when adding the filter to it. Thank you very much!

Best regards
André
