### ISSUE TITLE
Audit - EntityAdded problem

### ISSUE THREAD

**Issue by EdsonMiranda** [zzzprojects/EntityFramework-Plus#59]
Unchanged Null values are being considered as changed.
When I list properties from table AuditEntryProperties, they appears like this:
OldValue = NULL
NewValue = empty

**Comment by zzzprojects** [comment]
Thank you @EdsonMiranda,

We confirmed the issue. The logic check for NULL value to insert "NULL" in the database but the value in code is DBNull.Value instead, so an empty string is added instead.

We will try to make this fix this week.

**Comment by EdsonMiranda** [comment]
Ok, thanks!

**Comment by zzzprojects** [comment]
Hello @EdsonMiranda ,

The v1.4.8 has been released.

Let me know if the NewValue column now is saved with the value NULL

Best Regards,

Jonathan

**Comment by EdsonMiranda** [comment]
The problem changed, but still not working.
EntityAdded unchanged properties are being logged.
OldValue = NULL
NewValue = NULL

**Comment by zzzprojects** [comment]
Hello @EdsonMiranda ,

EntityAdded should always log all properties no?

All properties are in fact changed since it's a new whole entity.

**Comment by EdsonMiranda** [comment]
I was thinking about this, but usually strings have NULL as default and INT
and any other numeric properties have ZERO as default. You should consider
this when adding records. This will not record unecessary audit
information. Other similar tools do this way. But your tool is much better.

Think about!

Thanks
Edson

Em 17/10/2016 13:15, "ZZZ Projects" <notifications@github.com> escreveu:

**Comment by zzzprojects** [comment]
Thank you for your feedback,

We will add a property to ignore default value for EntityAdded.

Probably something like

```csharp
AuditManager.DefaultConfiguration.IgnoreEntityAddedDefaultValue = true;
```

**Comment by EdsonMiranda** [comment]
I think this is a very good and flexible solution!

**Comment by EdsonMiranda** [comment]
Is this feature available?

AuditManager.DefaultConfiguration.IgnoreEntityAddedDefaultValue = true;
or 
AuditManager.DefaultConfiguration.IgnoreDefaultValueEntityAdded = true;

**Comment by JonathanMagnan** [comment]
Hello @EdsonMiranda ,

From my knowledge, I don't think.

We will re-visit this one ;)

**Comment by JonathanMagnan** [comment]
Hello @EdsonMiranda ,

The v1.9.1 has been released.

Let me know if that's working as you expected.

Best Regards,

Jonathan

**Comment by Jogai** [comment]
For me I still see Old & New Values as NULL (my data types are: string, int?, short and bool if it makes any difference).

**Comment by JonathanMagnan** [comment]
Hello @Jogai ,

That's the expected behavior.

Instead to insert "0" for int, a `NULL` is inserted.

**Comment by Jogai** [comment]
Oh I see. I made another request (https://github.com/zzzprojects/EntityFramework-Plus/issues/491)  because in that case I want something different. 

By the way, awesome response time!
