### ISSUE TITLE
Audit exclude property change still logs to entries table

### ISSUE THREAD

**Issue by trekco** [zzzprojects/EntityFramework-Plus#592]
### Description
An audit entry is still added if only an excluded property has changed. Excluding properties works but if there is no other property changes then it still log an entry with the PK property

example code:
```
AuditManager.DefaultConfiguration.IgnorePropertyUnchanged = true;
AuditManager.DefaultConfiguration.Include<User>()
                        .ExcludeProperty<User>(u => u.DateLastSeen);
```

I expect that nothing gets logged, but when I change the DateLastSeen value then a entry is added in the entry table and the PK is added in the property table. Nothing else.

Is there a setting somewhere to prevent this?

I am using 
EntityFramework Core 3.1.1
Z.EntityFramework.Plus.Audit.EFCore 1.8.5

**Comment by JonathanMagnan** [comment]
Hello @trekco ,

By default, the key is always added even if not modified.

When adding audit entry in the `AutoSavePreAction`, you can simple remove all `AuditEntryProperty` from the `AuditEntry` if you really want no property.
 
There is no magic here, this is a simple one to many hierarchies (`AuditEntry` && `AuditEntryProperty`), so you can control 100% of what's happening.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by trekco** [comment]
Hi, Thank you for the feedback.

I don't think you understand I will try and explain better.

I do want properties to log, but in this instance I don't think anything should have logged.

If you look at the following class

```
class user 
{
   int Id {get;set;};
   DateTime DateLastSeen{get;set;}
   string Email {get;set;}
   string Name {get;set;}   
}

// config
AuditManager.DefaultConfiguration.IgnorePropertyUnchanged = true;
AuditManager.DefaultConfiguration.Include<User>()
                        .ExcludeProperty<User>(u => u.DateLastSeen);
```


DateLastSeen is excluded from the logs;

If I change the email then I expect the following
**Expected & Actual**
- 2 records in the property table for the **Id** and the **Email** that was changed
- An entry in the auditEntries table with the state **EntityModified**

If I change dateLastSeen and email I expect the same
**Expected & Actual**
- 2 records in the property table for the **Id** and the **Email** that was changed
- An entry in the auditEntries table with the state **EntityModified**
- no entry in property table for the property DateLastSeen. 

The examples above is working as expected and 100% correct.

If I only change **DateLastSeen** I expect the following
**Expected**
- no entry in property table because no properties was changed (Except the one that was excluded but we don't care about that one). no need to add Id property because there was no property changes.
- no entry in auditEntries table because no properties changed.

**Actual** - I think this is wrong
- One entry in property table for the "Id"
- An entry in the auditEntries table with the state **EntityModified**

It feels like a hack if I have to remove all the enties in **AutoSavePreAction** if only the Id property is in the changed properties.

If this does not seem wrong then you can close this issue, then I will have to accept it :)

**Comment by JonathanMagnan** [comment]
I now understand your point of view ;)

However, the `ExcludeProperty` doesn't work like this. It just doesn't log property that is excluded, it doesn't check if an included property has been modified or not. This is how the option has been initially designed.

Being wrong or right about how the expected behavior should work currently doesn't matter. The only thing that matters is to stay **backward compatible** with the current behavior.

But I see what kind of feature you will like to have, so maybe adding another option that does it would be the best of both world ;)

I will ask my developer to look at it.

**Comment by JonathanMagnan** [comment]
Hello @trekco ,

A new version has been released

If you set the option `IgnoreEntityUnchanged` to true, entity will only be audited if at least one not ignore properties has been modified.

Let me know if that's what you were looking for.

Best Regards,

Jon

**Comment by trekco** [comment]
@JonathanMagnan thank you. I am happy with the change. It works as I expected now

**Comment by JonathanMagnan** [comment]
Awesome @trekco,

we are glad everything is working out as expected! 

Don't hesitate to contact us for questions, issues or feedback.

Best regards,

Jon

**Comment by trekco** [comment]
@JonathanMagnan thanks will do and thank you for creating this awesome library, I wish I could afford "Entity Framework Extensions" so that I can use all the features

**Comment by JonathanMagnan** [comment]
Hello @trekco,

you can contact our sales team at sales@zzzprojects.com

and we will see what we can do regarding a license for Entity Framework Extensions

Jon
