### ISSUE TITLE
UpdateFromQueryAsync with IDictionary throws Argument types do not match

### ISSUE THREAD

**Issue by jomendoza84** [zzzprojects/EntityFramework-Plus#593]
### Description

Hi pals!

First of all thanks for this amazing lib, but currently I'm getting an exception when I try to set a null into a nullable field (FieldB) using the dictionary approach:

            var dict = new Dictionary<string, object>();

            dict.Add("FieldA", 3);
            dict.Add("FieldB", null);

            return Context.SomeTable.Where(p => true).UpdateFromQueryAsync(dict);

### Exception
```
System.ArgumentException: Argument types do not match
   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, IDictionary`2 dictionary, Action`1 batchUpdateBuilder)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, IDictionary`2 dictionary)
   at BatchUpdateExtensions.`1.()
```

### Further technical details
- EF version: "Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.0"
- EF Plus version: "Z.EntityFramework.Plus.EFCore" Version="3.0.43"
- Database Provider: SqlServer

**Comment by JonathanMagnan** [comment]
Hello @jomendoza84 ,

Thank you for reporting.

We will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @jomendoza84 ,

The v3.0.45 has been released.

Could you try it and let us know if everything now works as expected?

Best Regards,

Jon

**Comment by jomendoza84** [comment]
Hi Jon, the new version is working as expected :)

Thanks!!
