### ISSUE TITLE
DeferredCount Issue

### ISSUE THREAD

**Issue by CactusPie** [zzzprojects/EntityFramework-Plus#594]
### Description
Using DeferredCount times out for certain larger requests. The problem does not affect DeferredLongCount. For instance:

```
QueryFutureValue<int> countFuture = query.DeferredCount().FutureValue();
QueryFutureEnumerable<Server> resultFuture = query
	.OrderBy(x => x.ServerName)
	.Skip((filters.PageNumber - 1) * filters.PageSize)
	.Take(filters.PageSize)
	.Future();

// Times out here
List<Server> result = await resultFuture.ToListAsync(cancellationToken).ConfigureAwait(false);
long count = countFuture.Value;
```

If I use DeferredLongCount instead, the query works fine. It only happens to me with this specific table and for large count values (~20 000). Unfortunately, I cannot provide the source code in this case.

### Further technical details
- EF version: 6.2.0
- EF Plus version: 1.12.17
- Database Provider: Microsoft SQL Server 2014 (SP2) (KB3171021) - 12.0.5000.0 (X64)

**Comment by JonathanMagnan** [comment]
Hello @CactusPie ,

Unfortunately, if you cannot provide a runnable example that throw the error (we will probably need the database as well in you case), I don't think we will be able to reproduce it.

We don't create the SQL for the `Count` or `LongCount`, we use the one generated by Entity Framework.

If you can try to reproduce it in an external test project, that will be perfect for us. You can send it in private here: info@zzzprojects.com

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
