### ISSUE TITLE
Update : Must declare the scalar variable exception

### ISSUE THREAD

**Issue by Ilya-by** [zzzprojects/EntityFramework-Plus#595]
### Description
Attempt to perform update with increment of current integer value and got an exception from sql.
request.SeatNumber property using in update is not generated in sql paramenters "@__SeatNumber_2\" .

Code: 

```csharp
public async Task<Unit> Handle(AllocateSeatCommand request, CancellationToken cancellationToken)
        {
                var res= await _context.SeatBundles
                    .Where(s => s.Id == seatBundle.Id && s.AllocatedSeatCount + request.SeatNumber < s.Capacity)
                    .UpdateAsync(s => new SeatBundle() {AllocatedSeatCount = s.AllocatedSeatCount + request.SeatNumber}, cancellationToken);
        }
```

I've tried to make local variable like this : 

```csharp
int seatNumber = request.SeatNumber;
UpdateAsync(s => new SeatBundle() {AllocatedSeatCount = s.AllocatedSeatCount + seatNumber }, cancellationToken);
```

and it works.

SQL profile: 
`exec sp_executesql N'
UPDATE A 
SET A.[AllocatedSeatCount] = B.[AllocatedSeatCount] + @__SeatNumber_2
FROM [SeatBundles] AS A
INNER JOIN ( SELECT [s].[Id], [s].[AllocatedSeatCount], [s].[Capacity], [s].[CatalogSeatBundleId], [s].[Created], [s].[CustomerId], [s].[ExpirationDate], [s].[Price], [s].[PurchaseOrderId], [s].[StartDate], [s].[Updated]
FROM [SeatBundles] AS [s]
WHERE ([s].[Id] = @__seatBundle_Id_0) AND (([s].[AllocatedSeatCount] + @__request_SeatNumber_1) < [s].[Capacity])
           ) AS B ON A.[Id] = B.[Id]
',N'@__seatBundle_Id_0 uniqueidentifier,@__request_SeatNumber_1 int',@__seatBundle_Id_0='7F1249B5-7F53-442C-B2C2-B0C2FCF1281C',@__request_SeatNumber_1=6`

### Exception
`"Microsoft.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable \"@__SeatNumber_2\".\r\nIncorrect syntax near the keyword 'AS'.\r\n   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)\r\n   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)\r\n   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)\r\n   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)\r\n   at Z.EntityFramework.Plus.BatchUpdateExtensions.<>c__DisplayClass2_0`1.<UpdateAsync>b__0()\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n`

### Further technical details
- EF version: "Microsoft.EntityFrameworkCore" Version="3.1.2"
- EF Plus version:"Z.EntityFramework.Plus.EFCore" Version="3.0.45"
- Database Provider: "Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.2"

**Comment by JonathanMagnan** [comment]
Hello @Ilya-by ,
 
Thank you for reporting. All free projects issue are currently on hold for the next 2-3 weeks (we might still do some request from time to time).
 
Do you think you could provide a project sample with this issue? Even if the issue looks very easy to reproduce, often a missing piece of the puzzle is missing to reproduce it.

Having a project will give more chance that a developer will pick your issue to help you.

_You can send it to: info@zzzprojects.com if you need to keep the source private_
 
Best Regards,
 
Jonathan
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
