### ISSUE TITLE
IncludeOptimized() InvalidCastException when using UseInMemoryDatabase()

### ISSUE THREAD

**Issue by larsvliet** [zzzprojects/EntityFramework-Plus#598]
### Description
In our project we are running unit test using: https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory

### Exception
When running a test that includes a query with IncludeOptimized() we are getting the following stacktrace.

```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryContextFactory' to type 'Microsoft.EntityFrameworkCore.Query.Internal.RelationalQueryContextFactory'.
   at Z.EntityFramework.Plus.InternalExtensions.GetDbContext[T](IQueryable`1 source)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedProvider`1.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at Program.Main()
```

### Fiddle or Project
https://dotnetfiddle.net/8H19uw

### Further technical details
- EF version: 3.1.3
- EF Plus version: 3.0.46
- Database Provider: https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory

**Comment by JonathanMagnan** [comment]
Hello @larsvliet ,

Just let us know when your project will be ready.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by larsvliet** [comment]
Hi @JonathanMagnan,

I've added the example fiddle.

**Comment by JonathanMagnan** [comment]
Awesome thank you,

I will assign it to my developer.

**Comment by JonathanMagnan** [comment]
Hello @larsvliet ,

A new version has been released this morning.

Could you try it and let us know if that's fixed?

Best Regards,

Jon

**Comment by larsvliet** [comment]
Thank you. The issue is fixed!
