### ISSUE TITLE
support for asp.net core (dnxcore)?

### ISSUE THREAD

**Issue by rexhxiao** [zzzprojects/EntityFramework-Plus#6]
as the title

**Comment by zzzprojects** [comment]
Hello Rexhiao,

Perfect timing!

We are currently trying to move the library to dnxcore. A new version may be available later today if we success to move all the code.

**Comment by zzzprojects** [comment]
Hello Rexhiao,

The new version 1.0.7 is published for all EF Core packages. This version now targets "4.5.1" and "dnxcore50".

It's the first time we release a package with "dnxcore50", so let us know if we have made a mistake.

Best Regards,

Jonathan

**Comment by rexhxiao** [comment]
wow! good job.

**Comment by zzzprojects** [comment]
Feel free to re-open it if you have an issue with the new version.

**Comment by zzzprojects** [comment]
Closing the issue
