### ISSUE TITLE
Audit - Use another database

### ISSUE THREAD

**Issue by EdsonMiranda** [zzzprojects/EntityFramework-Plus#60]
Is it possible to save tracking log at another database than the database being tracked?

**Comment by zzzprojects** [comment]
Hello @EdsonMiranda ,

Yes, it's possible. 

1. Create another context for your auditing database
2. Override SaveChanges for the context of your data
3. Instead to add audit entry to your context, add it to your auditing context
4. Save your auditing context

**Example:**

```csharp
public class EntityContext : DbContext
{
    // ... context code ...
	
	public override int SaveChanges()
	{
		var audit = new Audit();
		audit.PreSaveChanges(this);
		var rowAffecteds = base.SaveChanges();
		audit.PostSaveChanges();

		if (audit.Configuration.AutoSavePreAction != null)
		{
			var auditingContext = new AuditingContext();
			audit.Configuration.AutoSavePreAction(auditingContext, audit);
			auditingContext.SaveChanges();
		}

		return rowAffecteds;
	}
}
```

Let me know if I successfully answered to your question

Best Regards,

Jonathan

**Comment by EdsonMiranda** [comment]
Works fine!! Thank you very much!
