### ISSUE TITLE
Manual Cache Clearing

### ISSUE THREAD

**Issue by SergeyBalanEmpeek** [zzzprojects/EntityFramework-Plus#606]
Hello Jonathan

I know `QueryCacheManager.IsAutoExpireCacheEnabled = true` is not yet supported in Core.

Is it possible to implement manual flushing like
`context.Accounts.ClearCache()` which cleans all cache entries for Account entity?

So I can work with `context.Accounts.FromCache()` without specifying any tags and clean all cache entries related to Account when I need it

Thank you

**Comment by JonathanMagnan** [comment]
Hello @SergeyBalanEmpeek ,

I don't think we have something like this but we will certainly look to it this week.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @SergeyBalanEmpeek ,

The new version has been released.

We added the method `ExpireCache()` to the DbSet and `ExpireType` to the `QueryCacheManager`.

We also added the missing method `ExpireAll` to the `QueryCacheManager` for EF Core

Let me know if that's what you were looking for.

**Comment by SergeyBalanEmpeek** [comment]
Thank you @JonathanMagnan very much, it works as expected
