### ISSUE TITLE
IncludeOptimized support for inheritance/HasDiscriminator

### ISSUE THREAD

**Issue by Dunge** [zzzprojects/EntityFramework-Plus#607]
### Description
It seems like the library doesn't work when using a model configured with inheritance (which should be the case for many complex include cases requiring this library).

### Full reproducible project (except you should change the ToTable/HasForeignKey/HasColumnName to match a real database schema):

```
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using Z.EntityFramework.Plus;

namespace IncludeOptimized
{
    // Model
    public enum EntityTypes
    {
        Unknown = 0,
        Type1,
        Type2
    }

    public class Entity
    {
        public int Id { get; set; }
        public EntityTypes Type { get; set; }
    }

    public class Derived : Entity
    {
        public List<DerivedInclude> Includes { get; set; }
    }

    public class Derived2 : Entity
    {
    }

    public class DerivedInclude
    {
        public int Id { get; set; }
        public string SomeProp { get; set; }
    }

    // Context
    public class DatabaseContext : DbContext
    {
        public virtual DbSet<Entity> Entities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
#if DEBUG
            optionsBuilder.EnableSensitiveDataLogging();
#endif

            optionsBuilder.UseSqlServer(@"Data Source=(local)\SQLEXPRESS;Initial Catalog=Jamlogic;Integrated Security=True", providerOptions =>
            {
                providerOptions.CommandTimeout(600);
            });
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Entity>(entity =>
            {
                entity.ToTable("Container");
                entity.HasKey(e => e.Id);
                entity.HasDiscriminator<EntityTypes>("Type")
                    .HasValue<Entity>(EntityTypes.Unknown)
                    .HasValue<Derived>(EntityTypes.Type1)
                    .HasValue<Derived2>(EntityTypes.Type2);
            });

            modelBuilder.Entity<Derived>(entity =>
            {
                entity.HasBaseType<Entity>();
                entity.HasMany(e => e.Includes).WithOne().HasForeignKey("Device_FK").OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity<Derived2>(entity =>
            {
                entity.HasBaseType<Entity>();
            });

            modelBuilder.Entity<DerivedInclude>(entity =>
            {
                entity.ToTable("Module");
                entity.HasKey(e => e.Id);
                entity.Property(e => e.SomeProp).HasColumnName("Model");
            });
        }
    }


    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new DatabaseContext())
            {
                var resultOk = context.Entities.Include("Includes").ToList();
                var resultOk2 = context.Entities.Include(e => (e as Derived).Includes).ToList();

                var resultException = context.Entities.IncludeOptimizedByPath("Includes").ToList();
                var resultNullRef = context.Entities.IncludeOptimized(e => (e as Derived).Includes).ToList();
            }
        }
    }
}
```

### Results:
Using built-in EFCore Includes(), both with a string and the expression tree version, the "Includes" list loads correctly on the derived entity.

Using IncludeOptimizedByPath() I receive this exception:

> System.Exception : 'Oops! the following type 'IncludeOptimized.Entity' doesn't contains the specified property 'Includes'. For more information, contact us: info@zzzprojects.com'

Using IncludeOptimized with an expression tree, I receive a NullReferenceException:
```
System.NullReferenceException : 
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.SetResult(IEnumerator`1 enumerator)
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.SetResult(DbDataReader reader)
   at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueries()
   at Z.EntityFramework.Plus.QueryFutureEnumerable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedParentQueryable`1.CreateEnumerable()
   at Z.EntityFramework.Plus.QueryIncludeOptimizedParentQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at IncludeOptimized.Program.Main(String[] args) in ..\source\repos\IncludeOptimized\IncludeOptimized\Program.cs :line 97
```

This is a shame. I have a very big model with multiple level inheritance and included entities lists only at some level.

Using EFCore 2.2 I was having a 2.5x performance boost compared to EF6, and updating to 3.1 I lost it all (queries now takes minutes to load). I found about this library from [this thread](https://github.com/dotnet/efcore/issues/18022) and believed it would be my savior, but it doesn't work.

### Further technical details
- EF version: Microsoft.EntityFrameworkCore.SqlServer 3.1.3
- EF Plus version: Z.EntityFramework.Plus.EFCore 3.0.49
- Database Provider: Microsoft SQL Server Express (64-bit) 14.0.2027.2

**Comment by JonathanMagnan** [comment]
Hello @Dunge ,

Thank you for reporting, we will look at it and see if there is something we can do ;)

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @Dunge ,

A new version has been released.

Could you try it and let us know if it's now working with your scenario.

Best Regards,

Jon

**Comment by Dunge** [comment]
Hello,

Unfortunately not.
Using the sample above, the IncludeOptimizedByPath() does not throw an exception anymore, but the relations don't seems to be loaded. the IncludeOptimized() with a cast still throw a null reference exception.

Using my more complete project I just did a quick test with IncludeOptimizedByPath() and it crash with a more complex exception (sorry it's in French):


```
System.ArgumentException
  HResult=0x80070057
  Message=Le champ '_queryCompiler' défini dans le type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider' n'est pas un champ de l'objet cible de type 'Z.EntityFramework.Plus.QueryIncludeOptimizedProvider`1[VerMac.JamLogic.Model.Containers.ContainerBase]'.
  Source=mscorlib
  Arborescence des appels de procédure :
   à System.Reflection.RtFieldInfo.CheckConsistency(Object target)
   à System.Reflection.RtFieldInfo.InternalGetValue(Object obj, StackCrawlMark& stackMark)
   à System.Reflection.RtFieldInfo.GetValue(Object obj)
   à Z.EntityFramework.Plus.InternalExtensions.IsInMemoryQueryContext[T](IQueryable`1 query)
   à Z.EntityFramework.Plus.QueryIncludeOptimizedByPath.IncludeOptimizedByPath[T](IQueryable`1 query, String navigationPath)
   à Z.EntityFramework.Plus.QueryIncludeOptimizedExtensions.IncludeOptimizedByPath[T](IQueryable`1 query, String navigationProperties)
   à LogPerformanceTest.Program.<Main>d__1.MoveNext() dans \source\repos\LogPerformanceTest\LogPerformanceTest\Program.cs :ligne 180
```

In any case, I followed the guide in the thread I originally linked to use SelectMany()/Load() to load collections relations and managed to get it working, and even cutting time by 2x from my EFCore2.2 version. So I don't really need your library anymore.

**Comment by JonathanMagnan** [comment]
Thank, I will let my developer know about it. Don’t worry with French, we are from Quebec, alors nous parlons français ;)

**Comment by kwoolley** [comment]
@JonathanMagnan - Any plans on resolving this? I noticed it was closed with no fixed release tagged. 

My project relies heavily on IncludeOptimized and has a few large inheritance/HasDiscriminator queries that are really dragging down the performance. We'd love to find a way to get this cast working with IncludeOptimized, if possible.

Thanks

**Comment by Dunge** [comment]
@kwoolley Personally I ended up not using this library and rewriting my queries using the method explained here:

https://gist.github.com/smitpatel/d4cb3619e5b33e8d9ea24d3f2a88333a

With ThenInclude().SelectMany().Load() in multiple instructions to build the query.

But now that EFCore5 is released, I think they added an option to use split queries natively, I haven't followed up but that was in their plans.
