### ISSUE TITLE
ArgumentOutOfRangeException when deleting an entity with no primary key

### ISSUE THREAD

**Issue by gastonmuijtjens** [zzzprojects/EntityFramework-Plus#608]
### Description
I'm trying to delete an entity with no primary key with `.DeleteFromQueryAsync()`, but it throws an `ArgumentOutOfRangeException`. Doing so on an entity with a primary key attached works without problems. I'm using a MariaDB database.

### Exception
```
Exception message: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Stack trace:
   at Z.EntityFramework.Extensions.BatchDelete.Execute[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query, Action`1 batchDeleteBuilder)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.<>c__DisplayClass2_0`1.<DeleteAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---

```

### Example Code
```csharp
public class EntityContext : DbContext
{
	public EntityContext()
	{
	}

	public EntityContext(DbContextOptions<EntityContext> options)
		: base(options)
	{
	}

	public virtual DbSet<DemoTable> DemoTables { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<DemoTable>(entity =>
		{
			entity.HasNoKey();

			entity.Property(e => e.First)
				.HasColumnType("varchar(20)")
				.HasCharSet("utf8mb4")
				.HasCollation("utf8mb4_unicode_ci");

			entity.Property(e => e.Second)
				.HasColumnType("varchar(20)")
				.HasCharSet("utf8mb4")
				.HasCollation("utf8mb4_unicode_ci");
		});
	}
}


public class DemoTable
{
	public string First { get; set; }
	public string Second { get; set; }
}

public class SomeClass
{
	public async Task SomeMethod()
	{
		// Demo purposes, in real world it is configured via DI
		var context = new EntityContext();
		
		// Throws ArgumentOutOfRangeException
		await context.DemoTables.DeleteFromQueryAsync();
	}
}
```

```sql
CREATE TABLE `DemoTable` (
   `First` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
   `Second` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

### Further technical details
- .NET Core version: 3.1
- EF version: 3.1.3
- EF Plus version: 3.0.49
- Database Provider: Pomelo.EntityFrameworkCore.MySql
- Database: MariaDB 10.4.12

**Comment by JonathanMagnan** [comment]
Hello @gastonmuijtjens ,

Thank you for reporting, I will ask my developer to try it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @gastonmuijtjens ,

My developer reviewed this request.

As you said, your entity have no key `entity.HasNoKey();`.

Unless I'm wrong, even `SaveChanges` doesn't work.

If your entity has no key, there is currently no way we can delete it. Well, in fact, the only way will be to use all columns to create this missing key.

Is that really what you want?

**Comment by gastonmuijtjens** [comment]
Hi @JonathanMagnan,

Thank you for your reply. You’re right, the entity does not have a key. I missed the information pointed out in [this article](https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types), EF Core treats keyless entities the same way as views, which means entities are not tracked and cannot be modified or deleted. So this is not a bug in your library, but perhaps it’s an idea to add a specific exception for this scenario, since the `ArgumentOutOfRangeException` is pretty confusing.

**Comment by JonathanMagnan** [comment]
Hello @gastonmuijtjens ,

Just to let you know that we released a new version with an error message when this scenario happens.

I believe we can now close this issue.

Have a great day,

Best Regards,

Jon

**Comment by gastonmuijtjens** [comment]
Ok, thanks for your help and letting me know
