### ISSUE TITLE
cache is not cleared

### ISSUE THREAD

**Issue by zanyar3** [zzzprojects/EntityFramework-Plus#610]
### Description
**MemoryCacheEntryOptions** cache is not cleared after AbsoluteExpirationRelativeToNow is expired

### Code 
```
var options = new MemoryCacheEntryOptions() { AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(30)};
QueryCacheManager.DefaultMemoryCacheEntryOptions = options;
var countriesTask = await ctx.Countries.FromCacheAsync();
var countries = countriesTask .ToList();
```

### Further technical details
- EF version: EF core
- EF Plus version: Install-Package Z.EntityFramework.Plus.EFCore -Version 3.0.50
- Database Provider: MS-SQL Server

**Comment by JonathanMagnan** [comment]
Hello @zanyar3 ,

We do not control the memory cache, you are currently using the one made by Microsoft `Microsoft.Extensions.Caching.Memory.dll`.

So we cannot change the current behavior about how they handle the expiration.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by zanyar3** [comment]
Hello @Jon

**Comment by zanyar3** [comment]
Hello @Jon

**Comment by zanyar3** [comment]
Hello @Jon

**Sorry for close and re-open Issue**

For expired cache use `QueryCacheManager.ExpireTag("MyTag");`

can you recommend me for better way ? or only have a way ?

**Comment by JonathanMagnan** [comment]
What do you want to do exactly @zanyar3 ?

You can expire a specific tag, a type, or all the cache but I'm not exactly sure of what you want at this moment ;)

**Comment by zanyar3** [comment]
Dear @Jon

you said can't expired specific cache via **Time** automatically ...

I want manually expire a specific tag, i was used `QueryCacheManager.ExpireTag("MyTag");`
what about this way ? know you better way ? via **Auto using time** or **Manually** ?

**Comment by JonathanMagnan** [comment]
Hello @zanyar3 ,

> you said can't expired specific cache via Time automatically ...

No, what I said is that we don't have control over this cache but anyway it doesn't matter ;)

I checked more your issue and using your code, we can see that the item is expired (2 requests is made to the database since the second one is expired).

When using the `AbsoluteExpirationRelativeToNow` options, you must do it differently:

```csharp
QueryCacheManager.MemoryCacheEntryOptionsFactory = () =>
{
    var options = new MemoryCacheEntryOptions() { AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(30) };
    return options;
};
```

Using the factory will ensure the `AbsoluteExpirationRelativeToNow` value will be the one taken from when we called the factory (so before adding the entry) and not the one when you created the options as, after the 30s, you will automatically add an expired item.

Could you try again with `MemoryCacheEntryOptionsFactory`? On our side, it was also working the way you wrote it initially.

Here is the full code we tried:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;

namespace Z.EntityFramework.Plus.Lab.EFCore3
{
	public class Request_CacheExpiration
	{
		public static void Execute()
		{
			// Create BD 
			using (var context = new EntityContext())
			{
				My.DeleteBD(context);
				context.Database.EnsureCreated();
			}

			// CLEAN  
			using (var context = new EntityContext())
			{
				context.EntitySimples.RemoveRange(context.EntitySimples);

				context.SaveChanges();
			}


			// SEED  
			using (var context = new EntityContext())
			{
				for (int i = 0; i < 3; i++)
				{
					context.EntitySimples.Add(new EntitySimple { ColumnInt = i , ColumnString  = "test" });
				}

				context.SaveChanges();
			}

			// TEST  
			using (var context = new EntityContext())
            {
				QueryCacheManager.MemoryCacheEntryOptionsFactory = () =>
				{
				var options = new MemoryCacheEntryOptions() { AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(1) };
				return options;
				};

				var list1 = context.EntitySimples.FromCache().ToList();
				Thread.Sleep(2000);
				var list2 = context.EntitySimples.FromCache().ToList();
			}
		}

		public class EntityContext : DbContext
		{
			public EntityContext()
			{
			}

			public DbSet<EntitySimple> EntitySimples { get; set; }

			protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
			{
				optionsBuilder.UseSqlServer(new SqlConnection(My.ConnectionString));

				base.OnConfiguring(optionsBuilder);
			}
		}

		public class EntitySimple
		{
			public int ID { get; set; }
			public int ColumnInt { get; set; }
			public string ColumnString { get; set; }
		}
	}
}
```

**Comment by JonathanMagnan** [comment]
Hello @zanyar3 

Since our last conversation, we haven't heard from you. 

Did you get the chance to try the provided solution?

Don't hesitate to contact us for further assistance. 

Best regards,

Jon

**Comment by zanyar3** [comment]
I not sure problem your library or my code 

Cache expired work if **Query & QueryCacheManager** content same class like code below
```
QueryCacheManager.MemoryCacheEntryOptionsFactory = () =>
                {
                    var options = new Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions() { AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(10) };
                    return options;
                };

                var books = await _context.AmperPriceBook.Select(b => new
                {
                    b.Id,
                    b.InvoiceDate,
                    b.SystemDate,
                    Operator = string.Concat(b.Operator.Name1, " ", b.Operator.Name2),
                    b.Remark,
                    Items = b.AmperPriceBookItem.Select(i => new
                    {
                        i.Id,
                        Job = i.Job.Caption,
                        i.Price
                    })
                }).OrderByDescending(a => a.InvoiceDate).ThenByDescending(a => a.SystemDate)
              .FromCacheAsync(DbBuffer.GenerateKeyForCache(nameof(AmperPriceBook)));
                return Ok(new { State = true, books = books.ToList() });
```

But if i want set cache for all cache query Init expired  time not work like this code below

```
public static void Init(int user, int expiredTime = 10)
		{
			RefreshBuffer(user);

			QueryCacheManager.MemoryCacheEntryOptionsFactory = () =>
			{
				var options = new MemoryCacheEntryOptions() { AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(expiredTime) };
				return options;
			};
		}
```

> How to set **expired  time** for all query cache ?

**Comment by JonathanMagnan** [comment]
Hello @zanyar3 ,

Could you provide a runnable example that show both scenarios? I think we will save time here. I'm afraid that if we answer, we might still not have the same behavior. So with a runnable project, we will be able to be 100% sure of the answer.

**Comment by zanyar3** [comment]
Hello @Jon

I mean if you Set  `QueryCacheManager` expired time anther class no detect expired cache if second time get cache list 

[Please look this example](https://dotnetfiddle.net/bFrS2n)

### Work when
if you directly set `QueryCacheManager` then get cach

**Comment by JonathanMagnan** [comment]
Hello @zanyar3 ,

I'm still unsure to understand what you mean.

Using your example, I get 2 calls to the database since your second `ToList` have indeed his cache expired.

If I change your sleep to `8000`, I get only 1 call to the database since the `ToList` uses the cache as expected.

**Comment by zanyar3** [comment]
Hello @JonathanMagnan 

I mean how to set cache for global ? I mean assign cache for all query ? 

I am using class **DbBuffer** content **Init()** function set 30sec for expired caching, my scenario  clear ? 

My scenarios not work cache time expired but when i use your example work because setted  same inside  function

**Comment by JonathanMagnan** [comment]
It should already work with the code you provided.

As said, please provide a runnable example that shows the issues if there is one as we currently don't make any progress in the communication so far. I'm still trying to figure what is not working so having a project will solve it.
