### ISSUE TITLE
Parametrized vs non-parametrized query

### ISSUE THREAD

**Issue by janmarques** [zzzprojects/EntityFramework-Plus#613]
Hi

using EFCore 3.1, EFPlus 3.0.5.

When querying the ef context, in my sample project the query that gets executed is a plain old SQL select statement.

```
-- EF+ Query Future: 1 of 6
SELECT TOP(2) [c].[Id], [c].[ClassEId], [c].[SomeProp]
FROM [ClassAs] AS [c]
WHERE [c].[Id] = 1
;

-- EF+ Query Future: 2 of 6
SELECT [c0].[Id], [c0].[SomeProp]
FROM [ClassAs] AS [c]
LEFT JOIN [ClassEs] AS [c0] ON [c].[ClassEId] = [c0].[Id]
WHERE [c].[Id] = 1
;

-- EF+ Query Future: 3 of 6
SELECT [t0].[Id], [t0].[ClassAId], [t0].[SomeProp]
FROM [ClassAs] AS [c]
INNER JOIN (
    SELECT [t].[Id], [t].[ClassAId], [t].[SomeProp]
    FROM (
        SELECT [c0].[Id], [c0].[ClassAId], [c0].[SomeProp], ROW_NUMBER() OVER(PARTITION BY [c0].[ClassAId] ORDER BY [c0].[Id]) AS [row]
        FROM [ClassBs] AS [c0]
        WHERE [c0].[SomeProp] < 2147482647
    ) AS [t]
    WHERE [t].[row] <= 5
) AS [t0] ON [c].[Id] = [t0].[ClassAId]
WHERE [c].[Id] = 1
;

-- EF+ Query Future: 4 of 6
SELECT [t0].[Id], [t0].[ClassAId], [t0].[SomeProp]
FROM [ClassAs] AS [c]
INNER JOIN (
    SELECT [t].[Id], [t].[ClassAId], [t].[SomeProp]
    FROM (
        SELECT [c0].[Id], [c0].[ClassAId], [c0].[SomeProp], ROW_NUMBER() OVER(PARTITION BY [c0].[ClassAId] ORDER BY [c0].[Id]) AS [row]
        FROM [ClassCs] AS [c0]
        WHERE [c0].[SomeProp] < 2147482647
    ) AS [t]
    WHERE [t].[row] <= 5
) AS [t0] ON [c].[Id] = [t0].[ClassAId]
WHERE [c].[Id] = 1
;

-- EF+ Query Future: 5 of 6
SELECT [t0].[Id], [t0].[ClassAId], [t0].[SomeProp]
FROM [ClassAs] AS [c]
INNER JOIN (
    SELECT [t].[Id], [t].[ClassAId], [t].[SomeProp]
    FROM (
        SELECT [c0].[Id], [c0].[ClassAId], [c0].[SomeProp], ROW_NUMBER() OVER(PARTITION BY [c0].[ClassAId] ORDER BY [c0].[Id]) AS [row]
        FROM [ClassDs] AS [c0]
        WHERE [c0].[SomeProp] < 2147482647
    ) AS [t]
    WHERE [t].[row] <= 5
) AS [t0] ON [c].[Id] = [t0].[ClassAId]
WHERE [c].[Id] = 1
;

-- EF+ Query Future: 6 of 6
SELECT [t0].[Id], [t0].[ClassAId], [t0].[SomeProp]
FROM [ClassAs] AS [c]
INNER JOIN (
    SELECT [t].[Id], [t].[ClassAId], [t].[SomeProp]
    FROM (
        SELECT [c0].[Id], [c0].[ClassAId], [c0].[SomeProp], ROW_NUMBER() OVER(PARTITION BY [c0].[ClassAId] ORDER BY [c0].[Id]) AS [row]
        FROM [ClassFs] AS [c0]
        WHERE [c0].[SomeProp] < 2147482647
    ) AS [t]
    WHERE [t].[row] <= 5
) AS [t0] ON [c].[Id] = [t0].[ClassAId]
WHERE [c].[Id] = 1
;

```

However, on our real project, the statement gets wrapped in 
```exec sp_executesql N'...'``` with parameters. 

The execution time is about 30 times longer according to SQL Profiler with the exec_sp around it.

So I would like to use the plain sql, not the stored procedure. When will/why will he device to switch between the 2, can I force it somehow to always generate the plain sql?

Thanks 
Jan

**Comment by janmarques** [comment]
OK I found that the difference is quite obvious, by replacing a hardcoded Id with a parameter id (not                     ```.SingleOrDefault(x => x.Id == 1);``` but rather ```.SingleOrDefault(x => x.Id == id);```

Performance is still not so good though :s

**Comment by JonathanMagnan** [comment]
Hello @janmarques ,

Our library just executes in batch what would have been executed in a single statement.

It doesn't optimize them. The `exec_sp` should not make a SQL take 30 times longer.

I recommend you to check the performance/index of this query outside of EF first to check what really causes this performance issue.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
