### ISSUE TITLE
Multiple IncludeOptimizedByPath Exception

### ISSUE THREAD

**Issue by CleytonGoncalves** [zzzprojects/EntityFramework-Plus#614]
### Description
Exception on multiple IncludeOptimizedByPath.

Ex: 
```
    context.Orders
        .IncludeOptimizedByPath("Seller")
        .IncludeOptimizedByPath("Items")
        .ToList()
```

### Exception
```
Exception message:
Field '_queryCompiler' defined on type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider' is not a field on the target object which is of type 'Z.EntityFramework.Plus.QueryIncludeOptimizedProvider`1[Program+Order]'.

Stack trace:
Unhandled exception. System.ArgumentException: Field '_queryCompiler' defined on type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider' is not a field on the target object which is of type 'Z.EntityFramework.Plus.QueryIncludeOptimizedProvider`1[Program+Order]'.
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at Z.EntityFramework.Plus.InternalExtensions.IsInMemoryQueryContext[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedByPath.IncludeOptimizedByPath[T](IQueryable`1 query, String navigationPath)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedExtensions.IncludeOptimizedByPath[T](IQueryable`1 query, String navigationProperties)
   at Program.Main()
```

### Fiddle or Project
https://dotnetfiddle.net/VRavfu

### Further technical details
- EF version: Core 3.1
- EF Plus version:  3.0.51
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @CleytonGoncalves ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @CleytonGoncalves ,

A new version has been released. The issue have been fixed in this version.

Let us know if everything works as expected.

Best Regards,

Jon

**Comment by CleytonGoncalves** [comment]
Working great!

Thank you.
