### ISSUE TITLE
Cache on FromSqlRaw (store procedure with parameters)

### ISSUE THREAD

**Issue by fenomeno83** [zzzprojects/EntityFramework-Plus#620]
Hi.
I need to cache a store procedure.
I use entity framework core using FromSqlRaw and cache using FromCacheAsync.

Seems that doesn't consider FromSqlRaw store parameters. So when I change them I will get every time the same results of the first cached query.

**Comment by JonathanMagnan** [comment]
Hello @fenomeno83 ,

Thank you for reporting, we will look if that's now possible to support it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @fenomeno83 ,

A new version has been released.

We improved the way we handle parameter value which should now correctly work with `FromSqlRaw`

Let me know if everything is now working,

Best Regards,

Jon

**Comment by fenomeno83** [comment]
Hi.
I've installed new version, ma seems that doesn't work.
If I change parameters used inside fromrawsql, they don't have affect (it is cached the first query with the first parameters)

Version 3.0.60

**Comment by JonathanMagnan** [comment]
Hello @fenomeno83 ,

Do you think you could provide us a runnable project?

It will help my developer to fix this issue faster and make sure your project get fixed next time he looks at it

You can send it to info@zzzprojects.com if you need to keep the source private

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by fenomeno83** [comment]
Hi.
I'll send you a me with test project

**Comment by fenomeno83** [comment]
Hi @JonathanMagnan , are you confirm that you are working on this issue? thanks

**Comment by JonathanMagnan** [comment]
Hello @fenomeno83,

Yes, we have received your project by mail. 

My developer is working on it. 

I will get back to you shortly.

Best regards,

Jon

**Comment by fenomeno83** [comment]
> Hello @fenomeno83 ,
> 
> A new version is now available.
> 
> We indeed missed a scenario which was not handled correctly when we created the cache key, it should now be fixed.
> 
> Let me know if everything is now working as expected.
> 
> Best Regards,
> 
> Jon

Now seems to work.
Thanks!

**Comment by JonathanMagnan** [comment]
Awesome @fenomeno83 !

Don't hesitate to contact us for questions, issues or feedback!

Best regards,

Jon
