### ISSUE TITLE
AddOrAppendOrderBy and AddOrAppendOrderByDescending are appended in wrong order

### ISSUE THREAD

**Issue by holpit** [zzzprojects/EntityFramework-Plus#621]
### Description
AddOrAppendOrderBy and AddOrAppendOrderByDescending are appended in reverse order.

`
 var queryableOrderIncorrect = from t in ctx.Table1 select t;

 queryableOrderIncorrect = queryableOrderIncorrect.AddOrAppendOrderBy("StartDate");

 queryableOrderIncorrect = queryableOrderIncorrect.AddOrAppendOrderByDescending("SerialId");
`

When executing the query, SerialId is appended before StartDate, changing the meaning of sort.

ORDER BY Seriald DESC, StartDate 
instead of
ORDER BY StartDate, SerialId DESC

I'm doing in the wrong manner or thers is a issue?

### Fiddle or Project
I've send a project with the issue to info@zzzprojects.com and create a fiddler: https://dotnetfiddle.net/I6yTG4

### Further technical details
- EF version: core 2.2.4
- EF Plus version: 2.0.56
- Database Provider: SqlServer

Thank you for support

**Comment by JonathanMagnan** [comment]
Thank you for reporting, we will look at it.

I recommend you if you can to move to `OrderByDynamic` and `ThenByDescendingDynamic`

```csharp
FiddleHelper.WriteTable(context.Customers.OrderByDynamic("x => x.CustomerId").ThenByDescendingDynamic("x => x.Name").ToList());
```

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @holpit ,

We checked this issue and it looks that this feature has never been coded to support `ThenByDescending`. It always performs an `OrderBy` unless multiple parameters is passed (in this case, it will do the `ThenBy` but in the same direction.

As we already support dynamic sorting as shown in my last answers, I'm not sure if we really improve this method.

**Comment by holpit** [comment]
Thank you @JonathanMagnan 
I've resolved my case as you suggested with OrderByDynamic end ThenByDescendingDynamic.
Now I'm aware how worksAddOrAppendOrderBy
