### ISSUE TITLE
Unable to passe a Func<T,bool> to a where clause in IncludeFilter

### ISSUE THREAD

**Issue by ltemimi** [zzzprojects/EntityFramework-Plus#622]
### Description
In the below Include filter I am unable to pass a Func<T,bool> or an Expression<Func<T,bool>> as my filter can change
     .IncludeFilter(i => i.Checks.Where(c => !c.IsDeleted && c.Active ))

### Exception
The exception tells me I can't pass a Func as a parameter.

Please help

**Comment by JonathanMagnan** [comment]
Hello Itemimi,

You need to pass an `Expression<Func<T1, T2>>`, the return must be an entity type or an IEnumerable<EntityType> such as:

```csharp
Expression<Func<EntitySimple, IEnumerable<EntityChild>>> filter = simple => simple.Childs.Where(x => x.ZZZ == 2);
var list = context.EntitySimples.IncludeOptimized(filter).ToList(); 
```

Let me know if that helped you,

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
