### ISSUE TITLE
Log Lookup Information

### ISSUE THREAD

**Issue by dongjason** [zzzprojects/EntityFramework-Plus#625]
### Description
Is there a way to record lookup information? For example, a Course is taught by an Instructor.  The course has a field of InstructorId storing the Id of the instructor.  If the instructor is changed, from Id 1 to Id 2, by default, it will record InstructorId changed from 1 to 2.  But that is not very good information for the user.  Is there a way to write Audit log of the Instructor name changes like from "Joe Smith" to "Thomas Wilson"?

Thanks.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Fiddle or Project
Create a Fiddle that reproduce the issue: https://dotnetfiddle.net/zB4SGA

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

_Note: If you are not able to provide code we can run and that reproduce the issue, we will not be able to fix it either._

### Further technical details
- EF version:3.1.6
- EF Plus version:3.0.57
- Database Provider:SQL Server

**Comment by JonathanMagnan** [comment]
Hello @dongjason ,

I don't think we currently have something that could support this scenario.

We indeed have a `Format` mechanism, but I don't think we currently allow easily to show the navigation property name.

Do your `Course` also have a navigation property toward the `Instructor` or you will need to retrieve it from your Context to get the instructor name?

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by dongjason** [comment]
We do have a navigational property towards the Instructor.

I was thinking of calling the format function, say for the InstructorId field, let it return x=>x.Instructor.Name instead of the raw InstructorId value.  Is that a possibility?

**Comment by dongjason** [comment]
Hi, I got it (somewhat) working using the format function override.  Test project is attached.

Please take a look, the location of setting the configuration is not ideal.  If I put the format configuration code in the Context's constructor, it gets an error because the other DBSet is not yet available.

[Test.EFPlusCoreMigration LogLookupValue.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/5029807/Test.EFPlusCoreMigration.LogLookupValue.zip)

**Comment by JonathanMagnan** [comment]
Hello @dongjason ,

Just to let you know that this request has been completed and will be released during the weekend.

You will be able to automatically add `meta property` and provide the old and new value as you wish. I will provide you an example when it will be released

**Comment by dongjason** [comment]
Jonathan,

That is great to hear.  Just to sync up our understanding, what we are trying to do is to provide some “context” for the audit information.  Hypothetically, assume we have a model with multiple relations like:  Course – Instructor – Department – University with courses information across multiple universities.  The user wants to report on course changes by university.  So we will need to store a “university-context” of the course audit record by tracing up the property chain to get the Course’s Instructor.Department.University.ID and store it in the audit record.

Is that what this fix may be able to do?

Thanks.

**Comment by JonathanMagnan** [comment]
I believe yes if I understand correctly, but I guess we will see if that perfectly to your requirement very soon

**Comment by JonathanMagnan** [comment]
Hello @dongjason ,

The v3.0.59 has been released.

You can now use the `MetaProperty` options to add additional property such as related names.

For example, if all navigations properties is populated, you can use it this way:

```csharp
AuditManager.DefaultConfiguration.MetaProperty<Course>("metaName", c => c.Instructor.Department.University.Name, c => c.Instructor.Department.University.Name);
```

This is a `Func`, so you can do pretty much anything you want such as using `Context.Find`, a dictionary or whatever technique you want to retrieve the name corresponding to the `Id` which was saved before.

So the `Id` keep being saved but you can add meta information about it.

Unfortunately, I'm missing time for an example but if you have difficulty to implement it, let me know and I will try to find it.

Let me also know if that was what you were looking for.

**Comment by dongjason** [comment]
Thanks a lot.  We will try it. On Aug 18, 2020 5:05 PM, Jonathan Magnan <notifications@github.com> wrote:
Hello @dongjason ,
The v3.0.59 has been released.
You can now use the MetaProperty options to add additional property such as related names.
For example, if all navigations properties is populated, you can use it this way:
AuditManager.DefaultConfiguration.MetaProperty<Course>("metaName", c => c.Instructor.Department.University.Name, c => c.Instructor.Department.University.Name);
This is a Func, so you can do pretty much anything you want such as using Context.Find, a dictionary or whatever technique you want to retrieve the name corresponding to the Id which was saved before.
So the Id keep being saved but you can add meta information about it.
Unfortunately, I'm missing time for an example but if you have difficulty to implement it, let me know and I will try to find it.
Let me also know if that was what you were looking for.

**Comment by JonathanMagnan** [comment]
Awesome @dongjason ,

Don't hesitate to contact us for questions, issues or feedback.

Best regards,

Jon
