### ISSUE TITLE
IncludeFilter wrong query generated.

### ISSUE THREAD

**Issue by PKFEric** [zzzprojects/EntityFramework-Plus#629]
### Description
This is the query

`.IncludeFilter(z => z.EdicionesLicenciasPartidos.Where(k => k.Id_Competicion == z.Id_Competicion && k.Id_Edicion == z.Id_Edicion)
                                                                                            .Select(h => h.Licencia)
                                                                                            .SelectMany(d => d.MediaLicencias.Where(i => i.Id_Competicion == z.Id_Competicion && i.Id_Edicion == z.Id_Edicion)))`

This is the SQL Query that generates EF+

`SELECT t1."Id", t1."Fecha_Actualizacion", t1."Fecha_Creacion", t1."Fecha_Publicable", t1."Fecha_vigencia", t1."Id_Competicion", t1."Id_Edicion", t1."Id_Licencia", t1."Id_Licencia_Subtipo", t1."Id_Licencia_Tipo", t1."Id_Media_Type", t1."Id_Usuario_UModificacion", t1."Id_Usuario_Validado", t1."Publicable", t1."Url", t1."Validado"
FROM (
    SELECT p."Id", p."Aforo", p."Fecha", p."Fecha_Actualizacion", p."Fecha_Creacion", p."Fecha_Publicable", p."Finalizado", p."Hora", p."Id_Club_Local", p."Id_Club_Visitante", p."Id_Competicion", p."Id_Edicion", p."Id_Ediciones_Equipo_Ganador", p."Id_Ediciones_Equipo_Local", p."Id_Ediciones_Equipo_Visitante", p."Id_Eliminatoria", p."Id_Equipacion_Local", p."Id_Equipacion_Visitante", p."Id_Fase", p."Id_Grupo", p."Id_Jornada", p."Id_Pabellon", p."Id_Subfase", p."Id_Usuario_UModificacion", p."Id_Usuario_Validado", p."Num_partido", p."Publicable", p."Publico", p."Puntos_local", p."Puntos_visitante", p."Validado"
    FROM "ACBSchema2"."Partidos" AS p
    WHERE (p."Publicable" = TRUE) AND (p."Id" = $1)
    LIMIT $2
) AS t
JOIN LATERAL (
    SELECT t."Id", t."Fecha_Actualizacion", t."Fecha_Creacion", t."Fecha_Publicable", t."Fecha_vigencia", t."Id_Competicion", t."Id_Edicion", t."Id_Licencia", t."Id_Licencia_Subtipo", t."Id_Licencia_Tipo", t."Id_Media_Type", t."Id_Usuario_UModificacion", t."Id_Usuario_Validado", t."Publicable", t."Url", t."Validado", e."Id" AS "Id0", l."Id" AS "Id1", e."Id_Partido", e."Id_Competicion" AS "Id_Competicion0", e."Id_Edicion" AS "Id_Edicion0"
    FROM "ACBSchema2"."EdicionesLicenciasPartidos" AS e
    INNER JOIN "ACBSchema2"."Licencias" AS l ON e."Id_Licencia" = l."Id"
    INNER JOIN (
        SELECT m."Id", m."Fecha_Actualizacion", m."Fecha_Creacion", m."Fecha_Publicable", m."Fecha_vigencia", m."Id_Competicion", m."Id_Edicion", m."Id_Licencia", m."Id_Licencia_Subtipo", m."Id_Licencia_Tipo", m."Id_Media_Type", m."Id_Usuario_UModificacion", m."Id_Usuario_Validado", m."Publicable", m."Url", m."Validado"
        FROM "ACBSchema2"."MediaLicencias" AS m
        WHERE (m."Id_Competicion" = t."Id_Competicion") AND (m."Id_Edicion" = t."Id_Edicion")
    ) AS **​t0 ON l."Id" = t."Id_Licencia"**
    WHERE (t."Id" = e."Id_Partido") AND ((t."Id_Competicion" = e."Id_Competicion") AND (t."Id_Edicion" = e."Id_Edicion"))
) AS t1 ON TRUE`

The   **t0 ON l."Id" = t."Id_Licencia"** is the bug

**Comment by JonathanMagnan** [comment]
Hello @PKFEric ,

A new version has been released. I'm not sure if that will fix your issue or not as we did slight changes.

We do not generate the query, we let Entity Framework handle this part.

If you believe you still have the issue and that's causing by us, please provide a **runnable project sample**? It will help my developer to get started to investigate it faster and make sure nothing is missing.

_Providing a project sample is now **REQUIRED**. It happened *too many times* that something **was missing** to investigate and/or answer an issue._

_Try to create a new project with only the minimal code (having too many non-related codes doesn’t help either)._  

You can send it to info@zzzprojects.com if you need to keep the source private

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
