### ISSUE TITLE
Audit | Audit Log in different Tables

### ISSUE THREAD

**Issue by zzzprojects** [zzzprojects/EntityFramework-Plus#63]
**Original Question**

> KarishImrith 
> Hi there,
> 
> This package is amazing! Makes things so much easier. However a feature is missing: I want to store audit logs in different tables per entity type because I fear that having all the logs on one table is going to cause a performance issue. Example: CustomerAuditEntry, CustomerAuditEntryProperty (so customer logs will be stored on these tables) and ProductAuditEntry, ProductAuditEntryProperty (so product logs will be stored on these tables). Thus each type has its own log tables and preventing one huge table.
> 
> On trying to work around your package to get my goal, I ran into the problem that has been posted. Cannot cast from Base class to Sub class.
> 
> Your assistance is appreciated.
> 
> Regards

**Comment by zzzprojects** [comment]
Hello KarishImrith,

Logging all in the same table will not cause performance issue. All will depend on how you will select auditing data and index. The suggested SQL script in the wiki doesn't have an index, so you may have to add it yourself if you use this table to retrieve data also.

To answer the original question, yes it's possible to log data in a different table.

Here is an example (not tested)

```csharp
public class CustomerAuditEntry: AuditEntry {}
public class CustomerAuditEntryProperty: AuditEntryProperty {}
public class ProductAuditEntry: AuditEntry {}
public class ProductAuditEntryProperty: AuditEntryProperty {}

public partial class EntityContext : DbContext
{
	public DbSet<CustomerAuditEntry> CustomerAuditEntries { get; set; }
	public DbSet<CustomerAuditEntryProperty> CustomerAuditEntryProperties { get; set; }
	public DbSet<ProductAuditEntry> ProductAuditEntries { get; set; }
	public DbSet<ProductAuditEntryProperty> ProductAuditEntryProperties { get; set; }

	// ...code...
}

AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) => {
	var ctx =  (context as EntityContext)
	
	// You can use EntitySetName, EntityName, Cast, Etc.. to determine in which DbSet to insert value
	ctx.CustomerAuditEntries.AddRange(audit.Entries.Where(x => x.Entry.Entity != null && x.Entry.Entity is Customer));
	ctx.ProductAuditEntry.AddRange(audit.Entries.Where(x => x.Entry.Entity != null && x.Entry.Entity is Product));
	
	// other types logic...
});
```

If you don't inherit from AuditEntry, you will need to import value.

See the section "Custom AuditEntry & Database First Approach" in the [Wiki](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Audit-%7C-Entity-Framework-Audit-Trail-Context-and-Track-Changes#autosave-audit)

Let me know if that answer to your question and you successfully make it work, or you need some help to implement it.

Best Regards,

Jonathan

**Comment by KarishImrith** [comment]
Hi Jonathan,

Thank you for your quick response. I have implemented the code you have suggested, it looks good to me except I am still getting that error for converting AuditEntry to one of its sub classes:

// You can use EntitySetName, EntityName, Cast, Etc.. to determine in which DbSet to insert value
    **ctx.CustomerAuditEntries.AddRange(audit.Entries.Where(x => x.Entry.Entity != null && x.Entry.Entity is Customer));
    ctx.ProductAuditEntry.AddRange(audit.Entries.Where(x => x.Entry.Entity != null && x.Entry.Entity is Product));**

I could possibly work around it by perhaps using a package like automapper to map the AuditEntry list to the appropriate sub type list. However, by any chance do you have a more elagant way of fixing this issue (cannot convert AuditEntry to sub type)?

Regards

**Comment by KarishImrith** [comment]
PS: Don't be shy to reply "Google" lol

**Comment by zzzprojects** [comment]
Hello @KarishImrith ,

Don't worry, we will help you to make it work.

As I said in my previous message, you need to implement the Custom AuditEntry & Database First Approach probably since your entity doesn't inherit from EF+ audit entity.

Here is an example to import them:
```csharp
public class CustomerAuditEntry: AuditEntry {}
public class CustomerAuditEntryProperty: AuditEntryProperty {}
public class ProductAuditEntry: AuditEntry {}
public class ProductAuditEntryProperty: AuditEntryProperty {}

public partial class EntityContext : DbContext
{
    public DbSet<CustomerAuditEntry> CustomerAuditEntries { get; set; }
    public DbSet<CustomerAuditEntryProperty> CustomerAuditEntryProperties { get; set; }
    public DbSet<ProductAuditEntry> ProductAuditEntries { get; set; }
    public DbSet<ProductAuditEntryProperty> ProductAuditEntryProperties { get; set; }

    // ...code...
}

AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) => {
    var ctx =  (context as EntityContext)

    // You can use EntitySetName, EntityName, Cast, Etc.. to determine in which DbSet to insert value
    ctx.CustomerAuditEntries.AddRange(audit.Entries.Where(x => x.Entry.Entity != null && x.Entry.Entity is Customer).Select(x => ImportCustomer(x));
    ctx.ProductAuditEntry.AddRange(audit.Entries.Where(x => x.Entry.Entity != null && x.Entry.Entity is Product).Select(x => ImportProduct(x));

    // other types logic...
})

using (var ctx = new Entities())
{
    Audit audit = new Audit();
    audit.CreatedBy = "ZZZ Projects"; // Optional

    ctx.Entity_Basic.Add(new Entity_Basic() {ColumnInt = 2});
    ctx.SaveChanges(audit);
}

public CustomerAuditEntry ImportCustomer(Z.EntityFramework.Plus.AuditEntry entry)
{
    var customAuditEntry = new CustomerAuditEntry
    {
        EntitySetName = entry.EntitySetName,
        EntityTypeName = entry.EntityTypeName,
        State = (int)entry.State,
        StateName = entry.StateName,
        CreatedBy = entry.CreatedBy,
        CreatedDate = entry.CreatedDate
    };

    customAuditEntry.AuditEntryProperties = entry.Properties.Select(x => ImportCustomer(x)).ToList();

    return customAuditEntry;
}

public CustomerAuditEntryProperty ImportCustomer(Z.EntityFramework.Plus.AuditEntryProperty property)
{
    var customAuditEntry = new CustomerAuditEntryProperty
    {
        RelationName = property.RelationName,
        PropertyName = property.PropertyName,
        OldValue = property.OldValueFormatted,
        NewValue = property.NewValueFormatted
    };

    return customAuditEntry;
}

public ProductAuditEntry ImportProduct(Z.EntityFramework.Plus.AuditEntry entry)
{
    var customAuditEntry = new ProductAuditEntry
    {
        EntitySetName = entry.EntitySetName,
        EntityTypeName = entry.EntityTypeName,
        State = (int)entry.State,
        StateName = entry.StateName,
        CreatedBy = entry.CreatedBy,
        CreatedDate = entry.CreatedDate
    };

    customAuditEntry.AuditEntryProperties = entry.Properties.Select(x => ImportProduct(x)).ToList();

    return customAuditEntry;
}

public ProductAuditEntryProperty ImportProduct(Z.EntityFramework.Plus.AuditEntryProperty property)
{
    var customAuditEntry = new ProductAuditEntryProperty
    {
        RelationName = property.RelationName,
        PropertyName = property.PropertyName,
        OldValue = property.OldValueFormatted,
        NewValue = property.NewValueFormatted
    };

    return customAuditEntry;
}
```

Let me know if that help

**Comment by KarishImrith** [comment]
Hi,

I now understand what you meant earlier by using the database first approach. Before reaching this understanding I was planning on mapping everything and it turns out that was exactly what you instructed me to do in the first place :D 

Will proceed with changes implementing the method you propose this evening. 

Just want to confirm, When you say "...since your entity doesn't inherit from EF+ audit entity." are you referring to my Customer type not inheriting from EF+ Audit? if so, are you implying that my Customer type is supposed to be inheriting from EF+ Audit? if so, could you kindly advise with reasoning and what that would allow me to do - if its not too much trouble.

Regards

**Comment by zzzprojects** [comment]
> Just want to confirm, When you say "...since your entity doesn't inherit from EF+ audit entity."...

Forget what I said ;) I made an error when writing this sentence. Since you must save in multiple tables, that will not work.

**Comment by zzzprojects** [comment]
Hello @KarishImrith ,

Can we close this issue or there is still some work to do?

**Comment by zzzprojects** [comment]
Closed Comment: Just re-open if there is still some work to do.

**Comment by KarishImrith** [comment]
I know this is super late but all in order.
Thank you for all the assistance
