### ISSUE TITLE
Parallel unit tests failing with InMemoryDbContextFactory

### ISSUE THREAD

**Issue by kdvtrifork** [zzzprojects/EntityFramework-Plus#630]
Hi again @JonathanMagnan 👋

As discussed in #344 I'm confused on how to setup the `BatchUpdateManager.InMemoryDbContextFactory` and `BatchDeleteManager.InMemoryDbContextFactory`
Our unit tests are randomly failing, and as said in the #344 it is because they are run parallel and `BatchUpdateManager.InMemoryDbContextFactory` is static so there is a clash. 

I have provided a test project on how we build our unit tests. 
Hope that can give you an idea of what our issue is. It is us doing something wrong 🤠

Thanks! ✌

[TestProject.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/5170284/TestProject.zip)

**Comment by JonathanMagnan** [comment]
Thank you for the project,

My developer will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @kdvtrifork ,

Sorry for the delay, we forget about this request.

One problem in your test might be if you have multiple `InMemoryDbContextFactory` in different other unit class.

As you understand, this property is static so if every parallel test keep overridden it, that sure doesn't help and will have some side impact.

Unfortunately, I'm not really sure what should be the best way on your side to implement it as you probably don't want to pass the factory in parameter to your repository.

Perharp for those specific case, you should run it sequential: https://stackoverflow.com/a/47174842/5619143

**Comment by kdvtrifork** [comment]
Hey! 

We got it working with running the tests sequential
