### ISSUE TITLE
Use `DB.Functions.Like()` in `WhereDynamic`

### ISSUE THREAD

**Issue by Kasta11111** [zzzprojects/EntityFramework-Plus#632]
### Description
Use `DB.Functions.Like()` in `WhereDynamic` throw error.

`context.Customers.WhereDynamic(x => "EF.Functions.Like(x.Name, \"%A%\")")`

As you can see in fiddle `Where` works fine

`context.Customers.Where(x => EF.Functions.Like(x.Name, "%A%"))`

### Exception

```
Unhandled exception. Z.Expressions.Compiler.Shared.EvalException: Oops! No applicable member has been found for the expression. The error occurred for expression "." at position 3 near ".Where(x => EF.Functions.".
```

### Fiddle or Project

Fiddle: https://dotnetfiddle.net/lOH4no

### Further technical details
- EF version: 3.1.1
- EF Plus version: 3.0.60
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @Kasta11111 ,

Thank you for reporting, we will look at how we can register some EF method by default.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/

**Comment by JonathanMagnan** [comment]
Hello @Kasta11111 ,

It took us some time but it should now works.

Starting from the v3.0.64, `EF.Functions` methods should now be automatically registered for SQL Server (not true for other providers for now)

**Comment by Kasta11111** [comment]
@JonathanMagnan 
Thank you, I did a few tests and it's working so far.
If I find something in the future I will let you know.

Thank you, good job. 👍

**Comment by JonathanMagnan** [comment]
Awesome!

We are glad everything is working out for you!

Feel free to contact us with any questions, issues or feedback.

Best regards,

Jon
