### ISSUE TITLE
Can I handle the transaction?

### ISSUE THREAD

**Issue by rex-pj** [zzzprojects/EntityFramework-Plus#634]
Hi
I am using the DeleteFromQuery to execute the batch delete, I want to delete data from several tables and I want to handle the transaction to commit when completed or rollback when exceptions are met.

So Do we have any transaction managed?

**Comment by JonathanMagnan** [comment]
Hello @rex-pj ,

Yes, the transaction started from the Context should be handled by the `DeleteFromQuery` method.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by mtinnes** [comment]
Hi Jonathan, I'm assuming the Delete() and DeleteAsync() extensions are also compatible with transactions for bulk delete ops?

**Comment by JonathanMagnan** [comment]
Unlike we are missing something, yes.

If a transaction is started within Entity Framework, the code should use it.

**Comment by rex-pj** [comment]
@JonathanMagnan
As I test in my application, the data is deleted after the DeleteFromQuery() is executed, and no ways to rollback.
For example:
dbContext.Articles.DeleteFromQuery(); // Deleted
dbContext.Users.DeleteFromQuery(); // Deleted
dbContext.SaveChanges(); // No meaning

So the data is deleted after DeleteFromQuery() and even the SaveChanges() is no meaning, I also test with a transaction like BeginTransaction() then use Rollback() but the data still not rollback().

**Comment by rex-pj** [comment]
Btw, I can handle the transaction by using dbContext.BeginTransaction() and I can Commit and Rollback also, my problem is solved, thanks for your help.

**Comment by Jalalx** [comment]
I think issues like ignoring `DbContext.SaveChanges()` and respecting `DbContext.Database.BeginTransaction()` must be included in the docs.
