### ISSUE TITLE
Way to get status of selected filter

### ISSUE THREAD

**Issue by grinay** [zzzprojects/EntityFramework-Plus#640]
Hello. I need to get the current status of filter and check if it is enabled or disabled . How can i do that?
I define filter for dbContext instance like that:

dbContext.Filter<IMayHaveTenant>(nameof(IMayHaveTenant), q=>q.Where(actualQuery))

**Comment by JonathanMagnan** [comment]
Hello @grinay ,

Unfortunately, there is no easy way to know it by query or entity type.

However, if you don't filter per specific type, you can always get it this way:

```csharp
var isEnabled = QueryFilterManager.Filter(nameof(IMayHaveTenant)).IsDefaultEnabled;
```

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by grinay** [comment]
> Hello @grinay ,
> 
> Unfortunately, there is no easy way to know it by query or entity type.
> 
> However, if you don't filter per specific type, you can always get it this way:
> 
> ```cs
> var isEnabled = QueryFilterManager.Filter(nameof(IMayHaveTenant)).IsDefaultEnabled;
> ```
> 
> Best Regards,
> 
> Jon
> 
> **Performance Libraries**
> `context.BulkInsert(list, options => options.BatchSize = 1000); `
> [Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) • [Dapper Plus](http://dapper-plus.net/)
> 
> **Runtime Evaluation**
> `Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
> [C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

But is understand correct base on property name is will return the default status of that filter, but not the current status. Is that true?

**Comment by JonathanMagnan** [comment]
Are you using EF6 or EF Core? Both filter work very differently

**Comment by JonathanMagnan** [comment]
Hello @grinay 

Since our last conversation, we haven't heard from you.

As mentioned in my previous message, would it be possible to know the EF version that you are using?

Looking forward to hearing from you, 

Jon

**Comment by grinay** [comment]
> Hello @grinay
> 
> Since our last conversation, we haven't heard from you.
> 
> As mentioned in my previous message, would it be possible to know the EF version that you are using?
> 
> Looking forward to hearing from you,
> 
> Jon

Sorry. Yes i'm using EF Core 3.

**Comment by JonathanMagnan** [comment]
Hello @grinay ,

We looked at the code and it seems there is no easy way to retrieve it or to add this option.

Adding an option doesn't look to be easy as the `QueryFilter` is pretty much shared through context and query. So when disabling a filter for a specific context, for example, we cannot keep the `IsDisabled` value without creating a new `QueryFilter` instance per context or even per query.

So, unfortunately, unless we re-write this feature, I don't think it's currently possible.

Best Regards,

Jon

**Comment by grinay** [comment]
Ok. Anyway already implemented it a way with "wrapper" pattern around filter enable and disable methods to order track those changes. Thanks.
