### ISSUE TITLE
IncludeOptimized projection does not work on Z.EntityFramework.Plus.EFCore 3.0.63

### ISSUE THREAD

**Issue by PavanTupuri** [zzzprojects/EntityFramework-Plus#641]
### Description
IncludeOptimized projection does not work on Z.EntityFramework.Plus.EFCore 3.0.63. There is no exception, but returns null.

```

### Code Sample:

public class Customer
	{
		public int CustomerID { get; set; }
		public string Name { get; set; }
		public List<Address> Contact { get; set; }
	}
	
	public class Address
	{
		public int AddressID { get; set; }
		public string Location { get; set; }
		public Boolean IsActive { get; set; }
	}

var result = context.Customers.IncludeOptimized(p => p.Contact.Where(q => q.IsActive)).FirstOrDefault()

result.Contact is always null




### Further technical details
- EF version: Microsoft.EntityFrameworkCore 3.1.0
- EF Plus version: Z.EntityFramework.Plus.EFCore 3.0.63
- Database Provider: Microsoft SQL Server

**Comment by JonathanMagnan** [comment]
Hello @PavanTupuri ,

Could you give us an example, your scenario look to work: https://dotnetfiddle.net/mdQTqK

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
