### ISSUE TITLE
The monthly trial period is expired (Is not free ?)

### ISSUE THREAD

**Issue by wtujvk** [zzzprojects/EntityFramework-Plus#644]
### Description
Describe the issue or proposed feature.
It say "EF Plus is FREE and will always be!" , But not. (at  https://entityframework-plus.net/download )

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).
Install-Package Z.EntityFramework.Plus.EF6 -Version 1.12.39 

Exception message: 
ystem.Exception: ERROR_005: The monthly trial period is expired. You can extend your trial by downloading the latest version as the beginning of every month. More information can be found here: https://entityframework-extensions.net/trial
Stack trace:
 在 .(ProviderType , Boolean , Boolean , Boolean , Boolean )
   在 Z.BulkOperations.BulkOperation.Execute()
   在 Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkInsert()
   在 .BulkInsert[T](BulkOperation`1 this, DbContext context, List`1 list, Boolean isManager, List`1 entitiesToUpdate, Type type, String typeName)
   在 .`1.(SchemaEntityType )
   在 System.Collections.Generic.List`1.ForEach(Action`1 action)
   在 .BulkInsert[T](DbContext this, BulkOperation`1 bulkOperation, IEnumerable`1 entities2, List`1 entitiesToUpdate)
   在 .BulkInsert[T](BulkOperation`1 this, DbContext context, IEnumerable`1 entities, List`1 entitiesToUpdate)
   在 DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   在 DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities)

### Fiddle or Project
Create a Fiddle that reproduce the issue: https://dotnetfiddle.net/zB4SGA

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

_Note: If you are not able to provide code we can run and that reproduce the issue, we will not be able to fix it either._

### Further technical details
- EF version:  6.2.0
- EF Plus version: 1.12.33
- Database Provider:
- Partial Packages:
  package id="EntityFramework" version="6.2.0" targetFramework="net461" 
  package id="Z.EntityFramework.Extensions" version="4.0.92" targetFramework="net461" 
  package id="Z.EntityFramework.Plus.EF6" version="1.12.33" targetFramework="net461" 
  package id="Z.Expressions.Eval" version="4.0.15" targetFramework="net461"

**Comment by JonathanMagnan** [comment]
Hello @wtujvk ,

Yes, the monthly trial is free. 

The latest version always contains a trial that expires at the end of the month. 

You can extend your trial for several months by downloading the latest version at the beginning of every month.

Let us know if you need further assistance. 

Best regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @wtujvk ,

Since our last conversation, we haven't heard from you.

Don't hesitate to contact us for further information regarding our library/

Best regards,

Jon
