### ISSUE TITLE
[Feature Request] Auditing, Soft Delete, Multi Tenant, Global Query Filters using shadow properties

### ISSUE THREAD

**Issue by ma3yta** [zzzprojects/EntityFramework-Plus#648]
### Description
https://trailheadtechnology.com/entity-framework-core-2-1-automate-all-that-boring-boiler-plate/

**Comment by JonathanMagnan** [comment]
Hello @Ma3yTa ,

Thank you for reporting, we will look at this feature.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
