### ISSUE TITLE
conditional caching on query fields?

### ISSUE THREAD

**Issue by aloksharma1** [zzzprojects/EntityFramework-Plus#649]
### Description
suppose for this query caching code
`var countries1 = ctx.Products.FromCache().ToList();`
is is possible to cache it partially so for product price and quantity is always queries from latest? this is required in some scenarios where main info doesn't change much but selective fields must remain up-to-date.

So i propose a method call like this
`var countries1 = ctx.Products.FromCache(x=>x.exclude(x.price) && x.exclude(x.qty)).ToList();`

**Comment by JonathanMagnan** [comment]
Hello @aloksharma1 ,

Unfortunately, we don't have an `Exclude` feature, we tried recently (last month) but didn't succeed to complete it.

So this is something that maybe something that might code later (which will work with and without the caching), but for now, we don't have any solution for this.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
