### ISSUE TITLE
Unable to build Trimmed app.

### ISSUE THREAD

**Issue by RomanHubyak** [zzzprojects/EntityFramework-Plus#652]
### Description
Unable to build an app with trimming enalbed.

### Exception

![image](https://user-images.githubusercontent.com/46841287/99072054-f5548080-25bb-11eb-9b9a-855eec1cb930.png)

### Further technical details
- EF version: EF Core 5.0
- EF Plus version: <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="5.1.0" />
- Database Provider: <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0" />

**Comment by JonathanMagnan** [comment]
Hello @RomanHubyak ,

First, we don't know anything at all about `trimming`. So it's currently hard to help here.

Are you using the following option: "Trim unused assemblies (in preview)." ?

If yes, I saw two solutions:
- Disable this option obviously
- Make any call to the library such as `Eval.Execute("1+1")` or `typeof(EvalManager)` in your project, so the assembly don't get "trimmed"

I don't think we can do anything on our side in the library to make it compatible.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
