### ISSUE TITLE
Question: Is `WithHint` extension method secure?

### ISSUE THREAD

**Issue by shoter** [zzzprojects/EntityFramework-Plus#660]
### Description
I had found extension method during my usage of `EntityFramework-Plus` project. I can use hints defined in `SqlServerTableHintFlags` and everything seems to work well but I am unable to find any piece of documentation about this feature. Is that method secure to use?

### Further technical details
- EF version: 3.1.8
- EF Core Plus version: 3.0.62.0,
- Database Provider: MSSql

**Comment by JonathanMagnan** [comment]
Hello @shoter ,

Yes, you can use it for SQL Server.

We hope to find time to document all new features during Christmas break

Let me know if that answers correctly to your question or if you have a question about how it works.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by shoter** [comment]
I am happy to hear that - thanks! :)

It would also be nice to see it in the repository as I am unable to find it. Is it intentional?

**Comment by JonathanMagnan** [comment]
Yes,

It shares too much code with some paid features such as `WhereBulkContains`, so it was impossible to make it 100% standalone yet.

**Comment by shoter** [comment]
Thank you answer. I am closing this issue then.
