### ISSUE TITLE
Batch delete or batch update with User Defined Table Type parameter

### ISSUE THREAD

**Issue by daujyungx** [zzzprojects/EntityFramework-Plus#661]
### Description

An Exception occurs (System.ArgumentException: No mapping exists from object type System.Object[] to a known managed provider native type. ) when batch delete or batch update with User Defined Table Type parameter.

### Fiddle or Project

https://dotnetfiddle.net/onPtaW

### Further technical details

- EF version: 3.1.10
- EF Plus version: 3.1.6

**Comment by JonathanMagnan** [comment]
Hello @daujyungx ,

Thank you for reporting, we will investigate what possible solution we could do to support UDT.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @daujyungx ,

My developer tried to support it but it's currently a little bit too complex to make it happens.

At this moment, the only solution we can provide is using the `WhereBulkContains` extension methods. However, this method is part of our paid library: https://entityframework-extensions.net/

Here is an online example: https://dotnetfiddle.net/nMXtRJ

Let me know if this solution works for you,

Best Regards,

Jon
