### ISSUE TITLE
JSON property not working with IncludeOptimized

### ISSUE THREAD

**Issue by nicumaxian** [zzzprojects/EntityFramework-Plus#665]
### Description
When querying entity containing JSON Property with `IncludeOptimization`, an exception is thrown.

### Exception
```
Exception message:
Unable to cast object of type 'System.String' to type 'Newtonsoft.Json.Linq.JObject'

Stack trace:
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Newtonsoft.Json.Linq.JObject'.
   at Z.EntityFramework.Plus.CreateEntityDataReader.GetFieldValue[T](Int32 ordinal)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
```

### Fiddle or Project
```
public class Vital
    {
        [Column("id")] public int Id { get; set; }

        [Column("resident_id")] public int ResidentId { get; set; }
        public virtual Resident Resident { get; set; }

        [Column("type")] public byte Type { get; set; }

        [Column("data")] public JObject Data { get; set; }

        [Column("performed_date")] public DateTime PerformedDate { get; set; }

        [Column("created_on_utc")] public DateTime CreatedOnUtc { get; set; }

        [Column("updated_on_utc")] public DateTime UpdatedOnUtc { get; set; }

        [Column("deleted")] public bool Deleted { get; set; }
    }

[Table("resident")]
    public class Resident
    {
        
        [Column("id")]
        public int Id { get; set; }

        [Column("allergies")]
        public string Allergies { get; set; }

        
        [Column("active")]
        public bool Active { get; set; }
        
        [Column("deleted")]
        public bool Deleted { get; set; }
    }

    public class ApplicationContext : DbContext
    {
        public DbSet<Vital> Vitals { get; set; }


        static ApplicationContext()
        {
            
            NpgsqlConnection.GlobalTypeMapper.UseJsonNet();
        }
        
        public ApplicationContext(DbContextOptions options) : base(options)
        {
        }
    }

namespace EfPlusPlayground
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var buildServiceProvider = BuildServiceProvider();

            var applicationContext = buildServiceProvider.GetService<ApplicationContext>();

            var data = await applicationContext.Vitals
                .IncludeOptimized(e => e.Resident)
                .ToListAsync();

            Console.WriteLine(ObjectDumper.Dump(data, DumpStyle.CSharp));
        }

        private static ServiceProvider BuildServiceProvider()
        {
            var serviceCollection = new ServiceCollection();
            serviceCollection.AddLogging(cfg => cfg.AddConsole());
            serviceCollection.AddDbContext<ApplicationContext>(
                cfg => cfg.UseNpgsql("User ID=postgres;Password=test;Host=localhost;Port=5432;Database=playground;")
            );

            var buildServiceProvider = serviceCollection.BuildServiceProvider();
            return buildServiceProvider;
        }
    }
}
```

This examples uses `Npgsql.Json.NET` to use Newtonsoft instead of default `System.Text.Json` from [Npgsql](https://www.npgsql.org/efcore/mapping/json.html?tabs=data-annotations%2Cpoco).
With `System.Text.Json` query also fails.

### Further technical details
- EF version: 3.1.10
- EF Plus version: Z.EntityFramework.Plus.EFCore 3.1.8
- Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL 3.1.4

**Comment by JonathanMagnan** [comment]
Hello @nicumaxian

Thank you for reporting, my developer has a very similar issue to look when he will be back from Christmas break next week.

I will ask him to look at this one as well if a solution is found.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @npbenjohnson ,

The v3.1.11 has been released last week but it looks like I forget to answer you.

Could you try it and let me know if my developer successfully fixed your issue.

He is currently not sure if the issue he fixed is the same as yours. If that's not the case, could you provide a runnable project with only this issue? You can send it in private here: info@zzzprojects.com (or a Fiddle if the website work). He told me that some configuration was missed so he added some code to make it works.

Best Regards,

Jon
