### ISSUE TITLE
When i enable audit auto save, it will throw exception when call SaveChangesAsync

### ISSUE THREAD

**Issue by skywalkeryin** [zzzprojects/EntityFramework-Plus#667]
### Description
The exception  "A second operation started on this context before a previous operation completed. " throwed, when call SaveChangesAsync

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext
```

### Fiddle or Project

```csharp
    public class CrmContext : DbContext
    {

        private  readonly ILoggerFactory _loggerFactory;
        public string AuditCreatedBy { get; set; }

        public CrmContext()
        {
            //If I comment below code, then it can save without any error.
            AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
                    // ADD "Where(x => x.AuditEntryID == 0)" to allow multiple SaveChanges with same Audit
                    (context as CrmContext).AuditEntries.AddRange(audit.Entries);
        }
        public CrmContext(DbContextOptions options, ILoggerFactory loggerFactory) : base(options)
        {
            this._loggerFactory = loggerFactory;
        }


        public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
        {
            var audit = new Audit();
            if (!string.IsNullOrEmpty(AuditCreatedBy))
            {
                audit.CreatedBy = AuditCreatedBy;
            }
            audit.PreSaveChanges(this);
            var rowAffecteds = await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
            audit.PostSaveChanges();

            if (audit.Configuration.AutoSavePreAction != null)
            {
                audit.Configuration.AutoSavePreAction(this, audit);
                await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
            }

            return rowAffecteds;
        }

        #region "DbSets"
       ...
        // added for db Change change Audit
        public DbSet<AuditEntry> AuditEntries { get; set; }
        public DbSet<AuditEntryProperty> AuditEntryProperties { get; set; }

        
        #endregion
    }
```

### Further technical details
- EF version: 3.1.2.0
- EF Plus version:3.0.40.0
- Database Provider:3.1.2.0

**Comment by JonathanMagnan** [comment]
Hello @Jon,
 
Do you think you could provide a **runnable project sample** for this issue? It will help my developer to get started to investigate it faster and make sure nothing is missing.

I saw you added some code, however by looking at it, it seems to be a very basic usage of the audit features. Everything seems fine on your side about the `async`. So I'm pretty sure something is missing to be able to reproduce it. Having a runnable project will ensure that we have everything to investigate it.

_Providing a project sample is now **REQUIRED**. It happened **too many times** that something **was missing** to investigate and/or answer an issue._

_Try to create a new project with only the minimal code (having too many non-related codes doesn’t help either)._  

You can send it to info@zzzprojects.com if you need to keep the source private

Best Regards,
 
Jon
 
---
 
**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)
 
**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by skywalkeryin** [comment]
Hi sir, 
The error fixed. It's not the audit issue.

**Comment by JonathanMagnan** [comment]
Awesome, thank for letting us know.
