### ISSUE TITLE
Transaction (Process ID 146) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction

### ISSUE THREAD

**Issue by wtujvk** [zzzprojects/EntityFramework-Plus#668]
### Description
DbSet.Where(predicate).Update(update);
var t =new TViewModel(){  Id=53, TaskDetailStatusPad =2 };
like: DbSet.Where(c=>c.id == t.Id).Update(c=>new Model(){ FailCount = t.FailCount ,TaskDetailStatusPad = t.TaskDetailStatusPad }); 

### Exception
System.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 146) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

```
Exception message:
Stack trace:
System.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 146) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   在 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   在 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   在 System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   在 System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   在 System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c.<NonQuery>b__4_0(DbCommand t, DbCommandInterceptionContext`1 c)
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   在 DbContextExtensions.[](IQueryable`1 , Expression`1 , Action`1 , Boolean )
   在 DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression, Action`1 bulkOperationFactory)
   在 Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory, Action`1 batchUpdateBuilder)
   在 Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateFactory)
   在 PowerEasy.StaticHtmlManage.Foundation.Logic.GenericRepository`2.BatchUpdate(Expression`1 predicate, Expression`1 update) 位置 D:\xx\\Logic\GenericRepository.cs:行号 101
   在 xx.Foundation.Logic.BaseLogic`2.BatchUpdate(Expression`1 where, Expression`1 update) 位置 D:\xx\Logic\BaseLogic.cs:行号 130
   在 xx.Logic.StaticHtmlManageDataLogic.UpdateTaskModelAfterAddFileOrDelete(xxDetail staticHtmlGenerationTaskDetail) 位置 D:\xx\Logic\StaticHtmlManageDataLogic.cs:行号 123
ClientConnectionId:2d75ec28-7440-4d06-aec0-9af5e12bf50b
Error Number:1205,State:51,Class:13

### Fiddle or Project
Create a Fiddle that reproduce the issue: https://dotnetfiddle.net/zB4SGA

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

_Note: If you are not able to provide code we can run and that reproduce the issue, we will not be able to fix it either._

### Further technical details
- targetFramework="net461"
- EF version: 6.4.0
- EF Plus version: 1.12.20
- Database Provider: .SqlServer

**Comment by JonathanMagnan** [comment]
Hello @wtujvk ,

If you wish, you can force the lock this way:

```csharp
context.Customers.Update(x => new Customer {IsActive = false}, options => options.UseTableLock = true);
```

At this moment, this is pretty much the maximum that is possible to do to avoid some deadlock.

We will eventually improve the library to allow a more optimized `UPDATE` statement for a simple scenario but there is no short term plan to doing it right now.

Let me know if that answers successfully your question.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by wtujvk** [comment]
It should be used lock before  Update ？
like this:
`
private static object lockObject =new objcet();

var t = new TViewModel(){ Id=53, TaskDetailStatusPad =2 };
lock(lockObject){
DbSet.Where(c=>c.id == t.Id).Update(c=>new Model(){ FailCount = t.FailCount ,TaskDetailStatusPad = t.TaskDetailStatusPad });
}
`

**Comment by JonathanMagnan** [comment]
Hello @wtujvk ,

This is the table that requires a lock, not your application.

Locking this part of the code in your application will not fix anything if the is a deadlock with another query somewhere else in your application.

```csharp
context.Customers.Update(x => new Customer {IsActive = false}, options => options.UseTableLock = true);
```

When using this option, a `TABLOCK` hint is added: https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table?view=sql-server-ver15

Best Regards,

Jon

**Comment by wtujvk** [comment]
I Walkthrough my code. Is this the cause?

`context.Customers.Update(x => new Customer {IsActive = false});`
`context.SaveChange();`

**Comment by JonathanMagnan** [comment]
Hello @wtujvk ,

SQL Server has a lock escalation, so even if you specify a row low, it could be escalated to a page or table lock when updating thousands of rows.

At this moment, we only have the `UseTableLock` option and I'm not sure a simple row lock will have any effect on this problem.

The `Update` method is an immediate method like `SaveChanges`, As soon as you call it, the query is executed so you don't have to call `SaveChanges` after. It should not be a problem however if there is no change.

The problem can come from multiple reasons, this really depends on how you use your transaction as they must be as short as possible.

At this point, if you only have a single row, I would recommend you to instead write the query or use directly EF. It will solve your problem without having to use the table lock.

**Comment by wtujvk** [comment]
I think the problem occurred in Incorrect Task relationship。

Task1=> 并行 subTask1, subTask2, subTask3 => updateStatus
Task2=> 并行 subTask1, subTask2, subTask3 => updateStatus
![image](https://user-images.githubusercontent.com/17868266/106685461-67f55b00-6603-11eb-969a-b133272c73e4.png)


I use `Task.WaitAll(Task1,Task2)`, but it not sure  `subTask1, subTask2, subTask3` isComplete. So I should relation there , add `TaskCreationOptions.AttachedToParent` For subTask1, subTask2, subTask3. After this,  update details status.

---------------------------------------------------------
我认为问题发生在多线程Task的问题上。父子线程关系不明确，导致子线程被错误的多次执行，从而引发死锁的问题。应该将subTask1, subTask2, subTask3添加到父任务上。Task和subTask都执行完然后更新状态 才能算任务完成。

**Comment by JonathanMagnan** [comment]
Hello @wtujvk ,

Honestly is starts to be out of the scope of how I can help you.

I don't know at 100% how your application work, so making such a recommendation is very hard and might be right and wrong depending on the situation.

If the deadlock happens exactly in this situation, this can be caused by our library how the "UPDATE" sql is made. While we for sure one day modify it to improve it, there is no short term plan to do it now. So meanwhile, in this exact situation, the only option, if you want to keep using our library, is using table lock. Otherwise, you can create your own `UPDATE` statement, if you keep it simple (not like us), you will probably not get this error.
