### ISSUE TITLE
UpdateBatch doesn't update all records when condition specified

### ISSUE THREAD

**Issue by vkrylovets** [zzzprojects/EntityFramework-Plus#670]
Hey there!

I have a question regarding UpdateBatch with the BatchSize and update conditions specified on EF Plus v.3.1.15

**Issue description**
Here is an example. We have Policies table with over 90k records. 68,080 of them are not enabled. But after executing the following code we get 98 affected rows.
```
var affectedRows = await context.Policies
    .Where(policy => policy.IsEnabled == false)
    .UpdateAsync(
        policy => new Policy { Tooltip = policy.Tooltip },
        update => { update.BatchSize = 100; });
```
Generated query:

```
DECLARE @stop INT
DECLARE @rowAffected INT
DECLARE @totalRowAffected INT
DECLARE @ZZZ_INDEX INT

SET @stop = 0
SET @totalRowAffected = 0
SET @ZZZ_INDEX = 0

SELECT Z_Batch.[PolicyId],
       ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS ZZZ_INDEX
INTO #ZZZBatch_0817540c_1706_4fa2_80a8_09d1e5fce53f
FROM [Policies] AS Z_Batch 

WHILE @stop = 0
BEGIN
    UPDATE A 
    SET A.[Tooltip] = B.[Tooltip]
    FROM [Policies] AS A
    INNER JOIN ( SELECT * FROM #ZZZBatch_0817540c_1706_4fa2_80a8_09d1e5fce53f AS ZZZ_temp
                WHERE ZZZ_temp.ZZZ_INDEX > @ZZZ_INDEX AND ZZZ_temp.ZZZ_INDEX <= @ZZZ_INDEX + 100
               ) AS ZZZ_Batch ON A.[PolicyId] = ZZZ_Batch.[PolicyId]
    INNER JOIN ( SELECT [p].[PolicyId], [p].[IsEnabled], [p].[Tooltip]
FROM [Policies] AS [p]
WHERE [p].[IsEnabled] = CAST(0 AS bit)
               ) AS B ON A.[PolicyId] = B.[PolicyId]

    SET @rowAffected = @@ROWCOUNT
    SET @ZZZ_INDEX = @ZZZ_INDEX + 100
    SET @totalRowAffected = @totalRowAffected + @rowAffected

    IF @rowAffected < 100
        SET @stop = 1
END

SELECT @totalRowAffected
```

The issue here is that we update only the records which satisfy condition `[p].[IsEnabled] = CAST(0 AS bit)` out of the first 100 and stop because of this:
```
    IF @rowAffected < 100
        SET @stop = 1
```

So generated query going to update records in batches of 100 till the moment when the first record not meeting the specified condition found.
Is it an issue or made for some reason? 

**Solution**
Having specified condition in the inserting query resolves the issue:
```
SELECT Z_Batch.[PolicyId],
       ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS ZZZ_INDEX
INTO #ZZZBatch_0817540c_1706_4fa2_80a8_09d1e5fce53f
FROM [Policies] AS Z_Batch 
WHERE [Z_Batch].[IsEnabled] = CAST(0 AS bit)
```

Best regards,
Viktor

**Comment by JonathanMagnan** [comment]
Hello @vkrylovets ,

Thank for reporting, that's indeed a very wrong behavior.

My developer will look at it and fix it asap. We already discussed the solution.

We cannot use your solution as we don't generate this part using your queries. For a simple scenario, we could probably find a way but for more scenarios with join, it could become troublesome.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @vkrylovets ,

The v5.1.17 has been released.

We indeed have a very bad logic to handle the `BatchSize`.

Could you try this latest version and let me know if everything is now working correctly?

Best Regards,

Jon

**Comment by vkrylovets** [comment]
Hello, @JonathanMagnan 

Just checked v3.1.17
Now `UpdateBatch` works like a charm. 
Generated SQL is correct. Thanks!

Best regards,
Viktor
