### ISSUE TITLE
Future and TransactionScope

### ISSUE THREAD

**Issue by tomerpeled** [zzzprojects/EntityFramework-Plus#671]
Is FutureQuery should work with a tranaction scope?
Say I want to run my "Future" queries in a read uncommitted isolation level, how can I do that?
For now, I'm getting the following exception:
"Root ambient transaction was completed before the nested transaction. The more nested transactions should be completed first."

Code example:
`using (new TransactionScope(TransactionScopeOption.Required, new TransactionOptions { IsolationLevel = System.Transactions.IsolationLevel.ReadUncommitted }, TransactionScopeAsyncFlowOption.Enabled))`
`{`
`	var gFuture = ctx.Groups.Take(1).Future();`
`	var uFuture = ctx.Users.Take(1).Future();`
`	gFuture.ToList().Dump();`
`}`

**Comment by tomerpeled** [comment]
OK I'll answer myself:
While using TransactionScopeOption.Suppress instead or TransactionScopeOption.Required it indeed works. Make sense when you think of how the Future transaction works.

**Comment by JonathanMagnan** [comment]
Hello @tomerpeled ,

We didn't successfully reproduce your issue. A transaction should not be created by our library for the QueryFuture features, we only use it if there is one already started.

However, it looks like you find out your solution.
