### ISSUE TITLE
Cannot find assembly when using newer extension

### ISSUE THREAD

**Issue by mrfatmen** [zzzprojects/EntityFramework-Plus#673]
I've updated my nuget packages and nu i get a Cannot find assembly Z.EntityFramework.Extensions, Version=5.1.19.0, Culture=neutral, PublicKeyToken=59b66d028979105b exception when setting the AuditManager configuration.

I have update my nuget packages from Z.Entityframework
Z.EntityFramework.Plus.EF6 to 5.1.19.0
Z.EntityFramework.Extensions to 5.1.22.0

Now when i start my application and the context class is initiated the following code when be executed.
```
  public partial class Context : DbContext
    {
        static Context()
        {
            AuditManager.DefaultConfiguration.Exclude(P => true);
            AuditManager.DefaultConfiguration.IncludeDataAnnotation();
            AuditManager.DefaultConfiguration.ExcludeDataAnnotation();
        }
<...>
```

When the AuditManager.DefaultConfiguration.Exclude(P => true); is hit, i get a exception that i can't find the "Z.EntityFramework.Extensions, Version=5.1.19.0" which is correct because it is 5.1.22.0.
In the app.config there is a binding rule tot version 0.0.0.0 - 5.1.22.0 should use 5.1.22.0

But still i get this error. I have now downgraded the extensions to 5.1.19 and everything works.
Shouldn't this also work with this newer version?

**Comment by JonathanMagnan** [comment]
Thank you for reporting,

Strongly named assembly requires the exact version which could explain why this issue happens.

A new version of EF Plus will be released later tonight. So you will be able to upgrade to every latest version of EF Plus and EFE.

When `EF Core 6` will be released, we will discuss for keeping the same assembly version but updating only the `AssemblyFileVersion`. It will fix this kind of issue but will probably bring a few others so we will double check when it will be time.

I will let you know when the new version will be ready.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @mrfatmen ,

The v5.1.23 has been released. So you can now upgrade to this version in EF Plus.

We will discuss later this week here how we should handle this scenario (either by forcing a specific version in the NuGet package or keeping the same assembly version).

**Comment by JonathanMagnan** [comment]
Hello @mrfatmen ,

Just to let you know that EF Plus will now have a forced dependency of EF Extensions. This means you will no longer able to upgrade to the newest version of EF Extensions without updating EF Plus first.

We usually release EF Plus 2-3 times a month, so I don't think it should be such a problem and have the advantage to avoid this exception.

Best Regards,

Jon

**Comment by mrfatmen** [comment]
Hello Jon,

Thank you, this would be perfect solution.
