### ISSUE TITLE
NRE when deleting shared entity type

### ISSUE THREAD

**Issue by achikhv** [zzzprojects/EntityFramework-Plus#676]
Hello!

## 1. Description
Getting NullReferenceException when trying to batch delete a SharedEntityType. 

## 2. Exception
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Z.EntityFramework.Extensions.BatchDelete.Execute[T](IQueryable`1 query)
   at BatchDeleteExtensions.DeleteFromQuery[T](IQueryable`1 query, Action`1 batchDeleteBuilder)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query, Action`1 batchDeleteBuilder)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query)
   at ConsoleApp.Program.Main(String[] args) in C:\Users\chichkov\source\repos\ConsoleApp6\Program.cs:line 42
```

## 3. Fiddle or Project
Here is the sample project in .NET5. It uses latest release version of EFCore 5.0.4 and the latest version of EFPlus 5.1.25
```
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Z.EntityFramework.Plus;

namespace ConsoleApp
{
	public class User
	{
		public int Id { get; set; }

		public string Name { get; set; }
	}

	class Context : DbContext
	{
		public DbSet<User> Users => Set<User>("User");

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer("Data Source=(localdb)\\MsSqlLocalDb; Initial Catalog=STE_Test; Integrated Security = true");
			optionsBuilder.LogTo(Console.WriteLine);
		}

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			modelBuilder.SharedTypeEntity<User>("User");
		}
	}


	public static class Program
	{
		public static void Main(string[] args)
		{
			var context = new Context();
			context.Database.EnsureDeleted();
			context.Database.EnsureCreated();
			
			context.Users.Where(x => x.Name == "test")
                                // Here goes exception
				.Delete();
		}
	}
}
```

I can't figure out if it is a bug or I am doing something wrong. Any help will be appreciated. 
Thanks in advance!

**Comment by JonathanMagnan** [comment]
Hello @achikhv ,

The issue happens because the model doesn't return the `EntityType` for `SharedEntityType`.

So in short, this line cause the problem in our code:

```csharp
dbContext.Model.FindEntityType(typeof(T));
```

A possible solution has already been found on our side. We are currently testing it.

I will give you an update soon.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @achikhv ,

The v5.1.26 has been released.

We will need to look deeper in our library to see if there is some more side impact with `SharedEntityType` but this scenario should now work correctly.

Let me know if everything also works on your side.

**Comment by achikhv** [comment]
Hello @JonathanMagnan

I've just tried 5.1.26, and the bug is fixed. Everything is working as expected.

Thank you!

**Comment by JonathanMagnan** [comment]
Awesome @achikhv !

We are glad to hear that the v5.1.26 fixed the issue!

Don't hesitate to contact us with any questions, 

Jon
