### ISSUE TITLE
Slow audit log request on big dataset. 

### ISSUE THREAD

**Issue by grinay** [zzzprojects/EntityFramework-Plus#685]
Hello Guys. 
First of all thanks for the libraries you provide. 
We using that extensively in our project. 

But I face an issue with querying the audit log in our database. It's really slow and often finished with a timeout (30 sec)
I solved this issue by extending the audit log by adding an extra field EntityId to the AuditEnty entity. And added indexes into AuditEntry property name and EntityId which is automatically filled based on GetPrimaryKey and then getting value in a factory method. 

Noticed that you appreciate the contribution and I would happy to add our extensions which I wrote for the audit log and also a few for Query filters as well. 

I wanted to ask if I can suggest some changes to speed up the audit log this way and make a PR? 
Wasn't sure where to ask this question.

**Comment by JonathanMagnan** [comment]
Hello @grinay ,

Honestly, I'm not sure to follow your change and how it could fix this performance issue.

So sure, go ahead and make a pull request. With some code, this will surely be easier to understand what you mean.

Normally, to speed up the audit saving part, we usually recommend:
- To change how audit is saved to use only one table (properties are saved in XML or JSON format)
- Use `BulkInsert` for our paid libraries

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @grinay ,

I will close this issue since we didn't receive any project.

However, we will re-open it whenever you are able to provide it. So no rush here ;)

Best Regards,

Jon
