### ISSUE TITLE
Compatibility with infocarrier

### ISSUE THREAD

**Issue by james1o4timothy** [zzzprojects/EntityFramework-Plus#686]
This is a question not feature request.
Is it possible to make this library compatible with 
https://github.com/azabluda/InfoCarrier.Core

**Comment by JonathanMagnan** [comment]
Hello @james1o4timothy ,

What exactly is not compatible with this library?

They have a reference to EF Core 3.x, so our v 3.x should already be compatible with anything you use through EF Core.

We don't really know this library so it will really depends of what is not working here.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)
