### ISSUE TITLE
Undocumented option SynchronizeSoftDeleteFormula

### ISSUE THREAD

**Issue by npbenjohnson** [zzzprojects/EntityFramework-Plus#687]
I'm hoping the SynchronizeSoftDeleteFormula is meant for external use to soft delete instead of hard deleting any un-matched entities, but I'm not sure what to put in it for SqlServer to change from a delete to an update.

**Comment by JonathanMagnan** [comment]
Hello @npbenjohnson ,

Here are some example:

```csharp
context.BulkSynchronize(list, option =>
{
                option.SynchronizeSoftDeleteFormula = "IsSoftDeleted = 1";
});

context.BulkSynchronize(list, option =>
{
                option.SynchronizeSoftDeleteFormula = "DeletionDate = GETDATE()";
});

context.BulkSynchronize(list, option =>
{
                option.SynchronizeSoftDeleteFormula = "IsSoftDeleted = 1 AND DeletionDate = GETDATE()";
});
```

It allows you to put any SQL after the `SET` statement on the update.

Let me know if that answer correctly to your question

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by npbenjohnson** [comment]
That worked for me, thank you
