### ISSUE TITLE
add support for ms access

### ISSUE THREAD

**Issue by kkordinia** [zzzprojects/EntityFramework-Plus#689]
There is an entity framework provider for Microsoft Access.

- [EntityFrameworkCore.Jet](https://www.nuget.org/packages/EntityFrameworkCore.Jet)
- [JetEntityFrameworkProvider](https://www.nuget.org/packages/JetEntityFrameworkProvider)

Please add Microsoft Access support to this repository. Thanks.

**Comment by JonathanMagnan** [comment]
Hello @kkordinia ,

Unfortunately, we currently have too many requests to add support to new providers. I added it to our internal wish list but to be honest, I don't think it will ever happen.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)
