### ISSUE TITLE
WhereDynamic with DateTime

### ISSUE THREAD

**Issue by LukeTOBrien** [zzzprojects/EntityFramework-Plus#690]
Hello there,

I know you are pretty fast at answering these so here goes.

How do we do a ``WhereDynamic` with dates?  
I have [forked one of your examples](https://dotnetfiddle.net/h3aKFl), what I am trying to do is:
```csharp
			.WhereDynamic(x => "x.Date > \"" + DateTime.Today.Date.ToString() +"\"")
```
But I am getting the error:
```
Unhandled exception. Z.Expressions.Compiler.Shared.EvalException: Oops! No applicable member has been found for the expression. The error occurred for expression "." at position 3 near ".Where(x => x.Date > \"06/".
```
What am I doing wrong?

In your [Where examples](https://dynamic-linq.net/basic-simple-query#more-where-examples) you do not have any dealing with dates and in your online examples I cannot find any with dates either.  
Maybe you can add some examples with dates?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @LukeTOBrien ,

You currently mix 2 libraries.

The link you provided is for the https://github.com/zzzprojects/System.Linq.Dynamic.Core libraries.

There are 2 ways to solves your issue:

You can pass the date in parameter (recommended):

```csharp
.WhereDynamic(x => "x.Date > theDate", new { theDate = DateTime.Today.Date})
```

_(be careful to don't use the same date are the property name)_

Or you can use a special syntax to specifies the string is a date

```csharp
.WhereDynamic(x => "x.Date > #" + DateTime.Today.Date.ToString("yyyy-MM-dd") +"#")
```

There is 2 supported syntax:

- `#date#`
- `##datetime##`

Let me know if that helped you to solve your issue.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by LukeTOBrien** [comment]
Hi @JonathanMagnan 

Thanks for the quick response.  
Yes I'm sorry about the mixup with the projects... I Googled and was reading another issue, I didn't check the repo name.

The first solution works perfect, Thanks.
