### ISSUE TITLE
Filters not applied in children collection

### ISSUE THREAD

**Issue by mlhuong** [zzzprojects/EntityFramework-Plus#692]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
When using IncludeOptimized() or IncudeFilter(), the filters are not applied.

## 2. Exception
No error, but the list of children items is incorrect.

```
Exception message:
Stack trace:
```

## 3. Fiddle or Project
Context.Filter<Report>(q => q.Where(x => x.IsActive));
Context.Filter<ReportItem>(q => q.Where(x => x.IsActive));
var result = await Context.Reports.IncludeOptimized(x => x.Items).ToArrayAsync();

**Comment by JonathanMagnan** [comment]
Hello @mlhuong ,

Are you using `EF6` or `EF Core`? The answer is very different depending on the version.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @mlhuong ,

I just double-checked, for EF Core, the filter is done on the `DbSet` level unlike `EF6`. So it works only for the `Reports` DbSet in your case.

`EF Core` now has a `Query Filter` features: https://docs.microsoft.com/en-us/ef/core/querying/filters

You should look at it. As they own the source code, they sure have more flexibility than us and should work with related entities that you included.

**Comment by mlhuong** [comment]
I will use EF Core query filters.

Thanks a lot.
