### ISSUE TITLE
.TemporalTableAll() SQL Error: "Incorrect syntax near 'SYSTEM_TIME'" 

### ISSUE THREAD

**Issue by zachjohnston** [zzzprojects/EntityFramework-Plus#693]
## 1. Description
When working with a legacy schema, I encountered a table containing a column with the same name as the table (i.e. dbo.Foo.Foo).  When we created a history table then queried using .TemporalTableAll(), the generated SQL was invalid: it had `FOR SYSTEM_TIME ALL` immediately after the column name in the SELECT clause.  Workaround is to rename the column so that it is different than the table name.

## 2. Exception
SQL Exception 

```
Exception message: Incorrect syntax near 'SYSTEM_TIME'
Stack trace:
```

**Comment by JonathanMagnan** [comment]
Hello @zachjohnston ,

Unfortunately after reviewing it, we choose to don't fix it for now.

Fixing it will currently make our code a little bit too complex for this kind of very special case since we need to support some case that doesn't currently have the `schema` name.

Best Regards,

Jon
