### ISSUE TITLE
Does it support Oracle DB??

### ISSUE THREAD

**Issue by BhusanBibhuti** [zzzprojects/EntityFramework-Plus#694]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
Does this framework support Oracle DB??

## 2. Exception
If you are seeing an exception, include the full exception details (message and stack trace).

```
Exception message:
Stack trace:
```

## 3. Fiddle or Project
If you are able,

Provide a Fiddle that reproduce the issue: https://dotnetfiddle.net/25Vjsn

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

## 4. Any further technical details
Add any relevant detail can help us.

**Comment by JonathanMagnan** [comment]
Hello @BhusanBibhuti ,

Yes most of our features if not all our features should support it.

Did you get an issue with a feature?

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)
