### ISSUE TITLE
Support for LinqKit's `ExpandableQueryProvider`

### ISSUE THREAD

**Issue by nrhoffmann** [zzzprojects/EntityFramework-Plus#695]
## 1. Description
I am trying to use LinqKit with the `BatchDelete` feature, but it seems like it is tied to the EF Core `QueryProvider`.

 Do you think you can support LinqKit's `ExpandableQueryProvider`?

## 2. Exception
If you are seeing an exception, include the full exception details (message and stack trace).

```
System.ArgumentException: Field '_queryCompiler' defined on type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider' is not a field on the target object which is of type 'LinqKit.ExpandableQueryProvider`1[Database.Models.MyModel]'.
   at System.Reflection.RtFieldInfo.GetValue(Object obj) in System.Private.CoreLib.dll:token 0x6004e49+0x3f
   at .[](IQueryable`1 ) in Z.EntityFramework.Extensions.EFCore.dll:token 0x600124f+0x0
   at Z.EntityFramework.Extensions.BatchDelete.Execute[T](IQueryable`1 query) in Z.EntityFramework.Extensions.EFCore.dll:token 0x60011bd+0x76
   at BatchDeleteExtensions.`1.() in Z.EntityFramework.Extensions.EFCore.dll:token 0x6000164+0x0
   at System.Threading.Tasks.Task`1.InnerInvoke() in System.Private.CoreLib.dll:token 0x6002cec+0xf
   at System.Threading.Tasks.Task.<>c.<.cctor>b__284_0(Object obj) in System.Private.CoreLib.dll:token 0x6002e8c+0x0
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002a30+0x15
```

## 3. Fiddle or Project
https://github.com/nrhoffmann/LinqKitReprex

## 4. Any further technical details
There are none at this time.

**Comment by JonathanMagnan** [comment]
Hello @nrhoffmann ,

Thank you for reporting,

My developer will look if that's possible.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @nrhoffmann ,

The v5.2.6 has been released.

We probably don't fully support LinqKit, however, the most basic cases should now be supported.

Let me know if everything is working for you.

Best Regards,

Jon

**Comment by CactusPie** [comment]
Hi,

I'm still having issues with Future queries. Basically, if the query uses .AsExpandableEFCore then executing .Future() on it will cause the following exception:

System.ArgumentException: Field '_queryCompiler' defined on type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider' is not a field on the target object which is of type 'LinqKit.ExpandableQueryProvider`1[MY_TYPE_HERE]'.

**Comment by JonathanMagnan** [comment]
Hello @CactusPie ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

Best Regards,

Jon

**Comment by CactusPie** [comment]
Hi @JonathanMagnan 

Sure, here it is:
[ExampleError.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/7610272/ExampleError.zip)

**Comment by JonathanMagnan** [comment]
Hello @CactusPie ,

The v6.13.5 has finally been released.

Let me know if the new version solved your issue correctly.

Best Regards,

Jon

**Comment by CactusPie** [comment]
Hi @JonathanMagnan 
Thanks for replying.
It's not quite fixed yet. The code I provided does work, but if you use two future queries it still throws an exception. I attached new code to reproduce the issue:

[ExampleError.zip](https://github.com/zzzprojects/EntityFramework-Plus/files/7837704/ExampleError.zip)

**Comment by JonathanMagnan** [comment]
Hello @CactusPie ,

The v6.13.9 has been released that includes the fix for the project you provided.

Best Regards,

Jon

**Comment by CactusPie** [comment]
Hi @JonathanMagnan 
Yes, it works now. Thank you so much!
