### ISSUE TITLE
[bug] Audit: Retrieving an AuditEntry fails when the AuditDisplay property is used

### ISSUE THREAD

**Issue by Ahmed-Abdelhameed** [zzzprojects/EntityFramework-Plus#696]
## Description
Currently, the `EntityTypeName` property/column of `AuditEntry` is used to store the type name of the entity by default. That's great. However, when the `AuditDisplay` attribute is applied to an entity, the display name gets used instead. This is very dangerous because some things are dependant on the type name (which is now lost), like [retrieving an audit entry](https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.Audit.Shared/Extensions/DbSet%60AuditEntry/DbSet%60AuditEntry.cs), for example.

I believe that `AuditEntry` should a) have another **mapped** property called `DisplayName` (or something similar) alongside the current `EntityTypeName`, b) use that new property for storing the display name, and c) make the current one hold the type name all the time.

I also think the same should be done for `AuditEntryProperty` (I noticed there's a property called `InternalPropertyName` but that one is not mapped and doesn't seem to be used).

## Steps to reproduce
1. Add an `<AuditDisplay>` attribute to an entity and set the name parameter to anything other than the class name.
2. Make a change that will create an audit entry and save it in the database.
3. Call `AuditEntries.Where(myEntity)` or `AuditEntries.Where<MyEntity>(someId)` and check the count of the returned collection.
4. It will always be zero (it doesn't find any because of what's explained above).
5. The fact that `EntityTypeName`'s value is something else other than the actual type name probably breaks the code in other places as well but this is what I noticed so far.

## Fiddle or Project
Runnable fiddle: https://dotnetfiddle.net/vBHwtN

## Environment
- .NET Framework 4.7.2.
- EF6.
- EFPlus 5.2.5.

**Comment by JonathanMagnan** [comment]
Hello @Ahmed-Abdelhameed ,

Thank you for your feedback, my developer will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @Ahmed-Abdelhameed ,

The v5.2.6 has been released 

Could you look at it and confirm us that the issue has been correctly fixed?

---

**Is this library useful to you?** Please help us by [becoming a sponsor](https://github.com/sponsors/zzzprojects) to keep it alive and supported.

**Comment by Ahmed-Abdelhameed** [comment]
Hi @JonathanMagnan ,

Thanks for the update.

Looks like the source code wasn't updated, so I'll have to comment based on the behavior that I can observe...

So, this particular test case has been resolved and the `.Where()` extension methods do return the entry as expected. However, the `EntityTypeName` property/column still holds the display name rather than the actual type name.

I'm guessing you fixed this by changing the implementation of the `.Where()` methods to search using the value of `AuditDisplayAttribute`. That's great and all but I was hoping you'd go a different route to cover cases when one's not using those extension methods? For example, if I needed to get all entries for `Person`, instead of writing this:

```
var entries = context.AuditEntries.Where(x => x.EntityTypeName == nameof(person)).ToList();
```

...I'd have to write something like this:

```
var attributes = typeof(Person).GetCustomAttributes(typeof(AuditDisplayAttribute), true);
var auditDisplayAttr = (attributes.FirstOrDefault() as AuditDisplayAttribute);
string displayName = auditDisplayAttr?.Name ?? nameof(person);
var entries = context.AuditEntries.Where(x => x.EntityTypeName == displayName).ToList();
```

And I would do that because I know about this issue. I doubt that other people would guess that they have to compare `EntityTypeName` to the display name set by the `AuditDisplay` attribute until they encounter a similar issue.

**Comment by JonathanMagnan** [comment]
Hello @Ahmed-Abdelhameed ,

Sorry for the long waiting.

The v5.2.10 has been released today.

We fixed the issue about the configuration always taken and added a new extension method for your purpose: `GetAuditDisplayName`

You can now use it this way:

```csharp
var entries = context.AuditEntries.Where(x => x.EntityTypeName == typeof(person).GetAuditDisplayName()).ToList();

var entries = context.AuditEntries.Where(x => x.EntityTypeName == typeof(person).GetAuditDisplayName(auditConfiguration)).ToList();
```

Let me know if that successfully answer to your request
