### ISSUE TITLE
Null-ref error when using Batch Delete with .Net 6 RC1

### ISSUE THREAD

**Issue by Webreaper** [zzzprojects/EntityFramework-Plus#700]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

I've got code that calls `IQueryable<T>.Delete()`, and it works fine with .Net 6 up to preview 7. I upgraded to RC1, and it crashes with a null-ref exception somewhere inside the `Delete` method.

Is this a known issue, and will you be releasing an RC1 version sometime soon? :)

**Comment by JonathanMagnan** [comment]
Hello @Webreaper ,

Are you using the latest version of our library: https://www.nuget.org/packages/Z.EntityFramework.Plus.EFCore/6.0.0-rc.1.21452.10-1? 

We released our RC1 compatible with them yesterday ;)

The latest EF Core RC1 had many breaking changes in their internal API, so if you were using a `preview` version of our library, it will sure throw an error like this one.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by Webreaper** [comment]
Heh. I did a check for any fixes and updated sometime on Tuesday night or Wednesday morning..... I'm guessing I must have missed the new build by a matter of a few hours!

Thanks, will give it a shot! :)

**Comment by Webreaper** [comment]
Confirmed fixed.

**Comment by JonathanMagnan** [comment]
Awesome @Webreaper 

Don't hesitate to contact us with any questions.

Best Regards,

Jon
