### ISSUE TITLE
Github wiki gone

### ISSUE THREAD

**Issue by ascott18** [zzzprojects/EntityFramework-Plus#706]
Most of the links in README.md link to somewhere in https://github.com/zzzprojects/EntityFramework-Plus/wiki/.

However, this project has no wiki, so all these links are dead.

**Comment by JonathanMagnan** [comment]
Hello @ascott18 ,

Thank you for reporting. We indeed forget the readme when we removed the wiki

All link has been fixed.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)
