### ISSUE TITLE
EF+ Query IncludeFilter multiple level AutitExtensions.Where<T> issue

### ISSUE THREAD

**Issue by WarrenBowley** [zzzprojects/EntityFramework-Plus#709]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

I have been following the example located at https://entityframework-plus.net/query-include-filter#load-multiple-level, but have run into an issue where the final where clause filter is throwing the following error:

Error CS0411 The type arguments for method 'AuditExtensions.Where<T>(DbSet<AuditEntry>, T)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

Fiddle that reproduce the issue: https://dotnetfiddle.net/2MgS4Q

Basically this seems to be a simple criteria to filter the returned data on both the first foreign key table, and then on it's foreign key table.  I am not trying to audit anything or access an audit trail, I just want to use a where clause in the last select statement to filter data even further.  

Essentially in the fiddle, I want to select contacts and filter the list of abbreviations (first foreign key table) on a specific criteria, and then filter that result on data from it's foreign key table.  The where clause can be extensive, and I've just provided a small subset of columns.

**Comment by JonathanMagnan** [comment]
Hello @WarrenBowley ,

Here is an online example for your scenario: https://dotnetfiddle.net/vQGYMW

Be careful when re-using the same context as otherwise, data from the ChangeTracker will be taken which are not filtered. So that's why I created a second context in my example (or you could have used the `AsNoTracking`).

Let me know if that's what you were looking for.

Best Regards,

Jon

---

**Is this library useful to you?** Please help us by [becoming a sponsor](https://github.com/sponsors/zzzprojects) to keep it alive and supported.

**Comment by WarrenBowley** [comment]
Jon:

Thanks for the quick response.  While that did resolve the issue I was having with the .Where clause, I'm not seeing the results I had expected (maybe I'm misunderstanding the IncludeFIlter clause).  

With the first .IncludeFilter(x => x.ContactAbbreviations.Where(y => y.RecordStatusID == 1)), it will join both records in the ContactAbbreviations table.

With the second .IncludeFilter(x => x.ContactAbbreviations.Where(y => y.RecordStatusID == 1).Select(y => y.Abbreviation_XRef).Where(y => y.RecordStatusID == 1)) I was hoping to eliminate one of the ContactAbbreviation rows where the associated Abbreviation did not meet the RecordStatusID == 1 criteria.

I have tried removing the first IncludeFilter and get 0 ContactAbbreviations.  I have also tried chaining the where clause similar to the example here https://stackoverflow.com/questions/54954522/includefilter-multiple-levels-not-working

                .IncludeFilter(x => x.ContactAbbreviations.Where(y => y.RecordStatusID == 1))
                .IncludeFilter(x => x.ContactAbbreviations.Where(y => true)
                                                          .Where(y => y.RecordStatusID == 1)
                                                          .Select(z => z.Abbreviation_XRef)
                                                          .Where(z => z.RecordStatusID == 1))

Essentially what I want to accomplish is equivalent to the following SQL:

SELECT
 *
FROM
 [dbo].[Contacts] [c]
 INNER JOIN [dbo].[ContactAbbreviations] [ca] ON [c].[ID] = [ca].[ContactID]
 INNER JOIN [dbo].[Abbreviation_XRef] [ax] ON [ca].[AbbreviationID] = [ax].[ID] AND [ax].[RecordStatusID] = 1

Which will return 1 Contact with 1 ContactAbbreviation and 1 Abbreviation_XRef. 

Every form of .IncludeFilter I've tried returns all the ContactAbbreviation rows.  I am probably doing it wrong, but can't seem to figure out where.

**Comment by JonathanMagnan** [comment]
Here is another Fiddle with 2 different queries: https://dotnetfiddle.net/C5pzJY

Be careful, I added a third row to see some differences from your original example.

In the first one query, I only filter the `Abbrivation_XRef` table as your SQL statement show

```csharp
List<Contact> searchResults = ctx.Contacts
	.Where(x => x.Name == "Contact 1")
	.IncludeFilter(x => x.ContactAbbreviations.Where(y => y.Abbreviation_XRef.RecordStatusID == 1))
	.IncludeFilter(x => x.ContactAbbreviations.Where(y => y.Abbreviation_XRef.RecordStatusID == 1).Select(y => y.Abbreviation_XRef))
	.ToList();
```

**Comment by WarrenBowley** [comment]
@JonathanMagnan  

I really appreciate all the help you have provided. I've created one final fiddle showing three different methods of achieving the result set I was looking for:

https://dotnetfiddle.net/eU4kAW

My last task is trying to figure out how to include a predicate for the where clause in example number 3.  It may not be possible as I need access to the context in the predicate in order to filter on the grandchild table (Abbreviation_XRef) in order to filter on the child table (ContactAbbreviations).

**Comment by JonathanMagnan** [comment]
Awesome,

If I understand, everything is working fine now?

**Comment by WarrenBowley** [comment]
Yes, thanks for all your help.  

Here is the final fiddle using IncludFilter and Predicates to make sure it's doing an inner join on all of the dynamic search criteria.

https://dotnetfiddle.net/BwDjHL
