### ISSUE TITLE
Chaining multiple AddOrAppendOrderBy and AddOrAppendOrderByDescending calls.

### ISSUE THREAD

**Issue by mihaikanyaro** [zzzprojects/EntityFramework-Plus#71]
Hi,

I am trying to chain some order by clauses, but it seems that the final AddOrAppend overwrites the previous ones. I've seen in the source code that there is a check for node name "MergeAs" to append order methods, otherwise the expression visits the method call, I don't know exactly how to obtain what I want.
My code is roughly this:
```C#
IQueryable<T> result = query;
foreach (string orderByClause in OrderBy)
{
       [...]
       result = orderByDirection == "ASC" ? result.AddOrAppendOrderBy(orderByField) : result.AddOrAppendOrderByDescending(orderByField);
}
```

**Comment by zzzprojects** [comment]
I'm a little bit surprised, but you are right.

There is an issue with the AddOrAppend method.

By example

**DON'T WORK**
```csharp
var list = ctx.Entity_Basics
    .AddOrAppendOrderBy(x => x.ID)
    .AddOrAppendOrderBy(x => x.ColumnInt)
    .ToList();
```

**WORK**
```csharp
var list = ctx.Entity_Basics
    .Where(x => true)
    .AddOrAppendOrderBy(x => x.ID)
    .AddOrAppendOrderBy(x => x.ColumnInt)
    .ToList();
```

I will try to fix it this weekend. Meanwhile, you can use the "Where(x => true)" workaround.

Best Regards,

Jonathan

**Comment by mihaikanyaro** [comment]
Hi Jonathan

Thanks a lot for your very prompt answer! I will use the workaround, as suggested.

**Comment by zzzprojects** [comment]
Hello @mihaikanyaro ,

The fix has been created. It should be available for Monday.

I will let you know as soon as I have more detail.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Hello @mihaikanyaro ,

The v1.4.10 is now available.

Let me know if AddOrAppendOrderBy is now working correctly

Best Regards,

Jonathan

**Comment by mihaikanyaro** [comment]
Hi Jonathan,

Just tested it, and it works as expected. Thank you for the fast resolution!

Mihai
