### ISSUE TITLE
Is Redis already supported?

### ISSUE THREAD

**Issue by flo2000ace** [zzzprojects/EntityFramework-Plus#710]
First of all, i love your project.

I want to cache my mysql database. Is it already possible to cache with redis? What caching is right now by default included, when i use caching?

**Comment by JonathanMagnan** [comment]
For EF6, it should already be supported:

```csharp
var connectionMultiplexer =  ConnectionMultiplexer.Connect("127.0.0.1:6379,allowAdmin=true");
QueryCacheManager.Cache = new RedisObjectCache(connectionMultiplexer.GetDatabase(), Newtonsoft.Json.JsonConvert.SerializeObject, (type, s) => Newtonsoft.Json.JsonConvert.DeserializeObject(s, type));
```

You can also implement your own in the same way: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryCache.Shared/RedisObjectCache.cs

For EF Core, nothing has been done yet.

Let me know if that answers your question.

Best Regards,

Jon

---

**Is this library useful to you?** Please help us by [becoming a sponsor](https://github.com/sponsors/zzzprojects) to keep it alive and supported.

**Comment by flo2000ace** [comment]
Hi, thank you for the fast response
What caching uses this libary by default? Can i use this class above and Redis should then work perfectly fine?

Best Regards,
Flo

**Comment by flo2000ace** [comment]
So i worked the hole morning on that, QueryCacheManager.Cache and ObjectCache are not from the same type. I am not that much into caching. I could write it on my own and commit or share it here, but i dont understand IMemoryCache how to create a entry there is only a key and no value in the [function call](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.imemorycache.createentry?view=dotnet-plat-ext-6.0#Microsoft_Extensions_Caching_Memory_IMemoryCache_CreateEntry_System_Object_)

**Comment by JonathanMagnan** [comment]
Hello @flo2000ace ,

Unfortunately as said, nothing has been done for EF Core on our side.

We maybe didn't dig enough when we tried, but we didn't succeed either so I don't think we can really help you here. We had the same problem as you ;(

**Comment by flo2000ace** [comment]
Ok then i also dont think i can do that, but one last question, what are you currently using for caching or is it disabled in ef core?

**Comment by JonathanMagnan** [comment]
Hello @flo2000ace ,

The cache used for EF Core is the `MemoryCache`: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryCache.Shared/QueryCacheManager.cs#L54

Unfortunately, the class is not the same as the one in the .NET Framework
