### ISSUE TITLE
IncludeOptimized adds Extra Order By field

### ISSUE THREAD

**Issue by jimalbert19** [zzzprojects/EntityFramework-Plus#712]
I am querying a postgres database and using IncludeOptimized. I have added an order by field that is not the primary key to my linq statement. The sql that is generated has an order by statement with the field I added and the primary key. This second order by parameter (the primary key) is causing the query to run very slowly and timing out. If I just remove the second order by field it works fine. I can't figure out how to remove the second order by field. 

Here is a simple example ...

```csharp
public class TableA {
   // Primary Key
   public int Id {get; set;}

   public int PartnerId {get; set;}

   // This field is not part of the primary key, but is part of a unique index which is 
   // includes both the PartnerId and MyOrderField
   public string MyOrderByField {get; set;}

   public int TableBId {get; set;}
   public TableB TableB {get; set;}
}

public class TableB {
  public int Id {get; set;}
}

var linq = from a in ctx.TableAs
                      where a.MyOrderByField >= "xxxxxxxxxxx"
                       and PartnerId = 10
                      orderby a.MyOrderByField
                      select a;

var l = linq.IncludeOptimized(x => x.TableB).Take(5000).ToList();
```

The sql that gets generated looks basically like this ...

1 of 2
select .... from TableA where MyOrderByField >= 'xxxxxxxxxx' order by MyOrderByField, Id

2 of 2
select ... from TableB where Id In (
select TableBId from TableA where MyOrderByField >= 'xxxxxxxxxx' order by MyOrderByField, Id
)

This is not exactly the sql, but hopefully you get the idea. the problem is with the "Id" getting added to the Order by. If I just remove this everything works great. Adding it make the query really slow.

Thanks
Jim

**Comment by JonathanMagnan** [comment]
Hello @jimalbert19 ,

Unfortunately, we do not control how the query is generated. We are not the ones who adds the `Id` but `Entity Framework` itself.

I'm pretty sure you currently get the same behavior without using our library (so by using a normal `Include`).

Unless you told us to inverse, there is nothing we can do here as we don't want to touch the SQL `Entity Framework` generates.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by jimalbert19** [comment]
Thanks for getting back so quick. I did the test that you suggested. I switched my IncludeOptimized to a standard Include. When I use the standard Include it does not add the extra order by field.

Here is the sql that gets generated using the standard Include ...

SELECT "Project1".... FROM (SELECT "Extent1"...., "Extent2".... FROM "public"."UserIdentity" AS "Extent1" INNER JOIN "public"."HEC_Utility" AS "Extent2" ON "Extent1"."UtilityId" = "Extent2"."id" WHERE "Extent1"."UtilityId" = @p__linq__0 AND "Extent1"."RecorderId" >= @p__linq__1) AS "Project1" ORDER BY "Project1"."RecorderId" ASC  LIMIT 5001

Here is the sql that gets generated using IncludeOptimized ...

-- EF+ Query Future: 1 of 2
SELECT "Project1"..... FROM (SELECT "Extent1".. FROM "public"."UserIdentity" AS "Extent1" WHERE "Extent1"."UtilityId" = @Z_1_p__linq__0 AND "Extent1"."RecorderId" >= @Z_1_p__linq__1) AS "Project1" ORDER BY "Project1"."RecorderId" ASC ,"Project1"."Id" ASC  LIMIT 5001
;

-- EF+ Query Future: 2 of 2
SELECT "Project1".... FROM (SELECT "Extent1"."Id", "Extent1"."RecorderId", "Extent2".... FROM "public"."UserIdentity" AS "Extent1" INNER JOIN "public"."HEC_Utility" AS "Extent2" ON "Extent1"."UtilityId" = "Extent2"."id" WHERE "Extent1"."UtilityId" = @Z_2_p__linq__0 AND "Extent1"."RecorderId" >= @Z_2_p__linq__1) AS "Project1" ORDER BY "Project1"."RecorderId" ASC ,"Project1"."Id" ASC  LIMIT 5001
;

Thanks
Jim

**Comment by JonathanMagnan** [comment]
Do you think you could provide a **runnable project sample** for this issue? It will help my developer to get started to investigate it faster and make sure nothing is missing.

For example, at this moment we don't even know which version of EF (or EF Core) you are using. So the project will surely safe us some time as it might be dependent on a specific major version.

_Providing a project sample is now **REQUIRED**. It happened **too many times** that something **was missing** to investigate and/or answer an issue._

_Try to create a new project with only the minimal code (having too many non-related codes doesn’t help either)._  

You can send it to info@zzzprojects.com if you need to keep the source private

Best Regards,
 
Jon
 
---
 
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by jimalbert19** [comment]
I'll try to put a sample together, but it might take a little bit of time. I have a work around for now, but I would like to understand what is going on.

Thanks for your help.
Jim

**Comment by JonathanMagnan** [comment]
Hello @jimalbert19, 

This issue will be closed since we haven't heard back from you.
However, don't hesitate to contact us once you'll be able to provide a runnable project sample.

Best Regards,
Jon
