### ISSUE TITLE
Audit - Performance degrades over time

### ISSUE THREAD

**Issue by Tyler-V** [zzzprojects/EntityFramework-Plus#713]
## 1. Description
We have implemented the Audit extension in our .NET Core Web API to handle the auditing requirements for a client, we are auditing transactions related to a Patient in a HIPAA-compliant remote patient monitoring web app. Some of the items captured are a Patient's Submission, Metrics/Questions, Records, etc. in total we had as many as 7 entities enabled for Audit.

What we had noticed was a significant performance reduction (over time) with the more auditable entities enabled, which was affecting the API's response times. After a deployment or restarting the Azure App Service, the first request would be in the 99th percentile, and then after a day or two or usage, it would slowly degrade taking response times from 200ms -> 1.5s -> 5s and beyond.

The memory and CPU profile on the App Service is not climbing in the application according to the graphs/application insights, it's just entering a degraded state.

When we remove auditing from the entities, we notice the requests (POST, PUT, PATCH) are no longer affected and the application performance is back to the 99th percentile and appears unaffected over time. In addition, when auditing is enabled the (GET) requests for anything not having to do with auditing are also performing in the 99th percentile and unaffected by auditing or any general application performance issues/memory leak.

So in summary, the requests that have some CRUD action on an entity that has auditing enabled appear to enter a slow performance degradation over time - resolved by an App Service restart - only to be degraded again after 24+ hours of usage making this library unusable for our client.

Here you can see what I am referring to in Application Insights indicating some sort of memory leak or resources that are not being cleaned up (internally) in the audit framework over time.

![image](https://user-images.githubusercontent.com/3893234/147764864-f5512e42-b352-46cd-aec6-98ecadd4a57d.png)

![image](https://user-images.githubusercontent.com/3893234/147764007-09a7ecb4-96c4-466c-a62f-dc01448ea333.png)

## 2. Exception
No exceptions were recorded

## 3. Example Code

This is one of 7 entities that were enabled for auditing
```
    public class MetricBase : BaseModel
    {
        public decimal BaseValue { get; set; }

        public decimal DeltaValue { get; set; }

        public decimal MinValue { get; set; }

        public decimal MaxValue { get; set; }

        public MetricType Type { get; set; }

        public MetricDeviceType Device { get; set; }
    }

    public class Metric : MetricBase, IAuditable
    {
        public Patient Patient { get; set; }

        public int RequiredMeasurements { get; set; }

        public User GetOwner() => Patient?.GetOwner();
    }
```

This is our custom auditing class
```
    public class UtmAuditEntry : AuditEntry
    {
        public string CreatedById { get; set; }

        public string OwnerId { get; set; }

        public string Owner { get; set; }
    }
```

This is our TenantContext (it is a multi-tenant system)
You can see we assign the creator and owner using the RequestContext which is injected in and contains the user's JWT where we are pulling the user credentials and assigning them back to the AuditEntry but there are no async calls.
```
public class TenantContext : DbContext
    {
        private readonly RequestContext _requestContext;
        private AuditConfiguration _auditConfiguration;

        public TenantContext()
        {
            AuditManager.DefaultConfiguration = GetAuditConfiguration();
        }

        public TenantContext(DbContextOptions options, RequestContext requestContext, SystemContext systemContext) :
            base(options)
        {
            _requestContext = requestContext;
            AuditManager.DefaultConfiguration = GetAuditConfiguration();
        }

        public DbSet<Metric> Metrics { get; set; }

        public DbSet<UtmAuditEntry> AuditEntries { get; set; }

        public DbSet<AuditEntryProperty> AuditEntryProperties { get; set; }

        public override async Task<int> SaveChangesAsync(
            CancellationToken cancellationToken = default)
        {
            this.UpdateBaseModelProperties(_requestContext?.ApplicationUser?.UserName);

            var audit = new Audit { CreatedBy = _requestContext?.ApplicationUser?.UserName ?? "SYSTEM" };
            audit.PreSaveChanges(this);
            int rowsAffected = await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
            audit.PostSaveChanges();
            audit.Configuration.AutoSavePreAction(this, audit);
            await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
            return rowsAffected;
        }

        public override int SaveChanges()
        {
            this.UpdateBaseModelProperties(_requestContext?.ApplicationUser?.UserName);
            var audit = new Audit { CreatedBy = _requestContext?.ApplicationUser?.UserName ?? "SYSTEM" };
            audit.PreSaveChanges(this);
            int rowsAffected = base.SaveChanges();
            audit.PostSaveChanges();
            audit.Configuration.AutoSavePreAction(this, audit);
            base.SaveChanges();
            return rowsAffected;
        }

        private AuditConfiguration GetAuditConfiguration()
        {
            if (_auditConfiguration != null) return _auditConfiguration;
            _auditConfiguration = AuditManager.DefaultConfiguration;
            _auditConfiguration.UseUtcDateTime = true;
            _auditConfiguration.ExcludeDataAnnotation();
            _auditConfiguration.AuditEntryFactory = AuditEntryFactory;
            _auditConfiguration.AutoSavePreAction = AutoSavePreAction;
            return _auditConfiguration;
        }

        private UtmAuditEntry AuditEntryFactory(AuditEntryFactoryArgs args)
        {
            if (!(args.EntityEntry.Entity is IAuditable entity))
            {
                return new UtmAuditEntry
                {
                    CreatedBy = _requestContext?.User?.FullName ?? "SYSTEM",
                    CreatedById = _requestContext?.User?.Id.ToString() ?? null,
                    Owner = "SYSTEM",
                    OwnerId = null
                };
            }

            (string createdById, string createdByName) = GetCreator();
            (string userId, string ownerName) = GetOwner(entity);

            return new UtmAuditEntry
            {
                CreatedBy = createdByName,
                CreatedById = createdById,
                Owner = ownerName,
                OwnerId = userId
            };
        }

        private void AutoSavePreAction(DbContext context, Audit audit)
        {
            var tenantContext = (context as TenantContext);
            var entities = audit.Entries.Cast<UtmAuditEntry>().ToList();
            tenantContext!.AuditEntries.AddRange(entities);
        }

        private (string, string) GetCreator()
        {
            return _requestContext.IsSystemAdmin || _requestContext.User is null
                ? (null, "SYSTEM")
                : (_requestContext.User.Id.ToString(), _requestContext.User.FullName);
        }

        private (string, string) GetOwner(IAuditable entity)
        {
            User user = entity?.GetOwner();
            return user is null ? (null, "SYSTEM") : (user.Id.ToString(), user.FullName);
        }
    }
```

For completeness, this is our IContextFactory where you can see we are creating a tenant context and implementing IDisposable
```
    public class TenantContextFactory : IContextFactory<TenantContext>, IDisposable
    {
        private readonly IHttpContextAccessor _accessor;
        private readonly SystemContext _systemContext;
        private readonly RequestContext _requestContext;
        private TenantContext _tenantContext;
        private bool _disposed;

        public TenantContextFactory(IHttpContextAccessor accessor, SystemContext systemContext,
            RequestContext requestContext)
        {
            _accessor = accessor;
            _systemContext = systemContext;
            _requestContext = requestContext;
        }

        private static DbContextOptions<TenantContext> CreateDbContextOptions(string connectionString)
        {
            var contextOptionsBuilder = new DbContextOptionsBuilder<TenantContext>();
            contextOptionsBuilder.UseSqlServer(connectionString);
            return contextOptionsBuilder.Options;
        }

        private string GetConnectionString(Guid tenantGuid)
        {
            Tenant tenant = _systemContext.Tenants.FirstOrDefault(t => t.Key == tenantGuid);
            if (tenant == null)
            {
                throw new Exception("Tenant does not exist.");
            }

            return tenant.ConnectionString;
        }

        public TenantContext CreateContext()
        {
            if (_accessor.HttpContext.HasTenantHeader())
            {
                Guid tenantGuid = _accessor.HttpContext.GetTenantGuid();
                string connectionString = GetConnectionString(tenantGuid);
                return CreateContext(connectionString, tenantGuid);
            }

            return null;
        }

        public TenantContext CreateContext(string connectionString, Guid tenantGuid)
        {
            DbContextOptions<TenantContext> options = CreateDbContextOptions(connectionString);
            _tenantContext = new TenantContext(options, _requestContext, _systemContext) { TenantGuid = tenantGuid };
            return _tenantContext;
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                if (disposing)
                {
                    _tenantContext?.Dispose();
                    _tenantContext = null;
                }
            }

            _disposed = true;
        }
    }
```

Startup.cs
```
            services.AddScoped<IContextFactory<TenantContext>, TenantContextFactory>();
```

![image](https://user-images.githubusercontent.com/3893234/147764203-4e8812f1-addb-4f73-9bf2-a2c70c9ca59e.png)
![image](https://user-images.githubusercontent.com/3893234/147764235-225b4efa-f48a-47b5-a50a-3f29c6ce8ee0.png)

![image](https://user-images.githubusercontent.com/3893234/147765384-881f2f17-b1bf-4ccb-a526-976395c114e2.png)

**Comment by Tyler-V** [comment]
@JonathanMagnan let me know if there's anything else I can provide

**Comment by JonathanMagnan** [comment]
Hello @Tyler-V ,

Do you think you could provide a **runnable project sample** for this issue? It will help my developer to get started to investigate it faster and make sure nothing is missing.

Even if you have probably provided all the code, it happens around 90% of the time that a little thing is missing which could explain everything (happened again just this morning!).

_Providing a project sample is now **REQUIRED**. It happened **too many times** that something **was missing** to investigate and/or answer an issue._

_Try to create a new project with only the minimal code (having too many non-related codes doesn’t help either)._  

You can send it to info@zzzprojects.com if you need to keep the source private

Best Regards,
 
Jon
 
---
 
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by Tyler-V** [comment]
Sample project sent @JonathanMagnan

**Comment by JonathanMagnan** [comment]
Hello @Tyler-V ,

The performance/memory issue is caused by the `ExcludeDataAnnotation` method used here (TenantContext.cs):

```csharp
if (_auditConfiguration != null) return _auditConfiguration;
_auditConfiguration = AuditManager.DefaultConfiguration;
_auditConfiguration.UseUtcDateTime = true;
_auditConfiguration.ExcludeDataAnnotation();
```

Every time a new context is created, the `DefaultConfiguration` is used, and the `ExcludeDataAnnotation` method is called.

However, the `ExcludeDataAnnoation` use a list internally of predicate to know what to include/exclude. So every time you call this method, this list of predicates grows and grows, which takes more space in memory and more time to solve as we need to go through all predicates, and then you get your current behavior.

One easy way to solve it would be to make the variable `_auditConfiguration` static as you don’t look to change it anyway. You will be sure the configuration will apply only once by doing it (a few more changes will be needed if you need it to be perfect for concurrency scenarios such as locking)

Another way to solve it is not using the DefaultConfiguration (which is global) but an instance configuration such as:

```csharp
_auditConfiguration = new AuditConfiguration();
```

Best Regards,

Jon

---

**Is this library useful to you?** Please help us by [becoming a sponsor](https://github.com/sponsors/zzzprojects) to keep it alive and supported.

**Comment by Tyler-V** [comment]
@JonathanMagnan good catch, 

I could see the `auditConfiguration.ExcludeIncludeEntityPredicates` was slowly increasing in count on each request.

Changing it to static was the cleanest solution.

Perhaps internally `ExcludeDataAnnotation` could use a dictionary or something to check if that property exists, I would mark this as resolved we will continue to test this thanks!
