### ISSUE TITLE
Cache invalidation of entities by key, or other manual cache invalidation options?

### ISSUE THREAD

**Issue by douglasg14b** [zzzprojects/EntityFramework-Plus#714]
Much of the caching I'm looking at has little need of time-based expiration, but rather expiration on update.

Can we manually invalidate a cache entry by the entity key? Or are there other options available for manually removing a cache entry?

**Comment by JonathanMagnan** [comment]
Hello @douglasg14b ,

For EF6, that's possible:

```csharp
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
	QueryCacheManager.IsAutoExpireCacheEnabled = true;
}
```

However, for EF Core, we didn't find yet how to make it works.

Let me know if that answers correctly to your question.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
> expiration on update.

If you talk about auto expiration, yes that's possible for EF6:

```csharp
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
	QueryCacheManager.IsAutoExpireCacheEnabled = true;
}
```

However, for EF Core we didn't find out how to make it happen yet.

> Can we manually invalidate a cache entry by the entity key

No, that's currently not possible. People usually use tags to remove everything cached for a specific table or part of the table.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by douglasg14b** [comment]
I was looking through this project for the source code, to see if I can just implement this myself, since cache invalidation is very much a `must have` for secondary caching, but I'm having a difficult time finding the source for this?

**Comment by JonathanMagnan** [comment]
Most of the code is here: https://github.com/zzzprojects/EntityFramework-Plus/blob/a6a03039931f67ddc0f8c528c8df084b461cbd88/src/shared/Z.EF.Plus.QueryCache.Shared/QueryCacheItemTracker.cs
