### ISSUE TITLE
Incorrect DLL in the `z.entityframework.plus.efcore.6.13.8.nupkg`

### ISSUE THREAD

**Issue by trejjam** [zzzprojects/EntityFramework-Plus#716]
Hi, I think something quite nasty happened in the release process.
When I updated `Z.EntityFramework.Plus` to 6.13.8 my project could not find `Z.EntityFramework.Plus.BatchDeleteExtensions`. I discovered that `z.entityframework.plus.efcore.6.13.8.nupkg` does not contain `z.entityframework.plus.efcore`, but `z.entityframework.extensions.efcore` instead. See following package directory screenshot:

![Screenshot from 2022-02-02 09-23-01](https://user-images.githubusercontent.com/3594540/152118282-b9c93337-c5b3-434c-9966-49edf71f523f.png)

Can you please republish the correct nupkg?

**Comment by JonathanMagnan** [comment]
Hello @trejjam ,

Thank you for reporting.

EF Plus was not on the list my developer had to release yesterday. We removed this release from the visible list you can see on NuGet as anyway, it doesn't contain the right package.

Best Regards,

Jon

**Comment by trejjam** [comment]
Ok, thanks
