### ISSUE TITLE
Update related entity 

### ISSUE THREAD

**Issue by arj060892** [zzzprojects/EntityFramework-Plus#718]
I'm looking for a way to update a nested object.

My current model is something like 

```
public class Contact
{
        public string FirstName { get; set; }
        public List<ProjectContact> Projects { get; set; }
        public int ContactId { get; set; }
}

public class ProjectContact
{
        public int ProjectId { get; set; }
        public int ContactId { get; set; }
}
```

And my current DB entities looks something like follow 

```
Contacts Table
=========================
ContactId            FirstName
-------------------- ---------------------
1                            AKH
```

```
Projects Table
========================
ProjectId            ProjectName
-------------------- --------------------
1                    P1
4                    P4
```

```
ProjectContacts Table
========================
ProjectId            ContactId
-------------------- --------------------
1                    1
4                    1
```

When I'm trying to update the Projects entity, as 
```
this.contactContext.Contacts.Update(c => new Contact
    {
        Projects = new List<ProjectContact> { new ProjectContact { ProjectId = 1 } }
    });
```
I'm getting an exception message:
`The destination column could not be found: Projects`

**Comment by JonathanMagnan** [comment]
Hello @arj060892 ,

Where the value `1` is really coming? Sound weird to be a constant.

Maybe something like this could work if the `1` is really a constant:

```csharp
this.contactContext.SelectMany(x => x.ProjectContact).Update(pc => new ProjectContact
    {
        ProjectId = 1 
    });
```

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by arj060892** [comment]
@JonathanMagnan above-mentioned code works inside a for loop which iterates through all Projects entities and checks for conditions, if the conditions are satisfied then the `contactId` and `projectId` should be inserted into `ProjectContacts` Table.
I have updated the table structure as well in the main question

**Comment by JonathanMagnan** [comment]
Thank for the additional info,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it in private here: info@zzzprojects.com

At this moment, the solution I provided looks to work perfectly but I'm not sure exactly what are your conditions that need to be satisfied. So it's hard to provide a good solution if we don't have the complete problem.

The way you currently do it is simply not supported and will probably be never.

Best Regards,

Jon
