### ISSUE TITLE
Exception Message: Could not load type 'Microsoft.EntityFrameworkCore.NavigationExtensions' from assembly 'Microsoft.EntityFrameworkCore, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### ISSUE THREAD

**Issue by ooples** [zzzprojects/EntityFramework-Plus#721]
I'm using the latest prerelease of Microsoft Entity Framework 7 and it isn't able to do anything without giving this exception which usually means I need to wait for the Z Entity Framework Plus versions to catch up but I wanted to report this anyway just in case

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

Thank you for reporting, we will soon look to release a version compatible with the preview of EF Core 7.

Probably next week if there is no code breaking our library.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @ooples ,

It will take us some more time, but we are making some good progress.

A release should be made in March but we have no specific date yet as some changes were more impacting our library than we initially thought.

Best Regards,

Jon

**Comment by ooples** [comment]
Ok I will test it out
