### ISSUE TITLE
net6.0 + EFPlus.EFCore 6: Why does BulkMerge always issue MARS query?

### ISSUE THREAD

**Issue by jzabroski** [zzzprojects/EntityFramework-Plus#727]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
BulkMerge hangs indefinitely (never completes) when an EFCore BeginTransaction() is invoked. 

In researching EFCore documentation, this appears to be the interaction of EFCore usage of SAVEPOINTs and EFPlus.EFCore using MARS queries. The issue does not happen if BeginTransaction() is not invoked and the programmer doesn't try to manually manage transactions.

See this EF Core documentation: https://docs.microsoft.com/en-us/ef/core/saving/transactions#savepoints

![image](https://user-images.githubusercontent.com/447485/169368461-6dd7e884-e73e-493e-b54a-261a82967087.png)

## 2. Exception
There is no exception, but the last statement to execute against the database in SQL Profiler is a MARS (Multiple Active Result Sets) query - and in the Debug Output window, I see 11 threads exit around the time this query is sent to the DB - and then the process hangs forever:

```
exec sp_executesql N'
/* SELECT server information */
SELECT  @@VERSION

/* SELECT table information */
SELECT  DestinationTable.Name AS DestinationName ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       ''ExecIsInsertTrigger'') = 1 )
        ) AS HasInsertTrigger ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       ''ExecIsUpdateTrigger'') = 1 )
        ) AS HasUpdateTrigger ,
        ( SELECT    1
          WHERE     EXISTS ( SELECT 1
                             FROM   sys.triggers AS X
                             WHERE  X.parent_id = A.object_id
                                    AND X.is_disabled = 0
                                    AND OBJECTPROPERTY(X.object_id,
                                                       ''ExecIsDeleteTrigger'') = 1 )
        ) AS HasDeleteTrigger
FROM    (SELECT @Table_0 AS Name) AS DestinationTable  
        LEFT JOIN sys.synonyms  AS B ON B.object_id = OBJECT_ID(DestinationTable.Name)
										AND COALESCE(PARSENAME(base_object_name,4), @@SERVERNAME) = @@SERVERNAME
										AND COALESCE(PARSENAME(base_object_name,3), DB_NAME(DB_ID())) = DB_NAME(DB_ID())
        INNER JOIN sys.tables   AS A ON A.object_id = OBJECT_ID(DestinationTable.Name)
                                        OR A.object_id = OBJECT_ID(B.base_object_name)
ORDER BY DestinationName

/* SELECT column information */
SELECT  DestinationTable.Name AS DestinationName ,
        C.name AS ColumnName ,
        C.column_id AS ColumnOrder ,
        C.precision AS Precision ,
        C.scale AS Scale ,
        C.max_length AS MaxLength ,
        C.collation_name AS Collation ,
        C.Is_Identity AS IsIdentity ,
        ( CASE WHEN EXISTS ( SELECT 1
                             FROM   sys.index_columns AS X
                             WHERE  X.index_id = B.index_id
                                    AND X.object_id = B.object_id
                                    AND X.column_id = C.column_id ) THEN 1
               ELSE 0
          END ) AS IsPrimaryKey ,
        C.system_type_id AS System_Type_Id ,
        D.Name AS TypeName,
        (CASE WHEN E.base_object_name IS NOT NULL THEN 1 ELSE 0 END) AS IsSynonym,
        D.is_user_defined,
        F.name,
		CASE WHEN C.default_object_id  = 0 THEN ''ZZZ_NO_DEFAULT'' ELSE ISNULL(OBJECT_DEFINITION(C.default_object_id), ''ZZZ_ERROR_DEFAULT_ZZZ'') END AS DefaultValueSql,
        C.is_nullable
FROM    (SELECT @Table_0 AS Name) AS DestinationTable
        LEFT JOIN sys.synonyms  AS E ON E.object_id = OBJECT_ID(DestinationTable.Name)
										AND COALESCE(PARSENAME(base_object_name,4), @@SERVERNAME) = @@SERVERNAME
										AND COALESCE(PARSENAME(base_object_name,3), DB_NAME(DB_ID())) = DB_NAME(DB_ID())
        INNER JOIN sys.tables   AS A ON A.object_id = OBJECT_ID(DestinationTable.Name)
                                        OR A.object_id = OBJECT_ID(E.base_object_name)
        LEFT JOIN sys.indexes   AS B ON B.object_id = A.object_id
                                        AND B.is_primary_key = 1
        INNER JOIN sys.columns  AS C ON C.object_id = A.object_id
        INNER JOIN sys.types    AS D ON D.system_type_id = C.system_type_id
                                     AND D.user_type_id = C.user_type_id
        INNER JOIN sys.schemas AS F ON D.schema_id = F.schema_id
ORDER BY DestinationName ,
        ColumnOrder
',N'@Table_0 nvarchar(12)',@Table_0=N'[dbo].[File]'
```

## 3. Fiddle or Project
I may send some private code to info@zzzprojects.com, but I figure I would first ask why you're issuing what looks like a MARS query (select version, select table information, select column information), when the EFCore documentation (screenshot above) says its incompatible with savepoints. (It's possible I misunderstood EFcores documentation, or misunderstood something else).

## 4. Any further technical details
I'm using a ContextFactory - File is not the primary entity being BulkMerged, but I'm using the IncludeGraph BulkMerge Operation builder.  I can see the query that is locking the C# thread is on a separate spid from the one that called `context.BeginTransaction()`

**Comment by JonathanMagnan** [comment]
Hello @jzabroski ,

Thank you for reporting.

We will indeed need you to create a runnable project with the issue. It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

I do not believe that your current issue is related to this but I can be wrong. Having a project will definitely help us to better understand what's happening.

Best Regards,

Jon

**Comment by jzabroski** [comment]
I haven't been able to repro it yet despite trimming the solution down. Hope to update tomorrow or Wednesday.

**Comment by jzabroski** [comment]
@JonathanMagnan  Was there a code change here?

**Comment by JonathanMagnan** [comment]
Hello @jzabroski ,

No, we are currently waiting for your project but we got no update on your side.

We will re-open the issue as soon as we get a project to continue investigating it. We can also re-open it right now if you would prefer it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @jzabroski ,

We don't use/force `MARS`, we just use your connection which either **you** have enabled it or not this option.

We pretty much open a connection from the `DbContext` if not already open and use this connection.

**Comment by jzabroski** [comment]
I see, I think the problem is likely on my end.  sorry to trouble you
