### ISSUE TITLE
[bug] Audit doesn't work well with Soft Delete and Soft Add

### ISSUE THREAD

**Issue by Ahmed-Abdelhameed** [zzzprojects/EntityFramework-Plus#731]
## Description
When using Soft Delete and Soft Add with Audit, you end up with an incorrect `AuditEntryState` in several cases. For example, if you only configure Soft Delete like this:

```
AuditManager.DefaultConfiguration.SoftDeleted<ISoftDelete>(x => x.IsSoftDeleted);
```

...then you try to undelete an item by setting `IsSoftDeleted` to `false`, the `AuditEntryState` remains `EntityModified` instead of `EntitySoftAdded`. At first, I thought I also need to configure Soft Add like this:

```
AuditManager.DefaultConfiguration.SoftAdded<ISoftDelete>(x => !x.IsSoftDeleted);
```

But if I do that, then changing _any property_ of the object produces a state of  `EntitySoftAdded` instead of `EntityModified`. That's because the `!x.IsSoftDeleted` predicate is always satisfied as long as the item is not deleted. This made me think that changing any property of an object while it's in a deleted state will produce a state of `EntitySoftDeleted` instead of `EntityModified` as well (which turned out to be true). So, it looks like changing the state from `EntityModified` to either `EntitySoftDeleted` or `EntitySoftAdded` is decided solely based on whether the _new values_ satisfy the predicate without taking into account old values.

##  Fiddle or Project
Runnable fiddle: https://dotnetfiddle.net/hW9Cak

## Environment
- .NET Framework 4.7.2.
- EF6.
- EFPlus 6.14.1.

**Comment by JonathanMagnan** [comment]
Hello @Ahmed-Abdelhameed ,

You are 100% right when you say that we only check the predicate without taking into account old values. We cannot support everyone's logic, so we let people create their own logic. It can someone lead to some side issues like the one you explain with the `SoftAdded` logic.

In this case, if you want to take into account the old value then you can still do it but the configuration will need to be on the instance one and not the default configuration.

Here is a working example: https://dotnetfiddle.net/9MpBUp

```csharp
var audit = new Audit();

audit.Configuration.SoftAdded<Person>(x => {
	// Checking if "IsSoftDeleted" here is better for performance reason (no need to get entry from object state for nothing)
	if(!x.IsSoftDeleted)
	{
		var entry = context.GetObjectContext().ObjectStateManager.GetObjectStateEntry(x);
		var IsSoftDeletedOrdinal = entry.CurrentValues.GetOrdinal("IsSoftDeleted");
		return entry.CurrentValues.GetValue(IsSoftDeletedOrdinal) != entry.OriginalValues.GetValue(IsSoftDeletedOrdinal);
	}
	
	return false;
});
```

Our logic still purely check for the predicate but this time, the predicate check if the old and new value is the same or different.

Let me know if that explains correctly the cause and the solution could work for you.

---

**Is this library useful to you?** Please help us by [becoming a sponsor](https://github.com/sponsors/zzzprojects) to keep it alive and supported.

**Comment by Ahmed-Abdelhameed** [comment]
Hey @JonathanMagnan , 

Thanks for your reply!

I think I get what you mean by people using different logic. For example, Soft Delete might be based on properties of a different type, multiple properties, or some other calculations outside of the database values (did I get that right?) and that's a fair point. Is there no way to still use the same predicate on the old value(s) and negate the result (since it has a `bool` type parameter anyway)? I'll try to look at the source code and see if I can come up with something. If so, I'll submit a PR.

I don't really like doing configuration on the instance because I have to repeat the same logic with each instance. For now, a better workaround would be to disable the Soft Add & Soft Delete configuration altogether and handle that manually in `AutoSavePreAction`. This is what I went with until I see if I can come up with something better for the global configuration. Here's an example of what I did:

```c#
AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
{
    foreach (var entry in audit.Entries.Where(x => x.State == AuditEntryState.EntityModified))
    {
        var isSoftDeltedProp = entry.Properties.SingleOrDefault(p => p.PropertyName == nameof(ISoftDeleteEntity.IsSoftDeleted));
        if (isSoftDeltedProp is null) continue;

        bool wasSoftDeleted = (bool)isSoftDeltedProp.OldValue;
        bool isSoftDeleted = (bool)isSoftDeltedProp.NewValue;
        if (wasSoftDeleted && !isSoftDeleted)
        {
            entry.State = AuditEntryState.EntitySoftAdded;
        }
        else if (isSoftDeleted && !wasSoftDeleted)
        {
            entry.State = AuditEntryState.EntitySoftDeleted;
        }
    }

    ((EFPlusContext)context).AuditEntries.AddRange(audit.Entries);
};
```

**Comment by JonathanMagnan** [comment]
Hello @Ahmed-Abdelhameed ,

> I don't really like doing configuration on the instance because I have to repeat the same logic with each instance.

You only need to create a method that does this logic and call it every time you create a new instance of the context. That's pretty much what the `DefaultConfiguration` does. So you just repeat one call, not the whole code. You can probably also inherit from the `Audit` class and create a constructor that takes the current context.

Your alternative solution is also a very good one which should perfectly work.
