### ISSUE TITLE
UpdateFromQuery for PostgerSQL LTree datatype is throwing exception.

### ISSUE THREAD

**Issue by prozyckiFP** [zzzprojects/EntityFramework-Plus#734]
### Description
Hi,
I have problems with the postgresql ltree data type.
I would like to use `UpdateFromQueryAsync` to change the 'LTree' path, but that doesn't work
`BulkInsertAsync` when adding entities with  `LTree` property  doesn't work as well.

What can I do with that?

### Exception
`Npgsql.PostgresException: '42883: operator does not exist: ltree <@ text`  

### Code
This is my Entity:

```csharp
public class Item
{
    public Guid ItemId { get; set; }
    public LTree Path { get; set; }

    public int OrderNumber { get; set; }
    public double SortValue { get; set; }
    
}

```

And on this line it throws exception:

```csharp
await _context.Items
     .Where(i => i.Path.IsDescendantOf(item.Path))
     .UpdateFromQueryAsync(i => new Item
     {
         Path = newParent.Path + i.Path.Subpath(currentParentNLevel),
     }, cancellationToken);
```

#### NugetPackage Versions
- Microsoft.EntityFrameworkCore: 6.0.7
- Npgsql.EntityFrameworkCore.PostgreSQL: 6.0.5
- Z.EntityFramework.Extensions.EFCore: 6.14.3
- Z.EntityFramework.Plus.EFCore: 6.14.3

#### Database version
- PostgreSQL: 14.1
- ltree extension: 1.2

**Comment by JonathanMagnan** [comment]
Hello @prozyckiFP ,

We will look at why the `ltree` does't work with `BulkInsert`.

I do not believe we will be able to make compatible this syntax for `UpdateFromQuery`.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @prozyckiFP ,

The v6.14.4 has been released.

The support for `LTree` has been added for `BulkInsert` and other bulk operations but as said, there is currently no plan for `UpdateFromQuery` at this moment.

Best Regards,

Jon
