### ISSUE TITLE
Console Output Sql Logger

### ISSUE THREAD

**Issue by zhangzw218** [zzzprojects/EntityFramework-Plus#737]
## 1. Description
When I use EFCore, I add it in the appsettings.json "Microsoft.EntityFrameworkCore.Database.Command": "Information"
Console can output Sql logs。
However, when using Z.EFCore.Plus, the log cannot be output.
I wonder if this is normal.

## 3. Fiddle or Project

I want to know if this is a known problem. If it could have been logged, then it is my problem. I will try to make a Demo to reproduce it.

**Comment by JonathanMagnan** [comment]
Hello @zhangzw218 ,

Do you mean that our library doesn't output SQL logs (which is normal here), or there is an issue, and the log doesn't work anymore at all even when not using methods of our library?

Unfortunately, most features from our library will not output as a different execution path is taken than the one usually done by EF Core. There is currently no short term plan to make everything compatible with logging.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by zhangzw218** [comment]
Only z.efcore.Plus does not output logs.EFCore can output logs normally.

So how should I see the execution log?
For example, Query.UpdateAsync(s=> s.ussername = "aaa"); How should I see the execution log?
I can see in the document that only BulkOperation can output logs, for example
public static Task BulkUpdateAsync<T>(this DbContext @this, IEnumerable<T> entities, Action<BulkOperation<T>> options) where T : class;
But the argument here is List<object>
I want to update only certain fields, For example, public static async Task<int> UpdateAsync<T>(this IQueryable<T> query, IDictionary<string, object> dictionary) where T : class
How do I view the execution log at this point?
……
And finally, the main reason I want to read the journal:


//1.Is this assignment allowed?
var query = await UserTestRepository.GetQueryableAsync(s => s.UserName == "aaa");
await query.UpdateAsync(s => new UserTest 
{ 
	CostAmount = s.CostAmount + 10,
});
The results didn't seem to match my expectations, so I wanted to see what the SQL statement looked like.

**Comment by JonathanMagnan** [comment]
Hello @zhangzw218 ,

You can find the `CommandText` and `Parameters` by using the `Executing` event.

Example:

```csharp
context.Customers
		.Where(x => x.IsActive && x.LastLogin < date)
		.Update(x => new Customer {IsActive = false, Description = "Updated"}, options => options.Executing = (command) => {
			// DO whatever you want here with the command                        
			Console.WriteLine(command.CommandText);
		});
```

Let me know if that answers your question.

---

**Is this library useful to you?** Please help us by [becoming a sponsor](https://github.com/sponsors/zzzprojects) to keep it alive and supported.

**Comment by zhangzw218** [comment]
Thank you very much. My problem is solved.
@JonathanMagnan
