### ISSUE TITLE
How do I know the second level cache is working

### ISSUE THREAD

**Issue by rosdi** [zzzprojects/EntityFramework-Plus#741]
## 1. Description
How do I know the second level cache is working? I tried to log some output from EF+ but I am not seeing any log. Right now the app is running seemingly without issue, But I have no way verifying that EF+ is caching the result.

I am using EF Core 6.

## 2. Exception
No exception, the app seems to be running fine with some of the queries are using `FromCache`.

**Comment by JonathanMagnan** [comment]
Hello @rosdi ,

If that's only for testing once, all you can do is [logging query](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/) or looking at SQL Profiler to see if the query has only be executed once and then was always retrieve from the cache after.

If you want a more permanent solution, that will highly depend of what you exactly want to do. There is several options such as:
- Creating your own MemoryCache (to be able to know when an item is cached or retrieved)
- Creating a ExistsFromCache method using some code similar as the one found [here](https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryCache.Shared/Extensions/IQueryable%60/FromCache.cs)
- Adding a hook on the [MemoryCacheEntryOptionsFactory](https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryCache.Shared/QueryCacheManager.cs#L186) so every time this function is called, you know something will be cached 

Let me know if that answer your questions or exactly what you want to do / check.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by rosdi** [comment]
Ok I will do just that. Now I get it. EF+ won't log anything. All I could monitor is the absence of queries being executed.

Thanks for the very detailed reply... I was browsing the documentation looking for this info but couldn't find any.
