### ISSUE TITLE
Wesbite is down?

### ISSUE THREAD

**Issue by CapitaineToinon** [zzzprojects/EntityFramework-Plus#745]
Hey there. I'm trying to check the documentation but it seems like the website is down? 

https://entityframework-plus.net/

<img width="1546" alt="image" src="https://user-images.githubusercontent.com/15376923/200802303-c7731145-99b8-4b21-83f4-7a82f76eb265.png">

**Comment by JonathanMagnan** [comment]
Hello @CapitaineToinon, 

Thank you for reaching out. 

The website should be up now. 

Let me know if you have any questions regarding our product. 

Best regards, 

Jon
