### ISSUE TITLE
QueryFuture future not working when using custom query compiler

### ISSUE THREAD

**Issue by akarboush** [zzzprojects/EntityFramework-Plus#746]
## 1. Description
As mentioned in the title, using a custom query compiler causes an exception when you use the QueryFuture.
I use the [NeinLinq ](https://github.com/axelheer/nein-linq) library to inject a lamda expression into my query, NeinLinq internally rewrites the query with custom rewriter and compiler to inject the expression.

I've looked into the code to see why it's failing and it looks like the [IsInMemoryQueryContext](https://github.com/zzzprojects/EntityFramework-Plus/blob/3cd8e18ea0ee52819262f4e0684d84a66024fe58/src/shared/Z.EF.Plus._Core.Shared/EFCore/IQueryable%60/IsInMemoryQueryContext.cs#LL32C8-L32C8) method that's in Future extension method is trying to [direct cast](https://github.com/zzzprojects/EntityFramework-Plus/blob/3cd8e18ea0ee52819262f4e0684d84a66024fe58/src/shared/Z.EF.Plus._Core.Shared/EFCore/IQueryable%60/IsInMemoryQueryContext.cs#L37) then compilerField to Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler, which will obviously fail due to the custom compiler that implements only the IQueryCompiler interface.

## 2. Exception
```
Exception message: Unable to cast object of type 'EmptyQueryCompiler' to type 'Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler'.

Stack trace: at Z.EntityFramework.Plus.InternalExtensions.IsInMemoryQueryContext[T](IQueryable`1 query)
   at Z.EntityFramework.Plus.QueryFutureExtensions.Future[T](IQueryable`1 query)
   at UserQuery.Main(), line 7
```

## 3. Fiddle or Project
https://dotnetfiddle.net/2tjDpz

**Comment by JonathanMagnan** [comment]
Hello @akarboush ,

Unfortunately, our library will not be compatible with `NeinLinq`. The `QueryFuture` feature depends so much on the implementation of the QueryCompiler.

We could surely fix the part about the `IsInMemoryQueryContext` but then all the rest of the code [here](https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryFuture.Shared/BaseQueryFuture.cs#L140) by example will not work at all.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)
