### ISSUE TITLE
Is EF Core Plus supports RedHat Linux?

### ISSUE THREAD

**Issue by sanme98** [zzzprojects/EntityFramework-Plus#748]
## 1. Description
Is this library support Linux especially RedHat? I double check the program folder, the Z.EntityFramework.Plus.EFCore.dll already inside. It is a .NET 6 project.

## 2. Exception
Error Could not load file or assembly 'Z.EntityFramework.Plus.EFCore, Version=6.17.1.0, Culture=neutral, PublicKeyToken=59b66d028979105b'. The system cannot find the file specified.

Thank you.

**Comment by JonathanMagnan** [comment]
Hello @sanme98 ,

We sure support Linux, but we do not have any tests on RedHat. But looking at the error, it seems to be more of an issue about a referenced dll.

Do you think you could try again with a very simple project (I mean, a basic console project that does by example just call a query `FromCache` method) and see if you have the problem?

If you still have the issue, could you send us the output so we can test it in some of our environments? You can send it in private here if needed: info@zzzprojects.com

Could you also double-check if the `dll` inside is really the version 6.17.1` or it's another version?

Let us know more about this issue.

Best Regards,

Jon

**Comment by sanme98** [comment]
@JonathanMagnan Thanks for your quick reply.

I found it was because I didn't copy the *.deps.json file, it contains all the dependency configuration and must be copied. 
Therefore, confirm it is supported on RedHat.

Once again, Thank you very much.
