### ISSUE TITLE
AutoSave with custom class

### ISSUE THREAD

**Issue by it-AhmedTaha** [zzzprojects/EntityFramework-Plus#749]
I'm attempting to use AutoSave with custom class.

Following this example [https://dotnetfiddle.net/lC7eWg](https://dotnetfiddle.net/lC7eWg) ,
I am creating two custom classes, filling it with custom data, casting, and then override SaveChangesAsync to AutoSave audit as shown in this example [https://dotnetfiddle.net/TFf8aj](https://dotnetfiddle.net/TFf8aj).

Code example:

```cs
public class EntityContext : DbContext
{
    public EntityContext() 
    {
        // Custom Class: Globally
        AuditManager.DefaultConfiguration
            .AuditEntryFactory = args => 
            new CustomAuditEntry() { Time_CustomAuditEntry = DateTime.Now  };

        AuditManager.DefaultConfiguration
            .AuditEntryPropertyFactory = args => 
            new CustomAuditEntryProperty() { Text_CustomAuditEntryProperty = "Text" };
			
        AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) => {
            ((EntityContext)context).AuditEntries.AddRange(audit.Entries.Cast<CustomAuditEntry>());
        };
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(new SqlConnection(FiddleHelper.GetConnectionStringSqlServer()));

        base.OnConfiguring(optionsBuilder);
    }
		
    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken)
    {
        var audit = new Audit();
        audit.PreSaveChanges(this);
        var rowAffecteds = await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
        audit.PostSaveChanges();

        if (audit.Configuration.AutoSavePreAction != null)
        {
            audit.Configuration.AutoSavePreAction(this, audit);
            await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
        }

        return rowAffecteds;
    }
    public DbSet<CustomAuditEntry> AuditEntries { get; set; }
    public DbSet<CustomAuditEntryProperty> AuditEntryProperties { get; set; }
}

public class CustomAuditEntry : AuditEntry
{
    public DateTime Time_CustomAuditEntry {get;set;}
}
	
public class CustomAuditEntryProperty : AuditEntryProperty
{
    public String Text_CustomAuditEntryProperty {get;set;}
}
```
However, the custom class properties are ignored.
Does AutoSave support custom class? If so, what is the correct approach?

**Comment by JonathanMagnan** [comment]
Thank you for reaching out to ZZZ Projects, due to the holiday vacation we will have limited email access which may cause some delays. 
We are sorry for any inconvenience.

**Comment by JonathanMagnan** [comment]
Hello @it-AhmedTaha ,

Looking at your Fiddle here: https://dotnetfiddle.net/lC7eWg , it looks like the `Time_CustomAuditEntry` and `Text_CustomAuditEntryProperty` was saved correctly.  I can see the date and the string `Text` on the first column in both output tables.

So I'm currently unsure if you find your answer and the Fiddle was modified, or if I don't understand the question correctly.

Let me know more,

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return

**Comment by it-AhmedTaha** [comment]
Problem is I can not get the Auto save to work with custom properties within my code. However, thanks to your response, I switched to a different package.
