### ISSUE TITLE
Unable to cast IStateManager exception

### ISSUE THREAD

**Issue by shaulbehr** [zzzprojects/EntityFramework-Plus#75]
Hi,
Just getting started with this package.  Here's some test code:
```
            using (var db = new MyContext())
            {
                db.Things.Where(d => d.DatabaseName != "Foo").Delete();
            }
```
I get the following exception:
```
System.InvalidCastException : Unable to cast object of type 'Microsoft.EntityFrameworkCore.Internal.LazyRef`1[Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IStateManager]' to type 'Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IStateManager'.
```
What am I doing wrong?

Thanks!

**Comment by zzzprojects** [comment]
Hello @shaulbehr,

Which version of EF Core are you using?

If you are using the version: EF Core 1.1-preview1 like in this issue #72, our library is not yet compatible.

The support should come very soon. I may try again this night if time permits.

Best Regards,

Jonathan

**Comment by shaulbehr** [comment]
Oh dear.  Yes, we are using the preview v1.1.0-alpha-21632.
You think you might have a build for us tomorrow?  :-)

**Comment by zzzprojects** [comment]
Hello @shaulbehr ,

I hoped to release it this night, but I believe it's now starting to be a little bit too late.

The fix to make it compatible with v1.1.0-preview1-final should be available tomorrow during the day. It will probably fix your v1.1.0-alpha-21632 as well.

Best Regards,

Jonathan

**Comment by shaulbehr** [comment]
Thank you, that would be awesome!

**Comment by zzzprojects** [comment]
Hello @shaulbehr ,

The v1.4.10 is now available. Let me know if this is now compatible with v1.1.0-alpha-21632

Best Regards,

Jonathan

**Comment by shaulbehr** [comment]
Working, thanks!
