### ISSUE TITLE
Provide support of entity projections

### ISSUE THREAD

**Issue by BenjaminAbt** [zzzprojects/EntityFramework-Plus#750]
Projections are one of the most important mechanisms for good query performance. Very widely used in the EF Core universe is [Automapper ProjectTo](https://docs.automapper.org/en/stable/Queryable-Extensions.html).

There is now different information whether EF Core Plus supports projections or not.
https://github.com/zzzprojects/EntityFramework-Plus/issues/609#issuecomment-625808196
https://github.com/zzzprojects/EntityFramework-Plus/issues/290#issuecomment-352818462
https://github.com/zzzprojects/EntityFramework-Plus/issues/290#issuecomment-352818462
https://github.com/zzzprojects/EntityFramework-Plus/issues/290#issuecomment-353755268

I am currently sitting in front of a project with a very simple query and a projection via AutoMapper.
```csharp
QueryFutureValue<MyProjection> itemQuery = news.Where( n => n.Id = 1)
                                .ProjectTo<MyProjection>(mapConfig)
                                .DeferredSingleOrDefault().FutureValue();

MyProjection? itemData = await itemQuery.ValueAsync(ct);
```

In principle the execution with `ProjectTo works`, the object is loaded - but in the MSSQL log I see that unlike without `Future()` the whole entity is loaded, which means data is dropped on client side but the select loads everything.

So the projection has no effect on the SQL query anymore with the use of `Future()`. It even looks to me that somehow the entire relation structure is loaded, although lazy loading is active and therefore just no eager loading of the entity should take place.

My question is what is the current state of projection support - and would ask for documentation of the state.
Thank you very much.

**Comment by JonathanMagnan** [comment]
Hello @BenjaminAbt ,

Thank you for reporting. I believe this comment provides the best answer about what is supported and what is not https://github.com/zzzprojects/EntityFramework-Plus/issues/290#issuecomment-353755268

The comment https://github.com/zzzprojects/EntityFramework-Plus/issues/609#issuecomment-625808196 about we do not support it for **IncludeOptimized** feature is still the same. We do not support `AutoMapper` for that feature.

In your example, you are currently using the `Query Future` feature, which we should already support for `AutoMapper`. I did a test with `FutureValue` and EF Core 7, and everything was looking fine.

However, it seems you have a major difference in your case, as you were using lazy loading. Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. So we will make sure we look at your problem exactly. You can also send the code in private here: info@zzzprojects.com
