### ISSUE TITLE
Is Insert from Query Is   Plus or Extension ???

### ISSUE THREAD

**Issue by evilz** [zzzprojects/EntityFramework-Plus#753]
Hello,

Maybe a stupid question but can someone confirm me that Insert From Query is free in Plus version ?

![image](https://user-images.githubusercontent.com/2937862/217266671-184c9598-5c7e-45b3-a7b1-b1688aa0ecf0.png)

Also how to log the query ?
thank

**Comment by JonathanMagnan** [comment]
Hello @evilz ,

That's is actually a good question ;)

The 3 following methods are from EF Extensions:

- `InsertFromQuery`
- `UpdateFromQuery`
- `DeleteFromQuery`

But even if they are from `EF Extensions`, they are free to use.

As you probably already know, `EF Plus` has a dependency on `EF Extensions`, so they are somewhat included in `EF Plus`.

So I guess the real answer is using `InsertFromQuery` is **FREE** and doesn't require any license

## Also how to log the query ?

You can do it by using the `Executing` event such as

```csharp
using (var context = new EntityContext())
{
	Action<DbCommand> action = x => {
		var t = x.CommandText;
	};
	
	context.EntitySimples.InsertFromQuery(option => 
	{
		option.SelectExpression = x => new { x.ColumnInt };
		option.Executing = action;
	});
}
```

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by antonpmpu** [comment]
Hi @JonathanMagnan 

I'm trying use **UpdateAsync** method from the Z.EntityFramework.Plus project, however as you mentioned above "EF Plus has a dependency on EF Extensions, so they are somewhat included in EF Plus", so I've removed references to the not free projects/dependencies and received following error:
The type '**BatchUpdate**' is defined in an assembly that is not referenced. You must add a reference to assembly 'Z.EntityFramework.Extensions, Version=8.102.1.0, Culture=neutral, PublicKeyToken=59b66d028979105b'.	

Based on the your previous reply I'm making conclusion that it's ok to refence Z.EntityFramework.Extensions and Z.Expressions.Eval in the **commercial** product without purchasing license. So, I can include Z.EntityFramework.Extensions into my project without violating license? So, I just need to make sure that none of my developers accidentally used paid functionality?

Are there any options to know which functionality\classes\etc (like InsertFromQuery you mentioned above) from the Z.EntityFramework.Extensions package is ok to use without license?

**Comment by JonathanMagnan** [comment]
Hello @antonpmpu ,

>  So, I can include Z.EntityFramework.Extensions into my project without violating license

Sure, there is no problem doing it.

You can ensure only community features through the `EntityFrameworkManager.IsCommunity = true`. When enabled, it will throw an error as soon as you use a paid feature.

You indeed need to keep a commercial license in the project. They share many codes, and some free features are even almost 100% part of the `Z.EntityFramework.Extensions` library.

> Are there any options to know which functionality\classes\etc (like InsertFromQuery you mentioned above) from the Z.EntityFramework.Extensions package is ok to use without license?

Pretty much all methods which doesn't contain the word `Bulk` is free so far. The only exception could be the `BatchSaveChanges` for EF6 which is also paid.

Let me know if that answer correctly your questions

Best Regards,

Jon
