### ISSUE TITLE
First() returns null (but should throw)

### ISSUE THREAD

**Issue by blackboxlogic** [zzzprojects/EntityFramework-Plus#757]
## 1. Description
I'm using `IQueryable.First()` on a query which sometimes returns empty. Based on the [documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.firstasync?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstAsync%60%601)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=efcore-6.0), when the result set is empty, I expect `First()` to throw `InvalidOperationException`, but instead, it returns null. This only happens when I call `.IncludeFilter()` on the query.

Is this expected behavior? Is there a way to restore `First()`'s exception behavior?

## 3. Fiddle or Project

Sample code:
(Storage is my dbContext, Clients can have Devices)
```
	// I expect this to throw an exception, but it returns null
	var returnsNull = Storage.Clients
		.Where(c => false) // Make sure there's no results
		.IncludeFilter(c => c.Devices)
		.First();

	// This throws an exception as expected
	var throwsAsExpected = Storage.Clients
		.Where(c => false) // Make sure there's no results
		.First();
```

## 4. Any further technical details
The issue happens with async calls also.

Z.EntityFramework.Plus.EFCore 6.18.5
Microsoft.EntityFrameworkCore.Tools 6.0.14
Microsoft.EntityFrameworkCore.SqlServer 6.0.14

**Comment by JonathanMagnan** [comment]
Hello @blackboxlogic ,

Thank you for reporting.

We will look at this issue as indeed, it shouldn't be the default behavior.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by JonathanMagnan** [comment]
Hello @blackboxlogic ,

The v7.20 has been released.

The issue should be fixed for `First` and `Single` methods and both will now return an error.

Best Regards,

Jon

**Comment by blackboxlogic** [comment]
Thanks for the fix @JonathanMagnan. I'm just trying this library out and I'm glad it's maintained.
