### ISSUE TITLE
Exception System.InvalidProgramException when calling IncludeOptimized() & Future() in .net MAUI Project

### ISSUE THREAD

**Issue by Adrian72112** [zzzprojects/EntityFramework-Plus#760]
## 1. Description
We are migrating an app from xamarin forms to .net maui and we are running into an issue with this library when calling this extension methods:

1. .IncludeOptimized()
2. .Future()

The sample project is in .net 6 but we have the same issue with a .net 7 maui project too.

```
Imported nuget:
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.15" />
		<PackageReference Include="SQLitePCLRaw.core" Version="2.1.4" />
		<PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.1.4" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.4" />
		<PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.4" />
		<PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="6.20.1" />
	</ItemGroup>

.  .  .
.  .  .

.Services.AddDbContextFactory<FoodContext>(opts =>
{
	opts.UseSqlite($"Filename=foods.sqlite3");
})   

.  .  .
.  .  .

using var ctx = factory.CreateDbContext();
                Food = ctx.FoundationFoods
                    .IncludeOptimized(ff => ff.FoodNutrients)
                    .IncludeOptimized(ff => ff.FoodNutrients.Select(fn => fn.Nutrient))
                    .IncludeOptimized(ff => ff.FoodPortions)
                    .IncludeOptimized(ff => ff.FoodPortions.Select(fp => fp.MeasureUnit))
                    .FirstOrDefault(ff => ff.Id == FoodId);

```
## 2. Exception

```
Z.EntityFramework.Plus.EFCore
   at Z.EntityFramework.Plus.InternalExtensions.IsInMemoryQueryContext[FoundationFood](IQueryable`1 query)
   at Z.EntityFramework.Plus.QueryFutureExtensions.FutureValue[FoundationFood](IQueryable`1 query)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedProvider`1[[FoodDatabase.Data.FoundationFood, FoodDatabase, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Execute[FoundationFood](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[FoundationFood](IQueryable`1 source, Expression`1 predicate)
   at FoodDatabase.ViewModels.FoundationFoodViewModel.Init() in /Users/atesore/Desktop/FoodDatabaseMaui-main/FoodDatabase/ViewModels/FoundationFoodViewModel.cs:line 62
   at FoodDatabase.ViewModels.FoundationFoodViewModel.ShowFoodAsync(Int32 foodId, String returnRoute) in /Users/atesore/Desktop/FoodDatabaseMaui-main/FoodDatabase/ViewModels/FoundationFoodViewModel.cs:line 77
```

We tried creating our custom nuget package with the reference inMemoryQueryContext removed but no luck:

```
{System.TypeLoadException: Generic Type Definition failed to init, due to: Could not load type of field 'Z.EntityFramework.Plus.QueryIncludeOptimizedParentQueryable`1[T]:<InternalProvider>k__BackingField' (1) due to: Could not resolve type with token 01000079 from typeref (expected class 'Microsoft.EntityFrameworkCore.Query.Internal.IAsyncQueryProvider' in assembly 'Microsoft.EntityFrameworkCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') assembly:Microsoft.EntityFrameworkCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type:Microsoft.EntityFrameworkCore.Query.Internal.IAsyncQueryProvider member:(null) assembly:/data/data/com.app.foodDatabase/files/.__override__/Z.EntityFramework.Plus.EFCore.dll type:QueryIncludeOptimizedParentQueryable`1 member:(null)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedExtensions.IncludeOptimized[User, UserGroup](IQueryable`1 query, Expression`1 queryIncludeFilter)
```
## 3. Fiddle or Project

Repo project:
https://github.com/Adrian72112/mauiEfPlusException

.Net 6 MAUI Project

## 4. Any further technical details

- EF version: 6.0.15
- EF Plus version: 6.20.1
- DB Provider: Sqlite

**Comment by JonathanMagnan** [comment]
Hello @Adrian72112 ,

Unfortunately, how we currently obfuscate the library is incompatible with Maui. However, we are currently working on it.

We already planned in mid-April to make several tests to make it compatible, so that's coming soon.

Best Regards,

Jon

**Comment by Adrian72112** [comment]
Hello @JonathanMagnan , hope you are doing well

Do you have any updates on this ?

Best regards,
Adrian

**Comment by JonathanMagnan** [comment]
Hello Adrian,

I will provide you an update next Tuesday.

**Comment by JonathanMagnan** [comment]
Hello @Adrian72112 ,

Here is the message answered to your manager this morning:

I got a discussion with my team yesterday.

We got a good and bad news about this issue.

**The bad**
Since that’s a significant change, we cannot deploy the fix directly to EF Extensions. Started by next month, we will begin to deploy the fix on some of the less popular libraries and see if someone got an error before rolling this fix to more popular libraries.

**The good**
However, we could directly give you a DLL with the issue fixed. So, at the same time, it will allow you to let us know if everything works as expected.

If you are interested, let us know exactly which version of our library you are currently using, and I will give you a direct download link (by email).

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello again, 

Since our last conversation, we haven't heard from you. 

Let me know if you need further assistance. 

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @Adrian72112 

A simple reminder that we are here to assist you. 

Don't hesitate to contact us if you need anything. 

Best regards, 

Jon

**Comment by Adrian72112** [comment]
Hello Jon,

Thank you for your message. We have received the DLL with the issue fixed and have tested it in MAUI. We can confirm that it is working correctly. We apologize for the delayed response on our end !

Best regards,
Adrian
