### ISSUE TITLE
Combine Future and FromCache

### ISSUE THREAD

**Issue by MrX101** [zzzprojects/EntityFramework-Plus#761]
I've been trying to figure out a way to make it so I can combine a large amount of requests into a single trip and then cache the result. But so far I see no way to achieve this without somehow manually adding the resulted to the cache. Is there something I'm missing in regards to this?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @MrX101 ,

You are not missing anything.

Both features cannot be used together.

It might eventually change as I see the value of being able to mix both, but at this moment, there is no plan for doing it.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)
