### ISSUE TITLE
Version 8 preview 4 has a .Contains bug

### ISSUE THREAD

**Issue by virzak** [zzzprojects/EntityFramework-Plus#767]
## 1. Description
Multiple `context.Customers.Where(z => allowedNames.Contains(z.Name)).DeferredCount().FutureValue();` throws.

This is possibly due to [improved contains](https://devblogs.microsoft.com/dotnet/announcing-ef8-preview-4/)

## 2. Exception
If you are seeing an exception, include the full exception details (message and stack trace).

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Z.EntityFramework.Plus.InternalExtensions.CopyFrom(DbParameter this, IRelationalParameter from, Object value, String newParameterName)
   at Z.EntityFramework.Plus.QueryFutureBatch.CreateCommandCombined(Boolean isAsync)
   at Z.EntityFramework.Plus.QueryFutureBatch.ExecuteQueriesAsync(CancellationToken cancellationToken)
   at Z.EntityFramework.Plus.QueryFutureValue`1.ValueAsync(CancellationToken cancellationToken)
   at Program.Main()
   at Program.<Main>()
Command terminated by signal 6
```

## 3. Fiddle or Project

[Improved contains with deferred count](https://dotnetfiddle.net/N16Qn7)

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

Thank you for reporting.

We will look at it.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by virzak** [comment]
It is that Declare statement in the generated SQL, isn't it?

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

We currently successfully fixed the part we had an issue with generating new `JSON` format values.

However, we still have an issue later that we are currently trying to understand. So we slowly progress but still have no solution for this preview yet.

**Comment by virzak** [comment]
Good thing I'm an upgrade freak,so you get a head start. Let me know if I can contribute in any way.

**Comment by virzak** [comment]
Hi @JonathanMagnan, any progress with this issue? Not a pressing issue, since 8 preview 3 still works fine, but EF Core 8 is about a 1.5 months to RC 1.

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

Honestly, we try from time to time but still have not found any good solution.

We updated recently to the last preview but still have the same bug so we will surely have eventually to put more time on it (we were somewhat hoping that the issue could be fixed within a new preview version but it doesn't look to happen)

**Comment by virzak** [comment]
Amazing! Thanks @JonathanMagnan! If you can release it for EF Core 8 preview 6 (the last .NET 6 version) it would be appreciated, since I can't currently move the clients to .NET 8 while it is still in beta or rc. Not a biggie if you can't though, as long as it works in November.

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

A new version has been released today for [EF Core 8 - Preview 7](https://www.nuget.org/packages/Z.EntityFramework.Extensions.EFCore/8.0.0-preview.7.23375.4-03)

Unfortunately, due to how our versioning works for the previous version, it was too hard to release this fix for preview 6 as well.

We saw today that `RC1` has been released, so a new version will probably be released for `RC1` as well next week (We currently don't know if preview 7 of our library is already compatible with the `RC1`).

Best Regards,

Jon
