### ISSUE TITLE
IncludeOptimized does not work with private set

### ISSUE THREAD

**Issue by SpaceOgre** [zzzprojects/EntityFramework-Plus#769]
## 1. Description
If an Entity class have a property with private set then IncludeOptimized does not work.

## 2. Exception
```
System.ArgumentException: Property set method not found.
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Z.EntityFramework.Plus.PropertyOrFieldAccessor.SetValue(Object obj, Object value)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.CheckNullRecursive(Object currentItem, List`1 paths, Int32 index)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedNullCollection.NullCollectionToEmpty(Object item, List`1 childs)
   at Z.EntityFramework.Plus.QueryIncludeOptimizedParentQueryable`1.CreateEnumerable()
   at Z.EntityFramework.Plus.QueryIncludeOptimizedParentQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

## 3. Fiddle or Project
```csharp
public class Entity
{
    public Collection<Child> Children { get; private set; }
}

public class Child{}
```

## 4. Any further technical details
I think it might be that you get the properties from the Entity Framework wrapper class type instead of the type from the actual class, since if you get it from the actual class then SetValue from PropertyInfo should work just fine for private setters.

Does not work:
```csharp
using System;
using System.Reflection;
using System.Reflection.Emit;

public class BaseClass
{
    public virtual String Prop
    {
        get;
		private set;
    }
}

public class ImpClass : BaseClass
{
}

public class TypeMain
{
    public static void Main() 
    {
        Type myType =(typeof(ImpClass));
	var obj = new ImpClass();
        PropertyInfo[] myPropertyInfo = myType.GetProperties(BindingFlags.Public|BindingFlags.Instance);
	myPropertyInfo[0].SetValue(obj, "test", null);
	obj.Dump();
    }
}
```

But this does:
```csharp
using System;
using System.Reflection;
using System.Reflection.Emit;

public class BaseClass
{
    public virtual String Prop
    {
        get;
		private set;
    }
}

public class ImpClass : BaseClass
{
}

public class TypeMain
{
    public static void Main() 
    {
        Type myType =(typeof(BaseClass));
        var obj = new ImpClass();
        PropertyInfo[] myPropertyInfo = myType.GetProperties(BindingFlags.Public|BindingFlags.Instance);
	myPropertyInfo[0].SetValue(obj, "test", null);
	obj.Dump();
    }
}
```

**Comment by JonathanMagnan** [comment]
Hello @SpaceOgre ,

Do you think you could create a Fiddle with the issue?

My developer tried to reproduce it, but he tells me everything is working: https://dotnetfiddle.net/2ab36j

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by SpaceOgre** [comment]
@JonathanMagnan will see if I can manage that.

But now i see that I totally forgot to mention that I saw the problem on Net Framework 4.8, sorry about that.

**Comment by JonathanMagnan** [comment]
Hello @SpaceOgre ,

Look like my developer cannot reproduce it either with EF6: https://dotnetfiddle.net/dsnsPF

Could you check what he did wrong on the Fiddle and provide one with the issue?

Best Regards,

Jon

**Comment by SpaceOgre** [comment]
@JonathanMagnan I finally tracked down the problem...

My first report was not correct, the problem arises when include a sub-child in the child include with at select:
```csharp
context.Set<Parent>().IncludedOptimized(x => x.Children.Select(y => y.Toy))
```

See this fiddle: https://dotnetfiddle.net/5q2VuO

**Comment by JonathanMagnan** [comment]
Hello @SpaceOgre ,

Unfortunately, we will have to abandon this one.

While we can successfully reproduce this issue, we have not found any easy way to fix it.

The proxy type created by Entity Framework makes handling this scenario harder.

So at this moment, we will treat this scenario as unsupported.

Best Regards,

Jon

---

**Are you finding this library useful? If so, please consider supporting its continued development by [becoming a sponsor](https://github.com/sponsors/zzzprojects).**

Additionally, if you think your enterprise would benefit from this library, we encourage you to suggest they [become a sponsor](https://github.com/sponsors/zzzprojects) as well. Your support will help ensure this library remains alive and well-supported.

**Comment by SpaceOgre** [comment]
@JonathanMagnan no problem, totalt get that it might be hard to fix. And the use of private setter in these cases is probably pretty rare. An easy fix is to use protected instead of private and you get more or less the same protection as private.
