### ISSUE TITLE
Slow performance using Query Filter Inheritance with automapper

### ISSUE THREAD

**Issue by gregemes** [zzzprojects/EntityFramework-Plus#77]
Hi,

I'm using the following code:

[Context constructor]:
this.Filter<BaseEntity>("SoftDelete", q => q.Where(x => !x.IsDeleted), isEnabled : true);

When I use auto mapper to map an IQueryable to IEnumerable, the performance is verrrrry slow (for this particular method, which is, FYI, an entity that doesn't inherit BaseEntity).

[MVC Controller]
var contacts = _mapper.Map<IEnumerable<ContactTableViewModel>>(query);

Am I doing something wrong? Please help!

Thanks

**Comment by gregemes** [comment]
By the way, I don't seem to have the issue with version 1.4.8, so I'm reverting to that for now!

**Comment by gregemes** [comment]
We are lazy loading in the entity that is slow. I suspect 1.4.10 broke something

**Comment by zzzprojects** [comment]
Hello @gregemes ,

I will look at this issue this weekend. We did a change on EF+ Query Filter which may impact the performance, so we will "revert" this change and add options instead.

I will give you more detail on Monday.

Best Regards,

Jonathan

**Comment by gregemes** [comment]
Great thanks- let me know if I can help at all.

**Comment by zzzprojects** [comment]
Hello @gregemes ,

We did a rollback on the changes we added in v1.4.10

Make sure to read the current [EF6 Limitation with Query Filter](https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Query-Filter-%7C-Entity-Framework-Dynamic-Instance-and-Global-Filters#entity-framework-6---limitations)

Let me know if the performance is now back to normal.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing Comment: Issue should be fixed since v1.4.10
