### ISSUE TITLE
How can i check free functions? 

### ISSUE THREAD

**Issue by KMastalerz** [zzzprojects/EntityFramework-Plus#770]
Hey i have really 'not smart' query: I assume not all functions/methods from this library are free, due to extensions reliability? How can I distinguish them?

**Comment by JonathanMagnan** [comment]
Hello @KMastalerz ,

First, I would recommend you to add this options to make sure that any paid features will throw an error right away:

```
EntityFrameworkManager.IsCommunity = true
```

You can see a good list of all free and paid features in the download page: https://entityframework-plus.net/download

In short, what is paid is:
- BatchSaveChanges (for EF6)
- Any features with "Bulk" inside of the name such as `BulkInsert`, `BulkSaveChanges`

Let me know if that answer correctly to your question.

Best Regards,

Jon

**Comment by KMastalerz** [comment]
Yes, I think it sums it up :)

**Comment by KMastalerz** [comment]
Thanks for quick response 👍
