### ISSUE TITLE
Parallel usage of EFCore and EF6

### ISSUE THREAD

**Issue by pfeigl** [zzzprojects/EntityFramework-Plus#774]
We have legacy code for an old database which is not migrated to EFCore but can be used in newer projects due to the code beeing built for netstandard2.1 with EF6.3.

In a newer project we write new DB code for a different database based on EFCore but have a reference to the legacy code.

Now, when we want to use something like `IQueryable<T>.UpdateAsync` we get quite a few errors because the code cannot identify from where to import it, as the namespace and class for the extension method is exactly the same in EFCore and EF6 of your libraries.

We have been able to resolve the situations for now by external aliasing the EF6 assembly.

However this feels very cumbersome. Is there any easier way to have both packages referenced and not get those errors?
Or do you offer other / alternative packages which also split the namespaces into something like EFCore and EF6 (instead of only splitting the assemblies / nuget packages)?

The root of the problem seems to be, that everything is just provided under the same `Z.EntityFramework.Plus` namespace and class- and method names collide in there.

Thanks,
Philipp

**Comment by JonathanMagnan** [comment]
Hello @pfeigl ,

Unfortunately, external aliasing one of both library is probably the "easiest" to do if both libraries are in the same project.

We currently don't have any alternative solution.

Best Regards,

Jon
