### ISSUE TITLE
The EF Plus batch Delete throws null reference exception.

### ISSUE THREAD

**Issue by nandhakishore92** [zzzprojects/EntityFramework-Plus#776]
I call the EF Plus batch delete method as follows:

`db.TestEntries.Where(row => row.Id > 3).Delete();`

With that simple delete call, I am getting a null reference exception. Please find below the stack trace.
```
   at Z.EntityFramework.Extensions.BatchDelete.Execute[T](IQueryable`1 query)
   at DbContextExtensions.[](IQueryable`1 , Action`1 , CancellationToken )
   at DbContextExtensions.DeleteFromQuery[TEntity](IQueryable`1 query, Action`1 bulkOperationFactory)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query, Action`1 batchDeleteBuilder)
   at Z.EntityFramework.Plus.BatchDeleteExtensions.Delete[T](IQueryable`1 query)
```

As I checked the BatchDeleteExtensions class of the EF Plus package, it has the following 2 extension methods for IQueryable<T>.
```
public static int Delete<T>(this IQueryable<T> query) where T : class
{ 
       return query.Delete(null); 
}

public static int Delete<T>(this IQueryable<T> query, Action<BatchDelete> batchDeleteBuilder) where T : class
{
	return query.DeleteFromQuery(delegate (BulkOperation options)
	{
		options.InternalIsEntityFrameworkPlus = true;
		options.BatchDeleteBuilder = batchDeleteBuilder;
	});
}
```
If I directly use the DeleteFromQuery as follows, it works.
`db.TestEntries.Where(row => row.Id > 3).DeleteFromQuery();`

What is the difference? The EF plus batch delete failed because it passes a null parameter to another delete method instead of directly calling query.DeleteFromQuery without any parameter?

**Comment by JonathanMagnan** [comment]
Hello @nandhakishore92 ,

I believe you are currently using `EF6` right? Initially, EF Plus had a different `Batch Delete` code than EF Extensions but shared the same logic for more complex scenarios.

I'm not sure at this moment why it failed in your case, but I believe that your context `db` has something we didn't expect to happen. A normal `Delete` still work great in our unit test and on Fiddle: https://dotnetfiddle.net/R6D5BX

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

We will be able to give a better explanation / fix if we can reproduce this issue.

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by JonathanMagnan** [comment]
> I am just curious why the second Delete method is called in the first one by simply passing null for the batchDeleteBuilder parameter. 

Simply for not repeating the code. By default, the `BatchDeleteBuilder` is null, so they share the same logic. Separating the code will be like:

```csharp
public static int Delete<T>(this IQueryable<T> query) where T : class
{ 
	return query.DeleteFromQuery(delegate (BulkOperation options)
	{
		options.InternalIsEntityFrameworkPlus = true;
		// options.BatchDeleteBuilder = batchDeleteBuilder;
	});
}
```

which will have a similar behavior that is calling the second method with null as the second parameter for the `batchDeleteBuilder`

> db.TestEntries.Where(row => row.Id > 3).DeleteFromQuery();

What currently makes the code work is not using the logic that was created in EF Plus.  You currently do not specify that the `DeleteFromQuery` should use the EF Plus logic by not specifying the following line: `options.InternalIsEntityFrameworkPlus = true;`.

As said, the EF Plus and EF Extensions have 2 differents logics and doesn't work at all in the same way for common scenario (without inheritance).

**Comment by nandhakishore92** [comment]
Hi Jon,

I think I found the issue. When I have a child entity that inherits from the parent entity, I am unable to delete the records from the child entity using the EF Plus IQueryable Delete extension method. But I can delete it fine with the EF Extensions DeleteFromQuery extension method.

I managed to create the fiddle where we can reproduce the issue. Please find it here: https://dotnetfiddle.net/eQAeZt.

Regards,
Nantha

**Comment by JonathanMagnan** [comment]
Awesome @nandhakishore92 ,

I will give this issue to my developer so he can look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @nandhakishore92 ,

I did a meeting with my employee to discuss this issue, and here is a quick summary:

For `EF6`, the `Delete` and `DeleteFromQuery` methods are 2 different methods (Unlike EF Core, in which the same exact code is used).

In short, the way the SQL is generated is better when using the `Delete` method (there is some slight difference). However, only the `DeleteFromQuery` method supports inheritance. The `Delete` method never supported inheritance.

Both methods are free and will always stay free, so for the case with inheritance, you can use `DeleteFromQuery`.

There is currently no plan to support inheritance for the `Delete` method in EF6 as we will now just redirect people to use `DeleteFromQuery` for those cases.

I'm not sure if that answers 100% to all your questions but if no, just let me know what else you will want to know.

Best Regards,

Jon

**Comment by nandhakishore92** [comment]
Hi Jon,

Thanks for the update! 

I think it answers my questions. I understand that it is safe to use DeleteFromQuery in the place of Delete. The only advantage of Delete is that it is "better" in generating the SQL but there won't be any differences in the actual delete operation. I will find and replace the Delete with DeleteFromQuery for the entities with inheritance in the code.

With that, I will close the ticket and if I need any more help, I will come back. Thanks again!

Regards,
Nantha
