### ISSUE TITLE
FromCache internally calls AsNoTracking<T> but should use AsNoTrackingWithIdentityResolution<T>

### ISSUE THREAD

**Issue by schuettecarsten** [zzzprojects/EntityFramework-Plus#780]
Internal implementations of `FromCache` or `FromCacheAsync` calls `AsNoTracking<T>` but should use `AsNoTrackingWithIdentityResolution<T>`. Identity resolution should be performed to ensure that all occurrences of an entity with a given key in the result set are represented by the same entity instance, also when query results are cached.

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

Thank you for reporting, we were not aware of this method.

We will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

We investigated the `AsNoTrackingWithIdentityResolution,` and the major problem we saw was the memory and the performance.

A simple case with 10k `Invoice` with every invoice having 5 `InvoiceItem` (so 60k entities in total) will take around 50% more memory and up to 4x more time. Obviously, the number will vary with the number of entities and `Include` and depending of the scenario, but you get the point.

So, by default, we are not really comfortable to change this current behavior. It will add some pros but also some cons.

Let me know if that makes sense.

Best Regards,

Jon

**Comment by schuettecarsten** [comment]
@JonathanMagnan 

I know about the performance and memory impacts but for my code it is very important that EF knows the entities and the IDs. So is an optional paramater an option? Like `.FromCache(bool useIdentityTracking = false)`? Biggest problem is that if I use `AsNoTrackingWithIdentityResolution `myself, it is overwritten by `AsNoTracking `in `FromCache `implementation.

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

Just to let you know that the next time we release EF Plus (probably next week), it will now be possible to set the following options to change the behavior globally:

```csharp
QueryCacheManager.UseAsNoTrackingWithIdentityResolution = true;
```

Best Regards,

Jon
