### ISSUE TITLE
[8.0.0-rc.1] Exception on MergeBulk with ColumnPrimaryKeyExpression, Column not found

### ISSUE THREAD

**Issue by schuettecarsten** [zzzprojects/EntityFramework-Plus#781]
I have an entity like this:

```csharp
public sealed partial class AzureConsumptionGroup : CmtTenantEntity
{
	[Column("Fk" + nameof(SubscriptionID))]
	public long SubscriptionID { get; set; }

	[ForeignKey(nameof(SubscriptionID))]
	public AzureSubscription Subscription { get; set; }

	public int YearAndMonth { get; set; }
```

The table has a column `FkSubscriptionID` as expected. When using `MergeBulkAsync` and `ColumnPrimaryKeyExpression` with the `SubscriptionID` property, I get an exception that the according column `SubscriptionID` cannot be found. That worked fine in 7.0.0 versions and fails since testing with 8.0.0-rc.1 here.

Sample code for BulkMergeAsync:

```csharp
	await dbContext.BulkMergeAsync(entitiesCollection, delegate (BulkOperation<TEntity> operation)
	{
		operation.ColumnPrimaryKeyExpression = x => new
		{
			x.SubscriptionID,
			x.YearAndMonth
		};
	}, cancellationToken).ConfigureAwait(false);
```

Exception:

```
An error occured while resolving ColumnPrimaryKey expression or name. See the inner exception for details.'

Inner Exception:
Missing Column : SubscriptionID
On entity : AzureSubscription
On Table : [azure].[Subscription]

Callstack:
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkMerge()
   at .BulkMerge[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .[](DbContext , SavingSelector , Action`1 )
   at .[](DbContext ,  , BulkOperationActionType , Action`1 )
   at .BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.`1.()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DbContextExtensions.`1.MoveNext()
   at EntityFrameworkDataContextExtensions.<MergeBulkAsync>d__13`3.MoveNext() [...]
```

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

My developer is currently not able to reproduce the same issue in EF Core 8. For an unknown reason, our library still tries to use the column name `SubscriptionID` instead of `FkSubscriptionID`. 

Best Regards,

Jon

**Comment by schuettecarsten** [comment]
@JonathanMagnan 
How to you get the column name from the model, which method/property are you using?

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

We get the column name from this method: https://github.com/dotnet/efcore/blob/726cb83f4b462265625ee3ea39f5c22df3bb0e49/src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs#L52

However, the column name depends on the `EntityType` as well (the `StoreObjectIdentifier` part), so depending on which kind of inheritance is `AzureConsumptionGroup`, we might have an issue and try to find the column name from the wrong entity type.

Surely having a project will help us to discover the problem.

**Comment by schuettecarsten** [comment]
@JonathanMagnan 
Ok, I just wanted to make sure that EFCore returns the correct column name for my model - it does. I will create a test project, meanwhile, please note that this only happens when I use the new IncludeGraph feature. Maybe this helps before I have the time to create the sample project.

**Comment by schuettecarsten** [comment]
@JonathanMagnan 
I've created a small sample project that throws the exception. Uncomment line 14 in Program.cs and it works. Please note lines 24 and 29 in TestContext.cs and the `HasColumnName` there. If I do not set the column name, it also works. Looks like the IncludeGraph does not respect the custom column names.

Link: https://1drv.ms/u/s!Ajk93YqKTO5fiJBeAPcCF4DIhzGtSQ?e=vb6gZ6

**Comment by JonathanMagnan** [comment]
Thank you @schuettecarsten, for the project,

We can now successfully reproduce the issue

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

We indeed has a bug with the `ColumnPrimaryKeyExpression`. Normally, options specific for an entity must be set in the [IncludeGraphOperationBuilder](https://entityframework-extensions.net/include-graph#includegraphoperationbuilder) such as:

```csharp
context.BulkMerge(entities, operation =>
{
	operation.IncludeGraph = true;	
	operation.IncludeGraphOperationBuilder = builder =>
	{
		if (builder is BulkOperation<Author>)
		{
			var bulk = (BulkOperation<Author>) builder;

			bulk.ColumnPrimaryKeyExpression = x => new
			{
				x.FirstName,
				x.LastName
			};
		}
	};
});
```

With the following code, our library now knows that the [ColumnPrimaryKeyExpression](https://entityframework-extensions.net/column-primary-key-expression) must be set only for the `Author` entity and not the `Book` entity.

We will look more at this issue to make sure the right error (to use `IncludeGraphOperationBuilder`) will be thrown in the upcoming release.

Let me know if that solves this issue.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

Starting from v8.101.0.0, the [ColumnPrimaryKeyExpression](https://entityframework-extensions.net/column-primary-key-expression) and similar options will now throw an error when multiple type is used.

We improved the error message to make it easier to understand that the option must be inside the [IncludeGraphOperationBuilder](https://entityframework-extensions.net/include-graph#includegraphoperationbuilder)

Best Regards,

Jon
