### ISSUE TITLE
FromCache: how to deal with lazy loading

### ISSUE THREAD

**Issue by ff-ils** [zzzprojects/EntityFramework-Plus#783]
In a website, if multiple requests use the same cached object that has lazy loaded collections, the enumeration breaks, because the object is bound to the first context (the context is Scoped).

Here is an example of test that fails:

	// Arrange	
	var ctx1 = ContextFactory.Create();
	var ctx2 = ContextFactory.Create();

	// Act
	var obj1 = ctx1.Set<MyEntity>().Where(i => i.Id == 1).FromCache()!;
	var obj2 = ctx2.Set<MyEntity>().Where(i => i.Id == 1).FromCache()!;

	// Assert
	Assert.That(obj1, Is.Not.SameAs(obj2));

Probably in this case the caching should happen at a lower level, i.e. on results from the SQL query and not on the instantiated entity. Is there a way to use EF Plus or I should find or implement a different solution?

**Comment by JonathanMagnan** [comment]
Hello @ff-ils ,

I just made a small test, and the objects look to be equal on my side (for the enum):

```csharp
var enum1 = context1.EntitySimples.Where(x => x.ColumnInt > 1).FromCache()!;
var enum2 = context2.EntitySimples.Where(x => x.ColumnInt > 1).FromCache()!;

var test1 = enum1 == enum2; // true
var test2 = object.Equals(enum1, enum2); // true
```

However, I'm not sure I would recommend our `FromCache` with proxy as you stated, the entities will keep a reference to the first context that called it from the cache.

Best Regards,

Jon
