### ISSUE TITLE
Add NET 8 support

### ISSUE THREAD

**Issue by KAJOOSH** [zzzprojects/EntityFramework-Plus#786]
Hello
The official and final version of NET 8 has been released.
Please upgrade the packages.

**Comment by JonathanMagnan** [comment]
Hello @KAJOOSH ,

The v8.101.0.0 is finally released.

You can download EF Plus for EF Core 8 here: https://www.nuget.org/packages/Z.EntityFramework.Plus.EFCore/8.101.0

Best Regards,

Jon
