### ISSUE TITLE
AuditConfiguration.Exclude(Func<object, bool>) allows any custom logic, but caches the result only by entity type

### ISSUE THREAD

**Issue by ascott18** [zzzprojects/EntityFramework-Plus#788]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
I have the following audit configuration:

``` cs
// Ignore creation of new timeslots, which is automatic and not interesting
.Exclude(e => e is TimeSlot ts && ts.TimeSlotId == default)
```

I would expect this configuration to filter out all creations of new TimeSlot entities, but instead it will either include or exclude all TimeSlot changes depending on whether the very first change since application startup was a create or not.

This is because `IsAuditedEntity` is caching the results of the predicate based only on type name, ignoring that there could be _any_ kind of logic inside the predicate. If this predicate is supposed to only be able to make determinations based on type, I would expect it to be passed a `System.Type` instance, not the actual entity instance. I don't see any documentation that states that this predicate-based exclusion is supposed to only be allowed to make determinations based on type.

## 3. Fiddle or Project
Reproduction is trivial and self-evident from the library's [source code](https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.Audit.Shared/AuditConfiguration/IsAuditedEntity.cs#L37-L41).

### Further technical details

- EF version: 8.0.0
- EF Plus version: 8.101.1.2
- Database Server version: N/A
- Database Provider version (NuGet): N/A

**Comment by JonathanMagnan** [comment]
Hello @ascott18 ,

Unless I'm also missing something, you are 100% right. We cache for the `type` if we should include or exclude the entity, and we do not check for every entity, and there is currently no way to do it. For multiple reasons, we don't have to change this default behavior at this moment (mainly performance reasons).

However, we are also open to making it work for your scenario.

At this moment, I see 3 solutions:
1. **Option to "disable cache"**:  By example, `AuditManager.DefaultConfiguration.DisableExcludeIncludeByType = true;`
2. **A new method**: `ExcludeByInstance(...)` // I did find any good name yet but you get the idea
3. **An overload**: `Exclude(predicate, bool)` // might be too much confusing this one

The easiest solution for us will surely be the first solution, as we will probably just have to either add an `if` or disable the check we do in the dictionary in the method you linked.

Do you have any preference on your side or any better idea about how it should be implemented?

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/)

**Comment by ascott18** [comment]
I think something like ExcludeByInstance makes the most sense to me. It would also be nice if the predicate to it would receive the whole `EntityEntry` instead of just the entity instance in order to have access to the `EntityState` (added, modified, deleted) and anything else someone might want to read from the EF change tracking.

**Comment by JonathanMagnan** [comment]
Hello @ascott18 ,

Just to let you know that we are currently doing a code review for a branch with the `ExcludeByInstance`. If everything go well, it should be released on 2024-01-16 or before.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @ascott18 ,

Just to let you know that 4 new methods are coming with our release next Tuesday

- ExcludeByInstance
- ExcludeByEntry
- IncludeByInstance
- IncludeByEntry

I believe it should cover everything you needed.

I will let you know when the new version will be released.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @ascott18 ,

The v8.101.2 has been released.

As said in my previous message, the 4 new methods are now available.

Let me know if that works perfectly or if something else is missing from your requirements.

Best Regards,

Jon

---

**Are you finding this library useful? If so, please consider supporting its continued development by [becoming a sponsor](https://github.com/sponsors/zzzprojects).**

Additionally, if you think your enterprise would benefit from this library, we encourage you to suggest they [become a sponsor](https://github.com/sponsors/zzzprojects) as well. Your support will help ensure this library remains alive and well-supported.

**Comment by ascott18** [comment]
Thank you!

**Comment by JonathanMagnan** [comment]
@ascott18 

Since our last conversation, we haven't heard from you. 

Let me know if everything is working as expected. 

Best regards, 

Jon
