### ISSUE TITLE
Future() throws error when being called from unit test project

### ISSUE THREAD

**Issue by jasbyte** [zzzprojects/EntityFramework-Plus#789]
## 1. Description
I am running a unit test which calls this method:

```
public List<string> Test()
{
    var test = new List<string> { "test" };

    var query = test.AsQueryable();

    var result = query.Future();

    return result.ToList();
}
```

Upon executing Future(). I get the following exception:

> Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com'

## 2. Exception

```
Message: 
Test method 
GetTests.TestMethod threw exception: 
System.Exception: Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com

 Stack Trace: 
PublicInternalExtensions.GetObjectQuery[T](IQueryable`1 query)
QueryFutureExtensions.Future[T](IQueryable`1 query)
QueryHandler.Test() line 157
GetTests.Test() line 587
```

### Further technical details

- EF version: [EF Core v6.4.4]
- EF Plus version: [EF Plus Core v8.103.1.3]

**Comment by JonathanMagnan** [comment]
Hello @jasbyte ,

Are you using a mocking library or something that could affect the `ObjectQuery`? 

It looks like we cannot find the `Query` from the `ObjectQuery` in your unit test.

Best Regards,

Jon

**Comment by jasbyte** [comment]
I am using Moq to mock my repositories

**Comment by JonathanMagnan** [comment]
Hello @jasbyte ,

Our library doesn't work with mocking libraries such as `Moq`. When using this kind of library, you usually mock data, so you don't really query the database, which makes it impossible for us to combine SQL queries.

A few of our features are compatible but some of them like `Query Future` is simply impossible for us.

As far as I can remember, we never supported `Moq` for this feature.

Best Regards,

Jon

**Comment by jasbyte** [comment]
Hello @JonathanMagnan 

Could you maybe explain why it doesn't work for my code I provided? Since in the code I provided I am not making use of the `Moq` library. 

Since I only use `AsQueryable` and `ToList` I would expect this to work fine.

**Comment by JonathanMagnan** [comment]
Hello @jasbyte ,

I don't know exactly your configuration, so it's hard for us to give the right reason why this is happening even if your DbSet doesn't use the Moq library.

However, if you could create a runnable project with the issue, we will be happy to look at it and explain why this is happening in your case.

Best Regards,

Jon

**Comment by jasbyte** [comment]
Hello @JonathanMagnan,

One of my colleagues tried this out in a separate project:

[](https://dotnetfiddle.net/IAOZFh)

But got the same exception. What caused this exception to be thrown since the `Moq` nugget package you mentioned earlier is not used in this project?

**Comment by JonathanMagnan** [comment]
Hello @jasbyte ,

If you provide this separate runnable project, we will be happy to tell you.

We will need to be able to run this project if you want an answer. Otherwise, we have no idea either, as we don't get this issue on our side.

Best Regards,

Jon

**Comment by jasbyte** [comment]
You can view it on this page:

https://dotnetfiddle.net/IAOZFh

**Comment by JonathanMagnan** [comment]
Hello @jasbyte ,

EF Plus must be used with EF6 / EF Core.

You currently don't use a `DbSet` in your example, so that's expected as it is impossible for us to currently `query` a database.

Best Regards,

Jon

**Comment by jasbyte** [comment]
Thank you for help

We ended up using this workaround:

```
public static IEnumerable<T> ToFuture<T>(this IQueryable<T> query)
{
    return query is ObjectQuery
        ? query.Future()
        : (IEnumerable<T>)query;
}
```
