### ISSUE TITLE
Problem with FromCache in EF8 when use "contains" (translated to openJson)

### ISSUE THREAD

**Issue by fenomeno83** [zzzprojects/EntityFramework-Plus#792]
Hi.
I've upgraded to EF8 but I've problems when i use "List.contains(column)".
In EF8, "contains" is translated to "openjson" (vs "IN(...)" of the previous versions).
If some values in List that makes contains,change, fromcache of Z.entityframework.plus doesn't understand the changes and it doesn't make new query, but uses a cached query (for example, if ListA.Contains(column) is cached and I do a new query with ListB.Contains(column), it returns old cached ListA.Contains(column) results and doesn't make a new query for ListB.Contains(column)...maybe fromcache doesn't manage properly openjson?).
I've solved with UseCompatibilityLevel(120) in dbcontext configuration; in this manner it doesn't use openjson but "old" translation in "IN(...)", and fromcache, as usual, understand changes in List.
Can you solve that issue?

**Comment by JonathanMagnan** [comment]
Hello @fenomeno83 ,

A new version is now available. The latest release note now contains this fix: https://github.com/zzzprojects/EntityFramework-Plus/releases/tag/8.102.1.0

Let us know if everything works as expected.

Best Regards,

Jon
