### ISSUE TITLE
AuditEntryProperties saving only primary Key (ID) of my table as PropertyName

### ISSUE THREAD

**Issue by SanthoshKumarGunda** [zzzprojects/EntityFramework-Plus#799]
## 1. Description

I am trying to insert and get pk value once done by using InsertOrUpdateAndGetIdAsync but audit not saving only id for main and chlild entities

## 4. Any further technical details
Add any relevant detail can help us.

i have entity.dbset which has [AuditInclude] attribute

```csharp
[AuditInclude]
[Table("CAPS_GroupTotal")]

public class GroupTotalUnit : FullAuditedEntity, IMustHaveTenant, IMayHaveOrganizationUnit, IHasConcurrency
{
    /// <summary> Overriding the ID column with GroupTotalId field. </summary>
    [Column("GroupTotalId")]
    public override int Id { get; set; }
------
------
}
```

 and with that created a DTO and in that i added another DTO as 
public List<GroupItemsDto> Children { get; set; }

now i am going to do operation as below,
var groupTotalId = await _groupTotalUnitRepository.InsertOrUpdateAndGetIdAsync(groupTotalUnit);

after successful transaction in AuditEntryProperties table in database only getting Id's (which are primary keys) are inserted but not storing the all properties of the table.

Note: for 1st time, i.e; statename 'EntityAdded' storng all properties of bot tables but 'EntityModified' saving only ID's instead of saving all my chages.

in 3 statenames EntityAdded,EntityDeleted is saving all properties(cloums) but EntityModified storing only Id property why not all?

can you help me to resolve this issue.

**Comment by JonathanMagnan** [comment]
Hello @SanthoshKumarGunda ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

At this moment, there are too many variables missing for us to try to reproduce it.

So the best way to get an answer will be to provide a runnable project with only this issue. You can send it also in private here: info@zzzprojects.com

Best Regards,

Jon

**Comment by SanthoshKumarGunda** [comment]
Hi @JonathanMagnan ,
Thanks for Yiur help!

Isuue got resolved.
routecause is calling UpdateAsync and did some modifications(inside the child entites as well) and then called await _unitOfWorkManager.Current.SaveChangesAsync(); due to that cange entries are not fetched in SaveChangesAsync();

**Comment by JonathanMagnan** [comment]
Awesome, thank you for letting us know.

Best Regards,

Jon
