### ISSUE TITLE
Problem with Audit.PreSaveChanges

### ISSUE THREAD

**Issue by andro44** [zzzprojects/EntityFramework-Plus#80]
Hi,

we're having issues with overriden SaveChanges on our Code First DBContext. Sometimes it all goes to hell throwing an "Object reference not set to an instance of an object." error. If we restart VS2015 debugging it starts working again.

I have no idea how to start searching for the cause of this as I'm not familiar with EFPlus source code.

In hope of someone pointing me in the right direction I'm pasting my override method along with the exception stacktrace. If anyone sees any issues, please point them out. This is basically the only EFPlus related code in our solution.

```csharp

    public ApplicationDbContext(IDbAccessConfiguration configuration, IPrincipal principal) : base(configuration.ConnectionString)
    {
      _principal = principal;
      AuditManager.DefaultConfiguration.Exclude(x => true);
      AuditManager.DefaultConfiguration.Include<IAuditable>();

      AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
         // ADD "Where(x => x.AuditEntryID == 0)" to allow multiple SaveChanges with same Audit
         (context as ApplicationDbContext).AuditEntries.AddRange(audit.Entries);
    }

    public override int SaveChanges()
    {
      var audit = new Audit();

      if (_principal != null)
      {
        audit.CreatedBy = _principal.Identity.GetUserId();
      }
      audit.PreSaveChanges(this);
      var rowAffecteds = base.SaveChanges();
      audit.PostSaveChanges();

      if (audit.Configuration.AutoSavePreAction != null)
      {
        audit.Configuration.AutoSavePreAction(this, audit);
        base.SaveChanges();
      }

      return rowAffecteds;
    }
```

```
Object reference not set to an instance of an object.
at Z.EntityFramework.Plus.AuditConfiguration.IsAuditedEntity(ObjectStateEntry entry)
   at Z.EntityFramework.Plus.Audit.PreSaveChanges(Audit audit, DbContext context)
   at ***.DB.ApplicationDbContext.SaveChanges() in ***\ApplicationDbContext.cs:line 105
```

**Comment by zzzprojects** [comment]
Hello Andro44,

I may be wrong but it looks **ApplicationDbContext** is your context constructor. So for every context you create, you add a new rule for "Exclude" and "Include".

So if you create 100 contexts, you will have added 200 rules!

I'm not sure if you use some concurrency, but this could for sure lead to some strange error in concurrency scenario like this one.

You should try to configure the global DefaultConfiguration only once.

By example, in a static constructor

```csharp
static ApplicationDbContext()
{
      AuditManager.DefaultConfiguration.Exclude(x => true);
      AuditManager.DefaultConfiguration.Include<IAuditable>();

      AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
         // ADD "Where(x => x.AuditEntryID == 0)" to allow multiple SaveChanges with same Audit
         (context as ApplicationDbContext).AuditEntries.AddRange(audit.Entries);
}

public ApplicationDbContext(IDbAccessConfiguration configuration, IPrincipal principal) : base(configuration.ConnectionString)
{
	_principal = principal;
}
```

Let me know if you still have the error after trying this.

Best Regards,

Jonathan

**Comment by andro44** [comment]
Well, that was easy :) It seems to have done the trick, thank you for your help.

Regards
Andrej
