### ISSUE TITLE
DeleteAsync with Take on PostgreSQL

### ISSUE THREAD

**Issue by r-ising** [zzzprojects/EntityFramework-Plus#808]
## 1. Description

DeleteAsync not working correctly with .Take() after upgrade from 8.103.1 to 8.103.3

## 2. Any further technical details

Code example

```	
var person1 = await Context.Set<PersonEntity>()
	.AsNoTracking()
	.FirstOrDefaultAsync();

await Context.Set<PersonEntity>()
	.AsNoTracking()
	.Where(p => p.Id == person1.Id)
	.Take(1)
	.DeleteAsync();

var person2 = await Context.Set<PersonEntity>()
	.AsNoTracking()
	.FirstOrDefaultAsync(p => p.Id == person1.Id);
// person2 is not null
```

If we remove the ".Take(1)" then person2 is null and it works correctly.

### Further technical details

- EF version: [EF Core v8.0.7]
- EF Plus version: [EF Plus Core v8.103.3]
- Database Server version: [PostgreSQL 16]
- Database Provider version (NuGet): [Npgsql v8.0.3]

**Comment by JonathanMagnan** [comment]
Hello @r-ising ,

Thank you for reporting.

We will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @r-ising .

Just to confirm that the issue has been fixed.

The fix will be released on September 24.

Best Regards,

Jon

**Comment by r-ising** [comment]
@JonathanMagnan Thanks, that sounds good to me.

**Comment by JonathanMagnan** [comment]
Hello @r-ising ,

The `v8.103.4.0` has been released today: https://github.com/zzzprojects/EntityFramework-Plus/releases/tag/8.103.4.0

Let me know if my developer correctly fixed your issue.

Best Regards,

Jon
