### ISSUE TITLE
How do I ignore / exclude the primary key property changes?

### ISSUE THREAD

**Issue by jamesborza** [zzzprojects/EntityFramework-Plus#81]
I don't want to capture primary key changes.

In the documentation: 
"You can choose to ignore or not property unchanged with IgnorePropertyUnchanged.
By default, properties unchanged are ignored unless it’s part of the primary key."

Doesn't Work:
AuditManager.DefaultConfiguration.IgnorePropertyUnchanged = true;

Doesn't Work:
AuditManager.DefaultConfiguration.ExcludeProperty();
AuditManager.DefaultConfiguration.ExcludeProperty<MyModel>(x => x.Id);

Thanks

**Comment by zzzprojects** [comment]
How will you know which entity has been changed if you don't know the primary key?

Currently, there are no options to do it directly, but you can easily ignore all properties by clearing the list before adding them

```csharp
AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
{
    audit.Entries.ForEach(x => x.Properties.Clear());
    (context as CurrentContext).AuditEntries.AddRange(audit.Entries);
};
```

Let me know why you doesn't want to log the key and we will maybe add the options.

Best Regards,

Jonathan

**Comment by jamesborza** [comment]
I was looking into adding the object PK to the AuditEntries table and not tracking the ID via AuditEntryProperties but I ended up just using the original config.

**Comment by samshiles** [comment]
Hi,

I think the problem is that if you load lots of objects into the context, but do not modify any of them, when you come to SaveChanges, you get audit entries against the unchanged entities which where simply loaded with a single auditentryproperty recording the Id of the entity, with a matching OldValue and NewValue.

**Comment by JonathanMagnan** [comment]
Hello @samshiles ,

Unless we made an error somewhere else, only Added, Modified && Deleted entries are taken

```
var changes = objectContext.ObjectStateManager.GetObjectStateEntries(EntityState.Added | EntityState.Modified | EntityState.Deleted);
```

Best Regards,

Jonathan
