### ISSUE TITLE
How to - .WithHint() together with .Include()

### ISSUE THREAD

**Issue by MartinPrzno** [zzzprojects/EntityFramework-Plus#810]
Hello. We would like to use your method `WithHint`. This is the code in C#:

```
IEnumerable<int> oplIds = ...;

var priceTiers = await _dbContext.PriceTiers
    .AsNoTracking()
    .Where(pt => oplIds.Contains(pt.OfferingPriceListId))
    .Include(pt => pt.TierPrices)
    .WithHint("INDEX(IX_TierPrice_PriceTierId)")
    .ToListAsync(cancellationToken);
```
Which generates SQL code like this:

```
SELECT [p].[Id], [p].[OfferingPriceListId], [p].[UnitsFrom], [p].[UnitsTo], [t].[Id], [t].[FixedPrice], [t].[Price], [t].[PriceTierId], [t].[PriceType], [t].[RenewalPeriod], [t].[UnitPrice]
FROM [priceList].[PriceTier] AS [p] WITH (INDEX(IX_TierPrice_PriceTierId)) -- WITH(INDEX()) is here
LEFT JOIN [priceList].[TierPrice] AS [t] ON [p].[Id] = [t].[PriceTierId]
WHERE [p].[OfferingPriceListId] IN (1585, 1586, ...)
ORDER BY [p].[Id]
```
However, we need the `WITH(INDEX())` to be on the table after `LEFT JOIN`, not after `FROM`, like this:

```
SELECT [p].[Id], [p].[OfferingPriceListId], [p].[UnitsFrom], [p].[UnitsTo], [t].[Id], [t].[FixedPrice], [t].[Price], [t].[PriceTierId], [t].[PriceType], [t].[RenewalPeriod], [t].[UnitPrice]
FROM [priceList].[PriceTier] AS [p]
LEFT JOIN [priceList].[TierPrice] AS [t] WITH (INDEX(IX_TierPrice_PriceTierId)) ON [p].[Id] = [t].[PriceTierId] -- want WITH(INDEX()) to be here
WHERE [p].[OfferingPriceListId] IN (1585, 1586, ...)
ORDER BY [p].[Id]
```
Is this possible to achieve?
Thank you

### Further technical details

- EF version: [EF Core v7.0.15]
- EF Plus version: [EF Plus Core v7.103.5]
- Database Server version: [MS SQL Server]
- Database Provider version (NuGet): [Microsoft.Data.SqlClient v5.1.1]

**Comment by JonathanMagnan** [comment]
Hello @MartinPrzno ,

You can pass a list of `Type` to include to the [Query Hint](https://entityframework-plus.net/ef-core-query-hint) features.

I will update the documentation in a few minutes to include an example.

Here is an example meanwhile with your code:

```csharp
var priceTiers = await _dbContext.PriceTiers
    .AsNoTracking()
    .Where(pt => oplIds.Contains(pt.OfferingPriceListId))
    .Include(pt => pt.TierPrices)
    .WithHint("INDEX(IX_TierPrice_PriceTierId)", typeof(TierPrice))
    .ToListAsync(cancellationToken);
```

As you can see, I added the type as the second parameter `WithHint("INDEX(IX_TierPrice_PriceTierId)", typeof(TierPrice))`

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
The documentation has been updated: https://entityframework-plus.net/ef-core-query-hint#how-to-specify-hints-for-particular-entity-types

Let me know if that is clear enough for the next person who might have this question.

Best Regards.

Jon

**Comment by MartinPrzno** [comment]
Yes, amazing!
Thank you very much
