### ISSUE TITLE
WhereDynamic Fails with Contains on Enum and String Properties

### ISSUE THREAD

**Issue by Josrph** [zzzprojects/EntityFramework-Plus#811]
**Problem Description**
I'm encountering an unexpected behavior with WhereDynamic in Z.EntityFramework.Plus where the Contains method works as expected in an in-memory list of entities but fails when executed against a database context. Specifically, Contains fails when used with both Enum or String properties in a database context.

Consider the following code:

```
public enum ProductType
{
    TypeA,
    TypeB
}

public class TestProduct
{
    public int ID { get; set; }
    public string Name { get; set; }
    public ProductType ProductType { get; set; }
}

string searchTerm = "A";

var testProducts = new List<TestProduct>()
{
	new TestProduct(){ID = 1, Name = "TestProduct1", ProductType = ProductType.TypeA},
	new TestProduct(){ID = 2, Name = "TestProduct2", ProductType = ProductType.TypeB},
};
var list1 = testProducts.WhereDynamic(x => $"x.ID.ToString().Contains(\"{searchTerm}\")").ToList(); // Works
var list2 = testProducts.WhereDynamic(x => $"x.Name.ToString().Contains(\"{searchTerm}\")").ToList(); // Works
var list3 = testProducts.WhereDynamic(x => $"x.ProductType.ToString().Contains(\"{searchTerm}\")").ToList(); // Works

using var ctx = new AppDbContext();
var list4 = ctx.Products.WhereDynamic(x => $"x.ID.ToString().Contains(\"{searchTerm}\")").ToList(); // Works
var list5 = ctx.Products.WhereDynamic(x => $"x.Name.ToString().Contains(\"{searchTerm}\")").ToList(); // Throws InvalidOperationException
var list6 = ctx.Products.WhereDynamic(x => $"x.ProductType.ToString().Contains(\"{searchTerm}\")").ToList(); // Throws InvalidOperationException
```

```
First Exception:
System.InvalidOperationException: 'The LINQ expression 'DbSet<Product>()
.Where(f => f.Name.ToString().Contains("A"))' could not be translated. Additional information: Translation of method 'object.ToString' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'

Second Exception:
System.InvalidOperationException: 'The LINQ expression 'DbSet<Product>()
.Where(f => f.ProductType.ToString().Contains("A"))' could not be translated. Additional information: Translation of method 'object.ToString' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
```

the following packages are installed:
```
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
<PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="8.103.4" />
```

**Comment by JonathanMagnan** [comment]
Hello @Josrph 

Thank you for reporting.

We will look if our library causes the error or if this is a limitation of EF Core / Pomelo.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @Josrph ,

My employee tried your project. See the following online example: https://dotnetfiddle.net/kDlVZC

## First Error
I'm not sure why you get an error here `ctx.Products.WhereDynamic(x => $"x.Name.ToString().Contains(\"{searchTerm}\")").ToList(); // Throws InvalidOperationException`, but looking at our online example, we don't have any problem on our side.

## Second Error
As for the second error `ctx.Products.WhereDynamic(x => $"x.ProductType.ToString().Contains(\"{searchTerm}\")").ToList();`, unfortunately, as you will see in the project, this is a limitation of EF Core and not our library. Even without our library, the same error is throw.

At the same time, it makes sense as only the "int" value from the enum is saved. Not the text representations.

For this one, you should probably filter in the application side. See the `list7` from our online example:

```csharp
// filter enum
var filteredProductTypes = Enum.GetNames(typeof(ProductType))
   .Where(name => name.Contains("searchTerm", StringComparison.OrdinalIgnoreCase))
   .Select(name => Enum.Parse(typeof(ProductType), name))
   .ToList();

var list7 = context.Products.Where(x => filteredProductTypes.Contains(x.ProductType)).ToList();
```

Let me know if that solves all your problems. Otherwise, let us know how we can reproduce the first error.

Best Regards,

Jon

**Comment by Josrph** [comment]
Ok, I solved my problem by using `Convert.ToString()` in `WhereDynamic()` along with using `[Column(TypeName = "nvarchar(20)")] `for all my entity enum properties so they are stored as strings which later allows filtering using `Contains()`

the errors turned out to be coming from `EF Core`, because as you try the same queries that throws using normal Linq Where(), the same exceptions are raised

Thanks anyway for your quick reply!
