### ISSUE TITLE
 Add NET 9 Support

### ISSUE THREAD

**Issue by KAJOOSH** [zzzprojects/EntityFramework-Plus#815]
Hello
The official and final version of NET 9 has been released.
Please upgrade the packages.
* I am facing various errors in "Z.EntityFramework.Plus.EFCore 8.103.6.2" in the project that I upgraded

**Comment by JonathanMagnan** [comment]
Hello @KAJOOSH ,

The support has been added today for [EF Plus (EF Core 9)](https://www.nuget.org/packages/Z.EntityFramework.Plus.EFCore/9.103.6.2)

Let me know if everything works as expected.

Best Regards,

Jon
