### ISSUE TITLE
Get cache key generated and used by FromCache

### ISSUE THREAD

**Issue by fenomeno83** [zzzprojects/EntityFramework-Plus#818]
In there a manner to get generated cachekey (based on query and parameters) by FromCache/FromCacheAsync?

I'd like send cache data via api to all other nodes, so when a node execute query, set own cache (automatically with FromCache), and send the cache data with cache key to all other nodes.
So all other nodes if execute query with same parameters using FromCache, no need to execute on database because use cache (that has sent the first node).

Is a manner to sicronize cache without use a distribuited server cache

Thanks

**Comment by fenomeno83** [comment]
Thanks for response! 
So, you don't expose as output something in FromCache to know what key has created automatically?

**Comment by fenomeno83** [comment]
something like this

       public async Task<List<CountryDto>> GetCountries()
 {
     **string key = null;
     bool isNewKey = false;**
     var ret = (await (from c in _db.Country
                        select new CountryDto()
                        {
                            Code = c.Code,
                            Description = c.Description

                        }).FromCacheAsync(new MemoryCacheEntryOptions() { AbsoluteExpirationRelativeToNow = TimeSpan.FromHours(ExpireCache.LowResetCacheHours) }, ExpireCache.Countries, **out key, out isNewKey**)).ToList();

     return ret;
 }

**Comment by JonathanMagnan** [comment]
Hello @fenomeno83 ,

Unfortunately, we do not expose what you are looking for directly from the method.

But if you look at our implementation, you could probably create your own method as everything you need is public and you have access to it.

For example:

- You can get the cache key this way: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryCache.Shared/Extensions/IQueryable%60/FromCache.cs#L45C15-L45C66
- You can check in the cache itself if the key already exists as the property is public: https://github.com/zzzprojects/EntityFramework-Plus/blob/master/src/shared/Z.EF.Plus.QueryCache.Shared/QueryCacheManager.cs#L158

Best Regards,

Jon

**Comment by fenomeno83** [comment]
Ok thanks, in this manner I can get the 2 info

     public async Task<List<CountryDto>> GetCountries()
     {

           var query = from c in _db.Country
                       select new CountryDto()
                       {
                           Code = c.Code,
                            Description = c.Description

                    };

           var key = QueryCacheManager.GetCacheKey(query, ["Countries"]);


          bool exist =  QueryCacheManager.Cache.TryGetValue(key, out _);


         return (await (query).FromCacheAsync(new MemoryCacheEntryOptions() { AbsoluteExpirationRelativeToNow = TimeSpan.FromHours(8) }, "Countries")).ToList();

      }

**Comment by fenomeno83** [comment]
So, I've created and extension method that wraps FromCacheAsync and do what I need

This is the original query

     public async Task<List<CountryDto>> GetCountries()
     {
       
        var ret = (await (from c in _db.Country
                    select new CountryDto()
                    {
                        Code = c.Code,
                        Description = c.Description

                    }).FromCacheAsync(new MemoryCacheEntryOptions() 
                       { AbsoluteExpirationRelativeToNow = TimeSpan.FromHours(24) }, 
                            "Countries")).ToList();

        return ret;
    }

It became:

      public async Task<List<CountryDto>> GetCountries()
      {
       
         var ret = (await (from c in _db.Country
                    select new CountryDto()
                    {
                        Code = c.Code,
                        Description = c.Description

                    }).FromCacheWrappedAsync(new MemoryCacheEntryOptions() 
                       { AbsoluteExpirationRelativeToNow = TimeSpan.FromHours(24) }, 
                            "Countries")).ToList();

        return ret;
     }

    public static class QuerableExtensions
    {
    public static async Task<IEnumerable<T>> FromCacheWrappedAsync<T>(this IQueryable<T> query, 
      MemoryCacheEntryOptions options, params string[] tags) where T : class
     {
        var key = QueryCacheManager.GetCacheKey(query, tags);

        bool exist = QueryCacheManager.Cache.TryGetValue(key, out _);

        var ret = await query.FromCacheAsync(options, default(CancellationToken), tags);

        if (!exist)
        {
            QueryCacheManager.Cache.TryGetValue(key, out object result);

            //send result to key of other nodes that expose and api that SetValue
        }

        return ret;
    }
}

**Comment by JonathanMagnan** [comment]
Hello @fenomeno83 ,

Awesome, I'm happy you succeeded in making it work.

Can we close this issue as I don't think at this moment we will include it in our base library?

Best Regards,

Jon

**Comment by fenomeno83** [comment]
Yes..thanks
