### ISSUE TITLE
How to use  Query Cache with Repository Pattern

### ISSUE THREAD

**Issue by maharatha** [zzzprojects/EntityFramework-Plus#82]
Hi -

I am using a third part framework and below is the code they have provided me to extend their repository for bulk insert . 

```
namespace MyProject
{
    //Add this class to .Core project

    public static class MyRepositoryExtensions
    {
        public static void Insert<TEntity, TPrimaryKey>(this IRepository<TEntity, TPrimaryKey> repository,
            IEnumerable<TEntity> entities)
            where TEntity : class, IEntity<TPrimaryKey>, new()
        {
            var type = Type.GetType("MyProject.MyRepositoryHelper, MyProject.EntityFramework");

            var bulkInsertMethod = type.GetMethod("BulkInsert", BindingFlags.Static | BindingFlags.Public);

            var genericMethod = bulkInsertMethod.MakeGenericMethod(typeof(TEntity), typeof(TPrimaryKey));

            genericMethod.Invoke(null, new object[] { repository, entities });
        }
    }
}

using System.Collections.Generic;

`namespace` MyProject
{
    //Add this class to .EntityFramework project

    public static class MyRepositoryHelper
    {
        public static void BulkInsert<TEntity, TPrimaryKey>(IRepository<TEntity, TPrimaryKey> repository, IEnumerable<TEntity> entities)
            where TEntity : class, IEntity<TPrimaryKey>, new()
        {
            var dbContext = repository.GetDbContext();
            dbContext.Set<TEntity>().AddRange(entities);
        }
    }
}
```

If i would like to use Z EntiityFramework for query caching , could you please guide me how to use it. Please note the above code is to help you understand how we can extend our repository.

**Comment by zzzprojects** [comment]
Hello @maharatha ,

I don't understand why the method is called BulkInsert when is only add entities with AddRange. That is not close to performance a real bulk insert library can do.

See: [Entity Framework Bulk Insert Library](http://www.zzzprojects.com/entity-framework/library/bulk-insert)

That being said, here is how I recommend you for allowing you to use caching and other features to your repository pattern

```csharp
public static partial class MyRepositoryExtensions
{
    public static DbSet<TEntity> ToSet<TEntity, TPrimaryKey>(this IRepository<TEntity, TPrimaryKey> repository)  where TEntity: class
    {
        return repository.GetDbContext().Set<TEntity>;
    }
}


myRepository.ToSet().Where(...).FromCache();
myRepository.ToSet().Where(...).Future()
// ...etc...
```

I'm not exactly sure how you use your repository pattern, so a better answer could exist. But I believe, the best solution is sometimes to let you have access directly to the DbSet

Let me know if that work or you need a better answer.

Best Regards,

Jonathan

**Comment by maharatha** [comment]
I am using the below code for bulk insert 

```
 public static void BulkInsert<TEntity, TPrimaryKey>(IRepository<TEntity, TPrimaryKey> repository, IEnumerable<TEntity> entities)
            where TEntity : class, IEntity<TPrimaryKey>, new()
        {
            var enumerable = entities as IList<TEntity> ?? entities.ToList();
            if (enumerable.Any())
            {
                if (!Z.EntityFramework.Extensions.LicenseManager.ValidateLicense())
                {
                    throw new Exception("Invalid License!");
                }
                var dbContext = repository.GetDbContext();
                //dbContext.Set<TEntity>().AddRange(entities);
                dbContext.BulkInsert(enumerable);
            }
        }
```

We are using the BulkInsert dll which you have mentioned above.

I was trying to use the same repository pattern and extend the GetAllfromCache

**Comment by maharatha** [comment]
For the repository pattern I am using GetAll returns IQueryable<T>. 

I am using ASPNetBoilerplate and below is the documentation for their coding  

http://www.aspnetboilerplate.com/Pages/Documents/Repositories

And below is the way they have extended the BulkInsert 

https://gist.github.com/hikalkan/74f624c0b42c78fb1619e92b3d1972f8

Hope this will help you to understand more and help me out

**Comment by zzzprojects** [comment]
Well,

I'm just not sure what is the question here ;)

From what I see, you successfully implemented BulkInsert and GetAllFromCache look to be pretty easy to implement.

```csharp
public static partial class MyRepositoryExtensions
{
    public static GetAll<TEntity> GetAllFromCache<TEntity, TPrimaryKey>(this IRepository<TEntity, TPrimaryKey> repository)  where TEntity: class
    {
        return repository.GetAll().FromCache();
    }
}
```

I'm for sure missing something in your question!

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing comment: No answer, feel free to re-open with more information
