### ISSUE TITLE
BulkInsertAsync (.net9) options.ForceValueGeneratedStrategy breaking change 

### ISSUE THREAD

**Issue by fuegans4213** [zzzprojects/EntityFramework-Plus#820]
## 1. Description
I am bumping my **Z.EntityFramework.Extensions.EFCore nuget** from **8.102.1.1** to **8.103.0** (and 9.103.6.3) and i have a breaking change issue on the use of the Option ForceValueGeneratedStrategy 

`await _dbSet.BulkInsertAsync(entities, options => { options.ForceValueGeneratedStrategy = ValueGeneratedStrategyType.OnAddOrUpdate; });`

## 2. Exception
Here is the build message i got :

```
error CS1061: 'BulkOperation<TModel>' does not contain a definition for 'ForceValueGeneratedStrategy' and no accessible extension method 'ForceValueGeneratedStrategy' accepting a first argument of type 'BulkOperation<TModel>' could be found (are you missing a using directive or an assembly reference?)

error CS0103: The name 'ValueGeneratedStrategyType' does not exist in the current context
```

How we can handle this breaking change

**Comment by JonathanMagnan** [comment]
Hello @fuegans4213 ,

You can find all the necessary information here: 
- https://github.com/zzzprojects/EntityFramework-Extensions/releases/tag/8.103.0.0 
- https://entityframework-extensions.net/explicit-value-resolution-mode

In your case, the `OnAddOrUpdate` has been replaced by:

```csharp
// The option `options.ForceValueGeneratedStrategy = ValueGeneratedStrategyType.OnAddOrUpdate` has been replaced by:
options.ExplicitValueResolutionMode = Z.EntityFramework.Extensions.ExplicitValueResolutionMode.AlwaysKeepValueOnInsertOrUpdate;
```

Let me know if you need more help.

Best Regards,

Jon

**Comment by fuegans4213** [comment]
Hello @JonathanMagnan ,

Thanks for the reply, 

I was looking on the repo [EntityFramework-Plus](https://github.com/zzzprojects/EntityFramework-Plus) not the [EntityFramework-Extensions](https://github.com/zzzprojects/EntityFramework-Extensions)

Sorry about that :D.

Regards,

Adrien.
