### ISSUE TITLE
Audit - Support for Soft Delete when using a SaveChangesInterceptor

### ISSUE THREAD

**Issue by accsojens** [zzzprojects/EntityFramework-Plus#821]
Hey 👋

The Audit Library supports "Soft Deletes":
https://entityframework-plus.net/ef-core-audit-soft-add-soft-delete

In practice the `EntityModified` State in `AuditEntry` will be replaced with `EntitySoftDeleted` when the configured Soft Delete Flag is set.

But for this to work, the entities have to be "softdeleted" before creating the `Audit` object and calling `audit.PreSaveChanges(this)`. This results in problems, because many resources are suggesting to implement Soft Delete using a `SaveChangesInterceptor`:
https://blog.jetbrains.com/dotnet/2023/06/14/how-to-implement-a-soft-delete-strategy-with-entity-framework-core/

The idea is that you can delete entites as normal and keep you codebase as-is. But during each call to `SaveChanges()` on the `DbContext` the Interceptor kicks in and replaces all entities with Deleted States in the `ChangeTracker` with Modify Operations setting the Soft Delete Flag.

```
public class SoftDeleteInterceptor : SaveChangesInterceptor
{
    public override InterceptionResult<int> SavingChanges(
        DbContextEventData eventData, 
        InterceptionResult<int> result)
    {
        if (eventData.Context is null) return result;
        
        foreach (var entry in eventData.Context.ChangeTracker.Entries())
        {
            if (entry is not { State: EntityState.Deleted, Entity: ISoftDelete delete }) continue;
            entry.State = EntityState.Modified;
            delete.IsDeleted = true;
            delete.DeletedAt = DateTimeOffset.UtcNow;
        }
        return result;
    }
}
```

So the problem is that during the SaveChanges() call the entities in the `ChangeTracker` will be modified, but since the Audit has do be created before the `SaveChanges()` it contains wrong Entries, stating that the entry really was deleted.

Maybe i am missing some configuration option for supporting this scenario, but i think the usage of Interceptors in EF Core is a great concept that is widely used and should be supported by EF Core Plus.

```
internal async Task<int> SaveChangesAsyncWithAudit(CancellationToken cancellationToken = default)
{
    Audit audit = new()
    {
        CreatedBy = GetCurrentUsed(),
    };

    audit.PreSaveChanges(this);
    int rowsAffected = await base.SaveChangesAsync(cancellationToken);
    audit.PostSaveChanges();

    var entriesToSave = audit.Entries.Cast<CustomAuditEntry>()
        .Where(entry => entry.Properties.Any(property => property.InternalPropertyName != nameof(WithId.Id)));

    AuditEntries.AddRange(entriesToSave);
    await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);

    return rowsAffected;
}
```

Thanks, in advance!

### Further technical details

- EF version: [EF Core v8.0.11]
- EF Plus version: [EF Plus Core v8.103.6]
- Database Server version: Postgres

**Comment by JonathanMagnan** [comment]
Hello @accsojens ,

Thank you for reporting, but I do not believe anything will be done on our side. We cannot access those `entities` as easily after the interceptors make the logic; we need to access them before the interceptor does the logic. It will be really hard for us to do anything.

However, on your side, you pretty much have to add the "soft delete" code as the first line of the method, and it will already work (even if you have added your interceptor)

```csharp
internal async Task<int> SaveChangesAsyncWithAudit(CancellationToken cancellationToken = default)
{
	// your soft delete code
	foreach (var entry in this.ChangeTracker.Entries())
	{
		if (entry is not { State: EntityState.Deleted, Entity: ISoftDelete delete }) continue;
		entry.State = EntityState.Modified;
		delete.IsDeleted = true;
		delete.DeletedAt = DateTimeOffset.UtcNow;
	}

	Audit audit = new()
	{
		CreatedBy = GetCurrentUsed(),
	};

	audit.PreSaveChanges(this);
	int rowsAffected = await base.SaveChangesAsync(cancellationToken);
	audit.PostSaveChanges();

	var entriesToSave = audit.Entries.Cast<CustomAuditEntry>()
		.Where(entry => entry.Properties.Any(property => property.InternalPropertyName != nameof(WithId.Id)));

	AuditEntries.AddRange(entriesToSave);
	await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);

	return rowsAffected;
}
```

Let me know if that solve your issue

Best Regards,

Jon

**Comment by accsojens** [comment]
Hey @JonathanMagnan ,

thanks for the super quick response.

In the meanwhile i found some Code Examples that maybe could allow to run the required Code for the Audit in a Interceptor as well, since there are before and after-save hooks available:
https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#savechanges-interception

If this does not work, i stick with you suggested approach. Thanks!

Bye, Jens
