### ISSUE TITLE
EF Core - Sort by string

### ISSUE THREAD

**Issue by dazinator** [zzzprojects/EntityFramework-Plus#83]
Just trying out this library, my use case is to OrderBy("someproperty"). Is this functionality available yet - I can't seem to see it anywhere.

**Comment by zzzprojects** [comment]
We support all dynamic query using the Eval-Expression.NET library.

Wiki: https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-LINQ-Dynamic

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Hello @dazinator ,

Can we close this issues?

Best Regards,

Jonathan

**Comment by dazinator** [comment]
Yep thanks!
