### ISSUE TITLE
Exclude Property Using Interface

### ISSUE THREAD

**Issue by maharatha** [zzzprojects/EntityFramework-Plus#85]
I am able to exclude Entities using INeedModLog interface which I have created.

How do I use this interface to exclude  certain properties.

I am trying something like below to exclude the property but it's throwing up error.
  [INeedModLog]
   public virtual string Location { get; set; }

Could you let me know the correct way ?

**Comment by zzzprojects** [comment]
Hello @maharatha ,

You have two way to exclude properties

## Solution 1 - Exclude directly property
See: https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Audit-%7C-Entity-Framework-Audit-Trail-Context-and-Track-Changes#exclude--include-property

```csharp
AuditManager.DefaultConfiguration.ExcludeProperty<IInterface>(x =>
   new { x.Property1, x.Property2 }); // Exclude single or many properties
```

## Solution 2 - Using Data Annotations
See: https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Audit-%7C-Entity-Framework-Audit-Trail-Context-and-Track-Changes#data-annotations

```csharp
public interface IEntitySimple
{
    public int Id { get; set; }

    [AuditExclude]
    public int Column1 { get; set;}
}

AuditManager.DefaultConfiguration.ExcludeDataAnnotation();
```

Let me know if I answered correctly to your question

Best Regards,

Jonathan

**Comment by maharatha** [comment]
Hi -

Below is how I am trying to use the data annotations 👍 
 AuditManager.DefaultConfiguration.IgnorePropertyUnchanged = true;
     AuditManager.DefaultConfiguration.IncludeDataAnnotation();
           AuditManager.DefaultConfiguration.ExcludeDataAnnotation();
           AuditManager.DefaultConfiguration.DataAnnotationDisplayName();

This works partially i.e. 

All of my Entities started getting logged in-spite of me using [AuditInclude] for certain entities. I would like to log/audit certain entities and I am expecting if I use the Data Annotation [AuditInclude] then only those entities should be audited not the entire entities in my project

It is excluding properties with [AuditExclude] data annotation

**Comment by zzzprojects** [comment]
Currently, to make IncludeDataAnnotation work, you must exclude first everything.

```csharp
AuditManager.DefaultConfiguration.Exclude(x => true); // Exclude ALL
AuditManager.DefaultConfiguration.IncludeDataAnnotation();
```

Now you point me out this problem. I'm not sure either if that make sense to force you to add this additional line since a lot of people will have the same problem. We should probably exclude everything by default implicitly when you call the method.

Let me know if that's working if you exclude everything first.

Best Regards,

Jonathan

**Comment by maharatha** [comment]
I had tried excluding everything first and then include but it didn't work
and nothing was logged.

I can try once more tomorrow first thing in the morning.

Really appreciate your swift response.

**Comment by maharatha** [comment]
It Worked !!! 👍

**Comment by zzzprojects** [comment]
That's great, I will let the issue open until I take the decision if we exclude or not everything by default.

**Comment by maharatha** [comment]
The Audit Manager is not tracking changes if we use Bulk Insert or Update using Z Entifty Framework bulk insert or update

**Comment by zzzprojects** [comment]
Hello @maharatha ,

You are right. It can work with BulkSaveChanges but not with other Bulk Operations. There is for sure some way to overcome this limitation since EFE have his Audit feature but this will require some custom code.

We added more detail and an example in the Wiki: https://github.com/zzzprojects/EntityFramework-Plus/wiki/EF-Audit-%7C-Entity-Framework-Audit-Trail-Context-and-Track-Changes#audit--entity-framework-extensions

Let me know if you need more information.

Best Regards,

Jonathan

**Comment by maharatha** [comment]
Hi Jonathan -

Thank you for the response. I have few questions : 

1) When does BulkSaveChangesWithAudit() gets called. In my DB context I am overriding the SaveChanges but I am not sure how to call the BulkSaveChangeswithAudit().

2) Secondly how do I do a bulk update using BulkUpdate. I am able to add or remove items using AddRange or Remove range but not sure how I can update it.

e.g. var dbContext = repository.GetDbContext();
                dbContext.Set<TEntity>().AddRange(entities);
                dbContext.BulkSaveChanges();

How do i use something like this to update.

**Comment by zzzprojects** [comment]
**1 - BulkSaveChangesWithAudit**

Your repository returns a DbContext, so you will need instead to create an extensions methods.

```csharp
public static class DbExtensions
{
    public static void BulkSaveChangesWithAudit(this DbContext context)
    {
        var audit = new Audit();
        audit.PreSaveChanges(context);

        context.BulkSaveChanges();

        audit.PostSaveChanges();

        if (audit.Entries.Count > 0)
        {
            context.BulkInsert(audit.Entries);

            // The ID must be set, there is currently no navigation properties in the AuditEntryProperty class
            audit.Entries.ForEach(x => x.Properties.ForEach(y => y.AuditEntryID = x.AuditEntryID));

            // Don't output the Id for EntryProperty for more performance
            context.BulkInsert(audit.Entries.SelectMany(y => y.Properties), operation =>
            {
                operation.AutoMapOutputDirection = false;
                operation.BatchSize = 50000;
            });
        }
    }
}
```

2 Bulk Update
How do you normally update? Are you probably limited to one entity at a time?

You can use a code similar to this. You will need to change yourself the state.

```csharp
ctx.Set<EntitySimple>().AddRange(list);
ctx.ChangeTracker.Entries<EntitySimple>().ToList().ForEach(x => x.State = EntityState.Modified);
ctx.BulkSaveChanges();
```

**Comment by JonathanMagnan** [comment]
Hello @maharatha ,

We are currently cleaning some old request.

I will close this one. Feel free to reopen if I closed it by mistake.

Best Regards,

Jonathan

---
_Help us to keep this library free: [Donate](http://www.zzzprojects.com/contribute)_
