### ISSUE TITLE
Query Filter | Setup Issue

### ISSUE THREAD

**Issue by zzzprojects** [zzzprojects/EntityFramework-Plus#87]
Original Question from deliotomaz 

> Hi,
> I am using a Generic Repository but Global Filters are not working.
> In my repository I have a property:
> protected DbSet<TEntity> DbSet { get { return Context.Set<TEntity>(); } }
> I am setting the Global Filter on Context constructor:
> QueryFilterManager.Filter<IEntidadeConta>("IEntidadeConta", q => q.Where(x => x.CodigoConta == dadosUsuarioResolver.CodigoContaCorrente)); QueryFilterManager.Filter<IExclusaoLogica>("IExclusaoLogica", q => q.Where(x => x.Ativo)); QueryFilterManager.InitilizeGlobalFilter(this);
> 
> The filter is not applied.
> An important thing: I didn't create DBSet properties on my DbContext. If I create them, the filters are applied.
> 
> Can you help me ?

Asked in issue #47

**Comment by zzzprojects** [comment]
Which version of Entity Framework are you using?

Query Filter doesn't work the same way in EF Core and EF6.

For EF Core, filter currently only work for DbSet specified in the DbContext.

For EF6, it shoulds work.

Let me know which version you are using.

Best Regards,

Jonathan

**Comment by deliotomaz** [comment]
Hi Jonathan, Thnks for quick response.
I am using EF6.
Note that I get this issue when I don't have my DbSet<> declared on my DbContext and load data using DbContext.Set<T> 
If I declare all DbSets and them Get data using DbContext.Set<T> it works.

**Comment by zzzprojects** [comment]
Hello @deliotomaz ,

Unfortunately, this is a limitation to our library currently. We only check type which is beyond a DbContext.

This weekend, we will try to add a new option to allow you to register some type which is not part of the DbContext

Example
```csharp
QueryFilterManager.RegisterType(typeof(MyCustomerType);
```

I will let you know more very soon.

Best Regards,

Jonathan

**Comment by deliotomaz** [comment]
Hi Jonathan,
Ok No problem.
Thanks for you help. This is will be very useful.

Best Regards,

Delio

**Comment by zzzprojects** [comment]
Hello @deliotomaz ,

The code for registering type has been completed.

Unfortunately, we didn't found where EF was cached all types, so you will need to explicitly register them.
 

The version should be ready for Monday, I will provide you more information tomorrow.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Hello @deliotomaz ,

Sorry for the delay,

We have added the method RegisterType as previously said, can you try it to see if it's now working?

Let me know if it's successfully fixed.

Best Regards,

Jonathan

**Comment by deliotomaz** [comment]
Hi Jonathan,
No problem with delay.
Thanks!!!!!
I will try it this weekend and feedback you.

Thanks for your help

Delio

**Comment by deliotomaz** [comment]
Hi Jonathan,
I am registering all types in my Context constructor:

` var types = typeof(EntidadeDominioBase).Assembly.GetTypes()
                        .Where(type => type.IsSubclassOf(typeof(EntidadeDominioBase)) && type != typeof(TrackedEntidadeBase));

            QueryFilterManager.RegisterType(types.ToArray());

            QueryFilterManager.Filter<IEntidadeConta>(q => q.Where(x => x.CodigoConta == dadosUsuarioResolver.CodigoContaCorrente));
            QueryFilterManager.Filter<IExclusaoLogica>(q => q.Where(x => x.Ativo));
             QueryFilterManager.InitilizeGlobalFilter(this);`

When I try to use any DbSet I get an exception : "The entity type <type>is not part of the model for the current context."

Any ideia if I am doing wrong ?

Best

Delio

**Comment by zzzprojects** [comment]
Hello @deliotomaz ,

You are right, we have found the bug.

The fix will be released soon. We are currently trying to release but it seems we have some internet/TFS problem.

**Comment by zzzprojects** [comment]
Hello @deliotomaz ,

The issue has been fixed in v1.4.14

Btw, you need to register type you will use in your DbSet. You don't have to register interface and base class if they are not part of your model.

```csharp
QueryFilterManager.RegisterType(typeof(EntitySimple));
//QueryFilterManager.RegisterType(typeof (IEntitySimple)); // Will works but not required

ctx.Set<EntitySimple>()...
```

**Comment by deliotomaz** [comment]
Hi,
I will try it and feedback you about the result.
Thanks again,

Best

**Comment by deliotomaz** [comment]
Hi,
It works !!!!!
Thanks Jonathan.

Good job.

Best

**Comment by JonathanMagnan** [comment]
Closing comment: Fix confirmed
