### ISSUE TITLE
Disable Cache by Default

### ISSUE THREAD

**Issue by KiarashS** [zzzprojects/EntityFramework-Plus#90]
Dear,

I want disable the cache by default and I use it whenever I need it, not the case that all queries be cached by default.

Thanks in advance.

**Comment by zzzprojects** [comment]
Hello @KiarashS ,

I'm not sure to fully understand this request.

- Are you talking about our Query Cache feature which you don't want to always cache?
- Are you talking about a whole new features which you will want to control what will be cache or not in the QueryCacheManager from Entity Framework?

Best Regards,

Jonathan

**Comment by KiarashS** [comment]
Hello @JonathanMagnan ,

Yes, your first guess is right, I talking about Query Cache feature which i don't always want to cache?


Thanks

**Comment by zzzprojects** [comment]
Perfect, so the next question is how do you know or how will you want to specify if you want to cache the query or not.

I mean, if you don't want to cache use, why are you using FromCache extension methods? I'm trying to find out the purpose of this request.

Best Regards,

Jonathan

**Comment by KiarashS** [comment]
@JonathanMagnan This is my understanding of your answer:

If we use `FromCache` extension method then result of query will be cached, 
and
If we don't use `FromCache` extension method then result of query will not be cached.

That's true?

**Comment by zzzprojects** [comment]
Hello @KiarashS ,

Exactly,

We don't cache query by default.  You need to explicitly add the FromCache extension methods to make a query use the cache (get or add the result to the cache).

Let me know if the question has been fully answered.

Best Regards,

Jonathan

**Comment by KiarashS** [comment]
@JonathanMagnan Yes, my question now is a document for me and others :)

Thank you very much.

**Comment by JonathanMagnan** [comment]
Closing comment: Answer confirmed
