### ISSUE TITLE
 AuditManager.DefaultConfiguration.AutoSavePreAction not called

### ISSUE THREAD

**Issue by mattjowens** [zzzprojects/EntityFramework-Plus#92]
Hey,

The Audit framework is not working in my EF6 model first project. How would you suggest trouble shooting this issue? The DB is created correctly via code migrations, my context contstructor is below.

```
 static ServiceEntities()
        {
            AuditManager.DefaultConfiguration.AutoSavePreAction = (context, audit) =>
            {
                var serviceEntities = context as ServiceEntities;
                if (serviceEntities != null)
                {
                    serviceEntities.AuditEntries.AddRange(audit.Entries);
                }
                else throw new InvalidOperationException($"Context is null for {context.Database.Connection}");
            };
        }

```
Is there any obvious reason that I could investigate?

Thanks for your help.

**Comment by zzzprojects** [comment]
Hello @mattjowens ,

I'm pretty sure the issue is because you don't call the SaveChanges overload (with the audit parameter), so our library is actually never called.

```csharp
var audit = new Audit();
ctx.SaveChanges(audit);
```

Another technic is overriding SaveChanges in your Context
```csharp
public override int SaveChanges()
{
	var audit = new Audit();
	audit.PreSaveChanges(this);
	var rowAffecteds = base.SaveChanges();
	audit.PostSaveChanges();

	if (audit.Configuration.AutoSavePreAction != null)
	{
		audit.Configuration.AutoSavePreAction(this, audit);
		base.SaveChanges();
	}

	return rowAffecteds;
}

ctx.SaveChanges();
```

Let me know if you successfully fixed the issue or you need more help.

Best Regards,

Jonathan

**Comment by mattjowens** [comment]
@zzzprojects i missed the overload. Thanks
